### ISSUE TITLE
Yuan2.0-2B-hf Load model to MTL got error: No module named 'transformers_modules.Yuan2'

### ISSUE THREAD

**Issue by violet17** [intel-analytics/BigDL#10202]
```
python.exe test_yuan2.py
C:\Users\test\Documents\rag\llmsd_env\lib\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: ''If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
2024-02-21 21:30:42,881 - root - INFO - intel_extension_for_pytorch auto imported
Creating tokenizer...
You are using the legacy behaviour of the <class 'transformers.models.llama.tokenization_llama.LlamaTokenizer'>. This means that tokens that come after special tokens will not be properly handled. We recommend you to read the related pull request available at https://github.com/huggingface/transformers/pull/24565
Creating model...
Traceback (most recent call last):
  File "C:\Users\test\Downloads\YuanLLM\test_yuan2.py", line 37, in <module>
    model = AutoModelForCausalLM.from_pretrained(model_path, trust_remote_code=True, load_in_4bit=True).eval()
  File "C:\Users\test\Documents\rag\llmsd_env\lib\site-packages\bigdl\llm\transformers\model.py", line 246, in from_pretrained
    model = cls.load_convert(q_k, optimize_model, *args, **kwargs)
  File "C:\Users\test\Documents\rag\llmsd_env\lib\site-packages\bigdl\llm\transformers\model.py", line 350, in load_convert
    model = cls.HF_Model.from_pretrained(*args, **kwargs)
  File "C:\Users\test\Documents\rag\llmsd_env\lib\site-packages\transformers\models\auto\auto_factory.py", line 461, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "C:\Users\test\Documents\rag\llmsd_env\lib\site-packages\transformers\models\auto\configuration_auto.py", line 992, in from_pretrained
    config_class = get_class_from_dynamic_module(class_ref, pretrained_model_name_or_path, **kwargs)
  File "C:\Users\test\Documents\rag\llmsd_env\lib\site-packages\transformers\dynamic_module_utils.py", line 443, in get_class_from_dynamic_module
    return get_class_in_module(class_name, final_module.replace(".py", ""))
  File "C:\Users\test\Documents\rag\llmsd_env\lib\site-packages\transformers\dynamic_module_utils.py", line 164, in get_class_in_module
    module = importlib.import_module(module_path)
  File "C:\Users\test\Documents\rag\llmsd_env\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'transformers_modules.Yuan2'
```

test code from: https://github.com/intel-analytics/BigDL/pull/9946/files#diff-d885dd2c6694f46ba7afb526cc35f91f75b89bde3eb8dab39ec71513e4216607

```
version:
sentence-transformers         2.3.1
transformers                  4.31.0 or 4.30.0
transformers-stream-generator 0.0.4
bigdl-core-xe-21              2.5.0b20240128 or 0220
bigdl-llm                     2.5.0b20240128 or 0220
```

**Comment by sgwhat** [comment]
We are reproducing the issue you mentioned, and will inform you of the solution ASAP.

**Comment by sgwhat** [comment]
Could you please provide the naming for the Yuan2 `model_path` on your MTL? @violet17

**Comment by violet17** [comment]
> Could you please provide the naming for the Yuan2 `model_path` on your MTL? @violet17


import torch, transformers
from transformers import AutoTokenizer,LlamaTokenizer
from bigdl.llm.transformers import AutoModelForCausalLM
import torch
import intel_extension_for_pytorch as ipex
import time


print("Creat tokenizer...")
model_path1 = r"C:\Users\test\Downloads\YuanLLM\Yuan2-2B-Janus-hf"
tokenizer = LlamaTokenizer.from_pretrained(model_path1, add_eos_token=False, add_bos_token=False, eos_token='<eod>')
tokenizer.add_tokens(['<sep>', '<pad>', '<mask>', '<predict>', '<FIM_SUFFIX>', '<FIM_PREFIX>', '<FIM_MIDDLE>','<commit_before>',
'<commit_msg>','<commit_after>','<jupyter_start>','<jupyter_text>','<jupyter_code>','<jupyter_output>','<empty_output>'], special_tokens=True)

print("Creat model...")
model_path2 = r"C:\Users\test\Downloads\YuanLLM\Yuan2.0-2B-hf"
model = AutoModelForCausalLM.from_pretrained(model_path2,  load_in_4bit=True, optimize_model=True,trust_remote_code=True)
model.to('xpu')

with torch.inference_mode():
    torch.xpu.synchronize()
    t0 = time.time()
    inputs = tokenizer("请问目前最先进的机器学习算法有哪些？", return_tensors="pt")["input_ids"].to("xpu")
    outputs = model.generate(inputs,do_sample=False,max_length=100)
    torch.xpu.synchronize()
    t1 = time.time()
    print("cost time: ", t1-t0)
    print(tokenizer.decode(outputs[0]))

**Comment by sgwhat** [comment]
Changing the model_path from `Yuan2.0` to `Yuan2` should work as expected.

**Comment by violet17** [comment]
Fixed. Thanks.
