### ISSUE TITLE
Error message from chatglm3/qwen generation script on MTL with iGPU

### ISSUE THREAD

**Issue by OpenVINO-dev-contest** [intel-analytics/BigDL#10241]
Installation process:
https://bigdl.readthedocs.io/en/latest/doc/LLM/Overview/install_gpu.html

Environment:
OS: Windows 11
HW: iGPU on MTL
 

Error logs:
```
(llm) PS C:\Users\S590_V53\Desktop\BigDL\python\llm\dev\benchmark> python .\benchmark.py                                                                      
C:\Users\S590_V53\miniconda3\envs\llm\lib\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: 'Could not find module 'C:\Users\S590_V53\miniconda3\envs\llm\Lib\site-packages\torchvision\image.pyd' (or one of its dependencies). Try using the full path with constructor syntax.'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
 warn(
2024-02-22 09:18:52,162 - root - INFO - intel_extension_for_pytorch auto imported
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 11.23it/s]
2024-02-22 09:18:55,772 - bigdl.llm.transformers.utils - INFO - Converting the current model to sym_int4 format......
<class 'transformers_modules.THUDM.chatglm3-6b.f30825950ce00cb0577bf6a15e0d95de58e328dc.modeling_chatglm.ChatGLMForConditionalGeneration'>
Traceback (most recent call last):
 File "C:\Users\S590_V53\Desktop\BigDL\python\llm\dev\benchmark\benchmark.py", line 23, in <module>
   output = model.generate(input_ids, do_sample=False, max_new_tokens=32)
 File "C:\Users\S590_V53\miniconda3\envs\llm\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
   return func(*args, **kwargs)
 File "C:\Users\S590_V53\Desktop\BigDL\python\llm\dev\benchmark\benchmark_util.py", line 1563, in generate
   return self.greedy_search(
 File "C:\Users\S590_V53\Desktop\BigDL\python\llm\dev\benchmark\benchmark_util.py", line 2385, in greedy_search
   outputs = self(
 File "C:\Users\S590_V53\Desktop\BigDL\python\llm\dev\benchmark\benchmark_util.py", line 533, in __call__
   return self.model(*args, **kwargs)
 File "C:\Users\S590_V53\miniconda3\envs\llm\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
   return self._call_impl(*args, **kwargs)
 File "C:\Users\S590_V53\miniconda3\envs\llm\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
   return forward_call(*args, **kwargs)
 File "C:\Users\S590_V53/.cache\huggingface\modules\transformers_modules\THUDM\chatglm3-6b\f30825950ce00cb0577bf6a15e0d95de58e328dc\modeling_chatglm.py", line 941, in forward
   transformer_outputs = self.transformer(
 File "C:\Users\S590_V53\miniconda3\envs\llm\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
   return self._call_impl(*args, **kwargs)
 File "C:\Users\S590_V53\miniconda3\envs\llm\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
   return forward_call(*args, **kwargs)
 File "C:\Users\S590_V53\miniconda3\envs\llm\lib\site-packages\bigdl\llm\transformers\models\chatglm2.py", line 170, in chatglm2_model_forward
   hidden_states, presents, all_hidden_states, all_self_attentions = self.encoder(
 File "C:\Users\S590_V53\miniconda3\envs\llm\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
   return self._call_impl(*args, **kwargs)
 File "C:\Users\S590_V53\miniconda3\envs\llm\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
   return forward_call(*args, **kwargs)
 File "C:\Users\S590_V53/.cache\huggingface\modules\transformers_modules\THUDM\chatglm3-6b\f30825950ce00cb0577bf6a15e0d95de58e328dc\modeling_chatglm.py", line 641, in forward
   layer_ret = layer(
 File "C:\Users\S590_V53\miniconda3\envs\llm\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
   return self._call_impl(*args, **kwargs)
 File "C:\Users\S590_V53\miniconda3\envs\llm\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
   return forward_call(*args, **kwargs)
 File "C:\Users\S590_V53/.cache\huggingface\modules\transformers_modules\THUDM\chatglm3-6b\f30825950ce00cb0577bf6a15e0d95de58e328dc\modeling_chatglm.py", line 544, in forward
   attention_output, kv_cache = self.self_attention(
 File "C:\Users\S590_V53\miniconda3\envs\llm\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
   return self._call_impl(*args, **kwargs)
 File "C:\Users\S590_V53\miniconda3\envs\llm\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
   return forward_call(*args, **kwargs)
 File "C:\Users\S590_V53\miniconda3\envs\llm\lib\site-packages\bigdl\llm\transformers\models\chatglm2.py", line 194, in chatglm2_attention_forward
   return forward_function(
 File "C:\Users\S590_V53\miniconda3\envs\llm\lib\site-packages\bigdl\llm\transformers\models\chatglm2.py", line 283, in chatglm2_quantized_attention_forward_8eb45c
   attn = linear_q4_0.query_key_fp8_matmul(query_layer, key) / math.sqrt(head_dim)
RuntimeError: Failed to load libsycl-fallback-bfloat16.spv -30 (PI_ERROR_INVALID_VALUE)
```

**Comment by ivy-lv11** [comment]
Could you please run the script under python/llm/scripts to print more information about the environment?

**Comment by ivy-lv11** [comment]
The problem might be solved by upgrading the version of transformers to 4.37.2.

**Comment by OpenVINO-dev-contest** [comment]
> Could you please run the script under python/llm/scripts following README.md to print more information about the environment? I guess it is caused by the mismatch of the version.

Sorry, there is no MTL device in my hands, but I will test it again when I got it.
