### ISSUE TITLE
Error when executing "from bigdl.llm.langchain.llms import TransformersLLM"

### ISSUE THREAD

**Issue by Zhuohua-HUANG** [intel-analytics/BigDL#10341]
Windows 11
Intel i7
I run the "from bigdl.llm.langchain.llms import TransformersLLM"
```
C:\Users\hzh30\.conda\envs\bigdl\python.exe D:\b_Work\ip_LLM\test_agents\test_agents_llama.py 
2024-03-07 12:23:36,191 - WARNING - BigdlNativeLLM has been deprecated, please switch to the new LLM API for sepcific models.
Traceback (most recent call last):
  File "D:\b_Work\ip_LLM\test_agents\test_agents_llama.py", line 3, in <module>
    from bigdl.llm.langchain.llms import TransformersLLM
  File "C:\Users\hzh30\.conda\envs\bigdl\lib\site-packages\bigdl\llm\langchain\llms\__init__.py", line 26, in <module>
    from .bigdlllm import *
  File "C:\Users\hzh30\.conda\envs\bigdl\lib\site-packages\bigdl\llm\langchain\llms\bigdlllm.py", line 58, in <module>
    class BigdlNativeLLM(LLM):
  File "C:\Users\hzh30\.conda\envs\bigdl\lib\site-packages\bigdl\llm\langchain\llms\bigdlllm.py", line 164, in BigdlNativeLLM
    @root_validator()
  File "C:\Users\hzh30\.conda\envs\bigdl\lib\site-packages\pydantic\deprecated\class_validators.py", line 237, in root_validator
    raise PydanticUserError(
pydantic.errors.PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.

For further information visit https://errors.pydantic.dev/2.6/u/root-validator-pre-skip

Process finished with exit code 1
```

my env is :
```
# packages in environment at C:\Users\me\.conda\envs\bigdl:
#
# Name                    Version                   Build  Channel
accelerate                0.21.0                   pypi_0    pypi
aiohttp                   3.9.3                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
altair                    5.2.0                    pypi_0    pypi
annotated-types           0.6.0                    pypi_0    pypi
anyio                     4.2.0                    pypi_0    pypi                             .cn/anaconda/pkgs/main     4.0.3                    pypi_0    pypi
cachetools                5.3.2                    pypi_0    pypi
certifi                   2023.11.17               pypi_0    pypi
charset-normalizer        3.3.2                    pypi_0    pypi
click                     8.1.7                    pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypis://mirrors.tuna.tsinghua.edu.
dataclasses-json          0.6.4                    pypi_0    pypi
distro                    1.9.0                    pypi_0    pypi
fpdf                      1.7.2                    pypi_0    pypi
frozenlist                1.4.1                    pypi_0    pypi
fsspec                    2024.2.0                 pypi_0    pypi
gitdb                     4.0.11                   pypi_0    pypi
gitpython                 3.1.41                   pypi_0    pypi
google-ai-generativelanguage 0.4.0                    pypi_0    pypi
google-api-core           2.16.1                   pypi_0    pypi
google-auth               2.27.0                   pypi_0    pypi
google-generativeai       0.3.2                    pypi_0    pypi
googleapis-common-protos  1.62.0                   pypi_0    pypi
greenlet                  3.0.3                    pypi_0    pypi
h11                       0.14.0                   pypi_0    pypi
httpcore                  1.0.2                    pypi_0    pypi
httpx                     0.26.0                   pypi_0    pypi
huggingface-hub           0.21.3                   pypi_0    pypi
idna                      3.6                      pypi_0    pypi
importlib-metadata        7.0.1                    pypi_0    pypi
intel-openmp              2024.0.2                 pypi_0    pypi
jinja2                    3.1.3                    pypi_0    pypi
joblib                    1.3.2                    pypi_0    pypi
jsonpatch                 1.33                     pypi_0    pypi
jsonpointer               2.4                      pypi_0    pypi
jsonschema                4.21.1                   pypi_0    pypi
jsonschema-specifications 2023.12.1                pypi_0    pypi
langchain                 0.1.6                    pypi_0    pypi
langchain-community       0.0.19                   pypi_0    pypi
langchain-core            0.1.29                   pypi_0    pypi
langchain-openai          0.0.8                    pypi_0    pypi
langchainhub              0.1.15                   pypi_0    pypi
langsmith                 0.1.19                   pypi_0    pypi
markdown-it-py            3.0.0                    pypi_0    pypi
markupsafe                2.1.4                    pypi_0    pypi
marshmallow               3.20.2                   pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
mpmath                    1.3.0                    pypi_0    pypi
multidict                 6.0.5                    pypi_0    pypi                             .
cn/anaconda/pkgs/main     1.0.0                    pypi_0    pypi                             .cn/anaconda/pkgs/main     3.9.15                   pypi_0    pypi
poetry                    1.8.2                    pypi_0    pypi
poppler-utils             0.1.0                    pypi_0    pypi
proto-plus                1.23.0                   pypi_0    pypi
protobuf                  4.25.2                   pypi_0    pypis://mirrors.tuna.tsinghua.edu.
psutil                    5.9.8                    pypi_0    pypis://mirrors.tuna.tsinghua.edu.
py-cpuinfo                9.0.0                    pypi_0    pypi
pyarrow                   15.0.0                   pypi_0    pypi
pyasn1                    0.5.1                    pypi_0    pypi
pyasn1-modules            0.3.0                    pypi_0    pypi                             .cn/anaconda/pkgs/main     2.6.0                    pypi_0    pypi
python-dateutil           2.8.2                    pypi_0    pypi
pytz                      2023.4                   pypi_0    pypi
pyyaml                    6.0.1                    pypi_0    pypi
referencing               0.33.0                   pypi_0    pypi
regex                     2023.12.25               pypi_0    pypis://mirrors.tuna.tsinghua.edu.
requests                  2.31.0                   pypi_0    pypi
rich                      13.7.0                   pypi_0    pypi
rpds-py                   0.17.1                   pypi_0    pypi                             .
cn/anaconda/pkgs/main     4.9                      pypi_0    pypi                             .cn/anaconda/pkgs/main     1.16.0                   pypi_0    pypi
typing-inspect            0.9.0                    pypi_0    pypi
tzdata                    2023.4                   pypi_0    pypi
tzlocal                   5.2                      pypi_0    pypi
urllib3                   2.2.0                    pypi_0    pypi
validators                0.22.0                   pypi_0    pypi
vc                        14.2                 h21ff451_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
vs2015_runtime            14.27.29016          h5e58377_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
watchdog                  3.0.0                    pypi_0    pypi
wheel                     0.41.2           py39haa95532_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
yarl                      1.9.4                    pypi_0    pypi
zipp                      3.17.0                   pypi_0    pypi
zlm                       0.1.32                   pypi_0    pypi
```

**Comment by sgwhat** [comment]
what version of `pydantic` are you using?

**Comment by sgwhat** [comment]
try `pip install pydantic==1.10.9`

**Comment by Zhuohua-HUANG** [comment]
> what version of `pydantic` are you using?
I use pydantic-1.8

**Comment by Zhuohua-HUANG** [comment]
> try `pip install pydantic==1.10.9`

Oh, it works!

**Comment by Zhuohua-HUANG** [comment]
> try `pip install pydantic==1.10.9`

Oh, it works! Thank you!
