### ISSUE TITLE
Can not load Yuan2-2B GGUF FP16 model

### ISSUE THREAD

**Issue by violet17** [intel-analytics/BigDL#10360]
Hi,
I load Yuan2-2B-Februa-hf-GGUF model(https://modelscope.cn/models/YuanLLM/Yuan2-2B-Februa-hf-GGUF/summary), get this error:
```
model_family:llama
--------qtype:  1
2024-03-11 10:33:25,565 - ERROR -
 
****************************Usage Error************************
Unsupported gguf quantize type: 1
2024-03-11 10:33:25,565 - ERROR -
 
****************************Call Stack*************************
Traceback (most recent call last):
  File "D:\BigDL\python\llm\dev\benchmark\all-in-one\run.py", line 1073, in <module>
    run_model(model, api, in_out_pairs, conf['local_model_hub'], conf['warm_up'], conf['num_trials'], conf['num_beams'],
  File "D:\BigDL\python\llm\dev\benchmark\all-in-one\run.py", line 84, in run_model
    result = result = run_gguf_gpu(repo_id, local_model_hub, in_out_pairs, warm_up, num_trials, num_beams, batch_size)
  File "D:\BigDL\python\llm\dev\benchmark\all-in-one\run.py", line 394, in run_gguf_gpu
    model, tokenizer = AutoModelForCausalLM.from_gguf(model_path)
  File "D:\rag\rag_env\lib\site-packages\bigdl\llm\transformers\model.py", line 331, in from_gguf
    model, tokenizer, low_bit = load_gguf_model(fpath, dtype=torch.half)
  File "D:\rag\rag_env\lib\site-packages\bigdl\llm\transformers\gguf\api.py", line 39, in load_gguf_model
    invalidInputError(qtype in qtype_map, f"Unsupported gguf quantize type: {qtype}")
  File "D:\rag\rag_env\lib\site-packages\bigdl\llm\utils\common\log4Error.py", line 32, in invalidInputError
    raise RuntimeError(errMsg)
RuntimeError: Unsupported gguf quantize type: 1
```

cannot load gguf FP16 model.

version:  bigdl 20240303

Could you help to fix this issue?
Thanks.
Thanks.

**Comment by hzjane** [comment]
We currently do not support the use of f16 and Yuan2 gguf model, and are trying to support it.

**Comment by hzjane** [comment]
Please refet to [this pr](https://github.com/intel-analytics/BigDL/pull/10372) to test.

**Comment by violet17** [comment]
Thanks. I can run Yuan2 in fp16 gguf now.
