### ISSUE TITLE
How to load model in 4bit when useing BigDL-LLM FastChat Serving 

### ISSUE THREAD

**Issue by kunger97** [intel-analytics/BigDL#10467]
When I read the document, I found that BigDL seems to be able to provide an openai like API interface through FastChat. However, due to memory limitations, I need to use 4Bit to quantitatively load the model, but I did not find in the document how to use 4Bit to quantitatively load the model. Can BigDL FastChat Serving use 4Bit quantification to load models? If not, is there any other way to quickly obtain an openai like API interface?

I also learned that BigDL seems to implement some vLLM functions, but vLLM in BigDL does not currently support qwen2, qwen or Orion.Is there any relevant plan to support these models?

**Comment by glorysdj** [comment]
please refer to https://github.com/intel-analytics/BigDL/blob/main/python/llm/src/bigdl/llm/serving/README.md
You can use 4Bit quantification to load models in BigDL FastChat Serving.
@Romanticoseu please also help to show an example.

We are refactoring BigDL vLLM functions and will support more models like QWen, etc. Will keep you updated on this issue once it's ready.

**Comment by Romanticoseu** [comment]
For example, if I want to load `llama-2-7b`, I should change the name from `llama-2-7b` to `bigdl-7b` to use `BigDL` backend.
When the environment is ready, I should:
Launch controller:
```bash
python3 -m fastchat.serve.controller
```
Launch model worker:
```bash
# For CPU
python3 -m bigdl.llm.serving.model_worker --model-path PATH/TO/bigdl-7b --device cpu

# For XPU
python3 -m bigdl.llm.serving.model_worker --model-path PATH/TO/bigdl-7b --device xpu
```
You can see the output like `covert model to sym_int4 format ...` if the bigdl adapter is working
Launch api_server:
```bash
python3 -m fastchat.serve.openai_api_server --host localhost --port 8000
```

**Comment by kunger97** [comment]
> For example, if I want to load `llama-2-7b`, I should change the name from `llama-2-7b` to `bigdl-7b` to use `BigDL` backend. When the environment is ready, I should: Launch controller:
> 
> ```shell
> python3 -m fastchat.serve.controller
> ```
> 
> Launch model worker:
> 
> ```shell
> # For CPU
> python3 -m bigdl.llm.serving.model_worker --model-path PATH/TO/bigdl-7b --device cpu
> 
> # For XPU
> python3 -m bigdl.llm.serving.model_worker --model-path PATH/TO/bigdl-7b --device xpu
> ```
> 
> You can see the output like `covert model to sym_int4 format ...` if the bigdl adapter is working Launch api_server:
> 
> ```shell
> python3 -m fastchat.serve.openai_api_server --host localhost --port 8000
> ```

Thanks for your reply, after I read the relevant documentation, I still can't confirm how to use 4Bit quantization to load the model.
Can it be understood that BigDL will load the model with 4-bit quantization by default?
I can't found any argument that mention load in 4bit at python/llm/src/bigdl/llm/serving/model_worker.py

**Comment by Romanticoseu** [comment]
Yes, we load the model with 4-bit quantization by default.
The key point here is that the model's path should include "bigdl" and **should not include paths matched by other model adapters**.
And we currently only support int4 quantization when using FastChat serving.

**Comment by kunger97** [comment]
> Yes, we load the model with 4-bit quantization by default. The key point here is that the model's path should include "bigdl" and **should not include paths matched by other model adapters**. And we currently only support int4 quantization when using FastChat serving.

I'm load Orion-14b-chat Model, i just test it can load in 4 bit via transformers api offered by bigdl, and it work normally but when i load it useing FastChat serving, it seems oom

the command i use:
`python3 -m bigdl.llm.serving.model_worker --model-path ./Orion/ --device xpu --cpu-offloading`

```
2024-03-19 20:21:53 | ERROR | stderr | Traceback (most recent call last):
2024-03-19 20:21:53 | ERROR | stderr |   File "/home/u1024969/intel/intelpython3/envs/SakuraLLM/lib/python3.10/runpy.py", line 196, in _run_module_as_main
2024-03-19 20:21:53 | ERROR | stderr |     return _run_code(code, main_globals, None,
2024-03-19 20:21:53 | ERROR | stderr |   File "/home/u1024969/intel/intelpython3/envs/SakuraLLM/lib/python3.10/runpy.py", line 86, in _run_code
2024-03-19 20:21:53 | ERROR | stderr |     exec(code, run_globals)
2024-03-19 20:21:53 | ERROR | stderr |   File "/home/u1024969/intel/intelpython3/envs/SakuraLLM/lib/python3.10/site-packages/bigdl/llm/serving/model_worker.py", line 488, in <module>
2024-03-19 20:21:53 | ERROR | stderr |     worker = ModelWorker(
2024-03-19 20:21:53 | ERROR | stderr |   File "/home/u1024969/intel/intelpython3/envs/SakuraLLM/lib/python3.10/site-packages/bigdl/llm/serving/model_worker.py", line 227, in __init__
2024-03-19 20:21:53 | ERROR | stderr |     self.model, self.tokenizer = load_model(
2024-03-19 20:21:53 | ERROR | stderr |   File "/home/u1024969/intel/intelpython3/envs/SakuraLLM/lib/python3.10/site-packages/bigdl/llm/serving/bigdl_llm_model.py", line 229, in load_model
2024-03-19 20:21:53 | ERROR | stderr |     model.to(device)
2024-03-19 20:21:53 | ERROR | stderr |   File "/home/u1024969/intel/intelpython3/envs/SakuraLLM/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2556, in to
2024-03-19 20:21:53 | ERROR | stderr |     return super().to(*args, **kwargs)
2024-03-19 20:21:53 | ERROR | stderr |   File "/home/u1024969/intel/intelpython3/envs/SakuraLLM/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1160, in to
2024-03-19 20:21:53 | ERROR | stderr |     return self._apply(convert)
2024-03-19 20:21:53 | ERROR | stderr |   File "/home/u1024969/intel/intelpython3/envs/SakuraLLM/lib/python3.10/site-packages/torch/nn/modules/module.py", line 810, in _apply
2024-03-19 20:21:53 | ERROR | stderr |     module._apply(fn)
2024-03-19 20:21:53 | ERROR | stderr |   File "/home/u1024969/intel/intelpython3/envs/SakuraLLM/lib/python3.10/site-packages/torch/nn/modules/module.py", line 810, in _apply
2024-03-19 20:21:53 | ERROR | stderr |     module._apply(fn)
2024-03-19 20:21:53 | ERROR | stderr |   File "/home/u1024969/intel/intelpython3/envs/SakuraLLM/lib/python3.10/site-packages/torch/nn/modules/module.py", line 810, in _apply
2024-03-19 20:21:53 | ERROR | stderr |     module._apply(fn)
2024-03-19 20:21:53 | ERROR | stderr |   [Previous line repeated 2 more times]
2024-03-19 20:21:53 | ERROR | stderr |   File "/home/u1024969/intel/intelpython3/envs/SakuraLLM/lib/python3.10/site-packages/torch/nn/modules/module.py", line 833, in _apply
2024-03-19 20:21:53 | ERROR | stderr |     param_applied = fn(param)
2024-03-19 20:21:53 | ERROR | stderr |   File "/home/u1024969/intel/intelpython3/envs/SakuraLLM/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1158, in convert
2024-03-19 20:21:53 | ERROR | stderr |     return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
2024-03-19 20:21:53 | ERROR | stderr | RuntimeError: Native API failed. Native API returns: -5 (PI_ERROR_OUT_OF_RESOURCES) -5 (PI_ERROR_OUT_OF_RESOURCES)
```

**Comment by Romanticoseu** [comment]
We currently do not support the Orion-14b-chat model for serving with FastChat. We recommend either trying a different model or prefixing the model path with 'bigdl' and trying again.
