### ISSUE TITLE
LLM QLoRA script issue

### ISSUE THREAD

**Issue by JeNi0310** [intel-analytics/BigDL#10476]
Hi Habana team,

I met a issue when I ran the script "qlora_finetune_llama2_70b_pvc_1550_4_card.sh" and deepspeed parameters are used.
When running the code, errors occur whenever a checkpoint step is encountered (for quick verification, I set the save checkpoint to 10 steps).
Please refer error log as below.
`Traceback (most recent call last):
  File "/home/pvc/BigDL/python/llm/example/GPU/LLM-Finetuning/QLoRA/alpaca-qlora/./alpaca_qlora_finetuning_70B.py", line 291, in <module>
    fire.Fire(train)
  File "/home/pvc/anaconda3/envs/llm/lib/python3.9/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/pvc/anaconda3/envs/llm/lib/python3.9/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/pvc/anaconda3/envs/llm/lib/python3.9/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/pvc/BigDL/python/llm/example/GPU/LLM-Finetuning/QLoRA/alpaca-qlora/./alpaca_qlora_finetuning_70B.py", line 281, in train
    trainer.train(resume_from_checkpoint=resume_from_checkpoint)
  File "/home/pvc/anaconda3/envs/llm/lib/python3.9/site-packages/transformers/trainer.py", line 1591, in train
    return inner_training_loop(
  File "/home/pvc/anaconda3/envs/llm/lib/python3.9/site-packages/transformers/trainer.py", line 1984, in _inner_training_loop
    self._maybe_log_save_evaluate(tr_loss, model, trial, epoch, ignore_keys_for_eval)
  File "/home/pvc/anaconda3/envs/llm/lib/python3.9/site-packages/transformers/trainer.py", line 2339, in _maybe_log_save_evaluate
    self._save_checkpoint(model, trial, metrics=metrics)
  File "/home/pvc/anaconda3/envs/llm/lib/python3.9/site-packages/transformers/trainer.py", line 2400, in _save_checkpoint
    self.model_wrapped.save_checkpoint(output_dir)
  File "/home/pvc/anaconda3/envs/llm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'DistributedDataParallel' object has no attribute 'save_checkpoint'
  1%|          | 10/1167 [04:14<8:10:29, 25.44s/it]`

**Comment by rnwang04** [comment]
Hi @JeNi0310 , Thank you for pointing this issue. We have reproduced it and will fix it ASAP.

**Comment by rnwang04** [comment]
Hi @JeNi0310 , we have fixed this issue, and you try deepspeed again with today's release (bigdl-llm>=2.5.0b20240321).
