### ISSUE TITLE
Run Qwen-7B-QAnything on MTL iGPU or Arc A770 get error

### ISSUE THREAD

**Issue by violet17** [intel-analytics/BigDL#10491]
log:
```
Traceback (most recent call last):
  File "D:\LLM\test_qwen.py", line 52, in <module>
    output = model.generate(input_ids,
  File "C:\Users\mi\.cache\huggingface\modules\transformers_modules\modeling_qwen.py", line 993, in generate
    return super().generate(
  File "C:\Users\mi\miniconda3\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\mi\miniconda3\lib\site-packages\transformers\generation\utils.py", line 1592, in generate
    return self.sample(
  File "C:\Users\mi\miniconda3\lib\site-packages\transformers\generation\utils.py", line 2696, in sample
    outputs = self(
  File "C:\Users\mi\miniconda3\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\mi\miniconda3\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\mi\.cache\huggingface\modules\transformers_modules\modeling_qwen.py", line 861, in forward
    transformer_outputs = self.transformer(
  File "C:\Users\mi\miniconda3\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\mi\miniconda3\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\mi\.cache\huggingface\modules\transformers_modules\modeling_qwen.py", line 744, in forward
    outputs = block(
  File "C:\Users\mi\miniconda3\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\mi\miniconda3\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\mi\.cache\huggingface\modules\transformers_modules\modeling_qwen.py", line 501, in forward
    attn_outputs = self.attn(
  File "C:\Users\mi\miniconda3\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\mi\miniconda3\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\mi\miniconda3\lib\site-packages\bigdl\llm\transformers\models\qwen.py", line 105, in qwen_attention_forward
    return forward_function(
  File "C:\Users\mi\miniconda3\lib\site-packages\bigdl\llm\transformers\models\qwen.py", line 327, in qwen_attention_forward_quantized
    invalidInputError(not self.use_flash_attn and not self.use_cache_quantization,
  File "C:\Users\mi\miniconda3\lib\site-packages\torch\nn\modules\module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'QWenAttention' object has no attribute 'use_cache_quantization'
```

model: https://modelscope.cn/models/netease-youdao/Qwen-7B-QAnything/summary
test code: https://github.com/intel-analytics/BigDL/blob/main/python/llm/example/GPU/HF-Transformers-AutoModels/Model/qwen/generate.py

version: 
bigdl-core-xe-21                        2.5.0b20240318
bigdl-llm                               2.5.0b20240318

**Comment by sgwhat** [comment]
The implementation of `Qwen-7b_QAnything` is somewhat different and not suitable for the current bigdl-llm optimization of Qwen model.
