### ISSUE TITLE
pydantic.errors.PydanticUserError: If you use `@root_validator` with pre=False (the default) 

### ISSUE THREAD

**Issue by shailesh837** [intel-analytics/BigDL#10501]
Please let me know why i am getting below error when i use langchain other package along with bigdl.llm.langchain.llms 
I am trying to use llama2:7b downloaded by ollama tool.I want to convert Natural Language to Flux Query[v2.7 InfluxDB] and back to Natural Language, **running on Intel Arc 770 GPU.**
Cod Snippet:
```
import streamlit as st
from influxdb_client import InfluxDBClient
from langchain.chains import LLMChain
from langchain.prompts import PromptTemplate
from langchain_community.chat_models import ChatOllama
from dotenv import load_dotenv
from datetime import datetime
import os, time
from llama_cpp import Llama
from langchain.callbacks.manager import CallbackManager
from langchain.callbacks.streaming_stdout import StreamingStdOutCallbackHandler
from langchain.chains import LLMChain
from langchain.prompts import PromptTemplate
from langchain_community.llms import LlamaCpp
import re
import argparse
from bigdl.llm.langchain.llms import TransformersLLM, TransformersPipelineLLM
#from langchain import PromptTemplate, LLMChain
from langchain import HuggingFacePipeline
#llm = ChatOllama(model="llama2:7b", temperature = 0.0) [ **really want to use this running on Intel Arc 770 GPU**]
llm = TransformersLLM.from_model_id(
        model_id="llama2:latest",
        model_kwargs={"temperature": 0, "max_length": 64, "trust_remote_code": True},
        **device_map='xpu'**
    )
```
**intel-extension-for-pytorch==2.1.10+xpu**
intel-opencl-rt==2024.0.2
intel-openmp==2024.0.2
**langchain==0.1.12**
```
For further information visit https://errors.pydantic.dev/2.6/u/root-validator-pre-skip
2024-03-21 23:43:13,737 - WARNING - BigdlNativeLLM has been deprecated, please switch to the new LLM API for sepcific models.
2024-03-21 23:43:13.738 Uncaught app exception
Traceback (most recent call last):
  File "/home/spandey2/LLM_SceneScape_ChatBot/llm_env/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 542, in _run_script
    exec(code, module.__dict__)
  File "/home/spandey2/LLM_SceneScape_ChatBot/SceneScape_InfluxDB_Local_LLM.py", line 18, in <module>
    from bigdl.llm.langchain.llms import TransformersLLM, TransformersPipelineLLM
  File "/home/spandey2/LLM_SceneScape_ChatBot/llm_env/lib/python3.10/site-packages/bigdl/llm/langchain/llms/__init__.py", line 26, in <module>
    from .bigdlllm import *
  File "/home/spandey2/LLM_SceneScape_ChatBot/llm_env/lib/python3.10/site-packages/bigdl/llm/langchain/llms/bigdlllm.py", line 58, in <module>
    class BigdlNativeLLM(LLM):
  File "/home/spandey2/LLM_SceneScape_ChatBot/llm_env/lib/python3.10/site-packages/bigdl/llm/langchain/llms/bigdlllm.py", line 164, in BigdlNativeLLM
    @root_validator()
  File "/home/spandey2/LLM_SceneScape_ChatBot/llm_env/lib/python3.10/site-packages/pydantic/deprecated/class_validators.py", line 237, in root_validator
    raise PydanticUserError(
pydantic.errors.PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.
```
Below example you provided as example works, if i run the  **meta-llama/Llama-2-7b-chat-hf** with your chat.py sample example as standalone, but I want to integrate above code with code above i added.
**Workign Code:**
```
python  chat.py -m meta-llama/Llama-2-7b-chat-hf -q 'I am using influxdb v2.7 version, so please consider flux query not sql query, 
Write flux query for visitor visiting booth from last 24 hours?
import argparse
from bigdl.llm.langchain.llms import TransformersLLM, TransformersPipelineLLM
from langchain import PromptTemplate, LLMChain
from langchain import HuggingFacePipeline
def main(args):
    question = args.question
    model_path = args.model_path
    template ="""{question}"""
    prompt = PromptTemplate(template=template, input_variables=["question"])
    llm = TransformersLLM.from_model_id(
        model_id=model_path,
        model_kwargs={"temperature": 0, "max_length": 64, "trust_remote_code": True},
        device_map='xpu'
    )
    llm_chain = LLMChain(prompt=prompt, llm=llm, verbose=True)
    output = llm_chain.run(question)
    print("====output=====")
    print(output)
if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='TransformersLLM Langchain Chat Example')
    parser.add_argument('-m','--model-path', type=str, required=True,
                        help='the path to transformers model')
    parser.add_argument('-q', '--question', type=str, default='What is AI?',
                        help='qustion you want to ask.')
    args = parser.parse_args()
    main(args)
```

**Comment by shailesh837** [comment]
Also I managed to get it running with python3.9 and older langchain version: langchain==0.0.184, But with even temperature=0 and prompt template clearly mentioning that we need only flux query, its generating Explanation and multiple times flux query, Also If i ask 2 question , its goes really wrong , not sure, If my code is wrong or bidl.llms TransformersLLM.from_model_id parameters:
**Question:**
How many of  people with distinct id's visited the booth from last 24 hours ?
**Response from:** 
Given the InfluxDB schema with bucket "SceneScape_LLM", measurement "booth", and fields: 
        Generate only Flux query with no explanation needed, with no title ,based on the natural language question: "How many of  people with distinct id's visited the booth from last 24 hours ??".
        Below are the Example format for a Flux query to calculate the average confidence level from last 24 hours:
        ```
        Example format for a Flux Query to calculate the distinct id from last 24 hours:
        ```
        from(bucket: "SceneScape_LLM")
        |> range(start: -24h)
        |> filter(fn: (r) => r["_measurement"] == "booth")
        |> filter(fn: (r) => r["_field"] == "id")
        |> count()
        |> yield(name: "count")
        ```
        Please provide your Flux query to answer the question "How many of  people with distinct id's visited the booth from last 24 hours ??".
        ```
        from(bucket: "SceneScape_LLM")
        |> range(start: -24h)
        |> filter(fn: (r) => r["_measurement"] == "booth")
        |> filter(fn: (r) => r["_field"] == "id")
        |> distinct()
        |> count()
        |> yield(name: "count")
        ```
        Please provide your Flux query to answer the question "How many of  people with distinct id's visited the booth from last 24 hours ??".
    ```

I'll provide the Flux query to answer the question "How many of people with distinct id's visited the booth from last 24 hours ??".

The Flux query is:
```
from(bucket: "SceneScape_LLM")
|> range(start: -24h)
|> filter(fn: (r) => r["_measurement"] == "booth")
|> filter(fn: (r) => r["_field"] == "id")
|> distinct()
|> count()
|> yield(name: "count")
```
Explanation:

* `from(bucket: "SceneScape_LLM")` specifies the InfluxDB bucket to query.
* `range(start: -24h)` specifies the time range to query, starting from 24 hours ago.
* `filter(fn: (r) => r["_measurement"] == "booth")` filters the data to only include measurements with the label "booth".
* `filter(fn: (r) => r["_field"] == "id")` filters the data to only include measurements with the field "id".
* `distinct()` groups the data by the "id" field, and removes any duplicate measurements.
* `count()` counts the number of unique measurements in the group.
* `yield(name: "count")` yields the count of unique measurements.

Note: The query assumes that the measurements with the label "booth" have the "id" field, and that the field "id" is unique for each measurement. If this is not the case, you may need to modify the query accordingly.

Code Snippet:
```
llm = TransformersLLM.from_model_id(
        model_id="meta-llama/Llama-2-7b-chat-hf",
        model_kwargs={"temperature": 0.0, "max_length": 64, "trust_remote_code": True},
        device_map='xpu'
    )
  def process_input(input_text, bucket_schema): 
    complete_query = ""
    for question in questions:
        query_prompt = PromptTemplate(
        input_variables=["question", "bucket_name", "fields", "measurement_bucket"],
        template="""
        Given the InfluxDB schema with bucket "{bucket_name}", measurement "{measurement_bucket}", and fields: {fields}
        Generate only Flux query with no explanation needed, with no title ,based on the natural language question: "{question}".
        Below are the Example format for a Flux query to calculate the average confidence level from last 24 hours:
        ```
        Example format for a Flux Query to calculate the distinct id from last 24 hours:
        ```
        from(bucket: "{bucket_name}")
        |> range(start: -24h)
        |> filter(fn: (r) => r["_measurement"] == "{measurement_bucket}")
        |> filter(fn: (r) => r["_field"] == "id")
        |> count()
        |> yield(name: "count")
        ```
        """
        )
        response_prompt = PromptTemplate(
            input_variables=["query_result", "question"],
            template="""
            Based on the following InfluxDB query result, provide the response with concise and clear answer to the original question : "{question}".

            Query Result:
            {query_result}

            Answer:
            """
        )
        query_chain = LLMChain(llm=llm, prompt=query_prompt)
        # Generate the InfluxDB query
        query = query_chain.run(
            question=question,
            bucket_name=bucket,
            measurement_bucket=measurement_bucket,
            fields=", ".join(bucket_schema)
        )
        try:
            # Extract only flux query from the response:
            response1 = query
            complete_query =  complete_query + "" + query
            # Regex pattern to find content between triple backticks
            #pattern = r"```(.*?)```"

            # Regex to find content starting with 'from' until the next triple backticks or end of string
            pattern = r"from\([^```]*\)"

            # Using re.DOTALL to make '.' match newlines as well
            match = re.findall(pattern, response1, re.DOTALL)
            # Execute the generated query
            query_result = execute_query(match[0])
            print(query_result)
            # Generate the natural language response
            response_chain = LLMChain(llm=llm, prompt=response_prompt)
            response = response_chain.run(query_result=str(query_result), question=question)
            complete_response =  complete_response + " " + response
        
        except Exception as e:
            # Handle the exception and provide an error message
            error_message = f"Error executing the query: {str(e)}"
            return complete_query, error_message

    return complete_query, complete_response
```

**Comment by hkvision** [comment]
Seems @root_validator is not compatible with langchain 0.1.12? Please take a look @shane-huang
