### ISSUE TITLE
AttributeError: 'Linear' object has no attribute 'qtype'. Did you mean: 'type'?

### ISSUE THREAD

**Issue by nazneenn** [intel-analytics/BigDL#10522]
Hello,
I am trying to port the llama2-7b inference onto Intel GPUs (Flex 170/140) from checkpoint with LoRa adapter weights. The model is finetuned on Nvidia.
```
import torch
from transformers import AutoTokenizer
from bigdl.llm.transformers import AutoModelForCausalLM
from peft import PeftConfig, PeftModel
import time
 
adapters_name = ""
 
print(f"Starting to load the model")
 
device = "xpu"
 
config = PeftConfig.from_pretrained(adapters_name)
m = AutoModelForCausalLM.from_pretrained(config.base_model_name_or_path,
                                                 load_in_4bit=True,
                                                 optimize_model=True,
                                                 trust_remote_code=True,
                                                 use_cache=True)
 
lora_model = PeftModel.from_pretrained(m, adapters_name,torch_dtype=torch.bfloat16).to(device)
tokenizer = AutoTokenizer.from_pretrained(config.base_model_name_or_path)
```
2024-03-22 10:18:39,996 - INFO - intel_extension_for_pytorch auto imported
Starting to load the model
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 11.53it/s]
2024-03-22 10:18:42,569 - INFO - Converting the current model to sym_int4 format......
Successfully loaded the model meta-llama/Llama-2-7b-chat-hf into memory
/home/intel/miniconda3/envs/bigdl-lenovo/lib/python3.10/site-packages/bigdl/llm/transformers/models/llama.py:218: UserWarning: Passing `padding_mask` is deprecated and will be removed in v4.37.Please make sure use `attention_mask` instead.`
  warnings.warn(
Traceback (most recent call last):
  File "/home/intel/nazneen/run.py", line 32, in <module>
    outputs = lora_model.generate(**inputs, do_sample=True, num_beams=1, max_new_tokens=200)
  File "/home/intel/miniconda3/envs/bigdl-lenovo/lib/python3.10/site-packages/peft/peft_model.py", line 1190, in generate
    outputs = self.base_model.generate(*args, **kwargs)
  File "/home/intel/miniconda3/envs/bigdl-lenovo/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/intel/miniconda3/envs/bigdl-lenovo/lib/python3.10/site-packages/transformers/generation/utils.py", line 1652, in generate
    return self.sample(
  File "/home/intel/miniconda3/envs/bigdl-lenovo/lib/python3.10/site-packages/transformers/generation/utils.py", line 2734, in sample
    outputs = self(
  File "/home/intel/miniconda3/envs/bigdl-lenovo/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/intel/miniconda3/envs/bigdl-lenovo/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/intel/miniconda3/envs/bigdl-lenovo/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 1038, in forward
    outputs = self.model(
  File "/home/intel/miniconda3/envs/bigdl-lenovo/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/intel/miniconda3/envs/bigdl-lenovo/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/intel/miniconda3/envs/bigdl-lenovo/lib/python3.10/site-packages/bigdl/llm/transformers/models/llama.py", line 1883, in llama_model_forward
    layer_outputs = decoder_layer(
  File "/home/intel/miniconda3/envs/bigdl-lenovo/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/intel/miniconda3/envs/bigdl-lenovo/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/intel/miniconda3/envs/bigdl-lenovo/lib/python3.10/site-packages/bigdl/llm/transformers/models/llama.py", line 228, in llama_decoder_forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/intel/miniconda3/envs/bigdl-lenovo/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/intel/miniconda3/envs/bigdl-lenovo/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/intel/miniconda3/envs/bigdl-lenovo/lib/python3.10/site-packages/bigdl/llm/transformers/models/llama.py", line 301, in llama_attention_forward_4_31
    return forward_function(
  File "/home/intel/miniconda3/envs/bigdl-lenovo/lib/python3.10/site-packages/bigdl/llm/transformers/models/llama.py", line 517, in llama_attention_forward_4_31_original
    if fp16_fusion_check(self.q_proj, hidden_states, self.training) and \
  File "/home/intel/miniconda3/envs/bigdl-lenovo/lib/python3.10/site-packages/bigdl/llm/transformers/models/utils.py", line 372, in fp16_fusion_check
    if proj.qtype != ggml_tensor_qtype["fp16"]:
  File "/home/intel/miniconda3/envs/bigdl-lenovo/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'Linear' object has no attribute 'qtype'. Did you mean: 'type'?

**Comment by Uxito-Ada** [comment]
Hi @nazneenn , instead of runtime merge, you can try an offline merge of the adapter into the origin model as shown [here](https://github.com/intel-analytics/ipex-llm/tree/main/python/llm/example/GPU/LLM-Finetuning/QA-LoRA#6-merge-the-adapter-into-the-original-model), and then load the merged one.

**Comment by nazneenn** [comment]
offline merging returns error,

Failed to merge the adapter, error: Native API failed. Native API returns: -5 (PI_ERROR_OUT_OF_RESOURCES) -5 (PI_ERROR_OUT_OF_RESOURCES).
Finish to merge the adapter into the original model and you could find the merged model in ./outputs/checkpoint-merged.

sycl-ls output,
```
[opencl:cpu:0] Intel(R) OpenCL, Intel(R) Xeon(R) Gold 6448H OpenCL 3.0 (Build 0) [2023.16.6.0.22_223734]
[opencl:cpu:1] Intel(R) OpenCL, Intel(R) Xeon(R) Gold 6448H OpenCL 3.0 (Build 0) [2023.16.12.0.12_195853.xmain-hotfix]
[opencl:gpu:2] Intel(R) OpenCL Graphics, Intel(R) Data Center GPU Flex 170 OpenCL 3.0 NEO  [23.22.26516.18]
[opencl:gpu:3] Intel(R) OpenCL Graphics, Intel(R) Data Center GPU Flex 140 OpenCL 3.0 NEO  [23.22.26516.18]
[opencl:gpu:4] Intel(R) OpenCL Graphics, Intel(R) Data Center GPU Flex 140 OpenCL 3.0 NEO  [23.22.26516.18]
[opencl:acc:5] Intel(R) FPGA Emulation Platform for OpenCL(TM), Intel(R) FPGA Emulation Device OpenCL 1.2  [2023.16.12.0.12_195853.xmain-hotfix]
[ext_oneapi_level_zero:gpu:0] Intel(R) Level-Zero, Intel(R) Data Center GPU Flex 170 1.3 [1.3.26516]
[ext_oneapi_level_zero:gpu:1] Intel(R) Level-Zero, Intel(R) Data Center GPU Flex 140 1.3 [1.3.26516]
[ext_oneapi_level_zero:gpu:2] Intel(R) Level-Zero, Intel(R) Data Center GPU Flex 140 1.3 [1.3.26516]
```

**Comment by Uxito-Ada** [comment]
> offline merging returns error,
> 
> Failed to merge the adapter, error: Native API failed. Native API returns: -5 (PI_ERROR_OUT_OF_RESOURCES) -5 (PI_ERROR_OUT_OF_RESOURCES). Finish to merge the adapter into the original model and you could find the merged model in ./outputs/checkpoint-merged.
> 
> sycl-ls output,
> 
> ```
> [opencl:cpu:0] Intel(R) OpenCL, Intel(R) Xeon(R) Gold 6448H OpenCL 3.0 (Build 0) [2023.16.6.0.22_223734]
> [opencl:cpu:1] Intel(R) OpenCL, Intel(R) Xeon(R) Gold 6448H OpenCL 3.0 (Build 0) [2023.16.12.0.12_195853.xmain-hotfix]
> [opencl:gpu:2] Intel(R) OpenCL Graphics, Intel(R) Data Center GPU Flex 170 OpenCL 3.0 NEO  [23.22.26516.18]
> [opencl:gpu:3] Intel(R) OpenCL Graphics, Intel(R) Data Center GPU Flex 140 OpenCL 3.0 NEO  [23.22.26516.18]
> [opencl:gpu:4] Intel(R) OpenCL Graphics, Intel(R) Data Center GPU Flex 140 OpenCL 3.0 NEO  [23.22.26516.18]
> [opencl:acc:5] Intel(R) FPGA Emulation Platform for OpenCL(TM), Intel(R) FPGA Emulation Device OpenCL 1.2  [2023.16.12.0.12_195853.xmain-hotfix]
> [ext_oneapi_level_zero:gpu:0] Intel(R) Level-Zero, Intel(R) Data Center GPU Flex 170 1.3 [1.3.26516]
> [ext_oneapi_level_zero:gpu:1] Intel(R) Level-Zero, Intel(R) Data Center GPU Flex 140 1.3 [1.3.26516]
> [ext_oneapi_level_zero:gpu:2] Intel(R) Level-Zero, Intel(R) Data Center GPU Flex 140 1.3 [1.3.26516]
> ```

Hi @nazneenn , it seems that your workload exceeds the max limit of GPU memory on your machine.
Could you provide the full error log? So that we can see which operation takes too much GPU memory.
And is it available to provide your adapter file so we can reproduce the issue?

**Comment by Uxito-Ada** [comment]
Hi @AdamStelmaszczyk , with the adapter file you provided, I succeed in merging it with Llama-2-7b-hf on FLEX 170
```log
Loading checkpoint shards: 100%|██████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.03s/it]
2024-03-27 00:52:09,879 - INFO - We will use 90% of the memory on device 0 for storing the model, and 10% for the buffer to avoid OOM. You can set `max_memory` in to a higher value to use more memory (at your own risk).
Using pad_token, but it is not set yet.
Using pad_token, but it is not set yet.
Finish to merge the adapter into the original model and you could find the merged model in /home/bigdl/adapter_checkpoint-merged.
```

This is my device:
```log
[opencl:acc:0] Intel(R) FPGA Emulation Platform for OpenCL(TM), Intel(R) FPGA Emulation Device OpenCL 1.2  [2023.16.10.0.17_160000]
[opencl:cpu:1] Intel(R) OpenCL, Intel(R) Xeon(R) Platinum 8480+ OpenCL 3.0 (Build 0) [2023.16.10.0.17_160000]
[opencl:gpu:2] Intel(R) OpenCL Graphics, Intel(R) Data Center GPU Flex 170 OpenCL 3.0 NEO  [23.43.27642.40]
[ext_oneapi_level_zero:gpu:0] Intel(R) Level-Zero, Intel(R) Data Center GPU Flex 170 1.3 [1.3.27642]
```

Check if any other workload at the same time or provide your full error log?

**Comment by nazneenn** [comment]
Hi @Uxito-Ada 
below is the complete error log:
```
/home/intel/miniconda3/envs/bigdl-lenovo/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: ''If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
2024-03-27 09:23:50,106 - INFO - intel_extension_for_pytorch auto imported
/home/intel/miniconda3/envs/bigdl-lenovo/lib/python3.10/site-packages/bitsandbytes/cextension.py:31: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
/home/intel/miniconda3/envs/bigdl-lenovo/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cadam32bit_grad_fp32
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.33it/s]
Failed to merge the adapter, error: [enforce fail at inline_container.cc:424] . unexpected pos 3103967040 vs 3103966928.
Finish to merge the adapter into the original model and you could find the merged model in ./outputs/checkpoint-200-merged.
```

CPU memory size :
```
intel@spr6448h:~$ free -m
               total        used        free      shared  buff/cache   available
Mem:         1031673       48732      634046         266      348894      976900
Swap:           8191           1        8190
```

**Comment by Uxito-Ada** [comment]
> Finish to merge the adapter into the original model and you could find the merged model in ./outputs/checkpoint-200-merged.

Hi @nazneenn , could you check whether the output has been written to `./outputs/checkpoint-200-merged` as shown in the log?
And your CPU memory is enough.
Did you run the [preparation steps](https://github.com/intel-analytics/ipex-llm/tree/main/python/llm/example/GPU/LLM-Finetuning/QA-LoRA#1-install) before using `export_merged_model.py`?

**Comment by nazneenn** [comment]
Hi @Uxito-Ada , the above error was caused by insufficient disk space. Now m able to merge adapter into the base model without any error.
Thank you for your active support.
