### ISSUE TITLE
SpatialFullConvolution.backward throws NullPointerException in python API

### ISSUE THREAD

**Issue by shane-huang** [intel-analytics/BigDL#1063]
Run below code snippet in jupyter throws NULL POINTER exception in `backward`.
```python
from bigdl.nn.layer import *
import numpy as np

input = np.random.randn(1,1,3,3)
print "input is :",input

m = SpatialFullConvolution(1, 2, 2, 2, 1, 1,0, 0, 0, 0, 1, False)
out = m.forward(input)
print "output m is :",np.array(out).shape

grad_out = np.empty([1,2,4,4])
grad_out.fill(0.1)

grad_in = m.backward(input,grad_out)
print "grad input of m is :",grad_in
```
Stack Trace as below
```
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-26-512a12c6babc> in <module>()
     12 grad_out.fill(0.1)
     13 
---> 14 grad_in = m.backward(input,grad_out)
     15 print "grad input of m is :",grad_in

/tmp/spark-0e09576a-6810-4a35-9f47-851f6fa697bc/userFiles-27614dc1-44e1-4b9d-adaa-ff086e2e5ba2/bigdl-0.2.0-SNAPSHOT-python-api.zip/bigdl/nn/layer.py in backward(self, input, grad_output)
    179                                self.value,
    180                                self.check_input(input),
--> 181                                self.check_input(grad_output))
    182         return self.convert_output(output)
    183 

/tmp/spark-0e09576a-6810-4a35-9f47-851f6fa697bc/userFiles-27614dc1-44e1-4b9d-adaa-ff086e2e5ba2/bigdl-0.2.0-SNAPSHOT-python-api.zip/bigdl/util/common.py in callBigDlFunc(bigdl_type, name, *args)
    306     sc = get_spark_context()
    307     api = getattr(jinstance, name)
--> 308     return callJavaFunc(sc, api, *args)
    309 
    310 

/tmp/spark-0e09576a-6810-4a35-9f47-851f6fa697bc/userFiles-27614dc1-44e1-4b9d-adaa-ff086e2e5ba2/bigdl-0.2.0-SNAPSHOT-python-api.zip/bigdl/util/common.py in callJavaFunc(sc, func, *args)
    341     """ Call Java Function """
    342     args = [_py2java(sc, a) for a in args]
--> 343     result = func(*args)
    344     return _java2py(sc, result)
    345 

/home/arda/shane/spark-1.6.3-bin-hadoop2.6/python/lib/py4j-0.9-src.zip/py4j/java_gateway.py in __call__(self, *args)
    811         answer = self.gateway_client.send_command(command)
    812         return_value = get_return_value(
--> 813             answer, self.gateway_client, self.target_id, self.name)
    814 
    815         for temp_arg in temp_args:

/home/arda/shane/spark-1.6.3-bin-hadoop2.6/python/pyspark/sql/utils.pyc in deco(*a, **kw)
     43     def deco(*a, **kw):
     44         try:
---> 45             return f(*a, **kw)
     46         except py4j.protocol.Py4JJavaError as e:
     47             s = e.java_exception.toString()

/home/arda/shane/spark-1.6.3-bin-hadoop2.6/python/lib/py4j-0.9-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    306                 raise Py4JJavaError(
    307                     "An error occurred while calling {0}{1}{2}.\n".
--> 308                     format(target_id, ".", name), value)
    309             else:
    310                 raise Py4JError(

Py4JJavaError: An error occurred while calling o47.modelBackward.
: java.lang.NullPointerException
	at com.intel.analytics.bigdl.nn.SpatialFullConvolution.updateGradInput(SpatialFullConvolution.scala:411)
	at com.intel.analytics.bigdl.nn.SpatialFullConvolution.updateGradInput(SpatialFullConvolution.scala:69)
	at com.intel.analytics.bigdl.nn.abstractnn.AbstractModule.backward(AbstractModule.scala:186)
	at com.intel.analytics.bigdl.python.api.PythonBigDL$$anonfun$modelBackward$1.apply(PythonBigDL.scala:1298)
	at com.intel.analytics.bigdl.python.api.PythonBigDL$$anonfun$modelBackward$1.apply(PythonBigDL.scala:1298)
	at com.intel.analytics.bigdl.python.api.PythonBigDL.backward(PythonBigDL.scala:1312)
	at com.intel.analytics.bigdl.python.api.PythonBigDL.modelBackward(PythonBigDL.scala:1298)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:381)
	at py4j.Gateway.invoke(Gateway.java:259)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:209)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by shane-huang** [comment]
Simiar code in scala runs without errors. 
```scala
val input = Tensor[Double](1,1,3,3).randn()
val gradOut = Tensor[Double](1,2,4,4).fill(0.1)
val m = SpatialFullConvolution[Tensor[Double],Double](1, 2, 2, 2, 1, 1,0, 0, 0, 0, 1, false)
m.forward(input)
m.backward(input,gradOut)
```
