### ISSUE TITLE
RoiPooling.forward throws type cast error in python

### ISSUE THREAD

**Issue by shane-huang** [intel-analytics/BigDL#1066]
Below code snippet causes error in python. BTW, there's no python unit test for RoiPooling layer.  
 
```python
from bigdl.nn.layer import *
import numpy as np

input_data = np.random.rand(2,2,6,8)
input_rois = np.array([0, 0, 0, 7, 5, 1, 6, 2, 7, 5, 1, 3, 1, 6, 4, 0, 3, 3, 3, 3],dtype='float64').reshape(4,5)
#print "input is :",input_data, input_rois

m = RoiPooling(3,2,1,bigdl_type='float')
out = m.forward([input_data,input_rois])
print "output of m is :",out
```
StackTrace as below:
```
creating: createRoiPooling

---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-42-9c81063d5338> in <module>()
      7 
      8 m = RoiPooling(3,2,1,bigdl_type='float')
----> 9 out = m.forward([input_data,input_rois])
     10 print "output of m is :",out

/tmp/spark-0e09576a-6810-4a35-9f47-851f6fa697bc/userFiles-27614dc1-44e1-4b9d-adaa-ff086e2e5ba2/bigdl-0.2.0-SNAPSHOT-python-api.zip/bigdl/nn/layer.py in forward(self, input)
    160                                "modelForward",
    161                                self.value,
--> 162                                self.check_input(input))
    163         return self.convert_output(output)
    164 

/tmp/spark-0e09576a-6810-4a35-9f47-851f6fa697bc/userFiles-27614dc1-44e1-4b9d-adaa-ff086e2e5ba2/bigdl-0.2.0-SNAPSHOT-python-api.zip/bigdl/util/common.py in callBigDlFunc(bigdl_type, name, *args)
    306     sc = get_spark_context()
    307     api = getattr(jinstance, name)
--> 308     return callJavaFunc(sc, api, *args)
    309 
    310 

/tmp/spark-0e09576a-6810-4a35-9f47-851f6fa697bc/userFiles-27614dc1-44e1-4b9d-adaa-ff086e2e5ba2/bigdl-0.2.0-SNAPSHOT-python-api.zip/bigdl/util/common.py in callJavaFunc(sc, func, *args)
    341     """ Call Java Function """
    342     args = [_py2java(sc, a) for a in args]
--> 343     result = func(*args)
    344     return _java2py(sc, result)
    345 

/home/arda/shane/spark-1.6.3-bin-hadoop2.6/python/lib/py4j-0.9-src.zip/py4j/java_gateway.py in __call__(self, *args)
    811         answer = self.gateway_client.send_command(command)
    812         return_value = get_return_value(
--> 813             answer, self.gateway_client, self.target_id, self.name)
    814 
    815         for temp_arg in temp_args:

/home/arda/shane/spark-1.6.3-bin-hadoop2.6/python/pyspark/sql/utils.pyc in deco(*a, **kw)
     43     def deco(*a, **kw):
     44         try:
---> 45             return f(*a, **kw)
     46         except py4j.protocol.Py4JJavaError as e:
     47             s = e.java_exception.toString()

/home/arda/shane/spark-1.6.3-bin-hadoop2.6/python/lib/py4j-0.9-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    306                 raise Py4JJavaError(
    307                     "An error occurred while calling {0}{1}{2}.\n".
--> 308                     format(target_id, ".", name), value)
    309             else:
    310                 raise Py4JError(

Py4JJavaError: An error occurred while calling o47.modelForward.
: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Float
	at scala.runtime.BoxesRunTime.unboxToFloat(BoxesRunTime.java:114)
	at com.intel.analytics.bigdl.tensor.TensorNumericMath$TensorNumeric$NumericFloat$.toType$mFc$sp(TensorNumeric.scala:154)
	at com.intel.analytics.bigdl.nn.RoiPooling.updateOutput(RoiPooling.scala:89)
	at com.intel.analytics.bigdl.nn.RoiPooling.updateOutput(RoiPooling.scala:42)
	at com.intel.analytics.bigdl.nn.abstractnn.AbstractModule.forward(AbstractModule.scala:168)
	at com.intel.analytics.bigdl.python.api.PythonBigDL$$anonfun$modelForward$1.apply(PythonBigDL.scala:1293)
	at com.intel.analytics.bigdl.python.api.PythonBigDL$$anonfun$modelForward$1.apply(PythonBigDL.scala:1293)
	at com.intel.analytics.bigdl.python.api.PythonBigDL.forward(PythonBigDL.scala:1304)
	at com.intel.analytics.bigdl.python.api.PythonBigDL.modelForward(PythonBigDL.scala:1293)
	at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:381)
	at py4j.Gateway.invoke(Gateway.java:259)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:209)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by shane-huang** [comment]
similar scala code works okay
```scala
val input_data = Tensor[Float](2,2,6,8).randn()
import com.intel.analytics.bigdl.tensor.Storage
val rois = Array(0, 0, 0, 7, 5, 1, 6, 2, 7, 5, 1, 3, 1, 6, 4, 0, 3, 3, 3, 3)
val input_rois = Tensor(Storage(rois.map(x => x.toFloat))).resize(4, 5)
val m = RoiPooling[Float](3, 2, 1)
m.forward(T(input_data,input_rois))
```

**Comment by SeaOfOcean** [comment]
maybe you can try 

```
m = RoiPooling(3,2,1.0,bigdl_type='float')
```

**Comment by shane-huang** [comment]
tried 
```python
m = RoiPooling(3,2,1.0,bigdl_type='float')
```
Still the same exception.

**Comment by zhichao-li** [comment]
@SeaOfOcean  maybe we need to refactor the code in :　BigDL/spark/dl/src/main/scala/com/intel/analytics/bigdl/nn/RoiPooling.scala .

There's duplicate code there which is just for type mapping, not sure if we can change `spatialScale` to be a Double type instead of `T` to simplify the logic.

**Comment by shane-huang** [comment]
Seems the problem is there isn't a way for scala to match existing python type into java Float.  python int will be convert to java Interger, python float will be converted to java Double. But the function signiture requires a java Double. We need either change the signiture or add a conversion before calling scala code. 
```scala
class RoiPooling[T: ClassTag](val pooledW: Int, val pooledH: Int, val spatialScale: T)
```

**Comment by SeaOfOcean** [comment]
I will change the spatialScale to Double

**Comment by SeaOfOcean** [comment]
I have tested with python code

```
input_data = np.random.rand(2,2,6,8)
input_rois = np.array([0, 0, 0, 7, 5, 1, 6, 2, 7, 5, 1, 3, 1, 6, 4, 0, 3, 3, 3, 3])
input_rois = np.reshape(rois, [4, 5])
m = RoiPooling(3,2,1.0,bigdl_type='float')
m.forward([input_data,input_rois])
```
It works with pr #1081

**Comment by SeaOfOcean** [comment]
seems it is a duplicate pr with #1078
