### ISSUE TITLE
[Unit test issue] "tensor1 should be equals tensor2" always pass even these two tensors are not equal

### ISSUE THREAD

**Issue by dding3** [intel-analytics/BigDL#1099]
I created a ut like
    val seed = 100
    RNG.setSeed(seed)
    val input = Tensor[Double](3, 32, 32).apply1(e => Random.nextDouble())
    val input2 = Tensor[Double](3, 32, 32).apply1(e => Random.nextDouble() + 2)
    input should be equals input2

which should fail, but it pass. 

Looks like "should be equals" doesn't work. I noticed lots of unit tests are using this way to check if two tensors are equal, since this way doesn't work, many unit tests cannot work as they are expected.

**Comment by qiuxin2012** [comment]
`should be equals` doesn't go to `DenseTensor.equals`, we should change to `shouldEqual`...

**Comment by qiuxin2012** [comment]
I just find another problem, If we use `should be` to compare two very big tensors, like Inception_v1's parameters who have 19,000,000 elements. ScalaTest will throw below error if the two big tensors is different.
```
Exception in thread "ScalaTest-dispatcher" java.lang.OutOfMemoryError: Requested array size exceeds VM limit
	at java.util.Arrays.copyOf(Arrays.java:2367)
	at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:130)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:114)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:415)
	at java.lang.StringBuilder.append(StringBuilder.java:132)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestReporterWithLocation.apply(ScalaTestReporterWithLocation.java:112)
	at org.scalatest.DispatchReporter$Propagator$$anonfun$run$1.apply(DispatchReporter.scala:240)
	at org.scalatest.DispatchReporter$Propagator$$anonfun$run$1.apply(DispatchReporter.scala:239)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.DispatchReporter$Propagator.run(DispatchReporter.scala:239)
	at java.lang.Thread.run(Thread.java:745)
```
I think OOM is happened when construct the error message. This error message contains the text of the two tensors, it's very very big one.

My suggestion is use `tensorA.equals(tensorB) should be (true)` instead of `tensorA should be (tensorB)` when tensorA and tensorB is huge.

**Comment by dding3** [comment]
I think it should be fine if "tensorA.equals(tensorB) should be (true)" can work as expected.

**Comment by yiheng** [comment]
Preview
My suggestion is that if the tensor is too large, the whole content of the tensor should not be print out.

Hereundefineds an example in numpy:
```python
>>> np.ndarray(shape=(100000), dtype=float)
array([ 0.,  0.,  0., ...,  0.,  0.,  0.])
```

We needn't touch this in this issue. Let me creaet another one
