### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: scala/collection/GenTraversableOnce$class

### ISSUE THREAD

**Issue by dx93** [intel-analytics/BigDL#1184]
Because I wanna acquire the time of training and synchronizing, I add some code to the file "BigDL\spark\dl\src\main\scala\com\intel\analytics\bigdl\models\lenet\Train.scala" . 
However, after I run command "bash make-dist.sh" and "source bigdl.sh", there is still something wrong.
 I guess it may be caused by the version of bigdl and scala doesn't match. But I don't know how to fix it. Is there anyone can help me? Thanks a lot! @jason-dai 
The following is the information of Error.
`Exception in thread "main" java.lang.NoClassDefFoundError: scala/collection/GenTraversableOnce$class
	at com.intel.analytics.bigdl.tensor.ArrayStorage.<init>(ArrayStorage.scala:23)
	at com.intel.analytics.bigdl.tensor.DenseTensor.<init>(DenseTensor.scala:191)
	at com.intel.analytics.bigdl.tensor.Tensor$.apply(Tensor.scala:656)
	at com.intel.analytics.bigdl.nn.SpatialConvolution.<init>(SpatialConvolution.scala:53)
	at com.intel.analytics.bigdl.nn.SpatialConvolution$.apply$mFc$sp(SpatialConvolution.scala:582)
	at com.intel.analytics.bigdl.models.lenet.LeNet5$.apply(LeNet5.scala:27)
	at com.intel.analytics.bigdl.models.lenet.Train$$anonfun$main$1.apply(Train.scala:56)
	at com.intel.analytics.bigdl.models.lenet.Train$$anonfun$main$1.apply(Train.scala:38)
	at scala.Option.map(Option.scala:146)
	at com.intel.analytics.bigdl.models.lenet.Train$.main(Train.scala:38)
	at com.intel.analytics.bigdl.models.lenet.Train.main(Train.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:738)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:187)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:212)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:126)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: scala.collection.GenTraversableOnce$class
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 20 more
`

**Comment by yiheng** [comment]
@dx93 which version of Spark are you using?

**Comment by dx93** [comment]
@yiheng Thanks for anwsering! I'm using spark 2.1.0 with scala 2.11.8. I guess errors may occur when I run "bash make-dist.sh", but don't know how to fix it.

**Comment by yiheng** [comment]
Please check this document.

https://github.com/intel-analytics/BigDL/wiki/Build-Page#build-for-spark-20-and-above

Have you tried it?

**Comment by jeisinge** [comment]
We are receiving the same error on Databricks.  The solution link is no longer valid.  What is/was the solution?

**Comment by jeisinge** [comment]
We found a workaround on Databricks.  We were attempting to link with release version of `com.intel.analytics.bigdl:bigdl-SPARK_2.2:0.5.0` per https://bigdl-project.github.io/0.5.0/#ScalaUserGuide/install-pre-built/ . Instead, we downloaded the release package from https://bigdl-project.github.io/0.5.0/#release-download/ and extracted `bigdl-SPARK_2.2-0.5.0-jar-with-dependencies.jar` to the classpath.

**Comment by yiheng** [comment]
That doc has been moved to this place:
https://bigdl-project.github.io/0.5.0/#ScalaUserGuide/install-build-src/#build-for-spark-20-and-above
