### ISSUE TITLE
ModuleNotFoundError: No module named 'vllm.distributed'

### ISSUE THREAD

**Issue by yangqing-yq** [intel-analytics/BigDL#12151]
Python 3.11.10 | packaged by conda-forge | (main, Sep 22 2024, 14:10:38) [GCC 13.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from vllm import SamplingParams
>>> from ipex_llm.vllm.xpu.engine import IPEXLLMClass as LLM
/home/wxf/miniforge3/envs/llm/lib/python3.11/site-packages/transformers/deepspeed.py:23: FutureWarning: transformers.deepspeed module is deprecated and will be removed in a future version. Please import deepspeed modules directly from transformers.integrations
  warnings.warn(
/home/wxf/miniforge3/envs/llm/lib/python3.11/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: ''If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
2024-09-30 18:40:24,346 - INFO - intel_extension_for_pytorch auto imported
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wxf/miniforge3/envs/llm/lib/python3.11/site-packages/ipex_llm/vllm/xpu/engine/__init__.py", line 16, in <module>
    from .engine import IPEXLLMAsyncLLMEngine, IPEXLLMLLMEngine, IPEXLLMClass
  File "/home/wxf/miniforge3/envs/llm/lib/python3.11/site-packages/ipex_llm/utils/ipex_importer.py", line 76, in custom_ipex_import
    return RAW_IMPORT(name, globals, locals, fromlist, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wxf/miniforge3/envs/llm/lib/python3.11/site-packages/ipex_llm/vllm/xpu/engine/engine.py", line 22, in <module>
    from ipex_llm.vllm.xpu.model_convert import _ipex_llm_convert
  File "/home/wxf/miniforge3/envs/llm/lib/python3.11/site-packages/ipex_llm/utils/ipex_importer.py", line 76, in custom_ipex_import
    return RAW_IMPORT(name, globals, locals, fromlist, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wxf/miniforge3/envs/llm/lib/python3.11/site-packages/ipex_llm/vllm/xpu/model_convert.py", line 18, in <module>
    from vllm.distributed import tensor_model_parallel_gather, tensor_model_parallel_all_gather
  File "/home/wxf/miniforge3/envs/llm/lib/python3.11/site-packages/ipex_llm/utils/ipex_importer.py", line 76, in custom_ipex_import
    return RAW_IMPORT(name, globals, locals, fromlist, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'vllm.distributed'

**Comment by QuentinVitt** [comment]
+1 

python 3.11.10 | followed the instructions for [Install ipex-llm](https://github.com/intel-analytics/ipex-llm/blob/main/docs/mddocs/Quickstart/install_linux_gpu.md#install-ipex-llm) and and then followed the [Install vllm](https://github.com/intel-analytics/ipex-llm/blob/main/docs/mddocs/Quickstart/vLLM_quickstart.md#2-install-vllm) instructions. I used the following fix for a problem i had: https://github.com/pytorch/pytorch/issues/123097#issuecomment-2050934427 and now have the same error: 

`Traceback (most recent call last):
  File "/home/quentin-vitt/vllm/offline_inference.py", line 35, in <module>
    from ipex_llm.vllm.xpu.engine import IPEXLLMClass as LLM
  File "/home/quentin-vitt/miniforge3/envs/ipex-vllm/lib/python3.11/site-packages/ipex_llm/vllm/xpu/engine/__init__.py", line 16, in <module>
    from .engine import IPEXLLMAsyncLLMEngine, IPEXLLMLLMEngine, IPEXLLMClass
  File "/home/quentin-vitt/miniforge3/envs/ipex-vllm/lib/python3.11/site-packages/ipex_llm/utils/ipex_importer.py", line 76, in custom_ipex_import
    return RAW_IMPORT(name, globals, locals, fromlist, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/quentin-vitt/miniforge3/envs/ipex-vllm/lib/python3.11/site-packages/ipex_llm/vllm/xpu/engine/engine.py", line 22, in <module>
    from ipex_llm.vllm.xpu.model_convert import _ipex_llm_convert
  File "/home/quentin-vitt/miniforge3/envs/ipex-vllm/lib/python3.11/site-packages/ipex_llm/utils/ipex_importer.py", line 76, in custom_ipex_import
    return RAW_IMPORT(name, globals, locals, fromlist, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/quentin-vitt/miniforge3/envs/ipex-vllm/lib/python3.11/site-packages/ipex_llm/vllm/xpu/model_convert.py", line 18, in <module>
    from vllm.distributed import tensor_model_parallel_gather, tensor_model_parallel_all_gather
  File "/home/quentin-vitt/miniforge3/envs/ipex-vllm/lib/python3.11/site-packages/ipex_llm/utils/ipex_importer.py", line 76, in custom_ipex_import
    return RAW_IMPORT(name, globals, locals, fromlist, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'vllm.distributed'
`

**Comment by xiangyuT** [comment]
Hi @yangqing-yq @QuentinVitt,
There is a recent update for out vllm repo but the [vllm installation instruction](https://github.com/intel-analytics/ipex-llm/blob/main/docs/mddocs/Quickstart/vLLM_quickstart.md#2-install-vllm) in our quickstart is not updated. The current branch for vllm is `0.5.4` instead of `sycl_xpu`. To update this, you could try using our docker image `intelanalytics/ipex-llm-serving-xpu:2.2.0-SNAPSHOT` or reinstall by these commands:
```
conda activate ipex-vllm
source /opt/intel/oneapi/setvars.sh
git clone -b 0.5.4 https://github.com/analytics-zoo/vllm.git
cd vllm
pip install -r requirements-xpu.txt
VLLM_TARGET_DEVICE=xpu python setup.py install
pip install mpi4py fastapi uvicorn openai
pip install gradio==4.43.0
pip install ray
```
