### ISSUE TITLE
A770运行 ipex_llm harness 跑chatglm3-6b 出现Error Message: property 'pad_token' of 'ChatGLMTokenizer' object has no setter

### ISSUE THREAD

**Issue by tao-ov** [intel-analytics/BigDL#12335]
(llm) test@test-Z590-VISION-D:~/ipexllm_whowhat/ipex-llm/python/llm/dev/benchmark/harness$ python run_llb.py --model ipex-llm --pretrained /home/test/models/LLM/haiyan-scp/chatglm3-6b/pytorch --precision sym_int4 --device xpu --tasks winogrande --batch 1 --no_cache --limit 0.1 --model_args dtype=float16
/home/test/miniforge3/envs/llm/lib/python3.11/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: ''If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
2024-11-05 15:33:52,489 - INFO - intel_extension_for_pytorch auto imported
WARNING: --limit SHOULD ONLY BE USED FOR TESTING. REAL METRICS SHOULD NOT BE COMPUTED USING LIMIT.
Selected Tasks: ['winogrande']
The repository for /home/test/models/LLM/haiyan-scp/chatglm3-6b/pytorch contains custom code which must be executed to correctly load the model. You can inspect the repository content at https://hf.co//home/test/models/LLM/haiyan-scp/chatglm3-6b/pytorch.
You can avoid this prompt in future by passing the argument `trust_remote_code=True`.

Do you wish to run the custom code? [y/N] y
Job config of task=winogrande, precision=sym_int4 failed. Error Message: property 'pad_token' of 'ChatGLMTokenizer' object has no setter
Here are results of all successful tasks:
Traceback (most recent call last):
  File "/home/test/ipexllm_whowhat/ipex-llm/python/llm/dev/benchmark/harness/run_llb.py", line 151, in <module>
    main()
  File "/home/test/ipexllm_whowhat/ipex-llm/python/llm/dev/benchmark/harness/run_llb.py", line 147, in main
    raise RuntimeError('\n'.join(fail))
RuntimeError: Job config of task=winogrande, precision=sym_int4 failed. Error Message: property 'pad_token' of 'ChatGLMTokenizer' object has no setter
![image](https://github.com/user-attachments/assets/4c609a7a-6636-4e44-ad30-b5502154389d)

**Comment by cranechu0131** [comment]
Hi tao-ov,

Please refer to this https://github.com/chatchat-space/Langchain-Chatchat/issues/1835, and update your [tokenization_chatglm.py](https://huggingface.co/THUDM/chatglm2-6b/blob/main/tokenization_chatglm.py)
 in your model folder, this ought to solve this issue.
