### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by zhpmatrix** [intel-analytics/BigDL#1242]
When I used pip to install BigDL, there were two versions I could choose, thus I installed BigDL with dev.

My code is as follows:

model.add(Reshape([embedding_dim, 1, sequence_len]))
model.add(SpatialConvolution(embedding_dim, 128, 5, 1))
model.add(ReLU())
model.add(SpatialMaxPooling(5, 1, 5, 1))

To debug code line by line, I got the results:

Reshape,ReLU,SpatialMaxPooling were added successfully except SpatialConvolution. The error information is as follows:

py4j.protocol.Py4JJavaError: An error occurred while calling o25.createSpatialConvolution.
: java.lang.NoClassDefFoundError: scala/collection/GenTraversableOnce$class
	at com.intel.analytics.bigdl.tensor.ArrayStorage.<init>(ArrayStorage.scala:23)
	at com.intel.analytics.bigdl.tensor.DenseTensor.<init>(DenseTensor.scala:191)
	at com.intel.analytics.bigdl.tensor.Tensor$.apply(Tensor.scala:722)
	at com.intel.analytics.bigdl.nn.SpatialConvolution.<init>(SpatialConvolution.scala:67)
	at com.intel.analytics.bigdl.nn.SpatialConvolution$.apply(SpatialConvolution.scala:631)
	at com.intel.analytics.bigdl.python.api.PythonBigDL.createSpatialConvolution(PythonBigDL.scala:324)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:237)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:128)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:211)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: scala.collection.GenTraversableOnce$class
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 17 more

To explore the problem, I use the command as follows:

scala -cp bigdl-0.2.0-SNAPSHOT-jar-with-dependencies.jar

bigdl-0.2.0-SNAPSHOT-jar-with-dependencies.jar is the file from BigDL with dev when I use pip tool to install the lib. When I run the code as follows:

val sconv = new nn.SpatialConvolution\[Float\](1,2,3,4)

I get the error information:

error: missing or invalid dependency detected while loading class file 'Tensor.class'.
Could not access term mllib in package org.apache.spark,
because it (or its dependencies) are missing. Check your build definition for
missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic classpath.)
A full rebuild may help if 'Tensor.class' was compiled against an incompatible version of org.apache.spark.

Rebudding the latest code is the best method to solve problem?

**Comment by dding3** [comment]
For java.lang.NoClassDefFoundError: scala/collection/GenTraversableOnce$class, it's be caused by wrong spark version used. Are you using spark >= 2.0, if that's the case, please use spark < 2.0.0. 

For the exception in scala which complains "Could not access term mllib in package org.apache.spark", please use "bigdl-0.2.0-SNAPSHOT-jar-with-dependencies-and-spark.jar".  It's not a frequently used jar,  so it's not installed with pip, you need build BigDL yourself and it can be found under "$BigDL_HOME/spark/dl/target"

@zhichao-li our documents and Bigbig in pypi claims requires spark>= 2.0.0, but actually it works for spark < 2.0.0, update documents? or update the jar in Bigbig?

**Comment by dding3** [comment]
BTW, I tried your code with spark < 2.0.0 and it works for me.

**Comment by zhichao-li** [comment]
Currently  pypi package only support Spark 1.6.3 as the version limitation on Pypi.  We would upgrade to Spark2.2 shortly as pyspark2.2 has been ready in pypi.

Please refer to this instruction page: https://github.com/intel-analytics/BigDL/blob/master/docs/docs/PythonSupport/python-install.md
