### ISSUE TITLE
Got the following error when trying to run run.example.sh --model vgg

### ISSUE THREAD

**Issue by bigdataexplorer** [intel-analytics/BigDL#1281]
Exception in thread "main" java.lang.NoSuchMethodError: scala.runtime.IntRef.create(I)Lscala/runtime/IntRef;
        at scopt.OptionParser.parse(options.scala:306)
        at com.intel.analytics.bigdl.models.vgg.Train$.main(Train.scala:35)
        at com.intel.analytics.bigdl.models.vgg.Train.main(Train.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

I am running Spark 2.1.1 on EMR

**Comment by bigdataexplorer** [comment]
Figured out the issue. Has to run Spark 2.0.2 on EMR when specifying  --spark spark_2.0
