### ISSUE TITLE
Compile error with Spark 2.2.0 / BlockManager.getLocalBytes changed in Spark 2.2.0

### ISSUE THREAD

**Issue by srowen** [intel-analytics/BigDL#1292]
```
mvn -Pspark_2.x -Dspark.version=2.2.0 clean compile
...
[error] /Users/srowen/Documents/Cloudera/BigDL/spark/dl/src/main/scala/com/intel/analytics/bigdl/parameters/AllReduceParameter.scala:194: type mismatch;
[error]  found   : Object
[error]  required: org.apache.spark.util.io.ChunkedByteBuffer
[error]               val localBuffer = BlockManagerWrapper.byteBufferConvert(weightBuffer)
[error]                                                                       ^
[error] /Users/srowen/Documents/Cloudera/BigDL/spark/dl/src/main/scala/com/intel/analytics/bigdl/parameters/AllReduceParameter.scala:229: type mismatch;
[error]  found   : Object
[error]  required: org.apache.spark.util.io.ChunkedByteBuffer
[error]               .getOrElse(bm.getRemoteBytes(blockId).get))
[error]         
```

The signature of `BlockManager.getLocalBytes` changed from Spark 2.1.x to Spark 2.2.0 in https://github.com/apache/spark/commit/b56ad2b1ec19fd60fa9d4926d12244fd3f56aca4 . 

I know that's not how BigDL is built, but it ends up causing problems at runtime. For example, @nishamuktewar noted this happens when you run on CDH 5.12 + Spark 2.2:

```
ERROR optim.DistriOptimizer$: Error: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 11.0 failed 4 times, most recent failure: Lost task 0.3 in stage 11.0 (TID 40, bottou02.sjc.cloudera.com, executor 2): java.util.concurrent.ExecutionException: java.lang.ClassCastException: org.apache.spark.storage.ByteBufferBlockData cannot be cast to org.apache.spark.util.io.ChunkedByteBuffer
  at java.util.concurrent.FutureTask.report(FutureTask.java:122)
  at java.util.concurrent.FutureTask.get(FutureTask.java:192)
  at com.intel.analytics.bigdl.parameters.FutureResult$$anonfun$waitResult$1.apply(AllReduceParameter.scala:244)
  at com.intel.analytics.bigdl.parameters.FutureResult$$anonfun$waitResult$1.apply(AllReduceParameter.scala:244)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.Iterator$class.foreach(Iterator.scala:893)
  at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
...
```

I think the fix is just to push this reference to `BlockManager` into `BlockManagerWrapper` and use reflection as needed to patch over the difference.

**Comment by yiheng** [comment]
@srowen thanks for reporting this. We haven't test BigDL on Spark 2.2. We will handle it.

**Comment by srowen** [comment]
I have a pull request ready, just testing that it builds.

**Comment by songhappy** [comment]
please use your local spark version to 2.0, this problem should be resolved.
