### ISSUE TITLE
error when running BigDL with Python 3.6

### ISSUE THREAD

**Issue by hhbyyh** [intel-analytics/BigDL#1293]
using Python 3.6.1 |Anaconda 4.4.0 (64-bit)

Need specific documentation if we don't support Python 3.6

pip3 install BigDL==0.2.0.dev3
python

from bigdl.util.common import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yuhao/anaconda3/lib/python3.6/site-packages/bigdl/util/common.py", line 24, in <module>
    from pyspark import RDD, SparkContext
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "/home/yuhao/tmp/bigDLTest/spark-1.6.3-bin-hadoop2.6/python/lib/pyspark.zip/pyspark/__init__.py", line 41, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "/home/yuhao/tmp/bigDLTest/spark-1.6.3-bin-hadoop2.6/python/lib/pyspark.zip/pyspark/context.py", line 37, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "/home/yuhao/tmp/bigDLTest/spark-1.6.3-bin-hadoop2.6/python/lib/pyspark.zip/pyspark/rdd.py", line 47, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "/home/yuhao/tmp/bigDLTest/spark-1.6.3-bin-hadoop2.6/python/lib/pyspark.zip/pyspark/statcounter.py", line 24, in <module>
  File "/home/yuhao/anaconda3/lib/python3.6/site-packages/numpy/__init__.py", line 146, in <module>
    from . import add_newdocs
  File "/home/yuhao/anaconda3/lib/python3.6/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/home/yuhao/anaconda3/lib/python3.6/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/home/yuhao/anaconda3/lib/python3.6/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/home/yuhao/anaconda3/lib/python3.6/site-packages/numpy/core/__init__.py", line 72, in <module>
    from numpy.testing.nosetester import _numpy_tester
  File "/home/yuhao/anaconda3/lib/python3.6/site-packages/numpy/testing/__init__.py", line 10, in <module>
    from unittest import TestCase
  File "/home/yuhao/anaconda3/lib/python3.6/unittest/__init__.py", line 58, in <module>
    from .result import TestResult
  File "/home/yuhao/anaconda3/lib/python3.6/unittest/result.py", line 7, in <module>
    from . import util
  File "/home/yuhao/anaconda3/lib/python3.6/unittest/util.py", line 119, in <module>
    _Mismatch = namedtuple('Mismatch', 'actual expected value')
  File "/home/yuhao/tmp/bigDLTest/spark-1.6.3-bin-hadoop2.6/python/lib/pyspark.zip/pyspark/serializers.py", line 381, in namedtuple
TypeError: namedtuple() missing 3 required keyword-only arguments: 'verbose', 'rename', and 'module'

**Comment by zhichao-li** [comment]
add doc saying we only tested against python2.7 and python3.5, but looks like it's an issue related to numpy version.

**Comment by hkvision** [comment]
https://issues.apache.org/jira/browse/SPARK-19019
This seems to be the conflict between python 3.6 and spark.
It has been resolved after spark 2.1.1.

**Comment by zhichao-li** [comment]
As the jira suggested, python3.6 only works with Spark 1.6.4, 2.0.3, 2.1.1, 2.2.0. We need to upgrade Spark version in Jenkins if we want to add python3.6 into the workflow.
