### ISSUE TITLE
There's exception if the total sample number cannot be divided by the batch_size.

### ISSUE THREAD

**Issue by zhichao-li** [intel-analytics/BigDL#1415]
If the total sample number cannot be divided by the batch_size. we would see bellowing exception.

Caused by: java.lang.IllegalArgumentException: requirement failed: invalid size: 1 == 2
	at scala.Predef$.require(Predef.scala:233)
	at com.intel.analytics.bigdl.tensor.DenseTensor.valueAt(DenseTensor.scala:520)
	at com.intel.analytics.bigdl.nn.ClassNLLCriterion$$anonfun$updateOutput$4.apply(ClassNLLCriterion.scala:100)
	at com.intel.analytics.bigdl.nn.ClassNLLCriterion$$anonfun$updateOutput$4.apply(ClassNLLCriterion.scala:99)
	at com.intel.analytics.bigdl.utils.ThreadPool$$anonfun$invoke$2.apply(ThreadPool.scala:162)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at com.intel.analytics.bigdl.utils.ThreadPool$$anon$1.execute(ThreadPool.scala:203)
	at scala.concurrent.impl.Future$.apply(Future.scala:31)
	at scala.concurrent.Future$.apply(Future.scala:485)
	at com.intel.analytics.bigdl.utils.ThreadPool.invoke(ThreadPool.scala:168)
	at com.intel.analytics.bigdl.nn.ClassNLLCriterion.updateOutput(ClassNLLCriterion.scala:99)
	at com.intel.analytics.bigdl.nn.ClassNLLCriterion.updateOutput(ClassNLLCriterion.scala:60)
	at com.intel.analytics.bigdl.nn.abstractnn.AbstractCriterion.forward(AbstractCriterion.scala:70)
	at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$6$$anonfun$7$$anonfun$apply$2.apply$mcI$sp(DistriOptimizer.scala:205)
	at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$6$$anonfun$7$$anonfun$apply$2.apply(DistriOptimizer.scala:197)
	at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$6$$anonfun$7$$anonfun$apply$2.apply(DistriOptimizer.scala:197)
	at com.intel.analytics.bigdl.utils.ThreadPool$$anonfun$1$$anon$4.call(ThreadPool.scala:112)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)

**Comment by zhichao-li** [comment]
cc @qiuxin2012

**Comment by qiuxin2012** [comment]
May because auto-batching convert target to a 2D tensor.

**Comment by qiuxin2012** [comment]
No a bug, but it's really an unreadable error message. I will fix it.

Sample's `target` for ClassNLLCriterion is one Int, but zhichao put a 2-element tensor to the `Sample`.
It's an illegal target size for ClassNLLCriterion. But ClassNLLCriterion can't throw a readable error message.
