### ISSUE TITLE
bigdl setting enviroment.    Py4JJavaError: An error occurred while calling None.org.apache.spark.api.java.JavaSparkContext.

### ISSUE THREAD

**Issue by brucebismarck** [intel-analytics/BigDL#1425]
I built two workers one master cluster in AWS. installed bigDL under python 3.4.

I run this code 
import pandas
import datetime as dt

from bigdl.nn.layer import *
from bigdl.nn.criterion import *
from bigdl.optim.optimizer import *
from bigdl.util.common import *
from bigdl.dataset.transformer import *

init_engine()
it reports following error when I run init_engine() no matter from Jupyter nor command line.

Py4JJavaError: An error occurred while calling None.org.apache.spark.api.java.JavaSparkContext.
: org.apache.spark.SparkException: Found both spark.executor.extraClassPath and SPARK_CLASSPATH. Use only the former.
	at org.apache.spark.SparkConf$$anonfun$validateSettings$7$$anonfun$apply$8.apply(SparkConf.scala:560)
	at org.apache.spark.SparkConf$$anonfun$validateSettings$7$$anonfun$apply$8.apply(SparkConf.scala:558)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.apache.spark.SparkConf$$anonfun$validateSettings$7.apply(SparkConf.scala:558)
	at org.apache.spark.SparkConf$$anonfun$validateSettings$7.apply(SparkConf.scala:546)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.SparkConf.validateSettings(SparkConf.scala:546)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:376)
	at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:236)
	at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
	at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:748)

If i run sc = SparkContext.getOrCreate(conf=create_spark_conf()) . It will report same error

**Comment by zhichao-li** [comment]
@brucebismarck  wondering how did you install BigDL , which BigDL version did you base on and could you share the launching script with us ? then we can take a look and try to reproduce it on our side.

**Comment by brucebismarck** [comment]
@zhichao-li  hi I used pip to install BigDL. I tried both 0.1.2 and 0.2.0. My spark version is 2.2. To my understanding, BigDL doesn't support cluster computing for spark version > 1.6 right?


I'm confused what do you mean launching script?

**Comment by zhichao-li** [comment]
There's a link you can follow on how to launch bigdl locally via pip.
https://bigdl-project.github.io/master/#PythonSupport/run-from-pip/
As the published pip package is compiled against Spark1.6, so "pip install" would only work for Spark1.6.x for now. 
If you want to try distributed training, you should follow this link:
https://bigdl-project.github.io/master/#PythonSupport/run-without-pip/
