### ISSUE TITLE
Error during loading caffe VGG model

### ISSUE THREAD

**Issue by hhbyyh** [intel-analytics/BigDL#1528]
vgg caffe model from https://github.com/BVLC/caffe/wiki/Model-Zoo#models-used-by-the-vgg-team-in-ilsvrc-2014 , both vgg-16 and vgg-19 met the same error.

code:
```
    val caffeModel =
      Module.loadCaffeModel(
        "/home/yuhao/workspace/github/hhbyyh/RealEstateImage/model/VGG_ILSVRC_16_layers.prototxt",
        "/home/yuhao/workspace/github/hhbyyh/RealEstateImage/model/VGG_ILSVRC_16_layers.caffemodel")
```

error:
```
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 1
	at java.util.Collections$EmptyList.get(Collections.java:4454)
	at caffe.Caffe$BlobShape.getDim(Caffe.java:248)
	at com.intel.analytics.bigdl.utils.caffe.V1LayerConverter.fromCaffeConvolution(V1LayerConverter.scala:48)
	at com.intel.analytics.bigdl.utils.caffe.Converter$$anonfun$init$1.apply(Converter.scala:573)
	at com.intel.analytics.bigdl.utils.caffe.Converter$$anonfun$init$1.apply(Converter.scala:573)
	at com.intel.analytics.bigdl.utils.caffe.Converter.convertLayerFromCaffe(Converter.scala:71)
	at com.intel.analytics.bigdl.utils.caffe.CaffeLoader.com$intel$analytics$bigdl$utils$caffe$CaffeLoader$$convertCaffeLayer(CaffeLoader.scala:389)
	at com.intel.analytics.bigdl.utils.caffe.CaffeLoader$$anonfun$createLayers$3.apply(CaffeLoader.scala:342)
	at com.intel.analytics.bigdl.utils.caffe.CaffeLoader$$anonfun$createLayers$3.apply(CaffeLoader.scala:314)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at com.intel.analytics.bigdl.utils.caffe.CaffeLoader.createLayers(CaffeLoader.scala:314)
	at com.intel.analytics.bigdl.utils.caffe.CaffeLoader.createCaffeModel(CaffeLoader.scala:270)
	at com.intel.analytics.bigdl.utils.caffe.CaffeLoader$.loadCaffe(CaffeLoader.scala:482)
	at com.intel.analytics.bigdl.nn.Module$.loadCaffeModel(Module.scala:79)
	at org.apache.spark.ml.linalg.SimilarityEvaluation$.getVGGFeaturesFromImage(SimilarityEvaluation.scala:188)
	at org.apache.spark.ml.linalg.SimilarityEvaluation$.main(SimilarityEvaluation.scala:38)
	at org.apache.spark.ml.linalg.SimilarityEvaluation.main(SimilarityEvaluation.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

**Comment by yiheng** [comment]
@SeaOfOcean can you please take a look at this?

**Comment by SeaOfOcean** [comment]
@hhbyyh can you try with #1530 ? And let me know if it can solve your problem.
I have tested with the model file mentioned above.
