### ISSUE TITLE
LookupTable will throw an Unreadable error message when input is illegal

### ISSUE THREAD

**Issue by qiuxin2012** [intel-analytics/BigDL#1583]
java.lang.IllegalArgumentException: requirement failed: -1 out of range 0 to 10
	at scala.Predef$.require(Predef.scala:224)
	at com.intel.analytics.bigdl.tensor.DenseTensor$.select(DenseTensor.scala:2313)
	at com.intel.analytics.bigdl.tensor.DenseTensor.select(DenseTensor.scala:377)
	at com.intel.analytics.bigdl.tensor.DenseTensor.index(DenseTensor.scala:1956)
	at com.intel.analytics.bigdl.nn.LookupTable.updateOutput(LookupTable.scala:174)
	at com.intel.analytics.bigdl.nn.LookupTable.updateOutput(LookupTable.scala:44)

**Comment by qiuxin2012** [comment]
LookupTable[embedding_1](1000, 8, 0.0, 1.7976931348623157E308, 2.0) ,  please also fix the default parameter
