### ISSUE TITLE
Some Graph backward issue

### ISSUE THREAD

**Issue by SeaOfOcean** [intel-analytics/BigDL#1592]
```
"graph backward" should "work" in {
    val data = Input()
    data.element.setName("data")
    val imInfo = Input()
    imInfo.element.setName("imInfo")
    val gt = Input()
    gt.element.setName("gt")
    val reshpe = InferReshape(Array(2, -1, 0)).setName("rs").inputs(data)
    val id0 = Identity().setName("id0").inputs(reshpe)
    val id1 = Identity().setName("id1").inputs(gt)
    val id2 = Identity().inputs(imInfo)
    val ct = ConcatTable().setName("ct").inputs(imInfo, gt, id0)
    val id3 = Identity().inputs(data)

    val graph = Graph(Array(data, imInfo, gt), Array(id0, ct, id3))

    val input = T(Tensor[Float](2, 3, 2, 4), Tensor[Float](1, 4), Tensor[Float](2, 7))

    graph.forward(input)
    graph.backward(input, graph.output)
  }
```

It throws
```
key not found: 1
java.util.NoSuchElementException: key not found: 1
	at scala.collection.MapLike$class.default(MapLike.scala:228)
	at scala.collection.AbstractMap.default(Map.scala:59)
	at scala.collection.mutable.HashMap.apply(HashMap.scala:65)
	at com.intel.analytics.bigdl.utils.Table.apply(Table.scala:91)
	at com.intel.analytics.bigdl.nn.Graph$$anonfun$backward$2.apply(Graph.scala:129)
	at com.intel.analytics.bigdl.nn.Graph$$anonfun$backward$2.apply(Graph.scala:124)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at com.intel.analytics.bigdl.nn.Graph.backward(Graph.scala:124)

```

Another example is

```
"graph backward" should "work" in {
    val data = Input()
    data.element.setName("data")
    val imInfo = Input()
    imInfo.element.setName("imInfo")
    val gt = Input()
    val reshpe = InferReshape(Array(2, -1, 0)).inputs(data)
    val id0 = Identity().setName("id0").inputs(reshpe)
    val id1 = Identity().setName("id1").inputs(gt)
    val id2 = Identity().inputs(imInfo)
    val id3 = Identity().inputs(data)

    val graph = Graph(Array(data, imInfo, gt), Array(id0, id1, id2, id3))
    graph.stopGradient(Array("id0"))

    val input = T(Tensor[Float](2, 3, 2, 4), Tensor[Float](1, 4), Tensor[Float](2, 7))

    graph.forward(input)
    graph.backward(input, graph.output)
  }
```

It throws

```
requirement failed: Some output nodes have not been executed
java.lang.IllegalArgumentException: requirement failed: Some output nodes have not been executed
	at scala.Predef$.require(Predef.scala:224)
	at com.intel.analytics.bigdl.nn.Scheduler$$anonfun$isFinished$1.apply(Scheduler.scala:70)
	at com.intel.analytics.bigdl.nn.Scheduler$$anonfun$isFinished$1.apply(Scheduler.scala:69)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
	at com.intel.analytics.bigdl.nn.Scheduler.isFinished(Scheduler.scala:69)
	at com.intel.analytics.bigdl.nn.Graph.backward(Graph.scala:119)
```

**Comment by yiheng** [comment]
For the first one, I think it's a bug in ConcatTable. You should add a layer into ConcatTable.
```scala
val ct = ConcatTable().setName("ct").add(Identity()).inputs(imInfo, gt, id0)
```

Anyway, ConcatTable should check if the submodules length before proceeding. Have fixed it.
