### ISSUE TITLE
Save huge model will throw OOMError

### ISSUE THREAD

**Issue by qiuxin2012** [intel-analytics/BigDL#1645]
```
val model = Linear(262144, 1024)
model.save("model.obj")
```

```
An exception or error caused a run to abort. 
java.lang.OutOfMemoryError
	at java.io.ByteArrayOutputStream.hugeCapacity(ByteArrayOutputStream.java:123)
	at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:117)
	at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
	at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:153)
	at java.io.ObjectOutputStream$BlockDataOutputStream.drain(ObjectOutputStream.java:1877)
	at java.io.ObjectOutputStream$BlockDataOutputStream.setBlockDataMode(ObjectOutputStream.java:1786)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1189)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at com.intel.analytics.bigdl.utils.File$.save(File.scala:71)
	at com.intel.analytics.bigdl.nn.abstractnn.AbstractModule.save(AbstractModule.scala:423)
```

**Comment by wzhongyuan** [comment]
did this use the java based serialization ?

**Comment by qiuxin2012** [comment]
@wzhongyuan Yes, It doesn't matter If you could provide another approach for saving&loading.
