### ISSUE TITLE
[0.3 release test] NoClassDefFoundError exception met when running lenetLocal 

### ISSUE THREAD

**Issue by dding3** [intel-analytics/BigDL#1709]
I followed https://bigdl-project.github.io/master/#ScalaUserGuide/run/#run-as-a-local-javascala-program to run lenetLocal, command is "java -cp xxxx" and below is the exception:
Exception in thread "main" java.lang.NoClassDefFoundError: scala/reflect/api/TypeCreator
        at com.intel.analytics.bigdl.models.lenet.LeNet5$.apply(LeNet5.scala:26)
        at com.intel.analytics.bigdl.example.lenetLocal.Train$$anonfun$main$1.apply(Train.scala:51)
        at com.intel.analytics.bigdl.example.lenetLocal.Train$$anonfun$main$1.apply(Train.scala:37)
        at scala.Option.map(Option.scala:145)

If I change the command to "scala -cp xxxx", it can work. Looks like we need to fix the exception or update the document to clarify that lenetlocal should run with scala.

**Comment by jason-dai** [comment]
@jenniew please take a look

**Comment by jenniew** [comment]
This issue is caused by scala-reflect dependency is excluded in scalatest dependency. Although it is added in BigDL/pom.xml, it is not in build jar file.
