### ISSUE TITLE
[0.3 release test] Modify README file of language model: java OutOfMemory Error

### ISSUE THREAD

**Issue by hkvision** [intel-analytics/BigDL#1724]
https://github.com/intel-analytics/BigDL/tree/master/spark/dl/src/main/scala/com/intel/analytics/bigdl/example/languagemodel 
I follow the README file to run the language model example.
Wondering several points:
1. `--overWriteCheckpoint` unknown option?
2. do we need to create `$HOME/model` manually?
3. When using spark-submit to run the example, I got OutOfMemory Error:
Caused by: Layer info: Graph[2b9ea77b]/Recurrent[29a74bfb]ArrayBuffer(TimeDistributed[5ee64020]Linear[468a879f](1500 -> 6000), LSTM(1500, 1500, 0.0))
java.lang.OutOfMemoryError: Java heap space

    at com.intel.analytics.bigdl.nn.abstractnn.AbstractModule.forward(AbstractModule.scala:286)
    at com.intel.analytics.bigdl.nn.Graph.updateOutput(Graph.scala:107)
    at com.intel.analytics.bigdl.nn.abstractnn.AbstractModule.forward(AbstractModule.scala:280)
    at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$8$$anonfun$9$$anonfun$apply$2.apply$mcI$sp(DistriOptimizer.scala:223)
    at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$8$$anonfun$9$$anonfun$apply$2.apply(DistriOptimizer.scala:216)
    at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$8$$anonfun$9$$anonfun$apply$2.apply(DistriOptimizer.scala:216)
    at com.intel.analytics.bigdl.utils.ThreadPool$$anonfun$1$$anon$4.call(ThreadPool.scala:112)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    ... 3 more

Even though I add `--driver-memory 10g \` & `--executor-memory 20g \`, I still got this error.
Anything I can take care of to avoid this error?

**Comment by zhangxiaoli73** [comment]
1. if you set --overWriteCheckpoint， it meas do overwrite, same as other examples.
2. yeah, you have to create $HOME/model manually
3. I think OutofMemory is caused by large batchSize. Please change batchSize to 2*total cores.

**Comment by hkvision** [comment]
Fine.

**Comment by hkvision** [comment]
Maybe modify the following:
1. `--hiddenSize` -> `--hidden`  in readme
2. `--overWriteCheckpoint` -> `--overWrite` in readme
3. Add `-r` = `--learningRate` in readme   (since in the example command we use `-r` but in the explanation we only have `--learningRate`
4. Maybe add a remark to guide users what to do when encountering OutofMemory Error?
