### ISSUE TITLE
[0.3 release] Run with pip install exception BigDL==0.3.0rc2

### ISSUE THREAD

**Issue by SeaOfOcean** [intel-analytics/BigDL#1732]
```
>>> from bigdl.util.common import *
Prepending /usr/local/lib/python2.7/dist-packages/bigdl/share/conf/spark-bigdl.conf to sys.path
>>> from pyspark import SparkContext
>>> from bigdl.nn.layer import *
>>> import bigdl.version
>>> 
>>> # create sparkcontext with bigdl configuration
... sc = SparkContext.getOrCreate(conf=create_spark_conf()) 
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/apache/spark/launcher/Main : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pyspark/context.py", line 334, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/usr/local/lib/python2.7/dist-packages/pyspark/context.py", line 115, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/usr/local/lib/python2.7/dist-packages/pyspark/context.py", line 283, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
  File "/usr/local/lib/python2.7/dist-packages/pyspark/java_gateway.py", line 95, in launch_gateway
    raise Exception("Java gateway process exited before sending the driver its port number")
Exception: Java gateway process exited before sending the driver its port number
>>> init_engine() # prepare the bigdl environment 
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/apache/spark/launcher/Main : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/bigdl/util/common.py", line 255, in init_engine
    callBigDlFunc(bigdl_type, "initEngine")
  File "/usr/local/lib/python2.7/dist-packages/bigdl/util/common.py", line 341, in callBigDlFunc
    jinstance = JavaCreator.instance(bigdl_type=bigdl_type).value
  File "/usr/local/lib/python2.7/dist-packages/bigdl/util/common.py", line 51, in instance
    cls._instance = cls(bigdl_type)
  File "/usr/local/lib/python2.7/dist-packages/bigdl/util/common.py", line 69, in __init__
    sc = get_spark_context()
  File "/usr/local/lib/python2.7/dist-packages/bigdl/util/common.py", line 324, in get_spark_context
    return SparkContext.getOrCreate(conf=conf or create_spark_conf())
  File "/usr/local/lib/python2.7/dist-packages/pyspark/context.py", line 334, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/usr/local/lib/python2.7/dist-packages/pyspark/context.py", line 115, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/usr/local/lib/python2.7/dist-packages/pyspark/context.py", line 283, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
  File "/usr/local/lib/python2.7/dist-packages/pyspark/java_gateway.py", line 95, in launch_gateway
    raise Exception("Java gateway process exited before sending the driver its port number")
Exception: Java gateway process exited before sending the driver its port number
>>> bigdl.version.__version__ # Get the current BigDL version
'0.3.0rc2'
>>> linear = Linear(2, 3) # Try to create a Linear layer
creating: createLinear
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/apache/spark/launcher/Main : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/bigdl/nn/layer.py", line 724, in __init__
    JTensor.from_ndarray(init_grad_bias))
  File "/usr/local/lib/python2.7/dist-packages/bigdl/nn/layer.py", line 66, in __init__
    bigdl_type, JavaValue.jvm_class_constructor(self), *args)
  File "/usr/local/lib/python2.7/dist-packages/bigdl/util/common.py", line 341, in callBigDlFunc
    jinstance = JavaCreator.instance(bigdl_type=bigdl_type).value
  File "/usr/local/lib/python2.7/dist-packages/bigdl/util/common.py", line 51, in instance
    cls._instance = cls(bigdl_type)
  File "/usr/local/lib/python2.7/dist-packages/bigdl/util/common.py", line 69, in __init__
    sc = get_spark_context()
  File "/usr/local/lib/python2.7/dist-packages/bigdl/util/common.py", line 324, in get_spark_context
    return SparkContext.getOrCreate(conf=conf or create_spark_conf())
  File "/usr/local/lib/python2.7/dist-packages/pyspark/context.py", line 334, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/usr/local/lib/python2.7/dist-packages/pyspark/context.py", line 115, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/usr/local/lib/python2.7/dist-packages/pyspark/context.py", line 283, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
  File "/usr/local/lib/python2.7/dist-packages/pyspark/java_gateway.py", line 95, in launch_gateway
    raise Exception("Java gateway process exited before sending the driver its port number")
Exception: Java gateway process exited before sending the driver its port number
```

**Comment by zhichao-li** [comment]
You get this error because a Java 7 VM tries to load a class compiled for Java 8.

Maybe we need to unify our JDK environment in our document

**Comment by SeaOfOcean** [comment]
change to Java 8 solves the problem

**Comment by jason-dai** [comment]
Need to update our pip install doc
