### ISSUE TITLE
Run python test on spark1.6.2 get below error

### ISSUE THREAD

**Issue by qiuxin2012** [intel-analytics/BigDL#1736]
Run python test on spark1.6.2 get below error
```
____________________________________________________________________________ TestDLClassifer.test_dlclassifier_fit_dlclassifiermodel_transform _____________________________________________________________________________
[gw1] linux2 -- Python 2.7.12 /usr/bin/python2.7

self = <test_dl_classifier.TestDLClassifer instance at 0x7f752e7a0128>

    def test_dlclassifier_fit_dlclassifiermodel_transform(self):
        model = Sequential().add(Linear(2, 2))
        criterion = ClassNLLCriterion()
        classifier = DLClassifier(model, criterion, [2]).setBatchSize(4)\
            .setLearningRate(0.01).setMaxEpoch(1000)
        data = self.sc.parallelize([
            ((2.0, 1.0), 1.0),
            ((1.0, 2.0), 2.0),
            ((2.0, 1.0), 1.0),
            ((1.0, 2.0), 2.0)])
    
        schema = StructType([
            StructField("features", ArrayType(DoubleType(), False), False),
            StructField("label", DoubleType(), False)])
        df = self.sqlContext.createDataFrame(data, schema)
>       dlClassifierModel = classifier.fit(df)

../bigdl/test_dl_classifier.py:156: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/opt/spark/latest/python/lib/pyspark.zip/pyspark/ml/pipeline.py:69: in fit
    return self._fit(dataset)
../../bigdl/models/ml_pipeline/dl_classifier.py:135: in _fit
    jmodel = callBigDlFunc(self.bigdl_type, "fitClassifier", self.value, dataset)
../../bigdl/util/common.py:458: in callBigDlFunc
    return callJavaFunc(sc, api, *args)
../../bigdl/util/common.py:493: in callJavaFunc
    result = func(*args)
/opt/spark/latest/python/lib/py4j-0.9-src.zip/py4j/java_gateway.py:813: in __call__
    answer, self.gateway_client, self.target_id, self.name)
/opt/spark/latest/python/lib/pyspark.zip/pyspark/sql/utils.py:45: in deco
    return f(*a, **kw)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

answer = 'xro113', gateway_client = <py4j.java_gateway.GatewayClient object at 0x7f754c59b250>, target_id = 'o36', name = 'fitClassifier'

    def get_return_value(answer, gateway_client, target_id=None, name=None):
        """Converts an answer received from the Java gateway into a Python object.
    
        For example, string representation of integers are converted to Python
        integer, string representation of objects are converted to JavaObject
        instances, etc.
    
        :param answer: the string returned by the Java gateway
        :param gateway_client: the gateway client used to communicate with the Java
            Gateway. Only necessary if the answer is a reference (e.g., object,
            list, map)
        :param target_id: the name of the object from which the answer comes from
            (e.g., *object1* in `object1.hello()`). Optional.
        :param name: the name of the member from which the answer comes from
            (e.g., *hello* in `object1.hello()`). Optional.
        """
        if is_error(answer)[0]:
            if len(answer) > 1:
                type = answer[1]
                value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
                if answer[1] == REFERENCE_TYPE:
                    raise Py4JJavaError(
                        "An error occurred while calling {0}{1}{2}.\n".
>                       format(target_id, ".", name), value)
E                   Py4JJavaError: An error occurred while calling o36.fitClassifier.
E                   : java.lang.NoSuchMethodError: org.apache.spark.ml.util.SchemaUtils$.appendColumn(Lorg/apache/spark/sql/types/StructType;Ljava/lang/String;Lorg/apache/spark/sql/types/DataType;)Lorg/apache/spark/sql/types/StructType;
E                       at org.apache.spark.ml.DLClassifier.transformSchema(DLClassifier.scala:53)
E                       at org.apache.spark.ml.PipelineStage.transformSchema(Pipeline.scala:68)
E                       at org.apache.spark.ml.DLEstimatorBase.fit(DLEstimatorBase.scala:75)
E                       at com.intel.analytics.bigdl.python.api.PythonBigDL.fitClassifier(PythonBigDL.scala:2052)
E                       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
E                       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
E                       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
E                       at java.lang.reflect.Method.invoke(Method.java:498)
E                       at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
E                       at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:381)
E                       at py4j.Gateway.invoke(Gateway.java:259)
E                       at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
E                       at py4j.commands.CallCommand.execute(CallCommand.java:79)
E                       at py4j.GatewayConnection.run(GatewayConnection.java:209)
E                       at java.lang.Thread.run(Thread.java:745)

/opt/spark/latest/python/lib/py4j-0.9-src.zip/py4j/protocol.py:308: Py4JJavaError

```

**Comment by megaSpoon** [comment]
Fixed by Zhichao.

createTempTable only exists on spark2.0 changed to registerTempTable
