### ISSUE TITLE
[0.3 release test - Tensorflow] Loading inception V3 exception

### ISSUE THREAD

**Issue by wzhongyuan** [intel-analytics/BigDL#1754]
Exception in thread "main" Layer info: Graph[a4f32f1e]/Adapter[InceptionV3/Predictions/Reshape_1]
java.lang.ClassCastException: java.lang.Float cannot be cast to java.lang.Integer
	at scala.runtime.BoxesRunTime.unboxToInt(BoxesRunTime.java:106)
	at com.intel.analytics.bigdl.utils.tf.loaders.Reshape$$anonfun$build$1.apply(Reshape.scala:39)
	at com.intel.analytics.bigdl.utils.tf.loaders.Reshape$$anonfun$build$1.apply(Reshape.scala:35)
	at com.intel.analytics.bigdl.utils.tf.loaders.Adapter.updateOutput(Adapter.scala:54)
	at com.intel.analytics.bigdl.utils.tf.loaders.Adapter.updateOutput(Adapter.scala:35)
	at com.intel.analytics.bigdl.nn.abstractnn.AbstractModule.forward(AbstractModule.scala:280)
	at com.intel.analytics.bigdl.nn.Graph.updateOutput(Graph.scala:107)
	at com.intel.analytics.bigdl.nn.abstractnn.AbstractModule.forward(AbstractModule.scala:280)
	at com.intel.analytics.bigdl.TestTF$.testLoader(TestTF.scala:19)
	at com.intel.analytics.bigdl.TestTF$.main(TestTF.scala:12)
	at com.intel.analytics.bigdl.TestTF.main(TestTF.scala)

	at com.intel.analytics.bigdl.nn.abstractnn.AbstractModule.forward(AbstractModule.scala:286)
	at com.intel.analytics.bigdl.nn.Graph.updateOutput(Graph.scala:107)
	at com.intel.analytics.bigdl.nn.abstractnn.AbstractModule.forward(AbstractModule.scala:280)
	at com.intel.analytics.bigdl.TestTF$.testLoader(TestTF.scala:19)
	at com.intel.analytics.bigdl.TestTF$.main(TestTF.scala:12)
	at com.intel.analytics.bigdl.TestTF.main(TestTF.scala)

**Comment by wzhongyuan** [comment]
Thanks for the work around @yiheng   I used your approach to freeze inception V3 model and the model could be loaded successfully, 
but forward would throw type error exception listed above.

As discussed offline, you will put a fix for it. I will close this issue once resolved.

**Comment by yiheng** [comment]
Already merged

**Comment by wzhongyuan** [comment]
Test works successfully with latest update
