### ISSUE TITLE
[0.3 release test] tree lstm requirement failed: copyStatus: container's length mismatchexcepted 1, but get 0

### ISSUE THREAD

**Issue by SeaOfOcean** [intel-analytics/BigDL#1765]
After finishing 5 epoch training, it throws
```
Exception in thread "main" java.lang.IllegalArgumentException: requirement failed: copyStatus: container's length mismatchexcepted 1, but get 0
	at scala.Predef$.require(Predef.scala:224)
	at com.intel.analytics.bigdl.nn.Container.copyStatus(Container.scala:143)
	at com.intel.analytics.bigdl.nn.Container.copyStatus(Container.scala:40)
	at com.intel.analytics.bigdl.nn.Container.copyStatus(Container.scala:148)
	at com.intel.analytics.bigdl.nn.Container.copyStatus(Container.scala:40)
	at com.intel.analytics.bigdl.nn.Utils$.copyModule(Utils.scala:238)
	at com.intel.analytics.bigdl.optim.DistriOptimizer.optimize(DistriOptimizer.scala:859)
	at com.intel.analytics.bigdl.example.treeLSTMSentiment.Train$.train(Train.scala:124)
	at com.intel.analytics.bigdl.example.treeLSTMSentiment.Train$.main(Train.scala:40)
	at com.intel.analytics.bigdl.example.treeLSTMSentiment.Train.main(Train.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

**Comment by zhangxiaoli73** [comment]
It is a bug in MapTable, and xianyan is woking on fix it.
