### ISSUE TITLE
Python run with pip install throws  Error: Master must either be yarn or start with spark, mesos, local

### ISSUE THREAD

**Issue by SeaOfOcean** [intel-analytics/BigDL#1796]
I ran pip install BigDL in my spark cluster environment, and it throws
Error: Master must either be yarn or start with spark, mesos, local

```
from bigdl.util.common import *
from pyspark import SparkContext
from bigdl.nn.layer import *
import bigdl.version

# create sparkcontext with bigdl configuration
sc = SparkContext.getOrCreate(conf=create_spark_conf()) 
```

```
>>> from pyspark import SparkContext
>>> from bigdl.nn.layer import *
>>> import bigdl.version
>>> 
>>> # create sparkcontext with bigdl configuration
... sc = SparkContext.getOrCreate(conf=create_spark_conf()) 
Error: Master must either be yarn or start with spark, mesos, local
Run with --help for usage help or --verbose for debug output
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pyspark/context.py", line 334, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/usr/local/lib/python2.7/dist-packages/pyspark/context.py", line 115, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/usr/local/lib/python2.7/dist-packages/pyspark/context.py", line 283, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
  File "/usr/local/lib/python2.7/dist-packages/pyspark/java_gateway.py", line 95, in launch_gateway
    raise Exception("Java gateway process exited before sending the driver its port number")
Exception: Java gateway process exited before sending the driver its port number
```

**Comment by yiheng** [comment]
how do you set spark master?

**Comment by SeaOfOcean** [comment]
I did not set spark master, just follow the BigDL readme to run examples

**Comment by yiheng** [comment]
You should set spark master. Or how does spark run?

**Comment by SeaOfOcean** [comment]
Set the master solves the problem

```
from bigdl.util.common import *
from pyspark import SparkContext
from bigdl.nn.layer import *
import bigdl.version

# create sparkcontext with bigdl configuration
sc = SparkContext.getOrCreate(conf=create_spark_conf().setMaster("local[2]")) 
init_engine() # prepare the bigdl environment 
bigdl.version.__version__ # Get the current BigDL version
linear = Linear(2, 3) # Try to create a Linear layer
```

**Comment by jason-dai** [comment]
We need to update the doc - maybe use local[*]
