### ISSUE TITLE
Error creating RnnCell in python when using activation=softplus or softsign

### ISSUE THREAD

**Issue by hkvision** [intel-analytics/BigDL#1855]
When I run the python unit test for creating rnn cell on master,
The following works with activation such as Tanh, Sigmoid, ReLU, SoftMax:
`layer= RnnCell(4, 3, Tanh(), True, True, L1Regularizer(0.5), L1Regularizer(0.5), L1Regularizer(0.5))`

However, if I change `Tanh()` to `SoftPlus()` or `SoftSign()`, I got the following error:

Py4JError: An error occurred while calling o27.createRnnCell. Trace:
py4j.Py4JException: Method createRnnCell([class java.lang.Integer, class java.lang.Integer, class com.intel.analytics.bigdl.nn.SoftPlus, class java.lang.Boolean, class java.lang.Boolean, class com.intel.analytics.bigdl.optim.L1Regularizer, class com.intel.analytics.bigdl.optim.L1Regularizer, class com.intel.analytics.bigdl.optim.L1Regularizer]) does not exist
    at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:318)
    at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:326)
    at py4j.Gateway.invoke(Gateway.java:272)
    at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
    at py4j.commands.CallCommand.execute(CallCommand.java:79)
    at py4j.GatewayConnection.run(GatewayConnection.java:214)
    at java.lang.Thread.run(Thread.java:748)

**Comment by hkvision** [comment]
@yiheng @yangw1234 now `SoftPlus` takes another `D` as tag but in RNN activation it only accepts `T`?
