### ISSUE TITLE
SpatialAveragePooling with NHWC would fail if input is [batch, 3, 20, 20]

### ISSUE THREAD

**Issue by zhichao-li** [intel-analytics/BigDL#1870]
[batch, 20, 20, 3] is ok.
[batch, 3, 20, 20] kw=3, kh=20

E                   java.lang.NullPointerException
E                   	at com.intel.analytics.bigdl.nn.SpatialAveragePooling.com$intel$analytics$bigdl$nn$SpatialAveragePooling$$updateOutputFrameFloatNHWC(SpatialAveragePooling.scala:274)
E                   	at com.intel.analytics.bigdl.nn.SpatialAveragePooling$$anonfun$updateOutput$2.apply$mcV$sp(SpatialAveragePooling.scala:417)
E                   	at com.intel.analytics.bigdl.nn.SpatialAveragePooling$$anonfun$updateOutput$2.apply(SpatialAveragePooling.scala:410)
E                   	at com.intel.analytics.bigdl.nn.SpatialAveragePooling$$anonfun$updateOutput$2.apply(SpatialAveragePooling.scala:410)
E                   	at com.intel.analytics.bigdl.utils.ThreadPool$$anonfun$invoke$2.apply(ThreadPool.scala:162)
E                   	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
E                   	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
E                   	at com.intel.analytics.bigdl.utils.ThreadPool$$anon$1.execute(ThreadPool.scala:203)
E                   	at scala.concurrent.impl.Future$.apply(Future.scala:31)
E                   	at scala.concurrent.Future$.apply(Future.scala:485)
E                   	at com.intel.analytics.bigdl.utils.ThreadPool.invoke(ThreadPool.scala:168)
E                   	at com.intel.analytics.bigdl.nn.SpatialAveragePooling.updateOutput(SpatialAveragePooling.scala:410)
E                   	at com.intel.analytics.bigdl.nn.SpatialAveragePooling.updateOutput(SpatialAveragePooling.scala:62)
E                   	at com.intel.analytics.bigdl.nn.abstractnn.AbstractModule.forward(AbstractModule.scala:280)
E                   	at com.intel.analytics.bigdl.nn.Sequential.updateOutput(Sequential.scala:39)
E                   	at com.intel.analytics.bigdl.nn.abstractnn.AbstractModule.forward(AbstractModule.scala:280)
E                   	at com.intel.analytics.bigdl.nn.Graph.updateOutput(Graph.scala:107)
E                   	at com.intel.analytics.bigdl.nn.abstractnn.AbstractModule.forward(AbstractModule.scala:280)
E                   	at com.intel.analytics.bigdl.python.api.PythonBigDL.modelForward(PythonBigDL.scala:1612)
E                   	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
E                   	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
E                   	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
E                   	at java.lang.reflect.Method.invoke(Method.java:498)
E                   	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
E                   	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:381)
E                   	at py4j.Gateway.invoke(Gateway.java:259)
E                   	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
E                   	at py4j.commands.CallCommand.execute(CallCommand.java:79)
E                   	at py4j.GatewayConnection.run(GatewayConnection.java:209)
E                   	at java.lang.Thread.run(Thread.java:745)
E                   
E                   	at com.intel.analytics.bigdl.nn.abstractnn.AbstractModule.forward(AbstractModule.scala:286)
E                   	at com.intel.analytics.bigdl.nn.Sequential.updateOutput(Sequential.scala:39)
E                   	at com.intel.analytics.bigdl.nn.abstractnn.AbstractModule.forward(AbstractModule.scala:280)
E                   	at com.intel.analytics.bigdl.nn.Graph.updateOutput(Graph.scala:107)
E                   	at com.intel.analytics.bigdl.nn.abstractnn.AbstractModule.forward(AbstractModule.scala:280)
E                   	at com.intel.analytics.bigdl.python.api.PythonBigDL.modelForward(PythonBigDL.scala:1612)
E                   	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
E                   	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
E                   	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
E                   	at java.lang.reflect.Method.invoke(Method.java:498)
E                   	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
E                   	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:381)
E                   	at py4j.Gateway.invoke(Gateway.java:259)
E                   	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
E                   	at py4j.commands.CallCommand.execute(CallCommand.java:79)
E                   	at py4j.GatewayConnection.run(GatewayConnection.java:209)
E                   	at java.lang.Thread.run(Thread.java:745)

**Comment by zhichao-li** [comment]
cc @yiheng  @yangw1234
