### ISSUE TITLE
 VolumetricMaxPooling serialization got  NullPointerException when using module.saveModel

### ISSUE THREAD

**Issue by jenniew** [intel-analytics/BigDL#1873]
When calling module.saveModel(), VolumetricMaxPooling serialization got  NullPointerException.

Code: pool_1 = VolumetricMaxPooling(2, 2, 2, 2, 2, 2, 0, 0, 0)(relu_1)

py4j.protocol.Py4JJavaError: An error occurred while calling o38.saveBigDLModule.
: java.lang.NullPointerException
	at scala.collection.mutable.ArrayOps$ofInt$.length$extension(ArrayOps.scala:162)
	at scala.collection.mutable.ArrayOps$ofInt.length(ArrayOps.scala:162)
	at scala.collection.IndexedSeqOptimized$class.slice(IndexedSeqOptimized.scala:106)
	at scala.collection.mutable.ArrayOps$ofInt.slice(ArrayOps.scala:156)
	at com.intel.analytics.bigdl.tensor.DenseTensor.size(DenseTensor.scala:71)
	at com.intel.analytics.bigdl.utils.serializer.DataConverter$TensorConverter$.setAttributeValue(DataConverter.scala:535)
	at com.intel.analytics.bigdl.utils.serializer.DataConverter$.setAttributeValue(DataConverter.scala:166)
	at com.intel.analytics.bigdl.nn.VolumetricMaxPooling$.doSerializeModule(VolumetricMaxPooling.scala:586)
	at com.intel.analytics.bigdl.utils.serializer.ModuleSerializable$class.serializeModule(ModuleSerializable.scala:154)
	at com.intel.analytics.bigdl.nn.VolumetricMaxPooling$.serializeModule(VolumetricMaxPooling.scala:551)
	at com.intel.analytics.bigdl.utils.serializer.ModuleSerializer$.serialize(ModuleSerializer.scala:66)
	at com.intel.analytics.bigdl.nn.Graph$$anonfun$doSerializeModule$3.apply(Graph.scala:691)
	at com.intel.analytics.bigdl.nn.Graph$$anonfun$doSerializeModule$3.apply(Graph.scala:682)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
	at com.intel.analytics.bigdl.nn.Graph$.doSerializeModule(Graph.scala:682)
	at com.intel.analytics.bigdl.utils.serializer.ModuleSerializable$class.serializeModule(ModuleSerializable.scala:154)
	at com.intel.analytics.bigdl.nn.Graph$.serializeModule(Graph.scala:562)
	at com.intel.analytics.bigdl.utils.serializer.ModuleSerializer$.serialize(ModuleSerializer.scala:66)
	at com.intel.analytics.bigdl.utils.serializer.ModulePersister$.saveToFile(ModuleLoader.scala:175)
	at com.intel.analytics.bigdl.nn.abstractnn.AbstractModule.saveModule(AbstractModule.scala:472)
	at com.intel.analytics.bigdl.python.api.PythonBigDL.saveBigDLModule(PythonBigDL.scala:1694)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:381)
	at py4j.Gateway.invoke(Gateway.java:259)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:209)
	at java.lang.Thread.run(Thread.java:745)

**Comment by wzhongyuan** [comment]
it should the same issue as fixed in https://github.com/intel-analytics/BigDL/pull/1867 because of the empty tensor (not null) with size() as null

**Comment by jenniew** [comment]
Yes, it is the same issue. After the PR is merged, we can close this issue.

**Comment by wzhongyuan** [comment]
@jenniew  the change has been merged into master, please give it a try to see if the issue's fixed, please let me know if still any issue..

**Comment by natnaelino** [comment]
@jenniew  



   Add your reaction 








@jenniew  try the New fix  now that it should ok and no bug by now .

**Comment by jenniew** [comment]
Verified. It's OK now.
