### ISSUE TITLE
SparseJoinTable with inconsistent sparse tensor input would get ArrayIndexOutOfBoundsException 

### ISSUE THREAD

**Issue by jenniew** [intel-analytics/BigDL#1932]
SparseJoinTable with inconsistent sparse tensor input would get ArrayIndexOutOfBoundsException. For example, some sparse tensor may have 3 indices, but some have 2 indices. 

Exception:

}/nn.SparseJoinTable(2)
java.lang.ArrayIndexOutOfBoundsException
	at java.lang.System.arraycopy(Native Method)
	at com.intel.analytics.bigdl.tensor.TensorNumericMath$TensorNumeric$NumericFloat$.arraycopy$mcF$sp(TensorNumeric.scala:641)
	at com.intel.analytics.bigdl.tensor.TensorNumericMath$TensorNumeric$NumericFloat$.arraycopy(TensorNumeric.scala:635)
	at com.intel.analytics.bigdl.tensor.TensorNumericMath$TensorNumeric$NumericFloat$.arraycopy(TensorNumeric.scala:425)
	at com.intel.analytics.bigdl.tensor.SparseTensor$.concat(SparseTensor.scala:1178)
	at com.intel.analytics.bigdl.tensor.SparseTensor$.concat(SparseTensor.scala:1053)
	at com.intel.analytics.bigdl.tensor.Tensor$.sparseConcat(Tensor.scala:1268)
	at com.intel.analytics.bigdl.nn.SparseJoinTable.updateOutput(SparseJoinTable.scala:61)
	at com.intel.analytics.bigdl.nn.SparseJoinTable.updateOutput(SparseJoinTable.scala:36)
	at com.intel.analytics.bigdl.nn.abstractnn.AbstractModule.forward(AbstractModule.scala:280)
	at com.intel.analytics.bigdl.nn.Sequential.updateOutput(Sequential.scala:39)
	at com.intel.analytics.bigdl.nn.abstractnn.AbstractModule.forward(AbstractModule.scala:280)
	at com.intel.analytics.bigdl.optim.Predictor$$anonfun$predict$1$$anonfun$apply$3.apply(Predictor.scala:72)
	at com.intel.analytics.bigdl.optim.Predictor$$anonfun$predict$1$$anonfun$apply$3.apply(Predictor.scala:71)
	at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:434)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.

**Comment by qiuxin2012** [comment]
Reproduced by 
```
    val indices1 = Array(0, 1, 2, 3, 3)
    val indices2 = Array(0, 1, 2, 3, 4)
    val values1 = Array(1f, 2f, 3f, 4f, 5f)
    val input1 = Tensor.sparse(Array(indices1, indices2), values1, Array(4, 5))
      .resize(Array(4, 5), 4)
    val indices3 = Array(0, 1, 2, 3, 4, 4)
    val indices4 = Array(0, 1, 2, 3, 3, 4)
    val values2 = Array(6f, 7f, 8f, 9f, 10f, 11f)
    val input2 = Tensor.sparse(Array(indices3, indices4), values2, Array(6, 5))
      .narrow(1, 2, 4)
    val sparseModel = Sequential().add(ParallelTable().add(Identity()).add(Identity()))
      .add(SparseJoinTable(2))
```
