### ISSUE TITLE
runtime error: Can't extract dynamic lib file to /tmp dir on Mac

### ISSUE THREAD

**Issue by songhappy** [intel-analytics/BigDL#1970]
Can't extract dynamic lib file to /tmp dir.
java.lang.Error: Can't find dynamic lib file in jar, path = libiomp5.dylib
java.lang.Error: Can't extract dynamic lib file to /tmp dir.
java.lang.Error: Can't find dynamic lib file in jar, path = libiomp5.dylib
	at com.intel.analytics.bigdl.mkl.MKL.extract(MKL.java:325)
	at com.intel.analytics.bigdl.mkl.MKL.<clinit>(MKL.java:51)
	at com.intel.analytics.bigdl.tensor.Tensor$.<init>(Tensor.scala:801)
	at com.intel.analytics.bigdl.tensor.Tensor$.<clinit>(Tensor.scala)
	at com.intel.analytics.bigdl.nn.abstractnn.Activity$.allocate(Activity.scala:74)
	at com.intel.analytics.bigdl.nn.abstractnn.AbstractModule.<init>(AbstractModule.scala:68)
	at com.intel.analytics.bigdl.nn.abstractnn.TensorModule.<init>(AbstractModule.scala:46)
	at com.intel.analytics.bigdl.nn.LocallyConnected1D.<init>(LocallyConnected1D.scala:66)
	at com.intel.analytics.bigdl.nn.LocallyConnected1D$.apply$mDc$sp(LocallyConnected1D.scala:589)
	at com.intel.analytics.bigdl.keras.LocallyConnected1DSuite$$anonfun$10.apply$mcV$sp(LocallyConnected1DSuite.scala:77)
	at com.intel.analytics.bigdl.keras.LocallyConnected1DSuite$$anonfun$10.apply(LocallyConnected1DSuite.scala:71)
	at com.intel.analytics.bigdl.keras.LocallyConnected1DSuite$$anonfun$10.apply(LocallyConnected1DSuite.scala:71)

**Comment by i8run** [comment]
It's due to the deploy process of jenkins and fixed now.

**Comment by zhichao-li** [comment]
Similar issue while trying to execute some unitest from Mac locally.
```
bjc[99776]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/bin/java (0x107ef04c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x107fcc4e0). One of the two will be used. Which one is undefined.

Can't extract dynamic lib file to /tmp dir.
java.lang.Error: Can't find dynamic lib file in jar, path = libiomp5.dylib
java.lang.Error: Can't extract dynamic lib file to /tmp dir.
java.lang.Error: Can't find dynamic lib file in jar, path = libiomp5.dylib
	at com.intel.analytics.bigdl.mkl.MKL.extract(MKL.java:325)
	at com.intel.analytics.bigdl.mkl.MKL.<clinit>(MKL.java:51)
	at com.intel.analytics.bigdl.tensor.Tensor$.<init>(Tensor.scala:801)
	at com.intel.analytics.bigdl.tensor.Tensor$.<clinit>(Tensor.scala)
	at com.intel.analytics.bigdl.optim.TableSpec$$anonfun$15.apply$mcV$sp(TableSpec.scala:287)
	at com.intel.analytics.bigdl.optim.TableSpec$$anonfun$15.apply(TableSpec.scala:285)
	at com.intel.analytics.bigdl.optim.TableSpec$$anonfun$15.apply(TableSpec.scala:285)
	at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.FlatSpecLike$$anon$1.apply(FlatSpecLike.scala:1647)
	at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
	at org.scalatest.FlatSpec.withFixture(FlatSpec.scala:1683)
	at org.scalatest.FlatSpecLike$class.invokeWithFixture$1(FlatSpecLike.scala:1644)
	at org.scalatest.FlatSpecLike$$anonfun$runTest$1.apply(FlatSpecLike.scala:1656)
	at org.scalatest.FlatSpecLike$$anonfun$runTest$1.apply(FlatSpecLike.scala:1656)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
	at org.scalatest.FlatSpecLike$class.runTest(FlatSpecLike.scala:1656)
	at org.scalatest.FlatSpec.runTest(FlatSpec.scala:1683)
	at org.scalatest.FlatSpecLike$$anonfun$runTests$1.apply(FlatSpecLike.scala:1714)
	at org.scalatest.FlatSpecLike$$anonfun$runTests$1.apply(FlatSpecLike.scala:1714)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:390)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:427)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
	at org.scalatest.FlatSpecLike$class.runTests(FlatSpecLike.scala:1714)
	at org.scalatest.FlatSpec.runTests(FlatSpec.scala:1683)
	at org.scalatest.Suite$class.run(Suite.scala:1424)
	at org.scalatest.FlatSpec.org$scalatest$FlatSpecLike$$super$run(FlatSpec.scala:1683)
	at org.scalatest.FlatSpecLike$$anonfun$run$1.apply(FlatSpecLike.scala:1760)
	at org.scalatest.FlatSpecLike$$anonfun$run$1.apply(FlatSpecLike.scala:1760)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:545)
	at org.scalatest.FlatSpecLike$class.run(FlatSpecLike.scala:1760)
	at org.scalatest.FlatSpec.run(FlatSpec.scala:1683)
	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:55)
	at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2563)
	at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2557)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:2557)
	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1044)
	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1043)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:2722)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1043)
	at org.scalatest.tools.Runner$.run(Runner.scala:883)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2(ScalaTestRunner.java:138)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:28)
```
