### ISSUE TITLE
Quantization integration test fail on java 1.7 which may be caused by BigDL-core

### ISSUE THREAD

**Issue by lopelopelope** [intel-analytics/BigDL#2044]
@i8run 
It succeed on java 1.8, but fail on java 1.7.
error message
*** RUN ABORTED ***
  java.lang.UnsupportedClassVersionError: com/intel/analytics/bigdl/tags/Integration : Unsupported major.minor version 52.0
  at java.lang.ClassLoader.defineClass1(Native Method)
  at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
  at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
  at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
  at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
  at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
  at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
  at java.security.AccessController.doPrivileged(Native Method)
  at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:425)

**Comment by i8run** [comment]
It has been fixed with the newest version.
