### ISSUE TITLE
 run python textclassifier example in bigdl-master will meet "java.lang.OutOfMemoryError"

### ISSUE THREAD

**Issue by zhangxiaoli73** [intel-analytics/BigDL#2101]
when running python textclassifier example in bigdl-master, get some weird info:
2017-12-25 15:36:21 INFO  ThreadPool$:79 - Set mkl threads to 1 on thread 16
and errors:
2017-12-25 15:38:55 ERROR Executor:91 - Exception in task 0.0 in stage 11.0 (TID 14)
java.lang.OutOfMemoryError: Java heap space
	at java.lang.reflect.Array.newInstance(Array.java:75)
	at java.io.ObjectInputStream.readArray(ObjectInputStream.java:1678)

but in scala textclassifier, the corresponding info is : ThreadPool$:79 - Set mkl threads to 1 on thread 1
and no errors.

**Comment by zhichao-li** [comment]
cc @psyyz10 
This is introduced in https://github.com/intel-analytics/BigDL/pull/1707
We need to update the readme to clarify the memory setting, and reduce the memory usage in the next release.
