### ISSUE TITLE
new Sample(SparseTensor, DenseTensor) will throw exception.

### ISSUE THREAD

**Issue by qiuxin2012** [intel-analytics/BigDL#2258]
@michellemay raised this issue in #979

**Comment by michellemay** [comment]
Also note that he optimizer will not work with sparse tensors as well:

java.lang.UnsupportedOperationException: SparseTensor: Unimplemented method
	at com.intel.analytics.bigdl.tensor.SparseTensor.stride(SparseTensor.scala:124)
        ...
	at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$9$$anonfun$10$$anonfun$apply$2.apply$mcI$sp(DistriOptimizer.scala:234)

**Comment by qiuxin2012** [comment]
@michellemay Could you show me your model?
I think you should use `SparseLinear` instead of `Linear` in your model.
