### ISSUE TITLE
RNN model failed with java.util.NoSuchElementException: None.get

### ISSUE THREAD

**Issue by ibingoogle** [intel-analytics/BigDL#2265]
Train rnn model on spark2.2.1 standalone mode using Tiny Shakespeare Texts corpus, failed with java.util.NoSuchElementException: None.get:

**$ spark-submit --master spark://sean:7077 --executor-cores 4 --total-executor-cores 4 --class com.intel.analytics.bigdl.models.rnn.Train dist/lib/bigdl-0.5.0-SNAPSHOT-jar-with-dependencies.jar -f ../Dataset/TinyShakespeareTexts/Input/ -s ../Dataset/TinyShakespeareTexts/Output -b 128 -e 2
18/02/01 14:59:47 INFO ThreadPool$: Set mkl threads to 1 on thread 1
18/02/01 14:59:50 INFO Engine$: Auto detect executor number and executor cores number
18/02/01 14:59:50 INFO Engine$: Executor number is 1 and executor cores number is 4
18/02/01 14:59:50 INFO Engine$: Find existing spark context. Checking the spark conf...
18/02/01 14:59:53 INFO Dictionary: 272304 words and32885 sentences processed
18/02/01 14:59:53 INFO Dictionary: save created dictionary.txt and discard.txt to/home/sean/workspace/Scala/BigDL/BigDLSpark-2.2.1/../Dataset/TinyShakespeareTexts/Output
18/02/01 14:59:54 INFO Train$: maxTrain length = 25, maxVal = 22
Exception in thread "main" java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:347)
	at scala.None$.get(Option.scala:345)
	at com.intel.analytics.bigdl.models.rnn.Train$$anonfun$main$1.apply(Train.scala:131)
	at com.intel.analytics.bigdl.models.rnn.Train$$anonfun$main$1.apply(Train.scala:40)
	at scala.Option.map(Option.scala:146)
	at com.intel.analytics.bigdl.models.rnn.Train$.main(Train.scala:40)
	at com.intel.analytics.bigdl.models.rnn.Train.main(Train.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:775)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:119)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)**

BTW:
1. I follow steps in https://github.com/intel-analytics/BigDL/tree/master/spark/dl/src/main/scala/com/intel/analytics/bigdl/models/rnn
2. The cluster only has one machine containing one worker and one master
3. I changed the command to the following (use two executors), but enounter with same issue:
spark-submit --master spark://sean:7077 --executor-cores 2 --total-executor-cores 4 --class com.intel.analytics.bigdl.models.rnn.Train dist/lib/bigdl-0.5.0-SNAPSHOT-jar-with-dependencies.jar -f ../Dataset/TinyShakespeareTexts/Input/ -s ../Dataset/TinyShakespeareTexts/Output -b 128 -e 2
3. I trained rnn model on yarn via the following command, but also encounter with same issue
spark-submit --master yarn --executor-cores 4 --num-executors 1 --executor-memory 4g --driver-memory 2g --class com.intel.analytics.bigdl.models.rnn.Train dist/lib/bigdl-0.5.0-SNAPSHOT-jar-with-dependencies.jar -f ../Dataset/TinyShakespeareTexts/Input/ -s ../Dataset/TinyShakespeareTexts/Output -b 128 -e 2

Thanks

**Comment by yiheng** [comment]
@hkvision please take a look at this issue

**Comment by hkvision** [comment]
Hi @ibingoogle 
This problem seems to arise from the missing argument `checkpoint`.
You can create a folder say `Model` to save the checkpoint snapshots and append `--checkpoint ../Dataset/TinyShakespeareTexts/Model` to the command. Then it should work!
Feel free to tell me if there's still problems. Thanks.

**Comment by ibingoogle** [comment]
@hkvision , Thanks, works now. I have closed this issue

**Comment by yiheng** [comment]
The error message is not clear. We should refine it.

**Comment by hkvision** [comment]
@yiheng I think we write this example (not only this one, but also other examples as well) under the assumption that users are to input all the necessary parameters. If there's missing parameter, then such exception will be thrown. If you want refinement, may have some discussion and refine other examples as well?

**Comment by yiheng** [comment]
@hkvision The error message is not clear. It should be something like "--checkpoint is missing" instead of "java.util.NoSuchElementException". I'm not sure if there're similar problems in other examples
