### ISSUE TITLE
How can I use different weights for multiclass in loss function

### ISSUE THREAD

**Issue by zzuzayu** [intel-analytics/BigDL#2270]
It have 3 class:[0,0,1],[1,0,0],[0,1,0]
the output of the model is:[a,b,c]
and a+b+c=1
When I didn't set the weights in BCECriterion(),it's all right.
But when I set the weights,I got an error.

my code:
```
from bigdl.optim.optimizer import *
from bigdl.nn.criterion import *
weights=np.array([0.775729175515,0.529479041768,1.69479178272])
optimizer = Optimizer(
        model=build_model(),
        training_rdd=train_rdd,
        criterion=BCECriterion(weights),
        end_trigger=MaxEpoch(max_epoch),
        batch_size=batch_size,
        optim_method=Adam())
optimizer.set_validation(
        batch_size=batch_size,
        val_rdd=test_rdd,
        trigger=EveryEpoch(),
        val_method=[Loss(BCECriterion(weights))])
```
error:

```
Py4JJavaError: An error occurred while calling o95.optimize.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 7.0 failed 1 times, most recent failure: Lost task 0.0 in stage 7.0 (TID 5, localhost): java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: requirement failed: current tensor is not contiguous
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$6$$anonfun$9.apply(DistriOptimizer.scala:216)
	at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$6$$anonfun$9.apply(DistriOptimizer.scala:216)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$6.apply(DistriOptimizer.scala:216)
	at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$6.apply(DistriOptimizer.scala:157)
	at org.apache.spark.rdd.ZippedPartitionsRDD2.compute(ZippedPartitionsRDD.scala:88)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: requirement failed: current tensor is not contiguous
	at scala.Predef$.require(Predef.scala:233)
	at com.intel.analytics.bigdl.tensor.DenseTensor.view(DenseTensor.scala:138)
	at com.intel.analytics.bigdl.tensor.Tensor$class.view(Tensor.scala:496)
	at com.intel.analytics.bigdl.tensor.DenseTensor.view(DenseTensor.scala:30)
	at com.intel.analytics.bigdl.nn.BCECriterion.updateGradInput(BCECriterion.scala:88)
	at com.intel.analytics.bigdl.nn.BCECriterion.updateGradInput(BCECriterion.scala:39)
	at com.intel.analytics.bigdl.nn.abstractnn.AbstractCriterion.backward(AbstractCriterion.scala:81)
	at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$6$$anonfun$7$$anonfun$apply$2.apply$mcI$sp(DistriOptimizer.scala:206)
	at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$6$$anonfun$7$$anonfun$apply$2.apply(DistriOptimizer.scala:197)
	at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$6$$anonfun$7$$anonfun$apply$2.apply(DistriOptimizer.scala:197)
	at com.intel.analytics.bigdl.utils.ThreadPool$$anonfun$1$$anon$4.call(ThreadPool.scala:112)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1431)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1419)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1418)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1418)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:799)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:799)
	at scala.Option.foreach(Option.scala:236)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:799)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1640)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1599)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1588)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:620)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1832)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1952)
	at org.apache.spark.rdd.RDD$$anonfun$reduce$1.apply(RDD.scala:1025)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:150)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:111)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:316)
	at org.apache.spark.rdd.RDD.reduce(RDD.scala:1007)
	at com.intel.analytics.bigdl.optim.DistriOptimizer$.optimize(DistriOptimizer.scala:260)
	at com.intel.analytics.bigdl.optim.DistriOptimizer.optimize(DistriOptimizer.scala:756)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:381)
	at py4j.Gateway.invoke(Gateway.java:259)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:209)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: requirement failed: current tensor is not contiguous
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$6$$anonfun$9.apply(DistriOptimizer.scala:216)
	at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$6$$anonfun$9.apply(DistriOptimizer.scala:216)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$6.apply(DistriOptimizer.scala:216)
	at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$6.apply(DistriOptimizer.scala:157)
	at org.apache.spark.rdd.ZippedPartitionsRDD2.compute(ZippedPartitionsRDD.scala:88)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	... 1 more
Caused by: java.lang.IllegaI got errorlArgumentException: requirement failed: current tensor is not contiguous
	at scala.Predef$.require(Predef.scala:233)
	at com.intel.analytics.bigdl.tensor.DenseTensor.view(DenseTensor.scala:138)
	at com.intel.analytics.bigdl.tensor.Tensor$class.view(Tensor.scala:496)
	at com.intel.analytics.bigdl.tensor.DenseTensor.view(DenseTensor.scala:30)
	at com.intel.analytics.bigdl.nn.BCECriterion.updateGradInput(BCECriterion.scala:88)
	at com.intel.analytics.bigdl.nn.BCECriterion.updateGradInput(BCECriterion.scala:39)
	at com.intel.analytics.bigdl.nn.abstractnn.AbstractCriterion.backward(AbstractCriterion.scala:81)
	at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$6$$anonfun$7$$anonfun$apply$2.apply$mcI$sp(DistriOptimizer.scala:206)
	at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$6$$anonfun$7$$anonfun$apply$2.apply(DistriOptimizer.scala:197)
	at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$6$$anonfun$7$$anonfun$apply$2.apply(DistriOptimizer.scala:197)
	at com.intel.analytics.bigdl.utils.ThreadPool$$anonfun$1$$anon$4.call(ThreadPool.scala:112)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more

```

**Comment by SeaOfOcean** [comment]
This is a bug in BigDL-0.4.0, we have fixed it in master code(0.5.0-SNAPSHOT)
