### ISSUE TITLE
SparseTensor will support 3 dimensions or more ?

### ISSUE THREAD

**Issue by Justontheway** [intel-analytics/BigDL#2279]
## Property
SparseTensor will support 3 dimensions or more ?

**Comment by qiuxin2012** [comment]
You can create 3D and even nD sparse tensor, but no Layer for 3D SparseTensor.
Could you tell me which kind of Layer do you want?

**Comment by Justontheway** [comment]
1. **Tensor.sparse(Array(2,3,4), 3)** or something like this will throw the following error
```
scala> Tensor.sparse(Array(2,3,4), 3)
java.lang.UnsupportedOperationException: SparseTensor: Unimplemented method
        at com.intel.analytics.bigdl.tensor.SparseTensor.toString(SparseTensor.s
cala:977)
        at java.lang.String.valueOf(String.java:2994)
        at scala.runtime.ScalaRunTime$.stringOf(ScalaRunTime.scala:331)
        at scala.runtime.ScalaRunTime$.replStringOf(ScalaRunTime.scala:337)
        at .<init>(<console>:10)
        at .<clinit>(<console>)
        at $print(<console>)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:734)

        at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:983)

        at scala.tools.nsc.interpreter.IMain.loadAndRunReq$1(IMain.scala:573)
        at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:604)
        at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:568)
        at scala.tools.nsc.interpreter.ILoop.reallyInterpret$1(ILoop.scala:760)
        at scala.tools.nsc.interpreter.ILoop.interpretStartingWith(ILoop.scala:8
05)
        at scala.tools.nsc.interpreter.ILoop.command(ILoop.scala:717)
        at scala.tools.nsc.interpreter.ILoop.processLine$1(ILoop.scala:581)
        at scala.tools.nsc.interpreter.ILoop.innerLoop$1(ILoop.scala:588)
        at scala.tools.nsc.interpreter.ILoop.loop(ILoop.scala:591)
        at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply$mcZ$sp(ILo
op.scala:882)
        at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scal
a:837)
        at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scal
a:837)
        at scala.tools.nsc.util.ScalaClassLoader$.savingContextLoader(ScalaClass
Loader.scala:135)
        at scala.tools.nsc.interpreter.ILoop.process(ILoop.scala:837)
        at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala
:83)
        at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:96)

        at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:105)
        at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)

```
2. I need to use **SpatialConvolution**.

**Comment by qiuxin2012** [comment]
@Justontheway 
1. SparseTensor's API is different from DenseTensor's API, See [SparseTensor](https://bigdl-project.github.io/master/#APIGuide/Data/#sparsetensor) for detail.

2. In my knowledge images are dense Data, could you tell me which kind of case will you use SpatialConvolution for Sparse Data?

**Comment by Justontheway** [comment]
I have some spatio-time data. I imagine it to sequential-images (time series spatio-data) to process.
