### ISSUE TITLE
0.5.0-Snapshot load 0.4.0 Faster-RCNN pvanet model fail

### ISSUE THREAD

**Issue by SeaOfOcean** [intel-analytics/BigDL#2302]
0.5.0-Snapshot BigDL load 0.4.0 Faster-RCNN pvanet model fail with exception
https://s3-ap-southeast-1.amazonaws.com/bigdl-models/object-detection/bigdl_frcnn-pvanet_PASCAL_0.4.0.model
```
Exception in thread "main" java.lang.RuntimeException: Loading module com.intel.analytics.bigdl.nn.Sequential exception :
	at com.intel.analytics.bigdl.utils.serializer.ModuleSerializer$.load(ModuleSerializer.scala:110)
	at com.intel.analytics.bigdl.utils.serializer.ModuleLoader$.loadFromFile(ModuleLoader.scala:64)
	at com.intel.analytics.bigdl.nn.Module$.loadModule(Module.scala:60)
	at com.intel.analytics.zoo.pipeline.fasterrcnn.example.Test$$anonfun$main$1.apply(Test.scala:86)
	at com.intel.analytics.zoo.pipeline.fasterrcnn.example.Test$$anonfun$main$1.apply(Test.scala:76)
	at scala.Option.foreach(Option.scala:257)
	at com.intel.analytics.zoo.pipeline.fasterrcnn.example.Test$.main(Test.scala:76)
	at com.intel.analytics.zoo.pipeline.fasterrcnn.example.Test.main(Test.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:738)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:187)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:212)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:126)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.RuntimeException: Loading module com.intel.analytics.bigdl.nn.StaticGraph exception :
	at com.intel.analytics.bigdl.utils.serializer.ModuleSerializer$.load(ModuleSerializer.scala:110)
	at com.intel.analytics.bigdl.utils.serializer.ContainerSerializable$$anonfun$loadSubModules$1.apply(ModuleSerializable.scala:373)
	at com.intel.analytics.bigdl.utils.serializer.ContainerSerializable$$anonfun$loadSubModules$1.apply(ModuleSerializable.scala:372)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at com.intel.analytics.bigdl.utils.serializer.ContainerSerializable$class.loadSubModules(ModuleSerializable.scala:372)
	at com.intel.analytics.bigdl.utils.serializer.ContainerSerializer$.loadSubModules(ModuleSerializable.scala:408)
	at com.intel.analytics.bigdl.utils.serializer.ContainerSerializable$class.doLoadModule(ModuleSerializable.scala:382)
	at com.intel.analytics.bigdl.utils.serializer.ContainerSerializer$.doLoadModule(ModuleSerializable.scala:408)
	at com.intel.analytics.bigdl.utils.serializer.ModuleSerializable$class.loadModule(ModuleSerializable.scala:91)
	at com.intel.analytics.bigdl.utils.serializer.ContainerSerializer$.loadModule(ModuleSerializable.scala:408)
	at com.intel.analytics.bigdl.utils.serializer.ModuleSerializer$.load(ModuleSerializer.scala:107)
	... 16 more
Caused by: java.lang.RuntimeException: Loading module com.intel.analytics.bigdl.nn.CAddTable exception :
	at com.intel.analytics.bigdl.utils.serializer.ModuleSerializer$.load(ModuleSerializer.scala:110)
	at com.intel.analytics.bigdl.nn.GraphSerializable$$anonfun$prepareLoadModule$3.apply(Graph.scala:592)
	at com.intel.analytics.bigdl.nn.GraphSerializable$$anonfun$prepareLoadModule$3.apply(Graph.scala:591)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at com.intel.analytics.bigdl.nn.GraphSerializable$class.prepareLoadModule(Graph.scala:591)
	at com.intel.analytics.bigdl.nn.Graph$.prepareLoadModule(Graph.scala:482)
	at com.intel.analytics.bigdl.nn.GraphSerializable$class.doLoadModule(Graph.scala:639)
	at com.intel.analytics.bigdl.nn.Graph$.doLoadModule(Graph.scala:482)
	at com.intel.analytics.bigdl.utils.serializer.ModuleSerializable$class.loadModule(ModuleSerializable.scala:91)
	at com.intel.analytics.bigdl.nn.Graph$.loadModule(Graph.scala:482)
	at com.intel.analytics.bigdl.utils.serializer.ModuleSerializer$.load(ModuleSerializer.scala:107)
	... 29 more
Caused by: java.lang.IllegalArgumentException: requirement failed: If your module contains multiple class tags, do you forget to override getClassTagNumerics method
	at scala.Predef$.require(Predef.scala:224)
	at com.intel.analytics.bigdl.utils.serializer.ModuleSerializable$$anonfun$doLoadModule$1$$anonfun$apply$1.apply(ModuleSerializable.scala:126)
	at com.intel.analytics.bigdl.utils.serializer.ModuleSerializable$$anonfun$doLoadModule$1$$anonfun$apply$1.apply(ModuleSerializable.scala:121)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at com.intel.analytics.bigdl.utils.serializer.ModuleSerializable$$anonfun$doLoadModule$1.apply(ModuleSerializable.scala:121)
	at com.intel.analytics.bigdl.utils.serializer.ModuleSerializable$$anonfun$doLoadModule$1.apply(ModuleSerializable.scala:120)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at com.intel.analytics.bigdl.utils.serializer.ModuleSerializable$class.doLoadModule(ModuleSerializable.scala:120)
	at com.intel.analytics.bigdl.utils.serializer.ModuleSerializer$.doLoadModule(ModuleSerializer.scala:32)
	at com.intel.analytics.bigdl.utils.serializer.ModuleSerializable$class.loadModule(ModuleSerializable.scala:91)
	at com.intel.analytics.bigdl.utils.serializer.ModuleSerializer$.loadModule(ModuleSerializer.scala:32)
	at com.intel.analytics.bigdl.utils.serializer.ModuleSerializer$.load(ModuleSerializer.scala:107)
	... 42 more
```

**Comment by wzhongyuan** [comment]
@SeaOfOcean    Clearly `CaddTable` has been modified to support multiple classtags thus not compatible

In 0.4.0
```scala
class CAddTable[T: ClassTag](val inplace: Boolean = false)
```
while in 0.5.0
```scala
class CAddTable[T: ClassTag, D: ClassTag](val inplace: Boolean = false)
```

**Comment by SeaOfOcean** [comment]
Can you set some default value so that it can be compatible with 0.4.0?

**Comment by wzhongyuan** [comment]
I don't think we should do that as it really layer specific...

**Comment by jason-dai** [comment]
We need to have some, possibly layer specific, way to load previous versions of models.
