### ISSUE TITLE
model serializable error when doing model evaluation in Lenet python model

### ISSUE THREAD

**Issue by jenniew** [intel-analytics/BigDL#2308]
Run model.evaluate in Lenet5 python example, and get such error.

scala.reflect.runtime.ReflectError: value immutable is not a package
	at scala.reflect.runtime.JavaMirrors$JavaMirror.scala$reflect$runtime$JavaMirrors$$makeScalaPackage(JavaMirrors.scala:915)
	at scala.reflect.runtime.JavaMirrors$class.missingHook(JavaMirrors.scala:1299)
	at scala.reflect.runtime.JavaUniverse.missingHook(JavaUniverse.scala:12)
	at scala.reflect.internal.Mirrors$RootsBase.universeMissingHook(Mirrors.scala:77)
	at scala.reflect.internal.Mirrors$RootsBase.missingHook(Mirrors.scala:79)
	at scala.reflect.internal.pickling.UnPickler$Scan.readExtSymbol$1(UnPickler.scala:226)
	at scala.reflect.internal.pickling.UnPickler$Scan.readSymbol(UnPickler.scala:250)
	at scala.reflect.internal.pickling.UnPickler$Scan.readSymbolRef(UnPickler.scala:783)
	at scala.reflect.internal.pickling.UnPickler$Scan.readType(UnPickler.scala:335)
	at scala.reflect.internal.pickling.UnPickler$Scan$$anonfun$readTypeRef$1.apply(UnPickler.scala:792)
	at scala.reflect.internal.pickling.UnPickler$Scan$$anonfun$readTypeRef$1.apply(UnPickler.scala:792)
	at scala.reflect.internal.pickling.UnPickler$Scan.at(UnPickler.scala:171)
	at scala.reflect.internal.pickling.UnPickler$Scan.readTypeRef(UnPickler.scala:792)
	at scala.reflect.internal.pickling.UnPickler$Scan.readType(UnPickler.scala:345)
	at scala.reflect.internal.pickling.UnPickler$Scan$$anonfun$readTypeRef$1.apply(UnPickler.scala:792)
	at scala.reflect.internal.pickling.UnPickler$Scan$$anonfun$readTypeRef$1.apply(UnPickler.scala:792)
	at scala.reflect.internal.pickling.UnPickler$Scan.at(UnPickler.scala:171)
	at scala.reflect.internal.pickling.UnPickler$Scan.readTypeRef(UnPickler.scala:792)
	at scala.reflect.internal.pickling.UnPickler$Scan.readType(UnPickler.scala:358)
	at scala.reflect.internal.pickling.UnPickler$Scan$LazyTypeRef$$anonfun$34.apply(UnPickler.scala:855)
	at scala.reflect.internal.pickling.UnPickler$Scan$LazyTypeRef$$anonfun$34.apply(UnPickler.scala:855)
	at scala.reflect.internal.pickling.UnPickler$Scan.at(UnPickler.scala:171)
	at scala.reflect.internal.pickling.UnPickler$Scan$LazyTypeRef.complete(UnPickler.scala:855)
	at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1231)
	at scala.reflect.internal.Symbols$Symbol.initialize(Symbols.scala:1374)
	at scala.reflect.internal.Symbols$Symbol.annotations(Symbols.scala:1581)
	at scala.reflect.internal.Symbols$Symbol.addAnnotation(Symbols.scala:1600)
	at scala.reflect.internal.pickling.UnPickler$Scan.readSymbolAnnotation(UnPickler.scala:491)
	at scala.reflect.internal.pickling.UnPickler$Scan.run(UnPickler.scala:88)
	at scala.reflect.internal.pickling.UnPickler.unpickle(UnPickler.scala:37)
	at scala.reflect.runtime.JavaMirrors$JavaMirror.unpickleClass(JavaMirrors.scala:565)
	at scala.reflect.runtime.SymbolLoaders$TopClassCompleter.complete(SymbolLoaders.scala:32)
	at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1231)
	at scala.reflect.internal.Symbols$Symbol.initialize(Symbols.scala:1374)
	at scala.reflect.internal.Symbols$Symbol.hasFlag(Symbols.scala:607)
	at scala.reflect.internal.Symbols$TermSymbol.isTermMacro(Symbols.scala:2453)
	at scala.reflect.internal.Symbols$Symbol.symbolKind(Symbols.scala:2263)
	at scala.reflect.internal.Symbols$Symbol.sanitizedKindString(Symbols.scala:2297)
	at scala.reflect.internal.Symbols$Symbol.kindString(Symbols.scala:2305)
	at scala.reflect.internal.Symbols$Symbol.toString(Symbols.scala:2350)
	at java.lang.String.valueOf(String.java:2994)
	at scala.collection.mutable.StringBuilder.append(StringBuilder.scala:197)
	at scala.collection.TraversableOnce$$anonfun$addString$1.apply(TraversableOnce.scala:322)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableOnce$class.addString(TraversableOnce.scala:320)
	at scala.collection.AbstractTraversable.addString(Traversable.scala:105)
	at scala.collection.TraversableOnce$class.mkString(TraversableOnce.scala:286)
	at scala.collection.AbstractTraversable.mkString(Traversable.scala:105)
	at scala.collection.TraversableLike$class.toString(TraversableLike.scala:639)
	at scala.collection.SeqLike$class.toString(SeqLike.scala:646)
	at scala.collection.AbstractSeq.toString(Seq.scala:40)
	at java.lang.String.valueOf(String.java:2994)
	at scala.collection.mutable.StringBuilder.append(StringBuilder.scala:197)
	at scala.reflect.internal.Symbols$Symbol.suchThat(Symbols.scala:1678)
	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:44)
	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:61)
	at scala.reflect.internal.Mirrors$RootsBase.staticModuleOrClass(Mirrors.scala:72)
	at scala.reflect.internal.Mirrors$RootsBase.staticModule(Mirrors.scala:161)
	at scala.reflect.internal.Mirrors$RootsBase.staticModule(Mirrors.scala:21)
	at com.intel.analytics.bigdl.utils.serializer.ModuleSerializable$$typecreator5$1.apply(ModuleSerializable.scala:191)
	at scala.reflect.api.TypeTags$WeakTypeTagImpl.tpe$lzycompute(TypeTags.scala:231)
	at scala.reflect.api.TypeTags$WeakTypeTagImpl.tpe(TypeTags.scala:231)
	at scala.reflect.api.TypeTags$class.typeOf(TypeTags.scala:335)
	at scala.reflect.api.Universe.typeOf(Universe.scala:59)
	at com.intel.analytics.bigdl.utils.serializer.ModuleSerializable$class.setDataTypes(ModuleSerializable.scala:191)
	at com.intel.analytics.bigdl.utils.serializer.ContainerSerializer$.setDataTypes(ModuleSerializable.scala:408)
	at com.intel.analytics.bigdl.utils.serializer.ModuleSerializable$class.serializeModule(ModuleSerializable.scala:176)
	at com.intel.analytics.bigdl.utils.serializer.ContainerSerializer$.serializeModule(ModuleSerializable.scala:408)
	at com.intel.analytics.bigdl.utils.serializer.ModuleSerializer$.serialize(ModuleSerializer.scala:77)
	at com.intel.analytics.bigdl.nn.abstractnn.AbstractModule.clone(AbstractModule.scala:470)
	at com.intel.analytics.bigdl.models.utils.ModelBroadcast.value(ModelBroadcast.scala:62)
	at com.intel.analytics.bigdl.optim.Evaluator$$anonfun$test$1.apply(Evaluator.scala:60)
	at com.intel.analytics.bigdl.optim.Evaluator$$anonfun$test$1.apply(Evaluator.scala:59)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by yiheng** [comment]
Looks like this is related with this change: https://github.com/intel-analytics/BigDL/commit/51a56d9bd21e16ba653baa5c8c78f1bf8ae11310

Which version of spark you're using?

**Comment by wzhongyuan** [comment]
@yiheng it seems wired, and specific to scala version, found below unsolved issue
https://github.com/scala/pickling/issues/369

**Comment by wzhongyuan** [comment]
it should be fixed in https://github.com/intel-analytics/BigDL/pull/2363, closing it now
