### ISSUE TITLE
DLEstimator raises "tensor in ArraySample should be contiguous" issue on Mac

### ISSUE THREAD

**Issue by songhappy** [intel-analytics/BigDL#2392]
java.lang.IllegalArgumentException: requirement failed: tensor in ArraySample should be contiguous, Please check your input.
    at scala.Predef$.require(Predef.scala:233)
    at com.intel.analytics.bigdl.dataset.ArraySample$.com$intel$analytics$bigdl$dataset$ArraySample$$typeCheck(Sample.scala:233)
    at com.intel.analytics.bigdl.dataset.ArraySample$.apply(Sample.scala:256)
    at com.intel.analytics.bigdl.dataset.Sample$.apply(Sample.scala:363)
    at com.intel.analytics.bigdl.dlframes.DLEstimator$$anonfun$15.apply(DLEstimator.scala:302)
    at com.intel.analytics.bigdl.dlframes.DLEstimator$$anonfun$15.apply(DLEstimator.scala:301)

**Comment by hhbyyh** [comment]
@songhappy I've discussed f2f with you about the issue and I cannot repro the issue on a linux server. Also you have the desktop with linux to try by yourself. I don't have a mac to repro the issue and cannot help much here.

Please do NOT assign the issue to me without talking to me first. And for any issue, please at least provide the code and environment specification.

**Comment by hhbyyh** [comment]
Adding myself back. @songhappy please add more details about the issue. 
E.g. version of Spark, submit script and the code that triggers the issue. 
I'll look into it later. Also I need to borrow the Mac @jenniew

**Comment by songhappy** [comment]
environment
Mac, spark1.6.0 and scala 2.10

code
https://github.com/intel-analytics/BigDL/blob/master/spark/dl/src/main/scala/com/intel/analytics/bigdl/example/dlframes/imageTransferLearning/ImageTransferLearning.scala

error info
java.lang.IllegalArgumentException: requirement failed: tensor in ArraySample should be contiguous, Please check your input.
	at scala.Predef$.require(Predef.scala:233)
	at com.intel.analytics.bigdl.dataset.ArraySample$.com$intel$analytics$bigdl$dataset$ArraySample$$typeCheck(Sample.scala:233)
	at com.intel.analytics.bigdl.dataset.ArraySample$.apply(Sample.scala:256)
	at com.intel.analytics.bigdl.dataset.Sample$.apply(Sample.scala:363)
	at com.intel.analytics.bigdl.dlframes.DLEstimator$$anonfun$15.apply(DLEstimator.scala:302)
	at com.intel.analytics.bigdl.dlframes.DLEstimator$$anonfun$15.apply(DLEstimator.scala:301)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:149)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:73)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1431)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1419)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1418)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1418)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:799)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:799)
	at scala.Option.foreach(Option.scala:236)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:799)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1640)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1599)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1588)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:620)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1832)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1845)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1858)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1929)
	at org.apache.spark.rdd.RDD.count(RDD.scala:1143)
	at com.intel.analytics.bigdl.dataset.DistributedDataSet$$anon$5.cache(DataSet.scala:191)
	at com.intel.analytics.bigdl.optim.DistriOptimizer.prepareInput(DistriOptimizer.scala:872)
	at com.intel.analytics.bigdl.optim.DistriOptimizer.optimize(DistriOptimizer.scala:895)
	at com.intel.analytics.bigdl.dlframes.DLEstimator.internalFit(DLEstimator.scala:331)
	at com.intel.analytics.bigdl.dlframes.DLEstimator.internalFit(DLEstimator.scala:163)
