### ISSUE TITLE
Downloaded BigDL 0.5 binary package cannot be used to convert images to sequence file

### ISSUE THREAD

**Issue by ZeweiChen11** [intel-analytics/BigDL#2487]
We downloaded BigDL 0.5 binary package for Spark 2.2.0 from https://bigdl-project.github.io/0.5.0/#release-download/. But it doesn't include bigdl-*-jar-with-dependencies-and-spark.jar to convert images. We used the only jar ./lib/bigdl-SPARK_2.2-0.5.0-jar-with-dependencies.jar and it reports error like following.

```
java -cp /mnt/disk1/Bigdl-0.5.0/lib/bigdl-SPARK_2.2-0.5.0-jar-with-dependencies.jar com.intel.analytics.bigdl.models.utils.ImageNetSeqFileGenerator -f . -o ./sequence/ -p 44
Exception in thread "main" java.lang.NoClassDefFoundError: scala/Product
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at com.intel.analytics.bigdl.models.utils.ImageNetSeqFileGenerator.main(ImageNetSeqFileGenerator.scala)
Caused by: java.lang.ClassNotFoundException: scala.Product
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 13 more
```

**Comment by yiheng** [comment]
This is a known issue. See https://github.com/intel-analytics/BigDL/issues/1709.

Currently the work around is install scala 2.11, and use scala intead of java to run that command.

**Comment by jason-dai** [comment]
Does the doc/readme use Java or Scala in the command line?

**Comment by yiheng** [comment]
It's java. https://github.com/intel-analytics/BigDL/tree/master/spark/dl/src/main/scala/com/intel/analytics/bigdl/models/inception

We should change it to scala before the fix is done.
