### ISSUE TITLE
Backward fail if CDivTable and Sum is used together

### ISSUE THREAD

**Issue by zhichao-li** [intel-analytics/BigDL#2502]
Here's the sample code to reproduce this issue:
scala
```
    val input1 = Input[Float]()
    val s = Sum[Float](dimension = 2, squeeze = false).inputs(input1)
    val div = CDivTable[Float]().inputs(input1, s)
    val graph = Graph(input = input1, output = div)
     val o = graph.forward(input)
     graph.backward(input, o)
```

requirement failed: invalid size eElement
java.lang.IllegalArgumentException: requirement failed: invalid size eElement
	at scala.Predef$.require(Predef.scala:233)
	at com.intel.analytics.bigdl.tensor.DenseTensor.view(DenseTensor.scala:172)
	at com.intel.analytics.bigdl.nn.Sum.updateGradInput(Sum.scala:101)
	at com.intel.analytics.bigdl.nn.Sum.updateGradInput(Sum.scala:44)
	at com.intel.analytics.bigdl.nn.abstractnn.AbstractModule.backward(AbstractModule.scala:268)
	at com.intel.analytics.bigdl.nn.StaticGraph.backwardExecution(StaticGraph.scala:137)
	at com.intel.analytics.bigdl.nn.StaticGraph.backward(StaticGraph.scala:69)

**Comment by zhichao-li** [comment]
@qiuxin2012 @yiheng

**Comment by qiuxin2012** [comment]
@zhichao-li input tensor's size?

**Comment by zhichao-li** [comment]
`    val input = Tensor[Float](Shape(2, 3).toSingle().toArray).rand(0, 1)`

**Comment by zhichao-li** [comment]
It turn out that it's because of `CDivTable` lacking the ability to broadcast when size not match in `backward` stage.  An enhancement we can make is to support the nice feature or throw exception explicitly in `forward` stage temporarily.
