### ISSUE TITLE
Generated tensorflow protobuf classes' signature is changed by relocating protobuf and may result in conflict

### ISSUE THREAD

**Issue by yangw1234** [intel-analytics/BigDL#2550]
If another project depends on both BigDL and tensorflow proto, there will be a conflict.

**Comment by yangw1234** [comment]
```
        <dependency>
            <groupId>com.intel.analytics.bigdl</groupId>
            <artifactId>${bigdl.artifactId}</artifactId>
            <version>${bigdl.version}</version>
            <scope>${bigdl-scope}</scope>
        </dependency>
        <dependency>
            <groupId>org.tensorflow</groupId>
            <artifactId>proto</artifactId>
            <version>1.8.0</version>
        </dependency>

```
```
```

**Comment by yangw1234** [comment]
```
        <dependency>
            <groupId>org.tensorflow</groupId>
            <artifactId>proto</artifactId>
            <version>1.8.0</version>
        </dependency>
        <dependency>
            <groupId>com.intel.analytics.bigdl</groupId>
            <artifactId>${bigdl.artifactId}</artifactId>
            <version>${bigdl.version}</version>
            <scope>${bigdl-scope}</scope>
        </dependency>
```

If tensorflow dependency is put before BigDL, `TensorflowLoader.load` does not work.
```
An exception or error caused a run to abort: org.tensorflow.framework.GraphDef.parseFrom(Lcom/intel/analytics/bigdl/shaded/protobuf/CodedInputStream;)Lorg/tensorflow/framework/GraphDef; 
java.lang.NoSuchMethodError: org.tensorflow.framework.GraphDef.parseFrom(Lcom/intel/analytics/bigdl/shaded/protobuf/CodedInputStream;)Lorg/tensorflow/framework/GraphDef;
	at com.intel.analytics.bigdl.utils.tf.TensorflowLoader$.parse(TensorflowLoader.scala:97)
	at com.intel.analytics.bigdl.utils.tf.TensorflowLoader$.load(TensorflowLoader.scala:56)
	at com.intel.analytics.zoo.pipeline.api.Net$.loadTF(Net.scala:158)
	at com.intel.analytics.zoo.pipeline.api.NetSpec$$anonfun$7.apply$mcV$sp(NetSpec.scala:93)
	at com.intel.analytics.zoo.pipeline.api.NetSpec$$anonfun$7.apply(NetSpec.scala:90)
	at com.intel.analytics.zoo.pipeline.api.NetSpec$$anonfun$7.apply(NetSpec.scala:90)
	at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.FlatSpecLike$$anon$1.apply(FlatSpecLike.scala:1647)
	at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
	at org.scalatest.FlatSpec.withFixture(FlatSpec.scala:1683)
	at org.scalatest.FlatSpecLike$class.invokeWithFixture$1(FlatSpecLike.scala:1644)
	at org.scalatest.FlatSpecLike$$anonfun$runTest$1.apply(FlatSpecLike.scala:1656)
	at org.scalatest.FlatSpecLike$$anonfun$runTest$1.apply(FlatSpecLike.scala:1656)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
	at org.scalatest.FlatSpecLike$class.runTest(FlatSpecLike.scala:1656)
	at com.intel.analytics.zoo.pipeline.api.keras.ZooSpecHelper.org$scalatest$BeforeAndAfter$$super$runTest(ZooSpecHelper.scala:30)
	at org.scalatest.BeforeAndAfter$class.runTest(BeforeAndAfter.scala:200)
	at com.intel.analytics.zoo.pipeline.api.keras.ZooSpecHelper.runTest(ZooSpecHelper.scala:30)
	at org.scalatest.FlatSpecLike$$anonfun$runTests$1.apply(FlatSpecLike.scala:1714)
	at org.scalatest.FlatSpecLike$$anonfun$runTests$1.apply(FlatSpecLike.scala:1714)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:390)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:427)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
	at org.scalatest.FlatSpecLike$class.runTests(FlatSpecLike.scala:1714)
	at org.scalatest.FlatSpec.runTests(FlatSpec.scala:1683)
	at org.scalatest.Suite$class.run(Suite.scala:1424)
	at org.scalatest.FlatSpec.org$scalatest$FlatSpecLike$$super$run(FlatSpec.scala:1683)
	at org.scalatest.FlatSpecLike$$anonfun$run$1.apply(FlatSpecLike.scala:1760)
	at org.scalatest.FlatSpecLike$$anonfun$run$1.apply(FlatSpecLike.scala:1760)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:545)
	at org.scalatest.FlatSpecLike$class.run(FlatSpecLike.scala:1760)
	at com.intel.analytics.zoo.pipeline.api.keras.ZooSpecHelper.org$scalatest$BeforeAndAfter$$super$run(ZooSpecHelper.scala:30)
	at org.scalatest.BeforeAndAfter$class.run(BeforeAndAfter.scala:241)
	at com.intel.analytics.zoo.pipeline.api.keras.ZooSpecHelper.run(ZooSpecHelper.scala:30)
	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:55)
	at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2563)
	at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2557)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:2557)
	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1044)
	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1043)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:2722)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1043)
	at org.scalatest.tools.Runner$.run(Runner.scala:883)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2(ScalaTestRunner.java:138)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:28)
```

**Comment by yangw1234** [comment]
cc @yiheng

**Comment by yiheng** [comment]
Thanks. Has reproduce the issue.

**Comment by yiheng** [comment]
@yangw1234 has raised a PR to fix it. Please help review.
