### ISSUE TITLE
Predict image in spark local mode get IllegalArgumentException

### ISSUE THREAD

**Issue by jenniew** [intel-analytics/BigDL#2558]
We met errors when using predictImage API to predict inception v1 w/ ImageNet val. But it reported java.lang.IllegalArgumentException for 5k images and java.lang.ArrayIndexOutOfBoundsException for 4999 images. Predicting 1000 images can pass.

Code:
     val conf = Engine.createSparkConf()
     conf.setAppName("Predict with trained model")
      val sc = new SparkContext(conf)
      Engine.init
      val model = Module.loadModule[Float](params.model)
      val images = ImageFrame.read(params.imageFolder, sc, params.nPartition)
      val partitionNum = images.toDistributed().rdd.partitions.length
      val partitions = images.toDistributed().rdd.partitions

      logger.info(s"partition number is: ${partitionNum}")
      images.toDistributed().rdd.mapPartitions(partition => {
        println(s"partition size: ${partition.size}")
        partition
      }).collect()

      val inceptionPreprocessing = Resize(256, 256) -> CenterCrop(224, 224) ->
        ChannelNormalize(123, 117, 104) ->
        MatToTensor[Float]() ->
        ImageFrameToSample[Float]()

      val data = inceptionPreprocessing(images)
      val output = model.predictImage(data)
      val result = output.toDistributed().rdd.collect

Execution script:

#!/bin/sh
spark-submit --master local[28]  --conf spark.driver.maxResultSize=20g --driver-memory 20g --class com.intel.analytics.bigdl.example.imageclassification.ImageClassifier ./dist/lib/bigdl-0.5.0-jar-with-dependencies.jar -f /root/val_5k --model /root/bigdl_inception-v1_imagenet_0.4.0.model  -p 4 

Exception:
java.lang.IllegalArgumentException: requirement failed: Input must have 4 dimensions, corresponding to (batch, channels, height, width)input dimension 3
	at scala.Predef$.require(Predef.scala:224)
	at com.intel.analytics.bigdl.nn.SpatialCrossMapLRN.updateOutput(SpatialCrossMapLRN.scala:97)
	at com.intel.analytics.bigdl.nn.SpatialCrossMapLRN.updateOutput(SpatialCrossMapLRN.scala:43)
	at com.intel.analytics.bigdl.nn.abstractnn.AbstractModule.forward(AbstractModule.scala:243)
	at com.intel.analytics.bigdl.nn.StaticGraph.updateOutput(StaticGraph.scala:59)
	at com.intel.analytics.bigdl.nn.abstractnn.AbstractModule.forward(AbstractModule.scala:243)
	at com.intel.analytics.bigdl.optim.Predictor$$anonfun$predictSamples$1.apply(Predictor.scala:70)
	at com.intel.analytics.bigdl.optim.Predictor$$anonfun$predictSamples$1.apply(Predictor.scala:69)
	at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:434)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
	at scala.collection.Iterator$$anon$19.hasNext(Iterator.scala:800)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at com.intel.analytics.bigdl.optim.Predictor$.predictImageBatch(Predictor.scala:50)
	at com.intel.analytics.bigdl.optim.Predictor$$anonfun$10$$anonfun$apply$4.apply(Predictor.scala:204)
	at com.intel.analytics.bigdl.optim.Predictor$$anonfun$10$$anonfun$apply$4.apply(Predictor.scala:203

**Comment by jason-dai** [comment]
@yiheng any update?

**Comment by yiheng** [comment]
Sorry for the late response. A little busy on the coming release.

I try the exact same code posted here on my desktop and cannot reproduce the error for 4999 or 5000. The difference is I use the master code and local[4] instead of local[28]

@jenniew Can you retry compiling your code with latest master code?

**Comment by yiheng** [comment]
@jenniew any update?

**Comment by jenniew** [comment]
I pulled the latest master code and run with local[4] on 5000 images, still got error:

 (21 + 4) / 3101]18/08/02 23:50:33 ERROR Executor: Exception in task 27.0 in stage 1.0 (TID 3128)
java.lang.ArrayIndexOutOfBoundsException
	at java.lang.System.arraycopy(Native Method)
	at com.intel.analytics.bigdl.tensor.TensorNumericMath$TensorNumeric$NumericFloat$.arraycopy$mcF$sp(TensorNumeric.scala:721)
	at com.intel.analytics.bigdl.tensor.TensorNumericMath$TensorNumeric$NumericFloat$.arraycopy(TensorNumeric.scala:715)
	at com.intel.analytics.bigdl.tensor.TensorNumericMath$TensorNumeric$NumericFloat$.arraycopy(TensorNumeric.scala:503)
	at com.intel.analytics.bigdl.dataset.MiniBatch$.copy(MiniBatch.scala:460)
	at com.intel.analytics.bigdl.dataset.MiniBatch$.copyWithPadding(MiniBatch.scala:380)
	at com.intel.analytics.bigdl.dataset.ArrayTensorMiniBatch.set(MiniBatch.scala:209)
	at com.intel.analytics.bigdl.dataset.ArrayTensorMiniBatch.set(MiniBatch.scala:111)
	at com.intel.analytics.bigdl.dataset.SampleToMiniBatch$$anon$2.next(Transformer.scala:346)
	at com.intel.analytics.bigdl.dataset.SampleToMiniBatch$$anon$2.next(Transformer.scala:323)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
	at scala.collection.Iterator$$anon$20.hasNext(Iterator.scala:634)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at com.intel.analytics.bigdl.optim.Predictor$.predictImageBatch(Predictor.scala:47)
	at com.intel.analytics.bigdl.optim.Predictor$$anonfun$9$$anonfun$apply$1.apply(Predictor.scala:144)
	at com.intel.analytics.bigdl.optim.Predictor$$anonfun$9$$anonfun$apply$1.apply(Predictor.scala:143)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:48)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:103)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:47)
	at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:273)
	at scala.collection.AbstractIterator.to(Iterator.scala:1157)
	at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:265)
	at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1157)
	at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:252)
	at scala.collection.AbstractIterator.toArray(Iterator.scala:1157)
	at org.apache.spark.rdd.RDD$$anonfun$collect$1$$anonfun$12.apply(RDD.scala:927)
	at org.apache.spark.rdd.RDD$$anonfun$collect$1$$anonfun$12.apply(RDD.scala:927)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1858)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1858)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[Stage 1:>                                                      (24 + 5) / 3101]18/08/02 23:50:33 ERROR TaskSetManager: Task 27 in stage 1.0 failed 1 times; aborting job
Exception in thread "main" org.apache.spark.SparkException: Job aborted due to stage failure: Task 27 in stage 1.0 failed 1 times, most recent failure: Lost task 27.0 in stage 1.0 (TID 3128, localhost): java.lang.ArrayIndexOutOfBoundsException
	at java.lang.System.arraycopy(Native Method)
	at com.intel.analytics.bigdl.tensor.TensorNumericMath$TensorNumeric$NumericFloat$.arraycopy$mcF$sp(TensorNumeric.scala:721)
	at com.intel.analytics.bigdl.tensor.TensorNumericMath$TensorNumeric$NumericFloat$.arraycopy(TensorNumeric.scala:715)
	at com.intel.analytics.bigdl.tensor.TensorNumericMath$TensorNumeric$NumericFloat$.arraycopy(TensorNumeric.scala:503)
	at com.intel.analytics.bigdl.dataset.MiniBatch$.copy(MiniBatch.scala:460)
	at com.intel.analytics.bigdl.dataset.MiniBatch$.copyWithPadding(MiniBatch.scala:380)
	at com.intel.analytics.bigdl.dataset.ArrayTensorMiniBatch.set(MiniBatch.scala:209)
	at com.intel.analytics.bigdl.dataset.ArrayTensorMiniBatch.set(MiniBatch.scala:111)
	at com.intel.analytics.bigdl.dataset.SampleToMiniBatch$$anon$2.next(Transformer.scala:346)
	at com.intel.analytics.bigdl.dataset.SampleToMiniBatch$$anon$2.next(Transformer.scala:323)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
	at scala.collection.Iterator$$anon$20.hasNext(Iterator.scala:634)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at com.intel.analytics.bigdl.optim.Predictor$.predictImageBatch(Predictor.scala:47)
	at com.intel.analytics.bigdl.optim.Predictor$$anonfun$9$$anonfun$apply$1.apply(Predictor.scala:144)
	at com.intel.analytics.bigdl.optim.Predictor$$anonfun$9$$anonfun$apply$1.apply(Predictor.scala:143)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:48)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:103)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:47)
	at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:273)
	at scala.collection.AbstractIterator.to(Iterator.scala:1157)
	at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:265)
	at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1157)
	at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:252)
	at scala.collection.AbstractIterator.toArray(Iterator.scala:1157)
	at org.apache.spark.rdd.RDD$$anonfun$collect$1$$anonfun$12.apply(RDD.scala:927)
	at org.apache.spark.rdd.RDD$$anonfun$collect$1$$anonfun$12.apply(RDD.scala:927)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1858)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1858)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by yiheng** [comment]
Looks like this only affect spark 1.6. Look into it.

**Comment by yiheng** [comment]
It's not related with Spark version. It's a bug in ImageFrame. When load grey image, it returns a one channel tensor instead of 3 channels tensor. So the input tensor to the model is incorrect.

**Comment by yiheng** [comment]
It's not a bug. As your data contains grey image, and your model only accept a 3 channel tensor, you should set the toRGB flag to true of the MatToTensor transformer.

**Comment by jenniew** [comment]
why is the grey image loading issue? I use the imagenet data which is color image not grey image, do you mean imageframe will read the color image as grey image?
