### ISSUE TITLE
Error 'assertion failed: total weight must larger than 0' - occasional failures when using NLLCriterion with some unlabeled data

### ISSUE THREAD

**Issue by griffinkardos** [intel-analytics/BigDL#2617]
I'm training on an dataset with some unlabeled data, using a parallel criterion, where one of the criteria is a reconstruction loss, and the other is a classification loss, which should be ignored for unlabeled data. When I call optimizer.optimize() with this criterion, it trains for some number of iterations (i.e, it doesn't fail on every iteration), before crashing with this error:

```
2018-08-21 23:56:02 ERROR ThreadPool$:115 - Error: java.lang.AssertionError: assertion failed: total weight must larger than 0
	at scala.Predef$.assert(Predef.scala:170)
	at com.intel.analytics.bigdl.nn.ClassNLLCriterion.updateGradInput(ClassNLLCriterion.scala:169)
	at com.intel.analytics.bigdl.nn.CrossEntropyCriterion.updateGradInput(CrossEntropyCriterion.scala:48)
	at com.intel.analytics.bigdl.nn.CrossEntropyCriterion.updateGradInput(CrossEntropyCriterion.scala:31)
	at com.intel.analytics.bigdl.nn.ParallelCriterion.updateGradInput(ParallelCriterion.scala:74)
	at com.intel.analytics.bigdl.nn.ParallelCriterion.updateGradInput(ParallelCriterion.scala:35)
	at com.intel.analytics.bigdl.nn.abstractnn.AbstractCriterion.backward(AbstractCriterion.scala:84)
	at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$4$$anonfun$6$$anonfun$apply$2.apply$mcI$sp(DistriOptimizer.scala:258)
	at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$4$$anonfun$6$$anonfun$apply$2.apply(DistriOptimizer.scala:249)
	at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$4$$anonfun$6$$anonfun$apply$2.apply(DistriOptimizer.scala:249)
	at com.intel.analytics.bigdl.utils.ThreadPool$$anonfun$1$$anon$4.call(ThreadPool.scala:112)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

I've optimized the same model with the same criterion on the same data with the unlabeled samples filtered out just fine. But I'd like to make use of the unlabeled data too.
According to the docs, 
> Note that if the target is -1, the training process will skip this sample. In other words, the forward process will return zero output and the backward process will also return zero gradInput.

Experimentally however, this works out with just a single data point:
```
test_criterion = ParallelCriterion()
test_criterion.add(MSECriterion()).add(CrossEntropyCriterion())

test_criterion = ParallelCriterion()
test_criterion.add(MSECriterion()).add(CrossEntropyCriterion())

pred = np.array([0.1,0.5,2,1,0.])
recon = np.array([1.,3.,4.])
combined = [recon, pred]
target = [np.array([2.,2.,5.]),np.array([-1])]
print(test_criterion.forward(combined, target))
print(test_criterion.backward(combined, target))
```

In this case forwards gives an appropriate loss (i.e it ignores the class scores), and backwards also gives an appropriate gradient.

However if I make this into a minibatch and do the same:
```
test_criterion = ParallelCriterion()
test_criterion.add(MSECriterion()).add(CrossEntropyCriterion())

pred = np.array([[0.1,0.5,2,1,0.]])
recon = np.array([[1.,3.,4.]])
combined = [recon, pred]
target = [np.array([[2.,2.,5.]]),np.array([[-1]])]
print(test_criterion.forward(combined, target))
print(test_criterion.backward(combined, target))
```
I get the same error as above, that the total weight needs to be greater than 0. If I do a minibatch where one target is -1 and the other is a positive integer, it works fine too. 

Looking at the source for ClassNLLCriterion, it appears that, for a single sample, the default weight is 1 regardess of whether the target is -1, whereas with the batch case, the default value is 0 for -1 labels, and 1 otherwise, which makes sense so you don't include those samples in calculating the total weight of a batch, but also means it fails if all the samples are unlabeled, and it would be more desirable for me if it would still return a forwards loss of 0, and a backwards gradient of zero. Not sure what the desired behavior or optimal workaround is though.

**Comment by yiheng** [comment]
For a minibatch, I think we should set the total_weight to 1 if find all samples are skipped. In that case, the gradient/loss are zero, and zero / one is still zero. Do you think it make sense?

**Comment by griffinkardos** [comment]
Yes, that's what I've done on my build and it's working perfectly:

```
while (i < batchSize) {
    val (o, w) = Await.result(results(i), Duration.Inf)
    output = ev.minus(output, o)
    total_weight = ev.plus(total_weight, w)
    i += 1
}
if(total_weight == 0){
    total_weight = ev.fromType[Int](1)
}
```
This stops it from throwing the assertion error, and the output & gradients are 0 as expected. I can't imagine some case where the total weight could be zero - other than all the targets being -1 or having weights for all the targets in the batch be zero - where we would want it to still error out. Otherwise I'll make a PR
