### ISSUE TITLE
java.lang.StackOverflowError 	at com.esotericsoftware.kryo.Generics.getConcreteClass(Generics.java:62)

### ISSUE THREAD

**Issue by wzxwf** [intel-analytics/BigDL#2621]
Run the sample VGG in 0.4_spark 2.2 and 0.5 spark _2.2
--conf "spark.driver.extraJavaOptions=-Xss8092k"
Setting properties is useless
why?
2018-08-23 16:59:47 INFO  Engine$:99 - Auto detect executor number and executor cores number
2018-08-23 16:59:47 INFO  Engine$:101 - Executor number is 1 and executor cores number is 4
2018-08-23 16:59:47 INFO  Engine$:292 - Find existing spark context. Checking the spark conf...
2018-08-23 16:59:50 INFO  DistriOptimizer$:838 - caching training rdd ...
2018-08-23 16:59:56 ERROR ApplicationMaster:91 - User class threw exception: java.lang.StackOverflowError
java.lang.StackOverflowError
	at com.esotericsoftware.kryo.Generics.getConcreteClass(Generics.java:62)
	at com.esotericsoftware.kryo.Generics.getConcreteClass(Generics.java:62)
	at com.esotericsoftware.kryo.Generics.getConcreteClass(Generics.java:62)
	at com.esotericsoftware.kryo.Generics.getConcreteClass(Generics.java:62)
	at com.esotericsoftware.kryo.Generics.getConcreteClass(Generics.java:62)
	at com.esotericsoftware.kryo.Generics.getConcreteClass(Generics.java:62)
	at com.esotericsoftware.kryo.Generics.getConcreteClass(Generics.java:62)
	at com.esotericsoftware.kryo.Generics.getConcreteClass(Generics.java:62)
	at com.esotericsoftware.kryo.Generics.getConcreteClass(Generics.java:62)
	at com.esotericsoftware.kryo.Generics.getConcreteClass(Generics.java:62)
	at com.esotericsoftware.kryo.Generics.getConcreteClass(Generics.java:62)
	at com.esotericsoftware.kryo.Generics.getConcreteClass(Generics.java:62)
	at com.esotericsoftware.kryo.Generics.getConcreteClass(Generics.java:62)
	at com.esotericsoftware.kryo.Generics.getConcreteClass(Generics.java:62)
	at com.esotericsoftware.kryo.Generics.getConcreteClass(Generics.java:62)
	at com.esotericsoftware.kryo.Generics.getConcreteClass(Generics.java:62)
	at com.esotericsoftware.kryo.Generics.getConcreteClass(Generics.java:62)
	at com.esotericsoftware.kryo.Generics.getConcreteClass(Generics.java:62)
	at com.esotericsoftware.kryo.Generics.getConcreteClass(Generics.java:62)
	at com.esotericsoftware.kryo.Generics.getConcreteClass(Generics.java:62)
	at com.esotericsoftware.kryo.Generics.getConcreteClass(Generics.java:62)
	at com.esotericsoftware.kryo.Generics.getConcreteClass(Generics.java:62)
	at com.esotericsoftware.kryo.Generics.getConcreteClass(Generics.java:62)
	at com.esotericsoftware.kryo.Generics.getConcreteClass(Generics.java:62)
	at com.esotericsoftware.kryo.Generics.getConcreteClass(Generics.java:62)
	at com.esotericsoftware.kryo.Generics.getConcreteClass(Generics.java:62)
	at com.esotericsoftware.kryo.Generics.getConcreteClass(Generics.java:62)
	at com.esotericsoftware.kryo.Generics.getConcreteClass(Generics.java:62)
	at com.esotericsoftware.kryo.Generics.getConcreteClass(Generics.java:62)
	at com.esotericsoftware.kryo.Generics.getConcreteClass(Generics.java:62)
	at com.esotericsoftware.kryo.Generics.getConcreteClass(Generics.java:62)
	at com.esotericsoftware.kryo.Generics.getConcreteClass(Generics.java:62)
	at com.esotericsoftware.kryo.Generics.getConcreteClass(Generics.java:62)
	at com.esotericsoftware.kryo.Generics.getConcreteClass(Generics.java:62)
	at com.esotericsoftware.kryo.Generics.getConcreteClass(Generics.java:62)
	at com.esotericsoftware.kryo.Generics.getConcreteClass(Generics.java:62)
	at com.esotericsoftware.kryo.Generics.getConcreteClass(Generics.java:62)
	at com.esotericsoftware.kryo.Generics.getConcreteClass(Generics.java:62)
	at com.esotericsoftware.kryo.Generics.getConcreteClass(Generics.java:62)
	at com.esotericsoftware.kryo.Generics.getConcreteClass(Generics.java:62)
	at com.esotericsoftware.kryo.Generics.getConcreteClass(Generics.java:62)
	at com.esotericsoftware.kryo.Generics.getConcreteClass(Generics.java:62)
	at com.esotericsoftware.kryo.Generics.getConcreteClass(Generics.java:62)
	at com.esotericsoftware.kryo.Generics.getConcreteClass(Generics.java:62)
	at com.esotericsoftware.kryo.Generics.getConcreteClass(Generics.java:62)
	at com.esotericsoftware.kryo.Generics.getConcreteClass(Generics.java:62)
	at com.esotericsoftware.kryo.Generics.getConcreteClass(Generics.java:62)
	at com.esotericsoftware.kryo.Generics.getConcreteClass(Generics.java:62)
	at com.esotericsoftware.kryo.Generics.getConcreteClass(Generics.java:62)

**Comment by yiheng** [comment]
This is a bug of kryo. See https://bigdl-project.github.io/0.6.0/#known-issues/
issue 3
