### ISSUE TITLE
BigDL compatibility issue on CDH

### ISSUE THREAD

**Issue by ZeweiChen11** [intel-analytics/BigDL#2628]
SW stack: BigDL 0.6, cdh 6.0
Running command:
```
spark-submit \
--master yarn \
--deploy-mode client \
--conf "spark.yarn.executor.memoryOverhead=60G" \
--conf "spark.blacklist.enabled=false" \
--conf "spark.dynamicAllocation.enabled=false" \
--executor-cores 36  \
--num-executors 4 \
--driver-memory 60g \
--executor-memory 180G \
--driver-class-path /root/BigDL-0.6.0/dist/lib/bigdl-*-jar-with-dependencies.jar \
--class com.intel.analytics.bigdl.models.inception.TrainInceptionV1 \
/root/BigDL-0.6.0/dist/lib/bigdl-*-jar-with-dependencies.jar \
--batchSize  1152 \
--learningRate 0.0896 \
-f hdfs:///user/root/sequence \
--maxEpoch 3 \
--checkpoint /mnt/disk2/ckp/inceptionv1

```

NPE Error 
```
2018-09-10 23:21:09 INFO  DistriOptimizer$:672 - Cache thread models...
2018-09-10 23:21:09 ERROR TaskSetManager:70 - Task 1 in stage 3.0 failed 1 times; aborting job
Exception in thread "main" org.apache.spark.SparkException: Job aborted due to stage failure: Task 1 in stage 3.0 failed 1 times, most recent failure: Lost task 1.0 in stage 3.0 (TID 152, hsw-node9, executor 1): java.lang.NullPointerException
        at com.intel.analytics.bigdl.models.utils.ModelBroadcast.value(ModelBroadcast.scala:120)
        at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$13$$anonfun$14.apply(DistriOptimizer.scala:643)
        at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$13$$anonfun$14.apply(DistriOptimizer.scala:642)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.immutable.Range.foreach(Range.scala:160)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.AbstractTraversable.map(Traversable.scala:104)
        at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$13.apply(DistriOptimizer.scala:642)
        at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$13.apply(DistriOptimizer.scala:625)
```

**Comment by yiheng** [comment]
Looks like this is similar with https://github.com/intel-analytics/BigDL/issues/2619. CDH6 is just released. We haven't test on it yet.

**Comment by tonye0115** [comment]
My spark yarn-cluster script:

===================================
spark2-submit \
    --conf spark.yarn.appMasterEnv.PYSPARK_PYTHON=Python/bin/python   \
    --master yarn \
    --deploy-mode  cluster  \
    --driver-memory 10g \
    --executor-memory 10g \
    --executor-cores 1 \
    --num-executors 10 \
    --jars ${ZOO_JAR_PATH} \
    --py-files ${PYTHON_API_ZIP_PATH},${PORJECT_HOME}/pyzoo/zoo/examples/objectdetection/hdfs_utils.py   \
    --archives hdfs://10.0.0.1:8020/user/deeplearn/analytics-zoo-work/library/Python-2.7.12.zip#Python  \
    --conf spark.dynamicAllocation.enabled=false \
    --conf spark.driver.extraClassPath=${ZOO_JAR_PATH}   \
    --conf spark.executor.extraClassPath=${ZOO_JAR_PATH}   \
   ${PORJECT_HOME}/pyzoo/zoo/examples/objectdetection/predict.py  \
    --hdfs_host  ${hdfsHost}   \
    --hdfs_port  ${hdfsPort}   \
    --model_path  ${modelPath}   \
    --img_path  ${imagePath}    \
    --output_path  ${outputPath}    \
    --partition_num ${partitionNum}

**Comment by i8run** [comment]
Hi,

It's due to the fix of `ModelBroadcast` is not compatible with KryoSerializer.
A workaround is adding `--conf "spark.serializer=org.apache.spark.serializer.JavaSerializer"` to command.

We will fix the bugs relevant with KryoSerializer after Spark 2.4.
