### ISSUE TITLE
ModuleLoader.loadFromFile from local filesystem will get an exception

### ISSUE THREAD

**Issue by glorysdj** [intel-analytics/BigDL#2630]
When load model from local file will get a hadoop home not set exception, can bigdl support loading from local file not with hadoop utils but plain old java style.

09:02:20.103 [main] DEBUG org.apache.hadoop.util.Shell - Failed to detect a valid hadoop home directory
java.io.IOException: HADOOP_HOME or hadoop.home.dir are not set.
	at org.apache.hadoop.util.Shell.checkHadoopHome(Shell.java:325)
	at org.apache.hadoop.util.Shell.<clinit>(Shell.java:350)
	at org.apache.hadoop.util.StringUtils.<clinit>(StringUtils.java:79)
	at org.apache.hadoop.security.Groups.parseStaticMapping(Groups.java:116)
	at org.apache.hadoop.security.Groups.<init>(Groups.java:93)
	at org.apache.hadoop.security.Groups.<init>(Groups.java:73)
	at org.apache.hadoop.security.Groups.getUserToGroupsMappingService(Groups.java:293)
	at org.apache.hadoop.security.UserGroupInformation.initialize(UserGroupInformation.java:283)
	at org.apache.hadoop.security.UserGroupInformation.ensureInitialized(UserGroupInformation.java:260)
	at org.apache.hadoop.security.UserGroupInformation.loginUserFromSubject(UserGroupInformation.java:789)
	at org.apache.hadoop.security.UserGroupInformation.getLoginUser(UserGroupInformation.java:774)
	at org.apache.hadoop.security.UserGroupInformation.getCurrentUser(UserGroupInformation.java:647)
	at org.apache.hadoop.fs.FileSystem$Cache$Key.<init>(FileSystem.java:2755)
	at org.apache.hadoop.fs.FileSystem$Cache$Key.<init>(FileSystem.java:2747)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2613)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:370)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:169)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:354)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:296)
	at com.intel.analytics.bigdl.utils.FileReader.<init>(File.scala:240)
	at com.intel.analytics.bigdl.utils.FileReader$.apply(File.scala:264)
	at com.intel.analytics.bigdl.utils.File$.readBytes(File.scala:198)
	at com.intel.analytics.bigdl.utils.serializer.ModuleLoader$.loadFromFile(ModuleLoader.scala:50)
	at com.intel.analytics.zoo.pipeline.inference.ModelLoader$$anonfun$loadFloatModel$1.apply(ModelLoader.scala:45)

**Comment by qiuxin2012** [comment]
Are you using BigDL without Hadoop and Spark?

**Comment by glorysdj** [comment]
yes, we need to do inference in pojo style, like plain web service, in a simple java env whiout spark and hadoop distribution but only libs

**Comment by yiheng** [comment]
This is a bug. We should fix it.

**Comment by qiuxin2012** [comment]
Not a issue. FileReader works fine without any HADOOP environment variables.  
This is only a debug message, not a unhandled exception.

If env "HADOOP_HOME" and system property "hadoop.home.dir" are unset, hadoop will throw an IOException in line [Shell.java#L290](https://github.com/apache/hadoop/blob/ac0538aac347bfd97cc0dee1db49db503c15f1d9/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/util/Shell.java#L290).
The exception will be catched in the following [Shell.java#L319](https://github.com/apache/hadoop/blob/ac0538aac347bfd97cc0dee1db49db503c15f1d9/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/util/Shell.java#L319), and set HADOOP_HOME_DIR to null. But FileSystem can works well even if HADOOP_HOME_DIR is  null.
