### ISSUE TITLE
Error loading the Torch model trained on ImageNet data in Spark yarn mode

### ISSUE THREAD

**Issue by algoscale1** [intel-analytics/BigDL#2641]
I am following this link [(https://github.com/intel-analytics/BigDL/tree/master/spark/dl/src/main/scala/com/intel/analytics/bigdl/example/imageclassification)] to load the Torch model trained on ImageNet data in Spark yarn mode. But i am getting this error - 

`18/10/03 12:52:09 INFO Engine$: Find existing spark context. Checking the spark conf...
[Stage 1:>                                                        (0 + 15) / 15]2018-10-03 12:52:29 ERROR TaskSetManager:70 - Task 5 in stage 1.0 failed 4 times; aborting job
Exception in thread "main" org.apache.spark.SparkException: Job aborted due to stage failure: Task 5 in stage 1.0 failed 4 times, most recent failure: Lost task 5.3 in stage 1.0 (TID 29, wn0-spark.1csc41zjafrutdj1trw201tr1e.cx.internal.cloudapp.net, executor 2): java.lang.NullPointerException
	at com.intel.analytics.bigdl.models.utils.ModelBroadcastImp.value(ModelBroadcast.scala:139)
	at com.intel.analytics.bigdl.dlframes.DLModel$$anonfun$16.apply(DLEstimator.scala:395)
	at com.intel.analytics.bigdl.dlframes.DLModel$$anonfun$16.apply(DLEstimator.scala:394)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:797)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:797)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:108)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:338)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
`

I am able to load the model in local mode though. This is my spark-submit command - 

> spark-submit --master yarn ---num-executors 8 --executor-cores 3 --driver-memory 10g  --class com.intel.analytics.bigdl.example.imageclassification.ImagePredictor  wasb://spark-operators-2018-09-19t07-04-00-058z@myspark1.blob.core.windows.net/bigdl-0.7.0-SNAPSHOT-jar-with-dependencies.jar --modelPath /home/sshuser/model/resnet-18.t7 --folder wasb://spark-operators-2018-09-19t07-04-00-058z@myspark1.blob.core.windows.net/read1 --modelType torch --isHdfs true --batchSizePerCore 20

What am i doing wrong?

**Comment by algoscale1** [comment]
Sorry, I found the similar issues [https://github.com/intel-analytics/BigDL/issues/2628](url).  Addind --conf "spark.serializer=org.apache.spark.serializer.JavaSerializer" with spark-submit command resolved it.

Thanks

**Comment by Bfzanchetta** [comment]
This conf solves the issue, however it doesn't quite explain why the issue happens in the first place.
If anyone could explain to us, we could benefit of some light shedding.
