### ISSUE TITLE
java.util.concurrent.ExecutionException: Boxed Error

### ISSUE THREAD

**Issue by land1725** [intel-analytics/BigDL#2689]
Hello,First of all ,I want to say thanks to all of BigDL contributors .The BigDL can run on spark so my company do not need to buy GPU machines.
But I have an issues  when I use BigDL.you can get the full error logs 
@yiheng @zhangxiaoli73 
my code like this:
    val ss = SparkSession.builder()
      .config(Engine.createSparkConf())
      .appName("LightGBM")
      .config("spark.sql.warehouse.dir", warehouseLocation)
      .config("spark.default.parallelism", 96)
      .config("spark.task.cpus", 1)
      .config("spark.sql.crossJoin.enabled", "true")
      .config("spark.serializer","org.apache.spark.serializer.JavaSerializer")
      //.master("local")
      .getOrCreate()

val featuresHead = finalInput.select("features").head
    val inputNumber = featuresHead(0).asInstanceOf[SparseVector].size
    //    println("inputNumber is " + inputNumber)

    Engine.init

    val weightInitMethod = Xavier
    val biasInitMethod = Xavier
    val hidden_1 = Linear(inputNumber, 512)
    hidden_1.setInitMethod(weightInitMethod, biasInitMethod)
    val hidden_2 = Linear(512, 1)
    hidden_2.setInitMethod(weightInitMethod, biasInitMethod)

    val model = Sequential()
      .add(hidden_1)
      .add(ReLU())
      .add(hidden_2)
      .add(Sigmoid())

    val criterion = ClassNLLCriterion()
    val estimator = new DLClassifier(model, criterion, Array(inputNumber))
      .setFeaturesCol("features")
      .setLabelCol("label")
      .setBatchSize(2048)
      .setOptimMethod(new Adam(0.002))
      .setMaxEpoch(10)
    val dlModel = estimator.fit(finalInput)
    dlModel.transform(finalInput).show(false)

the error log like this 

18/11/23 15:15:25 WARN scheduler.TaskSetManager: Lost task 1.0 in stage 122.0 (TID 3350, bigdata.node3, executor 1): java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: Boxed Error
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$4$$anonfun$8.apply(DistriOptimizer.scala:271)
	at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$4$$anonfun$8.apply(DistriOptimizer.scala:271)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$4.apply(DistriOptimizer.scala:271)
	at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$4.apply(DistriOptimizer.scala:209)
	at org.apache.spark.rdd.ZippedPartitionsRDD2.compute(ZippedPartitionsRDD.scala:89)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:109)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: Boxed Error
	at scala.concurrent.impl.Promise$.resolver(Promise.scala:55)
	at scala.concurrent.impl.Promise$.scala$concurrent$impl$Promise$$resolveTry(Promise.scala:47)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:244)
	at scala.concurrent.Promise$class.complete(Promise.scala:55)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:23)
	at com.intel.analytics.bigdl.utils.ThreadPool$$anon$1.execute(ThreadPool.scala:210)
	at scala.concurrent.impl.Future$.apply(Future.scala:31)
	at scala.concurrent.Future$.apply(Future.scala:494)
	at com.intel.analytics.bigdl.utils.ThreadPool.invoke(ThreadPool.scala:175)
	at com.intel.analytics.bigdl.nn.ClassNLLCriterion$mcF$sp.updateOutput$mcF$sp(ClassNLLCriterion.scala:130)
	at com.intel.analytics.bigdl.nn.ClassNLLCriterion$mcF$sp.updateOutput(ClassNLLCriterion.scala:89)
	at com.intel.analytics.bigdl.nn.ClassNLLCriterion$mcF$sp.updateOutput(ClassNLLCriterion.scala:69)
	at com.intel.analytics.bigdl.nn.abstractnn.AbstractCriterion.forward(AbstractCriterion.scala:73)
	at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$4$$anonfun$6$$anonfun$apply$2.apply$mcI$sp(DistriOptimizer.scala:260)
	at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$4$$anonfun$6$$anonfun$apply$2.apply(DistriOptimizer.scala:252)
	at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$4$$anonfun$6$$anonfun$apply$2.apply(DistriOptimizer.scala:252)
	at com.intel.analytics.bigdl.utils.ThreadPool$$anonfun$1$$anon$4.call(ThreadPool.scala:119)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
Caused by: java.lang.AssertionError: assertion failed: curTarget 0 is out of range 1 to 1
	at scala.Predef$.assert(Predef.scala:170)
	at com.intel.analytics.bigdl.nn.ClassNLLCriterion$mcF$sp$$anonfun$updateOutput$mcF$sp$5.apply(ClassNLLCriterion.scala:132)
	at com.intel.analytics.bigdl.nn.ClassNLLCriterion$mcF$sp$$anonfun$updateOutput$mcF$sp$5.apply(ClassNLLCriterion.scala:130)
	at com.intel.analytics.bigdl.utils.ThreadPool$$anonfun$invoke$2.apply(ThreadPool.scala:169)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	... 16 more

**Comment by zhangxiaoli73** [comment]
hi, some msg from your error:
Caused by: java.lang.AssertionError: assertion failed: curTarget 0 is out of range 1 to 1
So please check your labels, it should start from 1 not 0.

**Comment by land1725** [comment]
@zhangxiaoli73 hello thanks a lot ,I just solved the problem just as you said,Thanks again

**Comment by land1725** [comment]
when I changed the code like this ,the problem has solved
    val criterion = BCECriterion()
