### ISSUE TITLE
java.lang.RuntimeException: Didn't find weight block 

### ISSUE THREAD

**Issue by land1725** [intel-analytics/BigDL#2693]
Hello,I met a problem 
:Lost task 2.0 in stage 128542.0 (TID 54319, bigdata.node8, executor 3): java.util.concurrent.ExecutionException: java.lang.RuntimeException: Didn't find weight block test_0weightBytes3 in the block manager. Did you initialize this AllReduceParameter on every executor?
this problem occur when my train data is big, when the train data is small,I can successfully finish my demo.
my submit command is : 
nohup spark2-submit --class  HuoyingBigDL --master yarn --executor-memory 5G --num-executors 4 --driver-memory 8g --executor-cores 2  --conf spark.yarn.executor.memoryOverhead=1024 --conf spark.sql.shuffle.partitions=20 /data/recommend.jar &
val featuresHead = trainInput.select("features").head
    val inputNumber = featuresHead(0).asInstanceOf[SparseVector].size
    //    println("inputNumber is " + inputNumber)

    Engine.init

    val weightInitMethod = Xavier
    val biasInitMethod = Xavier
    val hidden_1 = Linear(inputNumber, 512)
    hidden_1.setInitMethod(weightInitMethod, biasInitMethod)
    val hidden_2 = Linear(512, 1)
    hidden_2.setInitMethod(weightInitMethod, biasInitMethod)

    val model = Sequential()
      .add(hidden_1)
      .add(ReLU())
      .add(hidden_2)
      .add(Sigmoid())

    val criterion = BCECriterion()
    val estimator = new DLClassifier(model, criterion, Array(inputNumber))
      .setFeaturesCol("features")
      .setLabelCol("label")
      .setBatchSize(2048)
      .setOptimMethod(new Adam())
      .setValidation(Trigger.everyEpoch, testInput, Array(new AUC()), 2048)
    val dlModel = estimator.fit(trainInput)
    val testRank = dlModel.transform(testInput)
    testRank.show(100, false)

**Comment by land1725** [comment]
[nohup.out.zip](https://github.com/intel-analytics/BigDL/files/2619719/nohup.out.zip)
you can get the whole file below .
18/11/27 19:33:07 INFO scheduler.DAGScheduler: ResultStage 128542 (reduce at DistriOptimizer.scala:329) failed in 16.366 s due to Job aborted due to stage failure: Task 2 in stage 128542.0 failed 4 times, most recent failure: Lost task 2.3 in stage 128542.0 (TID 54324, bigdata.node8, executor 3): java.util.concurrent.ExecutionException: java.lang.RuntimeException: Didn't find weight block test_0weightBytes3 in the block manager. Did you initialize this AllReduceParameter on every executor?
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.intel.analytics.bigdl.parameters.FutureResult$$anonfun$waitResult$1.apply(AllReduceParameter.scala:324)
	at com.intel.analytics.bigdl.parameters.FutureResult$$anonfun$waitResult$1.apply(AllReduceParameter.scala:324)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at com.intel.analytics.bigdl.parameters.FutureResult.waitResult(AllReduceParameter.scala:324)
	at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$4$$anonfun$apply$5.apply(DistriOptimizer.scala:238)
	at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$4$$anonfun$apply$5.apply(DistriOptimizer.scala:238)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$4.apply(DistriOptimizer.scala:238)
	at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$4.apply(DistriOptimizer.scala:209)
	at org.apache.spark.rdd.ZippedPartitionsRDD2.compute(ZippedPartitionsRDD.scala:89)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:109)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Didn't find weight block test_0weightBytes3 in the block manager. Did you initialize this AllReduceParameter on every executor?
	at com.intel.analytics.bigdl.parameters.AllReduceParameter$$anonfun$1$$anon$3$$anonfun$2.apply(AllReduceParameter.scala:201)
	at com.intel.analytics.bigdl.parameters.AllReduceParameter$$anonfun$1$$anon$3$$anonfun$2.apply(AllReduceParameter.scala:201)
	at scala.Option.getOrElse(Option.scala:121)
	at com.intel.analytics.bigdl.parameters.AllReduceParameter$$anonfun$1$$anon$3.call(AllReduceParameter.scala:200)
	at com.intel.analytics.bigdl.parameters.AllReduceParameter$$anonfun$1$$anon$3.call(AllReduceParameter.scala:196)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more

**Comment by zhangxiaoli73** [comment]
@land1725 Please check your train dataset partition number, it should be same with your  executor number.
