### ISSUE TITLE
Is the old StructuredStreaming Predictor going to update?

### ISSUE THREAD

**Issue by YongyiZhou** [intel-analytics/BigDL#2739]
Hello dear developers,
I'm a green hand in online training, and wish to find a demo .

So I search all issues and find that example "udfpredictor" used to have a StructuredStreamPredictor at 

https://github.com/intel-analytics/BigDL/tree/721ca0312f4252708d91eeb46eadc87a58df649c/spark/dl/src/main/scala/com/intel/analytics/bigdl/example/udfpredictor

I try to compile it and run, but errors shown. 
I try to fix it but problems come after problems. 
Is it possible to update this demo?

Sincerely

**Comment by YongyiZhou** [comment]
2019-02-20 19:08:48 WARN  NativeCodeLoader:62 - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2019-02-20 19:08:59 INFO  Engine$:112 - Auto detect executor number and executor cores number
2019-02-20 19:08:59 INFO  Engine$:114 - Executor number is 11 and executor cores number is 20
2019-02-20 19:09:00 INFO  ThreadPool$:86 - Set mkl threads to 1 on thread 1
2019-02-20 19:09:00 INFO  Engine$:387 - Find existing spark context. Checking the spark conf...
2019-02-20 19:09:04 INFO  TextClassifier:116 - Found 18828 texts.
2019-02-20 19:09:04 INFO  TextClassifier:117 - Found 20 classes
2019-02-20 19:09:29 INFO  TextClassifier:56 - Indexing word vectors.
2019-02-20 19:09:56 INFO  TextClassifier:67 - Found 18166 word vectors.
2019-02-20 19:10:09 INFO  DistriOptimizer$:731 - caching training rdd ...
2019-02-20 19:10:13 ERROR TaskSetManager:70 - Task 0 in stage 6.0 failed 4 times; aborting job
Exception in thread "main" org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 6.0 failed 4 times, most recent failure: Lost task 0.3 in stage 6.0 (TID 390, 10.42.43.16, executor 2): java.lang.IllegalArgumentException: requirement failed: shape total size doesn't match data length
	at scala.Predef$.require(Predef.scala:224)
	at com.intel.analytics.bigdl.tensor.Tensor$.apply$mFc$sp(Tensor.scala:981)
	at com.intel.analytics.bigdl.example.utils.TextClassifier$$anonfun$18.apply(TextClassifier.scala:244)
	at com.intel.analytics.bigdl.example.utils.TextClassifier$$anonfun$18.apply(TextClassifier.scala:242)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:149)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:109)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1599)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1587)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1586)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1586)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:831)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:831)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:831)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1820)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1769)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1758)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:642)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2027)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2048)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2067)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2092)
	at org.apache.spark.rdd.RDD.count(RDD.scala:1162)
	at com.intel.analytics.bigdl.dataset.DistributedDataSet$$anon$5.cache(DataSet.scala:191)
	at com.intel.analytics.bigdl.optim.AbstractOptimizer.prepareInput(AbstractOptimizer.scala:253)
	at com.intel.analytics.bigdl.optim.DistriOptimizer.prepareInput(DistriOptimizer.scala:732)
	at com.intel.analytics.bigdl.optim.DistriOptimizer.optimize(DistriOptimizer.scala:784)
	at com.intel.analytics.bigdl.example.utils.TextClassifier.trainFromData(TextClassifier.scala:268)
	at com.intel.analytics.bigdl.example.udfpredictor.Utils$.getModel(Utils.scala:69)
	at com.intel.analytics.bigdl.example.udfpredictor.StructuredStreamPredictor$$anonfun$main$1.apply(StructuredStreamPredictor.scala:51)
	at com.intel.analytics.bigdl.example.udfpredictor.StructuredStreamPredictor$$anonfun$main$1.apply(StructuredStreamPredictor.scala:34)
	at scala.Option.foreach(Option.scala:257)
	at com.intel.analytics.bigdl.example.udfpredictor.StructuredStreamPredictor$.main(StructuredStreamPredictor.scala:34)
	at com.intel.analytics.bigdl.example.udfpredictor.StructuredStreamPredictor.main(StructuredStreamPredictor.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:879)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:197)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:227)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:136)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.IllegalArgumentException: requirement failed: shape total size doesn't match data length
	at scala.Predef$.require(Predef.scala:224)
	at com.intel.analytics.bigdl.tensor.Tensor$.apply$mFc$sp(Tensor.scala:981)
	at com.intel.analytics.bigdl.example.utils.TextClassifier$$anonfun$18.apply(TextClassifier.scala:244)
	at com.intel.analytics.bigdl.example.utils.TextClassifier$$anonfun$18.apply(TextClassifier.scala:242)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:149)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:109)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
