### ISSUE TITLE
Remote RPC client disassociated when optimizer.optimize(), but no problem when forward and evaluate

### ISSUE THREAD

**Issue by YongyiZhou** [intel-analytics/BigDL#2790]
Remote RPC client disassociated when optimizer.optimize(),
 but no problem when model.forward and model.evaluate.

Code to repro this issue:

`
import com.intel.analytics.bigdl.utils.Engine
import com.intel.analytics.bigdl.tensor.Tensor
import com.intel.analytics.bigdl.nn._
import com.intel.analytics.bigdl.dataset.Sample
import com.intel.analytics.bigdl.optim._
import com.intel.analytics.bigdl.dataset.{FixedLength, PaddingParam}
import com.intel.analytics.bigdl.tensor.TensorNumericMath.TensorNumeric.NumericFloat
import org.apache.spark.rdd.RDD
import org.apache.spark.sql.{DataFrame, Dataset, SparkSession}
import org.apache.spark.sql.functions._

    Engine.init
    val vocabNum = 5000
    val embeddingDim = 50
    val maxSequenceLength = 1000
    val categoryNum = 16
    val executorCores = 8
    val numExecutors = 2
    val batchSize = executorCores*numExecutors

    val preprocessor = Sequential().add(LookupTable(vocabNum, embeddingDim).setInitMethod(Xavier).freeze())
    val model: Sequential[Float] = preprocessor  // input: Tensor of size(batchSize, SeqLength, EmbeddingDim)
    //model.add(Masking(0))// mask with value 0 for time-status
    model.add(Recurrent().add(GRU(embeddingDim, 16)))
    model.add(Select(2, maxSequenceLength)) // take the last time-step status which is at dim 2, these two params are count from 1
    model.add(Linear(16, categoryNum))
    model.add(SoftMax())

    println(model.toString())
    print(s"\n\n================== Test Forward======================\n\n")
    val testSeq = Seq.fill(maxSequenceLength)(3f).toArray
    testSeq(0) = 2f

    /*
     You should run next one code twice
    */

    val testTensor = Tensor(testSeq, Array(1,maxSequenceLength))
    println(model.forward(testTensor).toTensor)

    print(s"\n\n===================== Test Evaluate==================\n\n")
    val testLabel = new Array[Float](1)
    testLabel(0) = categoryNum
    val featureTensor = Tensor(testSeq, Array(maxSequenceLength))
    val labelTensor = Tensor(testLabel, Array(1))
    val testSample = Sample(featureTensor, labelTensor)
    val testSet = spark.sparkContext.parallelize(Seq(testSample))
    println(model.evaluate(testSet, Array(new Top1Accuracy[Float]))(0))

    print(s"\n\n======================== Test 4096 Sample Evaluate====================\n\n")
    val testSetMulti = spark.sparkContext.parallelize(Seq.fill(4096)(testSample)).coalesce(numExecutors)
    println(model.evaluate(testSetMulti, Array(new Top1Accuracy[Float]))(0))

    print(s"\n\n============== Test training==============\n\n")
    val optimizer = Optimizer(model = model, sampleRDD = testSetMulti, criterion = ClassNLLCriterion[Float](), batchSize = batchSize)

    optimizer.setOptimMethod(new ParallelAdam[Float]()).setEndWhen(Trigger.maxEpoch(1))
    optimizer.optimize()
`

Notice that if you are running a scala-shell,  the first time you define the Tensor for forward, you might met:

> error: missing or invalid dependency detected while loading class file 'DenseMatrix.class'.
Could not access type HandHold in value breeze.linalg.support.CanMapValues,
because it (or its dependencies) are missing. Check your build definition for
missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic classpath.)
A full rebuild may help if 'DenseMatrix.class' was compiled against an incompatible version of breeze.linalg.support.CanMapValues.
error: missing or invalid dependency detected while loading class file 'DenseVector.class'.
Could not access type HandHold in value breeze.linalg.support.CanMapValues,
because it (or its dependencies) are missing. Check your build definition for
missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic classpath.)
A full rebuild may help if 'DenseVector.class' was compiled against an incompatible version of breeze.linalg.support.CanMapValues.
error: missing or invalid dependency detected while loading class file 'Vector.class'.
Could not access type HandHold in value breeze.linalg.support.CanMapValues,
because it (or its dependencies) are missing. Check your build definition for
missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic classpath.)
A full rebuild may help if 'Vector.class' was compiled against an incompatible version of breeze.linalg.support.CanMapValues.

But you rerun it again, the result will show correctly. You won't met this first problem when you are in spark-submit.

Then forward and evaluate will work well, until you run optimizer.optimize. 
You might met these if you are in scala shell:

> scala>     optimizer.optimize()
[Stage 11:>                                                         (0 + 2) / 2]2019-03-30 23:31:28 WARN  TaskSetManager:66 - Lost task 0.0 in stage 11.0 (TID 28, 10.42.43.14, executor 1): java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: 0
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$4$$anonfun$8.apply(DistriOptimizer.scala:271)
	at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$4$$anonfun$8.apply(DistriOptimizer.scala:271)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$4.apply(DistriOptimizer.scala:271)
	at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$4.apply(DistriOptimizer.scala:209)
	at org.apache.spark.rdd.ZippedPartitionsRDD2.compute(ZippedPartitionsRDD.scala:89)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:109)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at com.intel.analytics.bigdl.nn.Dropout.updateGradInput(Dropout.scala:165)
	at com.intel.analytics.bigdl.nn.Dropout.updateGradInput(Dropout.scala:44)
	at com.intel.analytics.bigdl.nn.abstractnn.AbstractModule.backward(AbstractModule.scala:283)
	at com.intel.analytics.bigdl.nn.StaticGraph.backwardExecution(StaticGraph.scala:137)
	at com.intel.analytics.bigdl.nn.StaticGraph.backward(StaticGraph.scala:69)
	at com.intel.analytics.bigdl.nn.Cell.backward(Cell.scala:185)
	at com.intel.analytics.bigdl.nn.Recurrent.backward(Recurrent.scala:496)
	at com.intel.analytics.bigdl.nn.Recurrent.backward(Recurrent.scala:47)
	at com.intel.analytics.bigdl.nn.Sequential.backward(Sequential.scala:83)
	at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$4$$anonfun$6$$anonfun$apply$2.apply$mcI$sp(DistriOptimizer.scala:262)
	at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$4$$anonfun$6$$anonfun$apply$2.apply(DistriOptimizer.scala:252)
	at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$4$$anonfun$6$$anonfun$apply$2.apply(DistriOptimizer.scala:252)
	at com.intel.analytics.bigdl.utils.ThreadPool$$anonfun$1$$anon$4.call(ThreadPool.scala:119)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
2019-03-30 23:31:51 WARN  Signaling:66 - Cancelling all active jobs, this can take a while. Press Ctrl+C again to exit now.
2019-03-30 23:31:51 ERROR DistriOptimizer$:831 - Error: org.apache.spark.SparkException: Job 6 cancelled as part of cancellation of all jobs
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1599)
	at org.apache.spark.scheduler.DAGScheduler.handleJobCancellation(DAGScheduler.scala:1539)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$doCancelAllJobs$1.apply$mcVI$sp(DAGScheduler.scala:735)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$doCancelAllJobs$1.apply(DAGScheduler.scala:735)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$doCancelAllJobs$1.apply(DAGScheduler.scala:735)
	at scala.collection.mutable.HashSet.foreach(HashSet.scala:78)
	at org.apache.spark.scheduler.DAGScheduler.doCancelAllJobs(DAGScheduler.scala:735)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1792)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1769)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1758)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:642)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2027)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2124)
	at org.apache.spark.rdd.RDD$$anonfun$reduce$1.apply(RDD.scala:1029)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:363)
	at org.apache.spark.rdd.RDD.reduce(RDD.scala:1011)
	at com.intel.analytics.bigdl.optim.DistriOptimizer$.optimize(DistriOptimizer.scala:329)
	at com.intel.analytics.bigdl.optim.DistriOptimizer.optimize(DistriOptimizer.scala:806)
	at $line60.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:42)
	at $line60.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:47)
	at $line60.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:49)
	at $line60.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:51)
	at $line60.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:53)
	at $line60.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:55)
	at $line60.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:57)
	at $line60.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:59)
	at $line60.$read$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:61)
	at $line60.$read$$iw$$iw$$iw$$iw$$iw.<init>(<console>:63)
	at $line60.$read$$iw$$iw$$iw$$iw.<init>(<console>:65)
	at $line60.$read$$iw$$iw$$iw.<init>(<console>:67)
	at $line60.$read$$iw$$iw.<init>(<console>:69)
	at $line60.$read$$iw.<init>(<console>:71)
	at $line60.$read.<init>(<console>:73)
	at $line60.$read$.<init>(<console>:77)
	at $line60.$read$.<clinit>(<console>)
	at $line60.$eval$.$print$lzycompute(<console>:7)
	at $line60.$eval$.$print(<console>:6)
	at $line60.$eval.$print(<console>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:786)
	at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1047)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:638)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:637)
	at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
	at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:19)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest.loadAndRunReq(IMain.scala:637)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:569)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:565)
	at scala.tools.nsc.interpreter.ILoop.interpretStartingWith(ILoop.scala:807)
	at scala.tools.nsc.interpreter.ILoop.command(ILoop.scala:681)
	at scala.tools.nsc.interpreter.ILoop.processLine(ILoop.scala:395)
	at scala.tools.nsc.interpreter.ILoop.loop(ILoop.scala:415)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply$mcZ$sp(ILoop.scala:923)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:909)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:909)
	at scala.reflect.internal.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:97)
	at scala.tools.nsc.interpreter.ILoop.process(ILoop.scala:909)
	at org.apache.spark.repl.Main$.doMain(Main.scala:76)
	at org.apache.spark.repl.Main$.main(Main.scala:56)
	at org.apache.spark.repl.Main.main(Main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:879)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:197)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:227)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:136)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
org.apache.spark.SparkException: Job 6 cancelled as part of cancellation of all jobs
  at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1599)
  at org.apache.spark.scheduler.DAGScheduler.handleJobCancellation(DAGScheduler.scala:1539)
  at org.apache.spark.scheduler.DAGScheduler$$anonfun$doCancelAllJobs$1.apply$mcVI$sp(DAGScheduler.scala:735)
  at org.apache.spark.scheduler.DAGScheduler$$anonfun$doCancelAllJobs$1.apply(DAGScheduler.scala:735)
  at org.apache.spark.scheduler.DAGScheduler$$anonfun$doCancelAllJobs$1.apply(DAGScheduler.scala:735)
  at scala.collection.mutable.HashSet.foreach(HashSet.scala:78)
  at org.apache.spark.scheduler.DAGScheduler.doCancelAllJobs(DAGScheduler.scala:735)
  at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1792)
  at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1769)
  at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1758)
  at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
  at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:642)
  at org.apache.spark.SparkContext.runJob(SparkContext.scala:2027)
  at org.apache.spark.SparkContext.runJob(SparkContext.scala:2124)
  at org.apache.spark.rdd.RDD$$anonfun$reduce$1.apply(RDD.scala:1029)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
  at org.apache.spark.rdd.RDD.withScope(RDD.scala:363)
  at org.apache.spark.rdd.RDD.reduce(RDD.scala:1011)
  at com.intel.analytics.bigdl.optim.DistriOptimizer$.optimize(DistriOptimizer.scala:329)
  at com.intel.analytics.bigdl.optim.DistriOptimizer.optimize(DistriOptimizer.scala:806)
  ... 55 elided

And you might met RPC lost if you are in spark-submit:

> ============== Test training==============
2019-03-30 23:38:14 INFO  DistriOptimizer$:731 - caching training rdd ...
2019-03-30 23:38:16 INFO  DistriOptimizer$:605 - Cache thread models...
2019-03-30 23:38:22 INFO  DistriOptimizer$:607 - Cache thread models... done
2019-03-30 23:38:22 INFO  DistriOptimizer$:151 - Count dataset
2019-03-30 23:38:22 INFO  DistriOptimizer$:155 - Count dataset complete. Time elapsed: 0.162750473s
2019-03-30 23:38:22 INFO  DistriOptimizer$:163 - config  {
	computeThresholdbatchSize: 100
	maxDropPercentage: 0.0
	warmupIterationNum: 200
	isLayerwiseScaled: true
	dropPercentage: 0.0
 }
2019-03-30 23:38:22 INFO  DistriOptimizer$:167 - Shuffle data
2019-03-30 23:38:22 INFO  DistriOptimizer$:170 - Shuffle data complete. Takes 0.055475732s
2019-03-30 23:39:48 ERROR TaskSchedulerImpl:70 - Lost executor 1 on 10.42.43.14: Remote RPC client disassociated. Likely due to containers exceeding thresholds, or network issues. Check driver logs for WARN messages.
2019-03-30 23:39:55 ERROR TaskSchedulerImpl:70 - Lost executor 6 on 10.42.43.22: Remote RPC client disassociated. Likely due to containers exceeding thresholds, or network issues. Check driver logs for WARN messages.
2019-03-30 23:39:55 ERROR TaskSchedulerImpl:70 - Lost executor 10 on 10.42.43.17: Remote RPC client disassociated. Likely due to containers exceeding thresholds, or network issues. Check driver logs for WARN messages.

My spark-submit is below:

> /home/youjun/hadoop/spark-2.3.0-bin-hadoop2.7/bin/spark-submit \
 --class GeneClassifier \
 --master spark://master:7077 \
 --executor-memory 28G \
 --executor-cores 20 \
 --num-executors 13 \
 --total-executor-cores 260 \
 --driver-memory 20G \
 --conf 'spark.executor.extraJavaOptions=-Dbigdl.check.singleton=true' \
 --conf 'spark.driver.extraJavaOptions=-Dbigdl.check.singleton=true' \
 --conf 'spark.executor.extraJavaOptions=-Dbigdl.engineType=mkldnn' \
 --conf 'spark.driver.extraJavaOptions=-Dbigdl.engineType=mkldnn' \
 --conf spark.storage.memoryFraction=0.5 \
 --conf spark.executor.heartbeatInterval=1000000 \
 --conf spark.network.timeout=10000000 \
 --conf spark.executor.memoryOverhead=28G \
 --conf spark.driver.memoryOverhead=20G \
 --conf spark.rpc.message.maxSize=2047 \
 --conf spark.default.parallelism=1000 \
 --conf spark.serializer=org.apache.spark.serializer.JavaSerializer \
 --conf mapreduce.reduce.memory.mb=20480 \
/home/youjun/yongyi/project-gene/GeneFix.jar

I went to the Spark History Server, and find them are shut down during the reduceByKey. I have no idea what to do, help plz QAQ.

**Comment by wzhongyuan** [comment]
we are looking into it

**Comment by zhangxiaoli73** [comment]
@YongyiZhou From my tests, you should delete line "println(model.forward(testTensor).toTensor)" 
As model forward will init some internal states, so if you call forward before training, those states may not suitable for backward.
Besides, you should not use mkldnn engine as we have not support it for rnn model.

**Comment by YongyiZhou** [comment]
@zhangxiaoli73 Thanks, it works!

And I guess I could not use a duplicate model to do the test as well, likes:
`
val testmodel = model
`
It might because of that the duplicate model's inner index (e.g. layers' names) is same to the origin model?

**Comment by zhangxiaoli73** [comment]
@YongyiZhou If you want a duplicate model, please use
val testmodel = model.cloneModule()

**Comment by YongyiZhou** [comment]
@zhangxiaoli73  thanks, I would close this issue now.
