### ISSUE TITLE
cannot load mobilenet and mobilenet_v2

### ISSUE THREAD

**Issue by qiyuangong** [intel-analytics/BigDL#2982]
Ubuntu 16.04 or CentOS 7.6

Loading mobilenet_v1 and mobilnet_v2 encounter a native error.

Model download link https://analytics-zoo.github.io/master/#ProgrammingGuide/image-classification/

1. [moblenet](https://s3-ap-southeast-1.amazonaws.com/analytics-zoo-models/imageclassification/imagenet/analytics-zoo_mobilenet_imagenet_0.1.0.model)
2. [mobilenet_v2](https://analytics-zoo-models.s3-ap-southeast-1.amazonaws.com/analytics-zoo_mobilenet-v2_imagenet_0.1.0.model)

```
2019-12-11 14:44:32 WARN  NativeCodeLoader:62 - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2019-12-11 14:44:35 WARN  DistriOptimizer$:183 - Input formats NCHW by default, Please set explicitly if needed
2019-12-11 14:44:35 WARN  DistriOptimizer$:188 - Output formats NC by default, Please set explicitly if needed
Obtained 3 stack frames.
[FRAME 0] /tmp/mkldnn.native.596870892144559973/libjdnn.so(throw_exception_if_failed+0xb7) [0x14791938cdd9]
[FRAME 1] /tmp/mkldnn.native.596870892144559973/libjdnn.so(Java_com_intel_analytics_bigdl_mkl_MklDnn_MemoryDescInit+0x93) [0x14791938aa72]
[FRAME 2] [0x147a218b54ed]

[../src/main/c/memory.c:29] error: Java_com_intel_analytics_bigdl_mkl_MklDnn_MemoryDescInit returns 3
Exception in thread "main" Layer info: IRGraph[7aeb6347]
java.lang.IllegalArgumentException: [mkldnn] ivalid arguments
        at com.intel.analytics.bigdl.mkl.MklDnn.MemoryDescInit(Native Method)
        at com.intel.analytics.bigdl.nn.mkldnn.MemoryData$class.getMemoryDescription(MemoryData.scala:53)
        at com.intel.analytics.bigdl.nn.mkldnn.HeapData.getMemoryDescription(MemoryData.scala:118)
        at com.intel.analytics.bigdl.nn.mkldnn.MemoryData$class.getPrimitiveDescription(MemoryData.scala:62)
        at com.intel.analytics.bigdl.nn.mkldnn.HeapData.getPrimitiveDescription(MemoryData.scala:118)
        at com.intel.analytics.bigdl.nn.mkldnn.ReorderMemory.initFwdPrimitives(ReorderMemory.scala:134)
        at com.intel.analytics.bigdl.nn.mkldnn.ReorderManager.register(ReorderManager.scala:43)
        at com.intel.analytics.bigdl.nn.mkldnn.DnnGraph$$anonfun$initFwdPrimitives$1$$anonfun$apply$mcVI$sp$1.apply(DnnGraph.scala:427)
        at com.intel.analytics.bigdl.nn.mkldnn.DnnGraph$$anonfun$initFwdPrimitives$1$$anonfun$apply$mcVI$sp$1.apply(DnnGraph.scala:424)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
        at com.intel.analytics.bigdl.nn.mkldnn.DnnGraph$$anonfun$initFwdPrimitives$1.apply$mcVI$sp(DnnGraph.scala:424)
        at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
        at com.intel.analytics.bigdl.nn.mkldnn.DnnGraph.initFwdPrimitives(DnnGraph.scala:418)
        at com.intel.analytics.bigdl.utils.intermediate.IRGraph.com$intel$analytics$bigdl$utils$intermediate$IRGraph$$initPrimitives(IRGraph.scala:164)
        at com.intel.analytics.bigdl.utils.intermediate.IRGraph$$anonfun$updateOutput$1$$anonfun$apply$3.apply(IRGraph.scala:67)
        at com.intel.analytics.bigdl.utils.intermediate.IRGraph$$anonfun$updateOutput$1$$anonfun$apply$3.apply(IRGraph.scala:66)
        at com.intel.analytics.bigdl.utils.ThreadPool$$anonfun$1$$anon$5.call(ThreadPool.scala:156)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

        at com.intel.analytics.bigdl.nn.abstractnn.AbstractModule.forward(AbstractModule.scala:265)
        at com.intel.analytics.bigdl.example.inference.Perf$$anonfun$main$1.apply(Perf.scala:24)
        at com.intel.analytics.bigdl.example.inference.Perf$$anonfun$main$1.apply(Perf.scala:24)
        at com.intel.analytics.bigdl.example.inference.Perf$.time(Perf.scala:34)
        at com.intel.analytics.bigdl.example.inference.Perf$.main(Perf.scala:24)
        at com.intel.analytics.bigdl.example.inference.Perf.main(Perf.scala)

```

**Comment by i8run** [comment]
Because the last layer is conv and output tensor will be 4-D. BigDL mkl-dnn backend set the output tensor dim to 2-D by default. You can set output format by manual, `model.toGraph().asInstanceOf[StaticGraph[Float]].setOutputFormats(Array(Format.nchw))`.

**Comment by zhangxiaoli73** [comment]
@qiyuangong you can find some warning from your msg.
2019-12-11 14:44:35 WARN  DistriOptimizer$:183 - Input formats NCHW by default, Please set explicitly if needed
2019-12-11 14:44:35 WARN  DistriOptimizer$:188 - Output formats NC by default, Please set explicitly if needed

**Comment by qiyuangong** [comment]
Here is a dirty solution for this issue. :)
```
 val model = try {
      val tmpModel = preprocess(Module.loadModule[Float](params.model), params.outputFormat).quantize()
      tmpModel.forward(input)
      // Check quantize error
      tmpModel
    } catch {
      case _: Exception => {
        logger.info(s"Quantize error. Switch to FP32")
        preprocess(Module.loadModule[Float](params.model), params.outputFormat)
      }
    }
```

**Comment by qiyuangong** [comment]
Problem solved. Issue closed. :)
