### ISSUE TITLE
AssertionError: Expecting one jar: 2

### ISSUE THREAD

**Issue by m-developer96** [intel-analytics/BigDL#3049]
Hi!
I used both bigdl and keras style api but when I executed model (for example call optimize()) got the below error:

```
Caused by: org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/home/mahdi/workTable/spark/python/lib/pyspark.zip/pyspark/worker.py", line 364, in main
    func, profiler, deserializer, serializer = read_command(pickleSer, infile)
  File "/home/mahdi/workTable/spark/python/lib/pyspark.zip/pyspark/worker.py", line 69, in read_command
    command = serializer._read_with_length(file)
  File "/home/mahdi/workTable/spark/python/lib/pyspark.zip/pyspark/serializers.py", line 173, in _read_with_length
    return self.loads(obj)
  File "/home/mahdi/workTable/spark/python/lib/pyspark.zip/pyspark/serializers.py", line 587, in loads
    return pickle.loads(obj, encoding=encoding)
  File "/home/mahdi/.local/lib/python3.6/site-packages/bigdl/__init__.py", line 18, in <module>
    prepare_env()
  File "/home/mahdi/.local/lib/python3.6/site-packages/bigdl/util/engine.py", line 156, in prepare_env
    __prepare_bigdl_env()
  File "/home/mahdi/.local/lib/python3.6/site-packages/bigdl/util/engine.py", line 73, in __prepare_bigdl_env
    bigdl_classpath = get_bigdl_classpath()
  File "/home/mahdi/.local/lib/python3.6/site-packages/bigdl/util/engine.py", line 108, in get_bigdl_classpath
    assert len(jar_paths) == 1, "Expecting one jar: %s" % len(jar_paths)
AssertionError: Expecting one jar: 2
```

My spark initialization:

```
SUBMIT_ARGS = "--jars /home/mahdi/workTable/BigDL/lib/bigdl-SPARK_2.4-0.10.0-jar-with-dependencies.jar --properties-file /home/mahdi/workTable/BigDL/conf/spark-bigdl.conf pyspark-shell"
os.environ["PYSPARK_SUBMIT_ARGS"] = SUBMIT_ARGS
os.environ["PYSPARK_PYTHON"]="/usr/bin/python3"
os.environ["PYSPARK_DRIVER_PYTHON"]="/usr/bin/python3"
findspark.init()
conf=SparkConf()
conf.set("spark.driver.memory", "19g")
conf.set("spark.cores.max", "16")
conf.set("spark.executor.memory", "9700m")
conf.set("spark.executor.cores", "8")
conf.set("spark.executor.instances", "8")
conf.set("spark.rpc.message.maxSize","1024")
conf.set("spark.driver.extraJavaOptions","-Djava.io.tmpdir=/home/mahdi/workTable/temp/")
conf.set("spark.executor.extraJavaOptions","-Djava.io.tmpdir=/home/mahdi/workTable/temp/")
spark = SparkSession.builder.master("spark://172.18.16.74:7077").appName("Sentiment Analysis").config(conf=conf).getOrCreate()
```

How can I fix it?

Thanks:)

**Comment by m-developer96** [comment]
I install and use `analytics-zoo` too. Does it have a conflict with analytics-zoo?

**Comment by hkvision** [comment]
Could you check `/home/mahdi/.local/lib/python3.6/site-packages/bigdl/share/lib`, are there two jars under this folder?

**Comment by m-developer96** [comment]
@hkvision 
yes, I checked, there were 2 jars.
Thank you so much :)
