### ISSUE TITLE
EngineInit() failure: Exception in thread "main" java.lang.UnsatisfiedLinkError:   /tmp/dlNativeLoader8370768401448024359libiomp5.so:    Error relocating /tmp/dlNativeLoader8370768401448024359libiomp5.so:    __strncpy_chk: symbol not found     

### ISSUE THREAD

**Issue by shadyonfire** [intel-analytics/BigDL#3053]
I am trying to run DL job on Spark on kubernetes in cluster mode, and getting error java.lang.UnsatisfiedLinkError:__strncpy_chk: symbol not found.

This is the complete error stack.

Exception in thread "main" java.lang.UnsatisfiedLinkError:
  /tmp/dlNativeLoader8370768401448024359libiomp5.so: 
  Error relocating /tmp/dlNativeLoader8370768401448024359libiomp5.so: 
  __strncpy_chk: symbol not found
    

at java.lang.ClassLoader$NativeLibrary.load(Native Method)
    at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
    at java.lang.Runtime.load0(Runtime.java:809)
    at java.lang.System.load(System.java:1086)
    at com.intel.analytics.bigdl.mkl.MKL.<clinit>(MKL.java:56)
    at com.intel.analytics.bigdl.utils.Engine$.initThreadPool(Engine.scala:400)
    at com.intel.analytics.bigdl.utils.Engine$.setCoreNumber(Engine.scala:313)
    at com.intel.analytics.bigdl.utils.Engine$.setNodeAndCore(Engine.scala:470)
    at com.intel.analytics.bigdl.utils.Engine$.init(Engine.scala:124)
    at com.intel.analytics.bigdl.models.lenet.Train$$anonfun$main$1.apply(Train.scala:41)
    at com.intel.analytics.bigdl.models.lenet.Train$$anonfun$main$1.apply(Train.scala:36)

**Comment by qiyuangong** [comment]
Hi @shadyonfire 

This error is caused by incompatibilities of glibc. In most cases, this error happened when you're trying to run bigdl on lower version glibc (maybe due to OS version) or musl (Alpine LInux).  

Pls use Ubuntu 16.04 or higher images. :)

**Comment by shadyonfire** [comment]
Hi @qiyuangong , thanks for your attention.
I am currently using the OS version as follows:
```
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
Is this incompatible? If yes, this is my cluster setup. It works fine for all other types of workloads other than BigDL. Is there any solution?

**Comment by qiyuangong** [comment]
@shadyonfire 
Did you solve this issue?

**Comment by shadyonfire** [comment]
Yes @qiyuangong , Thanks for the help.
 My docker container image was alpine linux, I did not know before.
I used ubuntu 18.04 image. now it works fine.
Thanks again.

**Comment by qiyuangong** [comment]
You are welcome! :)
