### ISSUE TITLE
Enabling eventLog in spark throws exception of FileSystemClosed

### ISSUE THREAD

**Issue by shadyonfire** [intel-analytics/BigDL#3055]
I am using the release **0.11.0 precompiled jar** file. because i was unable to build the jar from source code.
I have saw this error in issue #1753 and resolved. If it was after 0.11.0 release. Can someone provide me the latest jar file for spark 2.3.1.
EventLog is getting stored successfully but file name has a suffix _.inprogress_ .
or help me with this issue.
I am enabling spark.eventLog
and giving a path to my hadoop HDFS folder.
The following exception occurs multiple times but program still runs and completed successfully.
**Sample error**
2020-09-10 14:55:19 ERROR AsyncEventQueue:91 - Listener EventLoggingListener threw an exception
java.io.IOException: Filesystem closed
	at org.apache.hadoop.hdfs.DFSClient.checkOpen(DFSClient.java:808)
	at org.apache.hadoop.hdfs.DFSOutputStream.flushOrSync(DFSOutputStream.java:1966)
	at org.apache.hadoop.hdfs.DFSOutputStream.hsync(DFSOutputStream.java:1946)
	at org.apache.spark.scheduler.EventLoggingListener$$anonfun$logEvent$3.apply(EventLoggingListener.scala:148)
	at org.apache.spark.scheduler.EventLoggingListener$$anonfun$logEvent$3.apply(EventLoggingListener.scala:147)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.scheduler.EventLoggingListener.logEvent(EventLoggingListener.scala:147)
	at org.apache.spark.scheduler.EventLoggingListener.onJobStart(EventLoggingListener.scala:175)
	at org.apache.spark.scheduler.SparkListenerBus$class.doPostEvent(SparkListenerBus.scala:37)
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
	at org.apache.spark.util.ListenerBus$class.postToAll(ListenerBus.scala:91)
	at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$super$postToAll(AsyncEventQueue.scala:92)
	at org.apache.spark.scheduler.AsyncEventQueue$$anonfun$org$apache$spark$scheduler$AsyncEventQueue$$dispatch$1.apply$mcJ$sp(AsyncEventQueue.scala:92)
	at org.apache.spark.scheduler.AsyncEventQueue$$anonfun$org$apache$spark$scheduler$AsyncEventQueue$$dispatch$1.apply(AsyncEventQueue.scala:87)
	at org.apache.spark.scheduler.AsyncEventQueue$$anonfun$org$apache$spark$scheduler$AsyncEventQueue$$dispatch$1.apply(AsyncEventQueue.scala:87)

**Comment by Le-Zheng** [comment]
@shadyonfire 
You may have a try with the latest [jar](https://repo1.maven.org/maven2/com/intel/analytics/bigdl/dist-spark-2.3.1-scala-2.11.8-all/0.11.1/dist-spark-2.3.1-scala-2.11.8-all-0.11.1.jar) for saprk-2.3.1.

**Comment by shadyonfire** [comment]
Hello @Le-Zheng , the problem is same as mentioned. though i have tried the latest jar given by you.
Is there any other solution?

**Comment by Le-Zheng** [comment]
Can you share which lines of codes cause the error?

**Comment by shadyonfire** [comment]
Hello @Le-Zheng the problem was with the instance of hdfs getting closed.
So i used a different hdfs cluster only to save eventLog and it worked fine. 

Problem is in File.scala.
It uses some method in which the hdfs returns the shared object. I think changing it to newInstance method will work on code.

**Comment by shadyonfire** [comment]
Hi i

**Comment by Le-Zheng** [comment]
> Hello @Le-Zheng the problem was with the instance of hdfs getting closed.
> So i used a different hdfs cluster only to save eventLog and it worked fine.
> 
> Problem is in File.scala.
> It uses some method in which the hdfs returns the shared object. I think changing it to newInstance method will work on code.

Hi @shadyonfire Thank you for replying. Could you give me tips on which lines of code in File.scala should be fixed? As I saw it have used the `newInstance` method.

**Comment by shadyonfire** [comment]
As of now i am sure which line of code. 
but as far as I know, you should create a newInstance for eventLoggers because as soon as the program ends it stops the shared instance and the exception occurs
i am attaching the error stack below that will help you to figure out.
2020-09-10 14:55:18 ERROR AsyncEventQueue:91 - Listener EventLoggingListener threw an exception
java.io.IOException: Filesystem closed
	at org.apache.hadoop.hdfs.DFSClient.checkOpen(DFSClient.java:808)
	at org.apache.hadoop.hdfs.DFSOutputStream.flushOrSync(DFSOutputStream.java:1966)
	at org.apache.hadoop.hdfs.DFSOutputStream.hsync(DFSOutputStream.java:1946)
	at org.apache.spark.scheduler.EventLoggingListener$$anonfun$logEvent$3.apply(EventLoggingListener.scala:148)
	at org.apache.spark.scheduler.EventLoggingListener$$anonfun$logEvent$3.apply(EventLoggingListener.scala:147)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.scheduler.EventLoggingListener.logEvent(EventLoggingListener.scala:147)
	at org.apache.spark.scheduler.EventLoggingListener.onJobStart(EventLoggingListener.scala:175)
	at org.apache.spark.scheduler.SparkListenerBus$class.doPostEvent(SparkListenerBus.scala:37)
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
	at org.apache.spark.util.ListenerBus$class.postToAll(ListenerBus.scala:91)
	at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$super$postToAll(AsyncEventQueue.scala:92)
	at org.apache.spark.scheduler.AsyncEventQueue$$anonfun$org$apache$spark$scheduler$AsyncEventQueue$$dispatch$1.apply$mcJ$sp(AsyncEventQueue.scala:92)
	at org.apache.spark.scheduler.AsyncEventQueue$$anonfun$org$apache$spark$scheduler$AsyncEventQueue$$dispatch$1.apply(AsyncEventQueue.scala:87)
	at org.apache.spark.scheduler.AsyncEventQueue$$anonfun$org$apache$spark$scheduler$AsyncEventQueue$$dispatch$1.apply(AsyncEventQueue.scala:87)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:87)
	at org.apache.spark.scheduler.AsyncEventQueue$$anon$1$$anonfun$run$1.apply$mcV$sp(AsyncEventQueue.scala:83)
	at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1322)
	at org.apache.spark.scheduler.AsyncEventQueue$$anon$1.run(AsyncEventQueue.scala:82)
