### ISSUE TITLE
error after the final epoch and accuracy output 

### ISSUE THREAD

**Issue by shane-huang** [intel-analytics/BigDL#306]
When run cluster mode of textclassification example, there's error after the final epoch and accuracy output. Details as below
...
2016-12-30 13:34:48 INFO  DistriOptimizer$:458 - top1 accuracy is Accuracy(correct: 3742, count: 3977, accuracy: 0.9409102338446065)
2016-12-30 13:34:48 ERROR ConnectionManager:75 - Corresponding SendingConnection to ConnectionManagerId(Gondolin-Node-092,36314) not found
2016-12-30 13:34:48 ERROR ConnectionManager:75 - Corresponding SendingConnection to ConnectionManagerId(Gondolin-Node-090,35572) not found
2016-12-30 13:34:48 ERROR ConnectionManager:75 - Corresponding SendingConnection to ConnectionManagerId(Gondolin-Node-057,34264) not found
2016-12-30 13:34:48 ERROR ConnectionManager:96 - Exception while sending message.
java.nio.channels.CancelledKeyException
        at org.apache.spark.network.nio.ConnectionManager.run(ConnectionManager.scala:461)
        at org.apache.spark.network.nio.ConnectionManager$$anon$7.run(ConnectionManager.scala:193)
2016-12-30 13:34:48 ERROR ConnectionManager:75 - no messageStatus for failed message id: 7
2016-12-30 13:34:48 ERROR ConnectionManager:96 - Exception while sending message.
java.nio.channels.CancelledKeyException
        at org.apache.spark.network.nio.ConnectionManager.run(ConnectionManager.scala:461)
        at org.apache.spark.network.nio.ConnectionManager$$anon$7.run(ConnectionManager.scala:193)
2016-12-30 13:34:48 ERROR ConnectionManager:75 - no messageStatus for failed message id: 5
2016-12-30 13:34:48 ERROR ConnectionManager:75 - Corresponding SendingConnection to ConnectionManagerId(Gondolin-Node-057,34264) not found
2016-12-30 13:34:48 ERROR ConnectionManager:75 - Corresponding SendingConnection to ConnectionManagerId(Gondolin-Node-090,35572) not found
2016-12-30 13:34:48 ERROR ConnectionManager:75 - Corresponding SendingConnection to ConnectionManagerId(Gondolin-Node-086,42332) not found

**Comment by zhichao-li** [comment]
This is due to there are some long running not daemon threads. and it has been fixed in the latest code.
