### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/spark/mllib/linalg/Vector

### ISSUE THREAD

**Issue by mullerhai** [intel-analytics/BigDL#3100]
When I use  spark 3.0.1 
also use bigdl  for spark 3 scala 2.12 meeting this  error ，

**Comment by mullerhai** [comment]
console log 
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/spark/mllib/linalg/Vector
	at com.intel.analytics.bigdl.tensor.Tensor$.apply(Tensor.scala:872)
	at com.intel.analytics.bigdl.nn.abstractnn.Activity$.allocate(Activity.scala:97)
	at com.intel.analytics.bigdl.nn.abstractnn.AbstractModule.<init>(AbstractModule.scala:68)
	at com.intel.analytics.bigdl.nn.abstractnn.TensorModule.<init>(AbstractModule.scala:49)
	at com.intel.analytics.bigdl.nn.Linear.<init>(Linear.scala:55)
	at com.intel.analytics.bigdl.nn.Linear$.apply$mFc$sp(Linear.scala:239)
	at DLClassifierLogisticRegression$.main(DLClassifierLogisticRegression.scala:36)
	at DLClassifierLogisticRegression.main(DLClassifierLogisticRegression.scala)
Caused by: java.lang.ClassNotFoundException: org.apache.spark.mllib.linalg.Vector
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 8 more

**Comment by mullerhai** [comment]
bigdl dependency 
https://mvnrepository.com/artifact/com.intel.analytics.bigdl/bigdl-SPARK_3.0

<dependency>
    <groupId>com.intel.analytics.bigdl</groupId>
    <artifactId>bigdl-SPARK_3.0</artifactId>
    <version>0.12.1</version>
</dependency>

**Comment by qiyuangong** [comment]
Hi @mullerhai 
We are try to reproduce this issue. Which example are you using/running? If not, pls provide example code.

**Comment by mullerhai** [comment]
> Hi @mullerhai
> We are try to reproduce this issue. Which example are you using/running? If not, pls provide example code.

Hi ,I have solve it,I think  maybe is sbt version made some problem
