### ISSUE TITLE
tests should be disabled when adding BigDL to pom

### ISSUE THREAD

**Issue by songhappy** [intel-analytics/BigDL#3115]
add dependency in my project like
        <dependency>
            <groupId>com.intel.analytics.zoo</groupId>
            <artifactId>analytics-zoo-bigdl_0.12.1-spark_2.4.3</artifactId>
            <version>0.9.0</version>
        </dependency>
mvn install failed because of failure of tests in BigDL, here is error message

[com.intel.analytics.bigdl.tensor.DenseTensor of size 10x1]
- Sample *** FAILED ***
  java.lang.IllegalArgumentException: Tensor cannot be cast to Table
  at com.intel.analytics.bigdl.tensor.Tensor$class.toTable(Tensor.scala:747)
  at com.intel.analytics.bigdl.tensor.DenseTensor.toTable(DenseTensor.scala:33)
  at com.intel.analytics.zoo.apps.tutorial.understandData$$anonfun$7.apply$mcV$sp(understandData.scala:150)
  at com.intel.analytics.zoo.apps.tutorial.understandData$$anonfun$7.apply(understandData.scala:142)
  at com.intel.analytics.zoo.apps.tutorial.understandData$$anonfun$7.apply(understandData.scala:142)
  at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
  at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  at org.scalatest.Transformer.apply(Transformer.scala:22)
  at org.scalatest.Transformer.apply(Transformer.scala:20)

**Comment by helenlly** [comment]
@Le-Zheng pls have a look

**Comment by Le-Zheng** [comment]
Can you try to add an option "-DskipTests"?

**Comment by qiuxin2012** [comment]
Seems your `com.intel.analytics.zoo.apps.tutorial.understandData$$anonfun$7.apply$mcV$sp(understandData.scala:150)` is not a bigdl's class? Please provide more informations.

**Comment by glorysdj** [comment]
mvn install will run tests in your own project, will not run any tests in analytics-zoo or bigdl, please check which test failed and where it is.

**Comment by qiuxin2012** [comment]
Add BigDL as dependency in your project won't run any BigDL's test, and this error is thrown by a failed unit test in your project. **Please change this issue's title to a right one**, and provide more information if you need more help,.

BTW, I recommend you to use Camel-Case class name `UnderstandData` instead of `understandData`.
