### ISSUE TITLE
An error occurred while running locally：Exception in thread "main" java.lang.UnsatisfiedLinkError: com.intel.analytics.bigdl.mkl.MKL.setNumThreads(I)V

### ISSUE THREAD

**Issue by 540667387** [intel-analytics/BigDL#3126]
I had an error running locally on Windows

println(Tensor[Float](2,3))

Exception in thread "main" java.lang.UnsatisfiedLinkError: com.intel.analytics.bigdl.mkl.MKL.setNumThreads(I)V
at com.intel.analytics.bigdl.mkl.MKL.setNumThreads(Native Method)
at com.intel.analytics.bigdl.mkl.MKL.setMklEnv(MKL.java:127)

i donot know why？

**Comment by Le-Zheng** [comment]
BigDL supports Linux and mac. Please try it on Linux or mac.

**Comment by 540667387** [comment]
> BigDL supports Linux and mac. Please try it on Linux or mac.

Well, that's too bad
