### ISSUE TITLE
saveTF java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by zepen** [intel-analytics/BigDL#3147]
`  
model.saveTF(Seq(("inputs", Seq(1, 1, 1))), "model.pb")
`

Exception in thread "main" java.lang.NoSuchMethodError: org.tensorflow.framework.AttrValue$Builder.setS(Lcom/intel/analytics/bigdl/shaded/protobuf/ByteString;)Lorg/tensorflow/framework/AttrValue$Builder;
	at com.intel.analytics.bigdl.utils.tf.TensorflowDataFormat$NHWC$.<init>(Tensorflow.scala:44)
	at com.intel.analytics.bigdl.utils.tf.TensorflowDataFormat$NHWC$.<clinit>(Tensorflow.scala)
	at com.intel.analytics.bigdl.nn.abstractnn.AbstractModule.saveTF$default$4(AbstractModule.scala:631)
	at com.zoo.samoyed.dl.bigDL.Test$.main(Test.scala:103)
	at com.zoo.samoyed.dl.bigDL.Test.main(Test.scala)

Maybe protobuf version no match, but i don't known how to choose version.

**Comment by yangw1234** [comment]
@zepen can you share the code so that we can reproduce this issue?

**Comment by zepen** [comment]
@yangw1234 This is my code. 
`scala
import com.intel.analytics.bigdl.DataSet
import com.intel.analytics.bigdl.dataset.{DataSet, MiniBatch, Sample}
import com.intel.analytics.bigdl.example.lenetLocal.Utils.{testMean, testStd, trainMean, trainStd}
import com.intel.analytics.bigdl
import com.intel.analytics.bigdl.nn.ClassNLLCriterion
import com.intel.analytics.bigdl.nn.keras.{Dense, Input, Model}
import com.intel.analytics.bigdl.optim.{Adagrad, Loss, OptimMethod, Optimizer, SGD, Top1Accuracy, Trigger}
import com.intel.analytics.bigdl.dataset.Sample
import com.intel.analytics.bigdl.tensor.Tensor
import com.intel.analytics.bigdl.numeric.NumericFloat
import com.intel.analytics.bigdl.utils.{Engine, File, Shape}
import org.apache.spark.SparkContext

object Test {

  def main(args: Array[String]): Unit = {

    val runReadDateFile = "20210730/"

    val conf = Engine.createSparkConf()
      .setAppName("BigDL Test")
      .set("spark.master", "local[4]")
      .set("spark.executor.heartbeatInterval", "300")
      .set("spark.network.timeout", "800")
      .set("spark.task.maxFailures", "1")
    val sc = new SparkContext(conf)
    Engine.init

//    val features = Array(Tensor(1, 3).rand, Tensor(1, 3).rand, Tensor(1, 3).rand, Tensor(1, 3).rand)
//    val labels = Array(Tensor(1).fill(1), Tensor(1).fill(0), Tensor(1).fill(1), Tensor(1).fill(0))
//    val sample = Sample(features, labels)

//    println(sample.getFeatureSize().mkString("Array(", ", ", ")"))

    val training = Seq(
      Sample(Tensor(3).rand, Tensor(1).fill(1)),
      Sample(Tensor(3).rand, Tensor(1).fill(1)),
      Sample(Tensor(3).rand, Tensor(1).fill(1)),
      Sample(Tensor(3).rand, Tensor(1).fill(1)),
      Sample(Tensor(3).rand, Tensor(1).fill(1))
    )
    val trainingRdd = sc.parallelize(training, 3)

    val input = Input[Float](inputShape = Shape(3), name = "inputs")
    val dense = Dense[Float](10, activation = "relu").inputs(input)
    val output = Dense[Float](outputDim = 1, activation = "sigmoid").inputs(dense)
    // create a graph container
    val model = Model[Float](input, output)

//    val trainSet = DataSet.rdd(trainingRdd, 1)
//
//    val validationSet = DataSet.rdd(trainingRdd, 1)

    val optimizer = Optimizer(
      model = model,
      sampleRDD = trainingRdd,
      criterion = ClassNLLCriterion[Float](),
      batchSize = 4
    )

    optimizer
//      .setValidation(
//        trigger = Trigger.everyEpoch,
//        dataset = validationSet,
//        vMethods = Array(new Top1Accuracy))
      .setOptimMethod(new Adagrad(learningRate=0.01, learningRateDecay=0.0002))
      .setEndWhen(Trigger.maxEpoch(10))
      .optimize()

//    model.compile(
//      optimizer = new SGD[Float](learningRate = 0.01, learningRateDecay = 0.1),
//      loss = [Float],
//      metrics = "loss"
//    )
//
//    model.fit(trainSet, nbEpoch = 10, validationData = validationSet)

    model.predict(trainingRdd).map(row=>println(row))

//    model.saveWeights("DNN", overWrite = true)

    model.saveTF(Seq(("inputs", Seq(1, 1, 1))), "model.pb")

    sc.stop()

  }
}

`

**Comment by yangw1234** [comment]
thanks @zepen .  
And may I ask how do you submit the code? 
Are you building a jar yourself depending on bigdl? If so, could you also share your pom.xml?

**Comment by zepen** [comment]
```xml
 <dependencies>

        <dependency>
            <groupId>com.intel.analytics.bigdl</groupId>
            <artifactId>bigdl-SPARK_1.6</artifactId>
            <version>0.11.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-core_${scala.binary.version}</artifactId>
            <version>${spark.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-sql_${scala.binary.version}</artifactId>
            <version>${spark.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-mllib_${scala.binary.version}</artifactId>
            <version>${spark.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-streaming_${scala.binary.version}</artifactId>
            <version>${spark.version}</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>com.aliyun.odps</groupId>
            <artifactId>cupid-sdk</artifactId>
            <version>${cupid.sdk.version}</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>com.aliyun.odps</groupId>
            <artifactId>hadoop-fs-oss</artifactId>
            <version>${cupid.sdk.version}</version>
        </dependency>

        <dependency>
            <groupId>com.aliyun.odps</groupId>
            <artifactId>odps-spark-datasource_${scala.binary.version}</artifactId>
            <version>3.3.8-public-hotfix1</version>
        </dependency>

        <dependency>
            <groupId>org.scala-lang</groupId>
            <artifactId>scala-library</artifactId>
            <version>${scala.version}</version>
        </dependency>
        <dependency>
            <groupId>org.scala-lang</groupId>
            <artifactId>scala-actors</artifactId>
            <version>${scala.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
            <version>2.12.1</version>
        </dependency>

        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-api</artifactId>
            <version>2.12.1</version>
        </dependency>

        <dependency>
            <groupId>com.google.protobuf</groupId>
            <artifactId>protobuf-java</artifactId>
            <version>3.1.0</version>
        </dependency>

    </dependencies>
```
@yangw1234 This is my pom dependencies.
i run code by local mode, such as java -javaagent xxx -classpath xxxx com.xxx.xxx.Test
it' s running on my idea, then exception as:
Exception in thread "main" java.lang.NoSuchMethodError: org.tensorflow.framework.AttrValue$Builder.setS(Lcom/intel/analytics/bigdl/shaded/protobuf/ByteString;)Lorg/tensorflow/framework/AttrValue$Builder;
	at com.intel.analytics.bigdl.utils.tf.TensorflowDataFormat$NHWC$.<init>(Tensorflow.scala:44)
	at com.intel.analytics.bigdl.utils.tf.TensorflowDataFormat$NHWC$.<clinit>(Tensorflow.scala)
	at com.intel.analytics.bigdl.nn.abstractnn.AbstractModule.saveTF$default$4(AbstractModule.scala:631)
	at com.zoo.samoyed.dl.bigDL.Test$.main(Test.scala:103)
	at com.zoo.samoyed.dl.bigDL.Test.main(Test.scala)

**Comment by yangw1234** [comment]
@zepen thanks, I am currently looking into it.

**Comment by sgwhat** [comment]
@zepen Hi, sorry I think this is a bug in your code, that is caused by only graph container can be saved as Tensorflow model, maybe you can try the code below to escape the container error.
```
val trainingRdd = sc.parallelize(training, 3)
import com.intel.analytics.bigdl.nn._
val input = Reshape(Array(3)).inputs()
val dense = Linear(3, 10).setName("fc1").inputs(input)
val relu = ReLU().setName("relu1").inputs(dense)
val output = Linear(10, 1).inputs(relu)
val model = Graph(input, output)
```
Also, it could be a better way if you choose `spark-shell-with-bigdl.sh` instead of java -javaagent xxx -classpath xxxx com.xxx.xxx.Test.

**Comment by helenlly** [comment]
@zepen , have you tried the steps above? or any update on the issue?

**Comment by zepen** [comment]
> @zepen , have you tried the steps above? or any update on the issue?
Have new error, such as NoClassDefFoundError when i spark-submit
spark version spark-2.3.0-bin-hadoop2.7,  and --jars bigdl-SPARK_2.3-0.12.2.jar all-0.12.2.jar

2021-11-25 19:15:39 INFO  DAGScheduler:54 - ResultStage 3 (count at DistriOptimizer.scala:650) failed in 0.163 s due to Job aborted due to stage failure: Task 0 in stage 3.0 failed 1 times, most recent failure: Lost task 0.0 in stage 3.0 (TID 4, localhost, executor driver): java.lang.NoClassDefFoundError: org/apache/spark/storage/BlockManagerWrapper$
        at com.intel.analytics.bigdl.parameters.AllReduceParameter.init(AllReduceParameter.scala:167)
        at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$11.apply(DistriOptimizer.scala:634)
        at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$11.apply(DistriOptimizer.scala:592)
        at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:800)
        at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:800)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
        at org.apache.spark.rdd.RDD$$anonfun$7.apply(RDD.scala:337)
        at org.apache.spark.rdd.RDD$$anonfun$7.apply(RDD.scala:335)
        at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1092)
        at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1083)
        at org.apache.spark.storage.BlockManager.doPut(BlockManager.scala:1018)
        at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:1083)
        at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:809)
        at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:335)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:286)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
        at org.apache.spark.scheduler.Task.run(Task.scala:109)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.apache.spark.storage.BlockManagerWrapper$
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 22 more

**Comment by helenlly** [comment]
@yangw1234  pls have a look

**Comment by yangw1234** [comment]
@zepen where did you get the `bigdl-SPARK_2.3-0.12.2.jar`? 
Could you try downloading our prebuilt jars from here (https://bigdl-project.github.io/master/#release-download/#release-0122), and use the `lib/bigdl-SPARK_2.3-0.12.2-jar-with-dependencies.jar`
