### ISSUE TITLE
Meet error com.esotericsoftware.kryo.KryoException 

### ISSUE THREAD

**Issue by mullerhai** [intel-analytics/BigDL#3148]
Hi sir: 
       when I run the example  test case  ,meet some error
Caused by: com.esotericsoftware.kryo.KryoException: Unable to find class: com.intel.analytics.bigdl.dataset.ByteRecord

testcase :package com.intel.analytics.bigdl.example.keras .Train

spark  version 3.1.2
java jdk  11
scala  2.12.13
bigdl  version  0.13.0

I don't know why the  

```
2021-09-10 19:02:54 ERROR TaskSetManager:73 - Task 4 in stage 648.0 failed 4 times; aborting job
2021-09-10 19:02:54 ERROR TaskSetManager:73 - Task 4 in stage 648.0 failed 4 times; aborting job
org.apache.spark.SparkException: Job aborted due to stage failure: Task 4 in stage 648.0 failed 4 times, most recent failure: Lost task 4.3 in stage 648.0 (TID 17487) (125.94.240.173 executor 1): java.io.IOException: com.esotericsoftware.kryo.KryoException: Unable to find class: com.intel.analytics.bigdl.dataset.ByteRecord
	at org.apache.spark.util.Utils$.tryOrIOException(Utils.scala:1412)
	at org.apache.spark.rdd.ParallelCollectionPartition.readObject(ParallelCollectionRDD.scala:69)
	at jdk.internal.reflect.GeneratedMethodAccessor386.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.base/java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1175)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2452)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2318)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1801)
	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2593)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2485)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2318)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1801)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:577)
	at java.base/java.io.ObjectInputStream.redirectedReadObject(ObjectInputStream.java:507)
	at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:76)
	at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:115)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:457)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:836)
Caused by: com.esotericsoftware.kryo.KryoException: Unable to find class: com.intel.analytics.bigdl.dataset.ByteRecord
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readName(DefaultClassResolver.java:160)
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:133)
	at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:693)
	at com.esotericsoftware.kryo.serializers.DefaultSerializers$ClassSerializer.read(DefaultSerializers.java:330)
	at com.esotericsoftware.kryo.serializers.DefaultSerializers$ClassSerializer.read(DefaultSerializers.java:318)
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:709)
	at com.twitter.chill.WrappedArraySerializer.read(WrappedArraySerializer.scala:34)
	at com.twitter.chill.WrappedArraySerializer.read(WrappedArraySerializer.scala:23)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:813)
	at org.apache.spark.serializer.KryoDeserializationStream.readObject(KryoSerializer.scala:296)
	at org.apache.spark.rdd.ParallelCollectionPartition.$anonfun$readObject$2(ParallelCollectionRDD.scala:79)
	at org.apache.spark.rdd.ParallelCollectionPartition.$anonfun$readObject$2$adapted(ParallelCollectionRDD.scala:79)
	at org.apache.spark.rdd.ParallelCollectionPartition$$Lambda$2209/0x0000000000000000.apply(Unknown Source)
	at org.apache.spark.util.Utils$.deserializeViaNestedStream(Utils.scala:171)
	at org.apache.spark.rdd.ParallelCollectionPartition.$anonfun$readObject$1(ParallelCollectionRDD.scala:79)
	at org.apache.spark.rdd.ParallelCollectionPartition$$Lambda$3340/0x0000000000000000.apply$mcV$sp(Unknown Source)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.apache.spark.util.Utils$.tryOrIOException(Utils.scala:1405)
	... 20 more
Caused by: java.lang.ClassNotFoundException: com.intel.analytics.bigdl.dataset.ByteRecord
	at java.base/java.lang.Class.forNameImpl(Native Method)
	at java.base/java.lang.Class.forName(Class.java:413)
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readName(DefaultClassResolver.java:154)
	... 37 more
```

**Comment by jason-dai** [comment]
See https://bigdl-project.github.io/master/#known-issues/; specifically:
```
On Spark 2.0, please use default Java serializer instead of Kryo because of Kryo Issue 341.
The issue has been fixed in Kryo 4.0. However, Spark 2.0 uses Kryo 3.0.3. 
Spark 1.5 and 1.6 do not have this problem.
```

**Comment by mullerhai** [comment]
> See https://bigdl-project.github.io/master/#known-issues/; specifically:
> 
> ```
> On Spark 2.0, please use default Java serializer instead of Kryo because of Kryo Issue 341.
> The issue has been fixed in Kryo 4.0. However, Spark 2.0 uses Kryo 3.0.3. 
> Spark 1.5 and 1.6 do not have this problem.
> ```

but I just use  spark version is 3.1.2 , it's not include on the  below content, please 
thx

**Comment by jason-dai** [comment]
> > See [bigdl-project.github.io/master/#known-issues](https://bigdl-project.github.io/master/#known-issues/); specifically:
> > ```
> > On Spark 2.0, please use default Java serializer instead of Kryo because of Kryo Issue 341.
> > The issue has been fixed in Kryo 4.0. However, Spark 2.0 uses Kryo 3.0.3. 
> > Spark 1.5 and 1.6 do not have this problem.
> > ```
> 
> but I just use spark version is 3.1.2 , it's not include on the below content, please
> thx

I think it is similar to Spark 2.x; please use the standard Java serializer instead of Kryo

**Comment by mullerhai** [comment]
> > > See [bigdl-project.github.io/master/#known-issues](https://bigdl-project.github.io/master/#known-issues/); specifically:
> > > ```
> > > On Spark 2.0, please use default Java serializer instead of Kryo because of Kryo Issue 341.
> > > The issue has been fixed in Kryo 4.0. However, Spark 2.0 uses Kryo 3.0.3. 
> > > Spark 1.5 and 1.6 do not have this problem.
> > > ```
> > 
> > 
> > but I just use spark version is 3.1.2 , it's not include on the below content, please
> > thx
> 
> I think it is similar to Spark 2.x; please use the standard Java serializer instead of Kryo

when I set use the   standard Java serializer  ,also  meet the same error  ,I dont know why

**Comment by Le-Zheng** [comment]
> > > > See [bigdl-project.github.io/master/#known-issues](https://bigdl-project.github.io/master/#known-issues/); specifically:
> > > > ```
> > > > On Spark 2.0, please use default Java serializer instead of Kryo because of Kryo Issue 341.
> > > > The issue has been fixed in Kryo 4.0. However, Spark 2.0 uses Kryo 3.0.3. 
> > > > Spark 1.5 and 1.6 do not have this problem.
> > > > ```
> > > 
> > > 
> > > but I just use spark version is 3.1.2 , it's not include on the below content, please
> > > thx
> > 
> > 
> > I think it is similar to Spark 2.x; please use the standard Java serializer instead of Kryo
> 
> when I set use the standard Java serializer ,also meet the same error ,I dont know why

Hi mullerhai,
I am trying to reproduce your issue. This example can run successfully on Spark3.1.2,  jdk 11 by following the example readme https://github.com/intel-analytics/BigDL/tree/master/spark/dl/src/main/scala/com/intel/analytics/bigdl/example/keras#readme. 
I have no idea why Kryo error happens. How did you run this example?

**Comment by helenlly** [comment]
@mullerhai  any update on the issue?
