### ISSUE TITLE
Copy validation data error

### ISSUE THREAD

**Issue by jenniew** [intel-analytics/BigDL#335]
Copy validation data error. When calling buffer.copy(rawData.data, normalize).setLabel(rawData.label) in BytesToBGRImg.apply(),  get NullPointerException.

Phenomena: The first iteration would fetch batchsize+1 images,  the last iteration would  try to copy , but the raw data is null, so got NullPointerException. 

ERROR ThreadPool$:106 - Error: java.lang.NullPointerException
	at com.intel.analytics.bigdl.dataset.image.BytesToBGRImg$$anonfun$apply$1.apply(BytesToBGRImg.scala:40)
	at com.intel.analytics.bigdl.dataset.image.BytesToBGRImg$$anonfun$apply$1.apply(BytesToBGRImg.scala:39)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
	at com.intel.analytics.bigdl.dataset.image.PreFetch$$anon$2.hasNext(MTLabeledBGRImgToBatch.scala:115)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
	at com.intel.analytics.bigdl.dataset.image.MTLabeledBGRImgToBatch$$anon$1$$anonfun$2$$anonfun$apply$1.apply$mcI$sp(MTLabeledBGRImgToBatch.scala:81)
	at com.intel.analytics.bigdl.dataset.image.MTLabeledBGRImgToBatch$$anon$1$$anonfun$2$$anonfun$apply$1.apply(MTLabeledBGRImgToBatch.scala:78)
	at com.intel.analytics.bigdl.dataset.image.MTLabeledBGRImgToBatch$$anon$1$$anonfun$2$$anonfun$apply$1.apply(MTLabeledBGRImgToBatch.scala:78)
	at com.intel.analytics.bigdl.utils.ThreadPool$$anonfun$invokeAndWait$1$$anonfun$apply$2.apply(Engine.scala:103)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617

**Comment by jenniew** [comment]
add label

**Comment by jenniew** [comment]
I use flickr pictures. They are in different sizes. The data is in gondolin-node-078:/disk7/flickr_style
My execution code : 
Execution code is as below:

DataSet.ImageFolder.images(path, 256)
.transform(
MTLabeledBGRImgToBatch(
width = imageSize,
height = imageSize,
batchSize = batchSize,
transformer = BGRImgCropper(cropWidth = imageSize, cropHeight = imageSize)
-> HFlip(0.5) -> BGRImgNormalizer(0.485, 0.456, 0.406, 0.229, 0.224, 0.225))
)
