### ISSUE TITLE
Append bigdl's jars to an instantiated  spark context

### ISSUE THREAD

**Issue by qiuxin2012** [intel-analytics/BigDL#3351]
I find a way to append bigdl's jars to an instantiated spark context.
But bigdl's spark-conf is missing, and initEngine will fail due to `Engine.init: Can not find spark.shuffle.reduceLocality.enabled`.
It can works if I start pyspark by `pyspark --properties-file scala/dllib/src/main/resources/spark-bigdl.conf`.
The error log is below:
```
(nzoo) xin@xin-dev:~/IntelAnalytics/BigDL$ pyspark
Python 3.7.11 (default, Jul 27 2021, 14:32:16) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
21/10/29 16:55:52 WARN util.Utils: Your hostname, xin-dev resolves to a loopback address: 127.0.0.1; using 10.239.158.150 instead (on interface enp0s31f6)
21/10/29 16:55:52 WARN util.Utils: Set SPARK_LOCAL_IP if you need to bind to another address
21/10/29 16:55:52 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /__ / .__/\_,_/_/ /_/\_\   version 2.4.6
      /_/

Using Python version 3.7.11 (default, Jul 27 2021 14:32:16)
SparkSession available as 'spark'.
>>> 
>>> from bigdl.dllib.utils.engine import get_bigdl_jars
Prepending /opt/anaconda3/envs/nzoo/lib/python3.7/site-packages/bigdl/share/dllib/conf/spark-bigdl.conf to sys.path
>>> jars = get_bigdl_jars()
>>> spark = SparkSession.builder.getOrCreate()
>>> spark._jsparkSession.sessionState().resourceLoader().addJar(jars[0])
>>> spark._jsparkSession.sessionState().resourceLoader().addJar(jars[1])
>>> 
>>> from bigdl.orca.common import *
>>> init_orca_context(cluster_mode="spark-submit")
Initializing orca context
Traceback (most recent call last):
  File "/opt/anaconda3/envs/nzoo/lib/python3.7/site-packages/pyspark/sql/utils.py", line 63, in deco
    return f(*a, **kw)
  File "/opt/anaconda3/envs/nzoo/lib/python3.7/site-packages/pyspark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o37.initEngine.
: java.lang.IllegalArgumentException: requirement failed: Engine.init: Can not find spark.shuffle.reduceLocality.enabled. For details please check https://bigdl-project.github.io/master/#APIGuide/Engine/
	at scala.Predef$.require(Predef.scala:224)
	at com.intel.analytics.bigdl.dllib.utils.Engine$.com$intel$analytics$bigdl$dllib$utils$Engine$$verify$1(Engine.scala:451)
	at com.intel.analytics.bigdl.dllib.utils.Engine$$anonfun$checkSparkContext$1.apply(Engine.scala:459)
	at com.intel.analytics.bigdl.dllib.utils.Engine$$anonfun$checkSparkContext$1.apply(Engine.scala:459)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
	at com.intel.analytics.bigdl.dllib.utils.Engine$.checkSparkContext(Engine.scala:459)
	at com.intel.analytics.bigdl.dllib.utils.Engine$.init(Engine.scala:125)
	at com.intel.analytics.bigdl.dllib.utils.python.api.PythonBigDL.initEngine(PythonBigDL.scala:2507)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:745)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/envs/nzoo/lib/python3.7/site-packages/bigdl/orca/common.py", line 200, in init_orca_context
    sc = init_nncontext(**spark_args)
  File "/opt/anaconda3/envs/nzoo/lib/python3.7/site-packages/bigdl/dllib/nncontext.py", line 483, in init_nncontext
    init_engine()
  File "/opt/anaconda3/envs/nzoo/lib/python3.7/site-packages/bigdl/dllib/utils/common.py", line 427, in init_engine
    callBigDlFunc(bigdl_type, "initEngine")
  File "/opt/anaconda3/envs/nzoo/lib/python3.7/site-packages/bigdl/dllib/utils/common.py", line 607, in callBigDlFunc
    raise e
  File "/opt/anaconda3/envs/nzoo/lib/python3.7/site-packages/bigdl/dllib/utils/common.py", line 603, in callBigDlFunc
    result = callJavaFunc(api, *args)
  File "/opt/anaconda3/envs/nzoo/lib/python3.7/site-packages/bigdl/dllib/utils/common.py", line 656, in callJavaFunc
    result = func(*args)
  File "/opt/anaconda3/envs/nzoo/lib/python3.7/site-packages/pyspark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
  File "/opt/anaconda3/envs/nzoo/lib/python3.7/site-packages/pyspark/sql/utils.py", line 79, in deco
    raise IllegalArgumentException(s.split(': ', 1)[1], stackTrace)
pyspark.sql.utils.IllegalArgumentException: 'requirement failed: Engine.init: Can not find spark.shuffle.reduceLocality.enabled. For details please check https://bigdl-project.github.io/master/#APIGuide/Engine/'
>>> from bigdl.dllib.nn.keras.layers.topology import Sequential
Traceback (most recent call last):
  File "/opt/anaconda3/envs/nzoo/lib/python3.7/site-packages/pyspark/sql/utils.py", line 63, in deco
    return f(*a, **kw)
  File "/opt/anaconda3/envs/nzoo/lib/python3.7/site-packages/pyspark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o37.initEngine.
: java.lang.IllegalArgumentException: requirement failed: Engine.init: Can not find spark.shuffle.reduceLocality.enabled. For details please check https://bigdl-project.github.io/master/#APIGuide/Engine/
	at scala.Predef$.require(Predef.scala:224)
	at com.intel.analytics.bigdl.dllib.utils.Engine$.com$intel$analytics$bigdl$dllib$utils$Engine$$verify$1(Engine.scala:451)
	at com.intel.analytics.bigdl.dllib.utils.Engine$$anonfun$checkSparkContext$1.apply(Engine.scala:459)
	at com.intel.analytics.bigdl.dllib.utils.Engine$$anonfun$checkSparkContext$1.apply(Engine.scala:459)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
	at com.intel.analytics.bigdl.dllib.utils.Engine$.checkSparkContext(Engine.scala:459)
	at com.intel.analytics.bigdl.dllib.utils.Engine$.init(Engine.scala:125)
	at com.intel.analytics.bigdl.dllib.utils.python.api.PythonBigDL.initEngine(PythonBigDL.scala:2507)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:745)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/envs/nzoo/lib/python3.7/site-packages/bigdl/dllib/nn/keras/layers/__init__.py", line 18, in <module>
    init_engine()
  File "/opt/anaconda3/envs/nzoo/lib/python3.7/site-packages/bigdl/dllib/utils/common.py", line 427, in init_engine
    callBigDlFunc(bigdl_type, "initEngine")
  File "/opt/anaconda3/envs/nzoo/lib/python3.7/site-packages/bigdl/dllib/utils/common.py", line 607, in callBigDlFunc
    raise e
  File "/opt/anaconda3/envs/nzoo/lib/python3.7/site-packages/bigdl/dllib/utils/common.py", line 603, in callBigDlFunc
    result = callJavaFunc(api, *args)
  File "/opt/anaconda3/envs/nzoo/lib/python3.7/site-packages/bigdl/dllib/utils/common.py", line 656, in callJavaFunc
    result = func(*args)
  File "/opt/anaconda3/envs/nzoo/lib/python3.7/site-packages/pyspark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
  File "/opt/anaconda3/envs/nzoo/lib/python3.7/site-packages/pyspark/sql/utils.py", line 79, in deco
    raise IllegalArgumentException(s.split(': ', 1)[1], stackTrace)
pyspark.sql.utils.IllegalArgumentException: 'requirement failed: Engine.init: Can not find spark.shuffle.reduceLocality.enabled. For details please check https://bigdl-project.github.io/master/#APIGuide/Engine/'
```

**Comment by qiuxin2012** [comment]
@jason-dai I can't find why we need `spark.shuffle.reduceLocality.enabled`, maybe a bug in very old spark, can we remove this requirement?

**Comment by qiuxin2012** [comment]
Can we change the requirements to warnings?

**Comment by qiuxin2012** [comment]
Current requirements configuration:
```
spark.shuffle.reduceLocality.enabled false
spark.shuffle.blockTransferService nio
spark.scheduler.minRegisteredResourcesRatio 1.0
spark.scheduler.maxRegisteredResourcesWaitingTime 3600s
spark.speculation false
spark.serializer org.apache.spark.serializer.JavaSerializer
```

**Comment by jason-dai** [comment]
> Can we change the requirements to warnings?

+1 for change to warning

**Comment by qiuxin2012** [comment]
Fixed in #3366

**Comment by qiuxin2012** [comment]
After we change the conf requirement to warning, If user is using yarn, without `spark.scheduler.minRegisteredResourcesRatio         1.0 spark.scheduler.maxRegisteredResourcesWaitingTime   3600s`, our job will start when a part of yarn containers are ready, this is not what we want, we should also check the number of active containers in `Engine.init`.

**Comment by jason-dai** [comment]
> After we change the conf requirement to warning, If user is using yarn, without `spark.scheduler.minRegisteredResourcesRatio 1.0 spark.scheduler.maxRegisteredResourcesWaitingTime 3600s`, our job will start when a part of yarn containers are ready, this is not what we want, we should also check the number of active containers in `Engine.init`.

I think we should ask the user to add these configurations to their job server (when launching their spark context)

**Comment by qiuxin2012** [comment]
> > After we change the conf requirement to warning, If user is using yarn, without `spark.scheduler.minRegisteredResourcesRatio 1.0 spark.scheduler.maxRegisteredResourcesWaitingTime 3600s`, our job will start when a part of yarn containers are ready, this is not what we want, we should also check the number of active containers in `Engine.init`.
> 
> I think we should ask the user to add these configurations to their job server (when launching their spark context)

OK, I will add more information to the warning. For the yarn's configuration, we can check the `sc.getExecutorMemoryStatus` to make sure the existing executors == `num-executors`.
