### ISSUE TITLE
Copy byte data to BGRImage error

### ISSUE THREAD

**Issue by jenniew** [intel-analytics/BigDL#336]
Using DataSet.ImageFolder.image(path: Path, scaleTo: Int) to load images,  when copy sample data in BGRImage , get such exception:

ERROR ThreadPool$:106 - Error: java.lang.ArrayIndexOutOfBoundsException: 294920
	at com.intel.analytics.bigdl.dataset.image.BGRImage.copy(Types.scala:148)
	at com.intel.analytics.bigdl.dataset.image.SampleToBGRImg$$anonfun$apply$1.apply(SampleToBGRImg.scala:40)
	at com.intel.analytics.bigdl.dataset.image.SampleToBGRImg$$anonfun$apply$1.apply(SampleToBGRImg.scala:39)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
	at com.intel.analytics.bigdl.dataset.image.PreFetch$$anon$2.hasNext(MTLabeledBGRImgToBatch.scala:115)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
	at com.intel.analytics.bigdl.dataset.image.MTLabeledBGRImgToBatch$$anon$1$$anonfun$2$$anonfun$apply$1.apply$mcI$sp(MTLabeledBGRImgToBatch.scala:81)
	at com.intel.analytics.bigdl.dataset.image.MTLabeledBGRImgToBatch$$anon$1$$anonfun$2$$anonfun$apply$1.apply(MTLabeledBGRImgToBatch.scala:78)
	at com.intel.analytics.bigdl.dataset.image.MTLabeledBGRImgToBatch$$anon$1$$anonfun$2$$anonfun$apply$1.apply(MTLabeledBGRImgToBatch.scala:78)
	at com.intel.analytics.bigdl.utils.ThreadPool$$anonfun$invokeAndWait$1$$anonfun$apply$2.apply(Engine.scala:103)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)

Execution code is as below:

DataSet.ImageFolder.images(path, 256)
        .transform(
          MTLabeledBGRImgToBatch(
            width = imageSize,
            height = imageSize,
            batchSize = batchSize,
            transformer = BGRImgCropper(cropWidth = imageSize, cropHeight = imageSize)
              -> HFlip(0.5) -> BGRImgNormalizer(0.485, 0.456, 0.406, 0.229, 0.224, 0.225))
        )

**Comment by yiheng** [comment]
Can you provide some image files cause this problem? The piece of code works fine on ImageNet images. So I would like take a look at the images.

**Comment by jenniew** [comment]
I use flickr pictures. They are in different sizes. You can check data from gondolin-node-078:/disk7/flickr_style/images
