### ISSUE TITLE
[Yarn-test] Cluster Error: jep.JepException: <class 'ImportError'>

### ISSUE THREAD

**Issue by piaolaidelangman** [intel-analytics/BigDL#3610]
# [fashino_mnist.py](https://github.com/intel-analytics/BigDL/tree/branch-2.0/python/orca/example/learn/pytorch/fashion_mnist)
## Yarn-Cluster Exception
```
creating: createZooKerasAccuracy
creating: createEstimator
creating: createEveryEpoch
creating: createMaxEpoch
2021-11-27 05:17:21 INFO  DistriOptimizer$:824 - caching training rdd ...
2021-11-27 05:17:50 INFO  DistriOptimizer$:650 - Cache thread models...
2021-11-27 05:17:51 INFO  DistriOptimizer$:652 - Cache thread models... done
2021-11-27 05:17:51 INFO  DistriOptimizer$:162 - Count dataset
2021-11-27 05:18:04 INFO  DistriOptimizer$:166 - Count dataset complete. Time elapsed: 12.86615251s
2021-11-27 05:18:16 WARN  DistriOptimizer$:168 - If the dataset is built directly from RDD[Minibatch], the data in each minibatch is fixed, and a single minibatch is randomly selected in each partition. If the dataset is transformed from RDD[Sample], each minibatch will be constructed on the fly from random samples, which is better for convergence.
2021-11-27 05:18:16 INFO  DistriOptimizer$:174 - config  {
	computeThresholdbatchSize: 100
	maxDropPercentage: 0.0
	warmupIterationNum: 200
	isLayerwiseScaled: false
	dropPercentage: 0.0
 }
2021-11-27 05:18:16 INFO  DistriOptimizer$:178 - Shuffle data
2021-11-27 05:18:16 INFO  DistriOptimizer$:181 - Shuffle data complete. Takes 2.89354E-4s
2021-11-27 05:18:17 ERROR DistriOptimizer$:935 - Error: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intel.analytics.bigdl.dllib.keras.layers.utils.KerasUtils$.invokeMethod(KerasUtils.scala:302)
	at com.intel.analytics.bigdl.dllib.keras.layers.utils.KerasUtils$.invokeMethodWithEv(KerasUtils.scala:329)
	at com.intel.analytics.bigdl.dllib.keras.models.InternalOptimizerUtil$.optimizeModels(Topology.scala:710)
	at com.intel.analytics.bigdl.dllib.keras.models.InternalDistriOptimizer.train(Topology.scala:910)
	at com.intel.analytics.bigdl.dllib.keras.models.InternalDistriOptimizer.train(Topology.scala:1123)
	at com.intel.analytics.bigdl.dllib.keras.models.InternalDistriOptimizer.train(Topology.scala:793)
	at com.intel.analytics.bigdl.dllib.estimator.Estimator.train(Estimator.scala:190)
	at com.intel.analytics.bigdl.dllib.estimator.python.PythonEstimator.estimatorTrainMiniBatch(PythonEstimator.scala:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
Caused by: jep.JepException: jep.JepException: <class 'ImportError'>: /dir2/yarn/nm_0/usercache/root/appcache/application_1635129125298_1545/container_1635129125298_1545_02_000001/python_env/lib/python3.7/lib-dynload/
_posixsubprocess.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _Py_write_noraise
	at com.intel.analytics.bigdl.orca.utils.PythonInterpreter$.threadExecute(PythonInterpreter.scala:98)
	at com.intel.analytics.bigdl.orca.utils.PythonInterpreter$.exec(PythonInterpreter.scala:108)
	at com.intel.analytics.bigdl.orca.net.TorchOptim.optimType$lzycompute(TorchOptim.scala:55)
	at com.intel.analytics.bigdl.orca.net.TorchOptim.optimType(TorchOptim.scala:38)
	at com.intel.analytics.bigdl.orca.net.TorchOptim.updateHyperParameter(TorchOptim.scala:166)
	at com.intel.analytics.bigdl.dllib.optim.DistriOptimizer$$anonfun$optimize$5.apply(DistriOptimizer.scala:420)
	at com.intel.analytics.bigdl.dllib.optim.DistriOptimizer$$anonfun$optimize$5.apply(DistriOptimizer.scala:419)
	at scala.collection.immutable.Map$Map1.foreach(Map.scala:116)
	at com.intel.analytics.bigdl.dllib.optim.DistriOptimizer$.optimize(DistriOptimizer.scala:419)
	... 23 more
Caused by: jep.JepException: <class 'ImportError'>: /dir2/yarn/nm_0/usercache/root/appcache/application_1635129125298_1545/container_1635129125298_1545_02_000001/python_env/lib/python3.7/lib-dynload/_posixsubprocess.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _Py_write_noraise
	at /dir2/yarn/nm_0/usercache/root/appcache/application_1635129125298_1545/container_1635129125298_1545_02_000001/python_env/lib/python3.7/subprocess.<module>(subprocess.py:152)
	at /dir2/yarn/nm_0/usercache/root/appcache/application_1635129125298_1545/container_1635129125298_1545_02_000001/python_env/lib/python3.7/platform.<module>(platform.py:116)
	at /dir2/yarn/nm_0/usercache/root/appcache/application_1635129125298_1545/container_1635129125298_1545_02_000001/python_env/lib/python3.7/site-packages/torch/__init__.<module>(__init__.py:14)
	at <string>.<module>(<string>:2)
	at jep.Jep.exec(Native Method)
	at jep.Jep.exec(Jep.java:478)
	at com.intel.analytics.bigdl.orca.utils.PythonInterpreter$$anonfun$1.apply$mcV$sp(PythonInterpreter.scala:106)
	at com.intel.analytics.bigdl.orca.utils.PythonInterpreter$$anonfun$1.apply(PythonInterpreter.scala:105)
	at com.intel.analytics.bigdl.orca.utils.PythonInterpreter$$anonfun$1.apply(PythonInterpreter.scala:105)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more

Traceback (most recent call last):
  File "fashion_mnist.py", line 196, in <module>
    main()
  File "fashion_mnist.py", line 170, in main
    checkpoint_trigger=EveryEpoch())
  File "/dir2/yarn/nm_0/usercache/root/appcache/application_1635129125298_1545/container_1635129125298_1545_02_000001/python_env/lib/python3.7/site-packages/bigdl/orca/learn/pytorch/pytorch_spark_estimator.py", line 170, in fit
    checkpoint_trigger, val_fset, self.metrics)
  File "/dir2/yarn/nm_0/usercache/root/appcache/application_1635129125298_1545/container_1635129125298_1545_02_000001/python_env/lib/python3.7/site-packages/bigdl/dllib/estimator/estimator.py", line 167, in train_minibatch
    validation_method)
  File "/dir2/yarn/nm_0/usercache/root/appcache/application_1635129125298_1545/container_1635129125298_1545_02_000001/python_env/lib/python3.7/site-packages/bigdl/dllib/utils/file_utils.py", line 164, in callZooFunc
    raise e
  File "/dir2/yarn/nm_0/usercache/root/appcache/application_1635129125298_1545/container_1635129125298_1545_02_000001/python_env/lib/python3.7/site-packages/bigdl/dllib/utils/file_utils.py", line 158, in callZooFunc
    java_result = api(*args)
  File "/dir2/yarn/nm_0/usercache/root/appcache/application_1635129125298_1545/container_1635129125298_1545_02_000001/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
  File "/dir2/yarn/nm_0/usercache/root/appcache/application_1635129125298_1545/container_1635129125298_1545_02_000001/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o76.estimatorTrainMiniBatch.
: jep.JepException: jep.JepException: <class 'ImportError'>: /dir2/yarn/nm_0/usercache/root/appcache/application_1635129125298_1545/container_1635129125298_1545_02_000001/python_env/lib/python3.7/lib-dynload/_posixsubprocess.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _Py_write_noraise
	at com.intel.analytics.bigdl.orca.utils.PythonInterpreter$.threadExecute(PythonInterpreter.scala:98)
	at com.intel.analytics.bigdl.orca.utils.PythonInterpreter$.exec(PythonInterpreter.scala:108)
	at com.intel.analytics.bigdl.orca.net.TorchOptim.optimType$lzycompute(TorchOptim.scala:55)
	at com.intel.analytics.bigdl.orca.net.TorchOptim.optimType(TorchOptim.scala:38)
	at com.intel.analytics.bigdl.orca.net.TorchOptim.updateHyperParameter(TorchOptim.scala:166)
	at com.intel.analytics.bigdl.dllib.optim.DistriOptimizer$$anonfun$optimize$5.apply(DistriOptimizer.scala:420)
	at com.intel.analytics.bigdl.dllib.optim.DistriOptimizer$$anonfun$optimize$5.apply(DistriOptimizer.scala:419)
	at scala.collection.immutable.Map$Map1.foreach(Map.scala:116)
	at com.intel.analytics.bigdl.dllib.optim.DistriOptimizer$.optimize(DistriOptimizer.scala:419)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intel.analytics.bigdl.dllib.keras.layers.utils.KerasUtils$.invokeMethod(KerasUtils.scala:302)
	at com.intel.analytics.bigdl.dllib.keras.layers.utils.KerasUtils$.invokeMethodWithEv(KerasUtils.scala:329)
	at com.intel.analytics.bigdl.dllib.keras.models.InternalOptimizerUtil$.optimizeModels(Topology.scala:710)
	at com.intel.analytics.bigdl.dllib.keras.models.InternalDistriOptimizer.train(Topology.scala:910)
	at com.intel.analytics.bigdl.dllib.keras.models.InternalDistriOptimizer.train(Topology.scala:1123)
	at com.intel.analytics.bigdl.dllib.keras.models.InternalDistriOptimizer.train(Topology.scala:793)
	at com.intel.analytics.bigdl.dllib.estimator.Estimator.train(Estimator.scala:190)
	at com.intel.analytics.bigdl.dllib.estimator.python.PythonEstimator.estimatorTrainMiniBatch(PythonEstimator.scala:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
Caused by: jep.JepException: <class 'ImportError'>: /dir2/yarn/nm_0/usercache/root/appcache/application_1635129125298_1545/container_1635129125298_1545_02_000001/python_env/lib/python3.7/lib-dynload/_posixsubprocess.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _Py_write_noraise
	at /dir2/yarn/nm_0/usercache/root/appcache/application_1635129125298_1545/container_1635129125298_1545_02_000001/python_env/lib/python3.7/subprocess.<module>(subprocess.py:152)
	at /dir2/yarn/nm_0/usercache/root/appcache/application_1635129125298_1545/container_1635129125298_1545_02_000001/python_env/lib/python3.7/platform.<module>(platform.py:116)
	at /dir2/yarn/nm_0/usercache/root/appcache/application_1635129125298_1545/container_1635129125298_1545_02_000001/python_env/lib/python3.7/site-packages/torch/__init__.<module>(__init__.py:14)
	at <string>.<module>(<string>:2)
	at jep.Jep.exec(Native Method)
	at jep.Jep.exec(Jep.java:478)
	at com.intel.analytics.bigdl.orca.utils.PythonInterpreter$$anonfun$1.apply$mcV$sp(PythonInterpreter.scala:106)
	at com.intel.analytics.bigdl.orca.utils.PythonInterpreter$$anonfun$1.apply(PythonInterpreter.scala:105)
	at com.intel.analytics.bigdl.orca.utils.PythonInterpreter$$anonfun$1.apply(PythonInterpreter.scala:105)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more

Stopping orca context
```

**Comment by piaolaidelangman** [comment]
I found a related issue in https://github.com/pyscripter/python4delphi/issues/143

**Comment by bestfleer** [comment]
Hello, can you tell me how to fix this problem? I still met jep error with bigdl-2.0 version. Thanks for your help
