### ISSUE TITLE
[BigDL-NANO] TCN cannot run in pseudo-distributed mode

### ISSUE THREAD

**Issue by zhentaocc** [intel-analytics/BigDL#3737]
TCN fails to run when num_processes==16.
Steps to reproduce:
1.  code is in PR: https://github.com/analytics-zoo/chronos-benchmark/pull/6
2.  Prepare dataset and env as instructed in ReadMe
3.  cd forecaster && python forecaster_tcn_altran_bigdl.py --data_path "../../altran/stats_ue.csv" --num_process 16

Error message:
```
Traceback (most recent call last):
  File "forecaster_tcn_altran_bigdl.py", line 106, in <module>
    trainer.fit(forecaster_tcn, datamodule=data_module)
  File "/home/zhentaoc/anaconda3/envs/bigdl/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 552, in fit
    self._run(model)
  File "/home/zhentaoc/anaconda3/envs/bigdl/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 917, in _run
    self._dispatch()
  File "/home/zhentaoc/anaconda3/envs/bigdl/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 985, in _dispatch
    self.accelerator.start_training(self)
  File "/home/zhentaoc/anaconda3/envs/bigdl/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py", line 92, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/home/zhentaoc/anaconda3/envs/bigdl/lib/python3.7/site-packages/bigdl/nano/pytorch/plugins/ddp_spawn.py", line 129, in start_training
    start_processes_new(self.new_process, **self.mp_spawn_kwargs)
  File "/home/zhentaoc/anaconda3/envs/bigdl/lib/python3.7/site-packages/bigdl/nano/pytorch/plugins/ddp_spawn.py", line 78, in start_processes_new
    process.start()
  File "/home/zhentaoc/anaconda3/envs/bigdl/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/home/zhentaoc/anaconda3/envs/bigdl/lib/python3.7/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/home/zhentaoc/anaconda3/envs/bigdl/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/zhentaoc/anaconda3/envs/bigdl/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/home/zhentaoc/anaconda3/envs/bigdl/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/home/zhentaoc/anaconda3/envs/bigdl/lib/python3.7/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "/home/zhentaoc/anaconda3/envs/bigdl/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 134, in reduce_tensor
    raise RuntimeError("Cowardly refusing to serialize non-leaf tensor which requires_grad, "
RuntimeError: Cowardly refusing to serialize non-leaf tensor which requires_grad, since autograd does not support crossing process boundaries.  If you just want to transfer the data, call detach() on the tensor before serializing (e.g., putting it on the queue).
```

**Comment by zhentaocc** [comment]
Resolved.
