### ISSUE TITLE
Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)

### ISSUE THREAD

**Issue by 704572066** [intel-analytics/BigDL#3819]
```
[root@localhost cluster-serving]# vim servables-conf.yaml
[root@localhost cluster-serving]# java -jar bigdl-serving-spark_2.4.6-0.14.0-20211215.133535-82-http.jar
2021-12-29 20:05:04 INFO  FrontEndApp$:52 - starting with FrontEndAppArguments(0.0.0.0,10020,10023,localhost,6379,serving_stream,cluster-serving_serving_stream:,1000,0,0,false,100,100,false,null,1234qwer,false,null,1234qwer,./servables-conf.yaml)
2021-12-29 20:05:04 INFO  FrontEndApp$:32 - parse arguments time elapsed [14.519386 ms]
2021-12-29 20:05:04 INFO  FrontEndApp$:58 - Multi Serving Mode
2021-12-29 20:05:04 INFO  ClusterServingServable:32 - redis-putter-1-1.0 initialized. time elapsed [0.912877 ms]
2021-12-29 20:05:04 INFO  ClusterServingServable:32 - redis-getter-1-1.0 initialized. time elapsed [0.64315 ms]
2021-12-29 20:05:04 INFO  RedisPutActor:62 - redis-putter-1-1.0 connect to plain Redis successfully.
2021-12-29 20:05:04 INFO  RedisGetActor:62 - redis-getter-1-1.0 connect to plain Redis successfully.
2021-12-29 20:05:05 INFO  RedisGetActor:32 - redis-getter-1-1.0 retrieve redis connection time elapsed [25.838614 ms]
2021-12-29 20:05:05 INFO  RedisPutActor:32 - redis-putter-1-1.0 retrieve redis connection time elapsed [26.220285 ms]
2021-12-29 20:05:05 INFO  ClusterServingServable:32 - queriers initialized. time elapsed [71.244663 ms]
2021-12-29 20:05:05 INFO  ClusterServingServable:32 - redis-ioActor-getter-1-1.0 initialized. time elapsed [0.736883 ms]
2021-12-29 20:05:05 INFO  FrontEndApp$:32 - load servable manager time elapsed [300.703757 ms]
2021-12-29 20:05:05 INFO  FrontEndApp$:90 - Servable Manager Load Success!
2021-12-29 20:05:05 INFO  FrontEndApp$:32 - initialize http route time elapsed [48.849035 ms]
Exception in thread "main" java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)
        at java.security.Provider$Service.newInstance(Provider.java:1617)
        at sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
        at sun.security.jca.GetInstance.getInstance(GetInstance.java:164)
        at javax.net.ssl.SSLContext.getInstance(SSLContext.java:156)
        at javax.net.ssl.SSLContext.getDefault(SSLContext.java:96)
        at com.typesafe.sslconfig.ssl.Ciphers$.recommendedCiphers(Ciphers.scala:25)
        at com.typesafe.sslconfig.akka.AkkaSSLConfig.configureCipherSuites(AkkaSSLConfig.scala:192)
        at com.typesafe.sslconfig.akka.AkkaSSLConfig.<init>(AkkaSSLConfig.scala:90)
        at com.typesafe.sslconfig.akka.AkkaSSLConfig$.createExtension(AkkaSSLConfig.scala:29)
        at com.typesafe.sslconfig.akka.AkkaSSLConfig$.createExtension(AkkaSSLConfig.scala:19)
        at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:1006)
        at akka.actor.ExtensionId$class.apply(Extension.scala:79)
        at com.typesafe.sslconfig.akka.AkkaSSLConfig$.apply(AkkaSSLConfig.scala:24)
        at com.typesafe.sslconfig.akka.AkkaSSLConfig$.apply(AkkaSSLConfig.scala:19)
        at akka.http.scaladsl.HttpExt.<init>(Http.scala:79)
        at akka.http.scaladsl.Http$.createExtension(Http.scala:1123)
        at akka.http.scaladsl.Http$.createExtension(Http.scala:892)
        at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:1006)
        at akka.actor.ExtensionId$class.apply(Extension.scala:79)
        at akka.http.scaladsl.Http$.apply(Http.scala:1118)
        at com.intel.analytics.bigdl.serving.http.FrontEndApp$$anonfun$main$1.apply$mcV$sp(FrontEndApp.scala:295)
        at com.intel.analytics.bigdl.serving.http.FrontEndApp$$anonfun$main$1.apply(FrontEndApp.scala:49)
        at com.intel.analytics.bigdl.serving.http.FrontEndApp$$anonfun$main$1.apply(FrontEndApp.scala:49)
        at com.intel.analytics.bigdl.serving.http.Supportive$class.timing(Supportive.scala:28)
        at com.intel.analytics.bigdl.serving.http.FrontEndApp$.timing(FrontEndApp.scala:38)
        at com.intel.analytics.bigdl.serving.http.FrontEndApp$.main(FrontEndApp.scala:49)
        at com.intel.analytics.bigdl.serving.http.FrontEndApp.main(FrontEndApp.scala)
Caused by: java.security.KeyStoreException: problem accessing trust store
        at sun.security.ssl.TrustManagerFactoryImpl.engineInit(TrustManagerFactoryImpl.java:73)
        at javax.net.ssl.TrustManagerFactory.init(TrustManagerFactory.java:250)
        at sun.security.ssl.SSLContextImpl$DefaultManagersHolder.getTrustManagers(SSLContextImpl.java:1041)
        at sun.security.ssl.SSLContextImpl$DefaultManagersHolder.<clinit>(SSLContextImpl.java:1011)
        at sun.security.ssl.SSLContextImpl$DefaultSSLContext.<init>(SSLContextImpl.java:1186)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.security.Provider$Service.newInstance(Provider.java:1595)
        ... 26 more
Caused by: java.io.EOFException
        at java.io.DataInputStream.readInt(DataInputStream.java:392)
        at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:661)
        at sun.security.provider.JavaKeyStore$JKS.engineLoad(JavaKeyStore.java:57)
        at sun.security.provider.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:224)
        at sun.security.provider.JavaKeyStore$DualFormatJKS.engineLoad(JavaKeyStore.java:71)
        at java.security.KeyStore.load(KeyStore.java:1445)
        at sun.security.ssl.TrustStoreManager$TrustAnchorManager.loadKeyStore(TrustStoreManager.java:370)
        at sun.security.ssl.TrustStoreManager$TrustAnchorManager.getTrustedCerts(TrustStoreManager.java:318)
        at sun.security.ssl.TrustStoreManager.getTrustedCerts(TrustStoreManager.java:55)
        at sun.security.ssl.TrustManagerFactoryImpl.engineInit(TrustManagerFactoryImpl.java:49)
        ... 35 more

```

**Comment by Litchilitchy** [comment]
@704572066  Seems your ssl auth has some error. Have you tried non-ssl config?

**Comment by 704572066** [comment]
> @704572066 Seems your ssl auth has some error. Have you tried non-ssl config?

how to configure non-ssl

**Comment by Litchilitchy** [comment]
@704572066 Do you have a config.yaml in your working directory? could you post its content here?

**Comment by 704572066** [comment]
> @704572066 Do you have a config.yaml in your working directory? could you post its content here?

![image](https://user-images.githubusercontent.com/23404868/147807842-b2cbf0a6-a605-4ed8-aea6-2c665a26c804.png)

**Comment by Litchilitchy** [comment]
Could you also post the `servable-manager` in your log
```
2021-12-29 20:05:05 INFO  FrontEndApp$:32 - load servable manager time elapsed [300.703757 ms]
2021-12-29 20:05:05 INFO  FrontEndApp$:90 - Servable Manager Load Success!
```

**Comment by 704572066** [comment]
> Could you also post the `servable-manager` in your log
> 
> ```
> 2021-12-29 20:05:05 INFO  FrontEndApp$:32 - load servable manager time elapsed [300.703757 ms]
> 2021-12-29 20:05:05 INFO  FrontEndApp$:90 - Servable Manager Load Success!
> ```

![image](https://user-images.githubusercontent.com/23404868/147808182-fb303ff7-4ce9-4fdd-a55b-2904eaf91b7c.png)

**Comment by 704572066** [comment]
> Could you also post the `servable-manager` content in your log
> 
> ```
> 2021-12-29 20:05:05 INFO  FrontEndApp$:32 - load servable manager time elapsed [300.703757 ms]
> 2021-12-29 20:05:05 INFO  FrontEndApp$:90 - Servable Manager Load Success!
> ```

I have resolved the problem, just run the comand : yum update ca-certificates || sudo yum -y reinstall ca-certificates
