### ISSUE TITLE
load tf2.4 exported savedModel into bigdl 

### ISSUE THREAD

**Issue by limn2o4** [intel-analytics/BigDL#3848]
I currently using analytics-zoo 1.11 and I get a Op type not registered error

**Comment by limn2o4** [comment]
the complete err msg are below
	at org.tensorflow.SavedModelBundle.load(Native Method)
	at org.tensorflow.SavedModelBundle.access$000(SavedModelBundle.java:27)
	at org.tensorflow.SavedModelBundle$Loader.load(SavedModelBundle.java:32)
	at org.tensorflow.SavedModelBundle.load(SavedModelBundle.java:95)
	at com.intel.analytics.zoo.pipeline.api.net.TFNetForInference$.fromSavedModel(TFNetForInference.scala:237)
	at com.intel.analytics.zoo.pipeline.api.net.python.PythonZooNet.createTFNetFromSavedModel(PythonZooNet.scala:107)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:745)

**Comment by yangw1234** [comment]
Hi @limn2o4 , sorry I did not understand your question.

Would you mind stating more clearly about the problem you faced? What's the code you used and what's complete error message?
