### ISSUE TITLE
k8s cluster mode can not use *jar-with-dependencies.jar

### ISSUE THREAD

**Issue by Le-Zheng** [intel-analytics/BigDL#3966]
The downloaded assembly "/opt/bigdl-0.14.0-SNAPSHOT/jars/*" in k8s image can support cluster mode. However, using ”bigdl-*-spark_3.1.2-0.14.0-SNAPSHOT-jar-with-dependencies.jar“ failed with `'JavaPackage' object is not callable` on driver pod.

script.py:
```
from bigdl.dllib.nncontext import *
sc = init_nncontext("lenet example")
```
submit cmd
```
spark-submit \
--master k8s://https://172.16.0.200:6443 \
--deploy-mode cluster \
--conf spark.kubernetes.authenticate.driver.serviceAccountName=spark \
--conf spark.kubernetes.node.selector.spark=true \
--archives local:///bigdl2.0/data/environment_cluster.tar.gz#python_env \
--conf spark.pyspark.driver.python=python_env/bin/python \
--conf spark.pyspark.python=python_env/bin/python \
--conf spark.executorEnv.PYTHONHOME=python_env \
--conf spark.kubernetes.container.image=10.239.45.10/arda/intelanalytics/bigdl-k8s-spark-3.1.2:0.14.0-SNAPSHOT-20220127 \
--conf spark.executor.extraClassPath=python_env/lib/python3.7/site-packages/bigdl/share/dllib/lib/bigdl-dllib-spark_3.1.2-0.14.0-SNAPSHOT-jar-with-dependencies.jar \
--conf spark.driver.extraClassPath=python_env/lib/python3.7/site-packages/bigdl/share/dllib/lib/bigdl-dllib-spark_3.1.2-0.14.0-SNAPSHOT-jar-with-dependencies.jar \
local:///bigdl2.0/data/script.py 
```

```
22/02/07 23:03:38 INFO KubernetesClusterSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 1.0
Traceback (most recent call last):
  File "/bigdl2.0/data/spark_cluster.py", line 36, in <module>
    sc = init_nncontext("lenet example")
  File "/opt/spark/work-dir/python_env/lib/python3.7/site-packages/bigdl/dllib/nncontext.py", line 542, in init_nncontext
    sc = init_internal_nncontext(conf, spark_log_level, redirect_spark_log)
  File "/opt/spark/work-dir/python_env/lib/python3.7/site-packages/bigdl/dllib/nncontext.py", line 695, in init_internal_nncontext
    redire_spark_logs()
  File "/opt/spark/work-dir/python_env/lib/python3.7/site-packages/bigdl/dllib/utils/common.py", line 471, in redire_spark_logs
    callBigDlFunc(bigdl_type, "redirectSparkLogs", log_path)
  File "/opt/spark/work-dir/python_env/lib/python3.7/site-packages/bigdl/dllib/utils/common.py", line 617, in callBigDlFunc
    for jinvoker in JavaCreator.instance(bigdl_type, gateway).value:
  File "/opt/spark/work-dir/python_env/lib/python3.7/site-packages/bigdl/dllib/utils/common.py", line 56, in instance
    cls._instance = cls(bigdl_type, *args)
  File "/opt/spark/work-dir/python_env/lib/python3.7/site-packages/bigdl/dllib/utils/common.py", line 105, in __init__
    self.value.append(getattr(jclass, "ofFloat")())
TypeError: 'JavaPackage' object is not callable
```
On driver pod, the path "python_env/lib/python3.7/site-packages/bigdl/share/dllib/lib/bigdl-dllib-spark_3.1.2-0.14.0-SNAPSHOT-jar-with-dependencies.jar" is verified that exists.

**Comment by Tony-Feng** [comment]
I think I encountered this before. When I used a yaml file to config the job, I solved it by adding `--jar` option with `bigdl-dllib-spark_3.1.2-0.14.0-SNAPSHOT-jar-with-dependencies.jar` and its path. I presume it's similar here. Hope this could be helpful.

**Comment by Le-Zheng** [comment]
> Hi @Le-Zheng, I think I encountered this before. When I used a yaml file to config the job, I solved it by adding `--jar` option with `bigdl-dllib-spark_3.1.2-0.14.0-SNAPSHOT-jar-with-dependencies.jar` and its path. I presume it's similar here. Hope this could be helpful.

Hi Tony, many thanks for your advice. I tried to add `--jar` and the error shows `ERROR TaskSchedulerImpl: Lost an executor 1 (already removed): Unable to create executor due to /opt/spark/work-dir/python_env/lib/python3.7/site-packages/bigdl/share/dllib/lib/bigdl-dllib-spark_3.1.2-0.14.0-SNAPSHOT-jar-with-dependencies.jar`.
