### ISSUE TITLE
Nano quantization report AssertionError on the second time 

### ISSUE THREAD

**Issue by TheaperDeng** [intel-analytics/BigDL#4002]
Here is a minimal example:
```python
model = ResNet18(10, pretrained=False, include_top=False, freeze=True)
loss = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)
train_loader = create_data_loader(data_dir, batch_size, num_workers, data_transform)
trainer = Trainer(max_epochs=1)
pl_model = Trainer.compile(model, loss, optimizer)
qmodel = trainer.quantize(pl_model, train_loader, train_loader,
                              metric=torchmetrics.F1(10), framework='pytorch_fx',
                              approach='static',
                              tuning_strategy='basic',
                              accuracy_criterion={'relative': 0.99,
                                                  'higher_is_better': True})
qmodel = trainer.quantize(pl_model, train_loader, train_loader,
                              metric=torchmetrics.F1(10), framework='pytorch_fx',
                              approach='static',
                              tuning_strategy='basic',
                              accuracy_criterion={'relative': 0.99,
                                                  'higher_is_better': True})
```
it will report this on the second time.
```bash
Traceback (most recent call last):
  File "test.py", line 68, in <module>
    'higher_is_better': True})
  File "/home/junweid/BigDL/python/nano/src/bigdl/nano/pytorch/trainer/Trainer.py", line 239, in quantize
    metric)
  File "/home/junweid/BigDL/python/nano/src/bigdl/nano/quantization/neural_compressor/quantization.py", line 102, in post_training_quantize
    name="%s_%s" % (framework_metric.__name__, type(metric).__name__)
  File "/home/junweid/miniconda3/envs/chronos/lib/python3.7/site-packages/neural_compressor/experimental/quantization.py", line 287, in metric
    metrics.register(user_metric.name, user_metric.metric_cls)
  File "/home/junweid/miniconda3/envs/chronos/lib/python3.7/site-packages/neural_compressor/experimental/metric/metric.py", line 116, in register
    assert name not in self.metrics.keys(), 'registered metric name already exists.'
AssertionError: registered metric name already exists.
```

I am pretty sure this should be a INC issue, but we may have a look first. @zhentaocc

**Comment by zhentaocc** [comment]
It's not INC's problem. I think each call of `trainer.quantize(..)` will register the metric into INC as `F1`, so this is the reason.   
Maybe we should have better implementation in https://github.com/intel-analytics/BigDL/blob/branch-2.0/python/nano/src/bigdl/nano/quantization/neural_compressor/quantization.py#L90-L103.
