### ISSUE TITLE
java.lang.Error: Can't extract so file to /tmp dir when trying to run textClassifier example

### ISSUE THREAD

**Issue by lefromage** [intel-analytics/BigDL#401]
cd /Users/zz/Downloads/BigDL

BASE_DIR=/Users/zz/Downloads/BigDL/dl/src/main/scala/com/intel/analytics/bigdl/example/textclassification

./scripts/bigdl.sh -- spark-submit --master "local[*]" --driver-memory 20g                     \
>            --class com.intel.analytics.bigdl.example.textclassification.TextClassifier \
>            ./dl/target/bigdl-SPARK_2.0-0.1.0-SNAPSHOT-jar-with-dependencies-and-spark.jar --batchSize 128              \
>            --baseDir ${BASE_DIR} --partitionNum 4

Set engine type to mkl_blas
2017-01-20 15:36:57 INFO  TextClassifier$:246 - Current parameters: TextClassificationParams(/Users/zz/Downloads/BigDL/dl/src/main/scala/com/intel/analytics/bigdl/example/textclassification,1000,20000,0.8,128,100,4,1,4)

Exception in thread "main" java.lang.Error: Can't extract so file to /tmp dir
	at com.intel.analytics.bigdl.mkl.MKL.extract(MKL.java:175)
	at com.intel.analytics.bigdl.mkl.MKL.<clinit>(MKL.java:26)
	at com.intel.analytics.bigdl.utils.ThreadPool.setMKLThread(Engine.scala:82)
	at com.intel.analytics.bigdl.utils.Engine$.initModelThreadPool(Engine.scala:295)
	at com.intel.analytics.bigdl.utils.Engine$.<init>(Engine.scala:283)
	at com.intel.analytics.bigdl.utils.Engine$.<clinit>(Engine.scala)
	at com.intel.analytics.bigdl.example.textclassification.TextClassifier.train(TextClassifier.scala:149)
	at com.intel.analytics.bigdl.example.textclassification.TextClassifier$$anonfun$main$1.apply(TextClassifier.scala:248)
	at com.intel.analytics.bigdl.example.textclassification.TextClassifier$$anonfun$main$1.apply(TextClassifier.scala:245)
	at scala.Option.map(Option.scala:146)
	at com.intel.analytics.bigdl.example.textclassification.TextClassifier$.main(TextClassifier.scala:245)
	at com.intel.analytics.bigdl.example.textclassification.TextClassifier.main(TextClassifier.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:736)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:185)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:210)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:124)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

**Comment by jason-dai** [comment]
@lefromage are you running on linux or mac?

**Comment by lefromage** [comment]
mac
I found in the wiki that I needed to do:
bash make-dist.sh -P mac
now it seems to be working

but I have another issue, so I will close this one and open another.
Thanks
