### ISSUE TITLE
Ray worker died dealing with large dataset

### ISSUE THREAD

**Issue by marcomeng** [intel-analytics/BigDL#4502]
I was dealing with about 70,000,000 records with bigdl tensorflow:
after the predict, got following error:
It was ok when dealing with 1,000,000 record. I don't even know where to get the ray logs. I get following logs from yarn spark.

^[[2m^[[36m(Worker pid=24261, ip=10.21.0.111)^[[0m ^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^M2211/2211 [==============================] - ETA: 0s^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^M2211/2211 [==============================] - 653s 293ms/step
2022-04-26 00:04:39,922 WARNING worker.py:1245 -- A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: ffffffffffffffff0579da0d2425ba96a7c4971101000000 Worker ID: da8e1e4d01954542a5dd49205883cd9b33b8fcb0a3a39ca47cebc39c Node ID: 5d9293d71a06602c9e671d335fc97d9861829a892c801c21e358bfb9 Worker IP address: 10.21.0.101 Worker port: 15016 Worker PID: 213026
2022-04-26 00:04:41,250 WARNING worker.py:1245 -- A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: ffffffffffffffff0558a421c83d412fc832c63701000000 Worker ID: 16ad0953571a7ed548bf2c0af67e1f9c8a9fe22a2c81778d95990337 Node ID: 5d9293d71a06602c9e671d335fc97d9861829a892c801c21e358bfb9 Worker IP address: 10.21.0.101 Worker port: 15000 Worker PID: 208574
2022-04-26 00:04:46,388 WARNING worker.py:1245 -- A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: ffffffffffffffffcad68580f467933cafa0cda801000000 Worker ID: 7b2b2aa63edd0b153f9af6a0f7a9a0db4bb0130b34cde03eec8f82f7 Node ID: 3b9b972b2089acd7da2ffa001459a448300954cdb055b9ff39e18eb2 Worker IP address: 10.21.0.129 Worker port: 15019 Worker PID: 68184
2022-04-26 00:04:46,605 WARNING worker.py:1245 -- A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: ffffffffffffffffe6c831e032d42474220cf95501000000 Worker ID: 61505632d451868303adb0b5b2a360bd37dd8cc1cc21ed87eb25d7e2 Node ID: 5d9293d71a06602c9e671d335fc97d9861829a892c801c21e358bfb9 Worker IP address: 10.21.0.101 Worker port: 15005 Worker PID: 211943
2022-04-26 00:04:47,609 WARNING worker.py:1245 -- A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: ffffffffffffffff62a4874a63c033aaf44b236401000000 Worker ID: 5518d6f6d977304b40bea59bf6dea0bbb140c13e2ae8c6b8add0c2fc Node ID: 3b9b972b2089acd7da2ffa001459a448300954cdb055b9ff39e18eb2 Worker IP address: 10.21.0.129 Worker port: 15000 Worker PID: 63661
^[[2m^[[36m(Worker pid=102829, ip=10.21.0.133)^[[0m WARNING:tensorflow:/job:worker/replica:0/task:5 seems down, retrying 1/3
^[[2m^[[36m(Worker pid=102857, ip=10.21.0.133)^[[0m WARNING:tensorflow:/job:worker/replica:0/task:5 seems down, retrying 1/3
^[[2m^[[36m(Worker pid=38916, ip=10.21.0.126)^[[0m WARNING:tensorflow:/job:worker/replica:0/task:5 seems down, retrying 1/3

An error occurred while calling z:org.apache.spark.api.python.PythonRDD.collectAndServe.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 1297 in stage 24.0 failed 4 times, most recent failure: Lost task 1297.3 in stage 24.0 (TID 15129, 222f07-03-129, executor 50): org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/export1/yarn/local/usercache/bigdata/appcache/application_1650466476190_0555/container_e120_1650466476190_0555_01_000051/pyspark.zip/pyspark/worker.py", line 377, in main
    process()
  File "/export1/yarn/local/usercache/bigdata/appcache/application_1650466476190_0555/container_e120_1650466476190_0555_01_000051/pyspark.zip/pyspark/worker.py", line 372, in process
    serializer.dump_stream(func(split_index, iterator), outfile)
  File "/export/yarn/local/usercache/bigdata/appcache/application_1650466476190_0555/container_e120_1650466476190_0555_01_000001/environment/lib/python3.7/site-packages/bigdl/orca/data/ray_xshards.py", line 163, in <lambda>
  File "/export1/yarn/local/usercache/bigdata/appcache/application_1650466476190_0555/container_e120_1650466476190_0555_01_000051/environment/lib/python3.7/site-packages/bigdl/orca/data/ray_xshards.py", line 112, in get_from_ray
    local_store_handle = ray.get_actor(idx_to_store_name[idx])
  File "/export1/yarn/local/usercache/bigdata/appcache/application_1650466476190_0555/container_e120_1650466476190_0555_01_000051/environment/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/export1/yarn/local/usercache/bigdata/appcache/application_1650466476190_0555/container_e120_1650466476190_0555_01_000051/environment/lib/python3.7/site-packages/ray/worker.py", line 1925, in get_actor
    return worker.core_worker.get_named_actor_handle(name, namespace or "")
  File "python/ray/_raylet.pyx", line 1748, in ray._raylet.CoreWorker.get_named_actor_handle
  File "python/ray/_raylet.pyx", line 158, in ray._raylet.check_status
ValueError: Failed to look up actor with name 'partition:fd2af2e9-0a23-4ed0-b0c6-4477f03275c1:10.21.0.129'. This could because 1. You are trying to look up a named actor you didn't create. 2. The named actor died. 3. You did not use a namespace matching the namespace of the actor.

        at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.handlePythonException(PythonRunner.scala:456)
        at org.apache.spark.api.python.PythonRunner$$anon$1.read(PythonRunner.scala:592)
        at org.apache.spark.api.python.PythonRunner$$anon$1.read(PythonRunner.scala:575)
        at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.hasNext(PythonRunner.scala:410)
        at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
        at org.apache.spark.storage.memory.MemoryStore.putIterator(MemoryStore.scala:221)

**Comment by marcomeng** [comment]
I was able to find the ray error message in the raylet.out file

[2022-04-25 23:58:23,378 I 207881 207991] object_manager.cc:716: Received duplicate or cancelled chunk at index 185 of object 32e9c17d1eb874031e690bf6c578dbc83d3a320e0100000001000000: overall 1154/8156 failed
[2022-04-25 23:58:23,382 I 207881 207990] object_manager.cc:716: Received duplicate or cancelled chunk at index 190 of object 32e9c17d1eb874031e690bf6c578dbc83d3a320e0100000001000000: overall 1155/8157 failed
[2022-04-25 23:58:23,391 I 207881 207991] object_manager.cc:716: Received duplicate or cancelled chunk at index 198 of object 32e9c17d1eb874031e690bf6c578dbc83d3a320e0100000001000000: overall 1156/8158 failed
[2022-04-25 23:58:23,394 I 207881 207990] object_manager.cc:716: Received duplicate or cancelled chunk at index 202 of object 32e9c17d1eb874031e690bf6c578dbc83d3a320e0100000001000000: overall 1157/8159 failed
[2022-04-25 23:58:23,397 I 207881 207991] object_manager.cc:716: Received duplicate or cancelled chunk at index 195 of object 32e9c17d1eb874031e690bf6c578dbc83d3a320e0100000001000000: overall 1158/8160 failed

**Comment by yushan111** [comment]
Maybe your ray object-store memory is not sufficient for 70,000,000 records. You could try increasing `exra_executor_memory_for_ray` in `init_orca_context`.  
```python
from bigdl.orca import init_orca_context
init_orca_context(exra_executor_memory_for_ray=“100g”)
```
Besides, for debugging the memory issue, you could use the Ray dashboard to monitor memory usage. (You may find a hint like `View the Ray dashboard at http://127.0.0.1:8265
` in your log).

**Comment by marcomeng** [comment]
> 
I created 400 spark executor, and set executor-memory 6g, spark.yarn.executor.memoryOverhead=2G
does the exra_executor_memory_for_ray related to spark executor-memory? is it part of the spark executor-memory?
what's the best practice to set it?

**Comment by yushan111** [comment]
> Thanks, it worked.

Great!
