### ISSUE TITLE
BigDL on Apache Spark1.6.2 validation failed

### ISSUE THREAD

**Issue by kaiseu** [intel-analytics/BigDL#463]
BigDL on Apache Spark1.6.2 validation failed: 

17/02/14 16:41:09 INFO optim.DistriOptimizer$: [Wall Clock 889.551336265s] Validate model...
Exception in thread "dispatcher-event-loop-6" java.lang.NoSuchMethodError: org.apache.spark.util.Utils$.tryOrIOException(Lscala/Function0;)V
        at org.apache.spark.rdd.ZippedPartitionsLocalityPartition.writeObject(ZippedPartitionsWithLocalityRDD.scala:106)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1028)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
        at org.apache.spark.serializer.JavaSerializationStream.writeObject(JavaSerializer.scala:44)
        at org.apache.spark.serializer.JavaSerializerInstance.serialize(JavaSerializer.scala:101)
        at org.apache.spark.scheduler.Task$.serializeWithDependencies(Task.scala:211)
        at org.apache.spark.scheduler.TaskSetManager.resourceOffer(TaskSetManager.scala:460)
        at org.apache.spark.scheduler.TaskSchedulerImpl$$anonfun$org$apache$spark$scheduler$TaskSchedulerImpl$$resourceOfferSingleTaskSet$1.apply$mcVI$sp(TaskSchedulerImpl.scala:252)
        at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:141)
        at org.apache.spark.scheduler.TaskSchedulerImpl.org$apache$spark$scheduler$TaskSchedulerImpl$$resourceOfferSingleTaskSet(TaskSchedulerImpl.scala:247)
        at org.apache.spark.scheduler.TaskSchedulerImpl$$anonfun$resourceOffers$3$$anonfun$apply$8.apply(TaskSchedulerImpl.scala:317)
        at org.apache.spark.scheduler.TaskSchedulerImpl$$anonfun$resourceOffers$3$$anonfun$apply$8.apply(TaskSchedulerImpl.scala:315)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
        at org.apache.spark.scheduler.TaskSchedulerImpl$$anonfun$resourceOffers$3.apply(TaskSchedulerImpl.scala:315)
        at org.apache.spark.scheduler.TaskSchedulerImpl$$anonfun$resourceOffers$3.apply(TaskSchedulerImpl.scala:315)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
        at org.apache.spark.scheduler.TaskSchedulerImpl.resourceOffers(TaskSchedulerImpl.scala:315)
        at org.apache.spark.scheduler.cluster.CoarseGrainedSchedulerBackend$DriverEndpoint.org$apache$spark$scheduler$cluster$CoarseGrainedSchedulerBackend$DriverEndpoint$$makeOffers(CoarseGrainedSchedulerBackend.scala:200)
        at org.apache.spark.scheduler.cluster.CoarseGrainedSchedulerBackend$DriverEndpoint$$anonfun$receive$1.applyOrElse(CoarseGrainedSchedulerBackend.scala:123)
        at org.apache.spark.rpc.netty.Inbox$$anonfun$process$1.apply$mcV$sp(Inbox.scala:116)
        at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:204)
        at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:100)
        at org.apache.spark.rpc.netty.Dispatcher$MessageLoop.run(Dispatcher.scala:215)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

**Comment by jason-dai** [comment]
Are you using Scala 2.11? Have you built BigDL using Scala 2.11 (see https://github.com/intel-analytics/BigDL/wiki/Build-Page#build-using-scala-210-or-211)?

**Comment by kaiseu** [comment]
I just build with make-dist.sh, not add other parameters.

**Comment by jason-dai** [comment]
By default, make-dist.sh uses Scala 2.10 for Spark 1.5.x or 1.6.x, and Scala 2.11 for Spark 2.0. (See https://github.com/intel-analytics/BigDL/wiki/Build-Page#build-using-scala-210-or-211.) Which Scala version did you use to run the BigDL program, Scala 2.10 or 2.11?

**Comment by kaiseu** [comment]
Do you mean that Scala must be installed on each nodes of the cluster? I did not change anything after download the source code and build by using make-dist.sh. My cluster did not have Scala installed, but have JDK1.8, so would this cause some problem?
I noticed it's spark1.5.1 in the pom.xml but the scope is provided, so if I did not edit anything the default built out jar is based on what spark version? That is to say, how can BigDL know which spark version is used? The document only involved building parameters for spark2.0.

**Comment by zhichao-li** [comment]
@kaiseu, wondering what's the Scala version of the Spark you used? BigDL compile on top of Scala 2.10 by default, there might be problem if using Spark which compile against Scala 2.11.

**Comment by kaiseu** [comment]
I use Apache Spark1.6.2, so the Scala should be 2.10.

**Comment by yiheng** [comment]
@kaiseu are you trying an example when met this error? If so, can you provide me the command so I can repo in my env.

**Comment by yiheng** [comment]
@kaiseu I have summit a PR to fix this. Can you try the latest code?

**Comment by yiheng** [comment]
I see this is fixed in another issue https://github.com/intel-analytics/BigDL/issues/499. Close this issue.
