### ISSUE TITLE
the relationship between core/node and spark.executor.cores/executor instances

### ISSUE THREAD

**Issue by kaiseu** [intel-analytics/BigDL#465]
1+3 nodes cluster, each node with 64GB memory and below CPU cores,
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                32
On-line CPU(s) list:   0-31
Thread(s) per core:    2
Core(s) per socket:    8
Socket(s):             2
NUMA node(s):          2

spark.executor.memory=8g
spark.executor.cores=4

VGG failed with below configuration, 
spark-submit --class com.intel.analytics.bigdl.models.vgg.Train dist/lib/bigdl-0.1.0-SNAPSHOT-jar-with-dependencies.jar --core 1 --node 24 --env spark -f CIFAR-10/cifar-10-batches-bin/ -b 96

--core: The number of physical cores used in each executor (or container) of the Spark cluster.

--node: The number of executor (container) number of the Spark cluster. When running in Spark local mode, it should be set to 1.

the number of physical cores used in each executor here is 1, the umber of executor of the cluster is 24(8*3), so why it failed?

Exception in thread "main" org.apache.spark.SparkException: Job aborted due to stage failure: Task 3 in stage 13.0 failed 1 times, most recent failure: Lost task 3.0 in stage 13.0 (TID 35, qac8-node3): java.lang.IllegalArgumentException: requirement failed: Detect multi-task run on one Executor/Container. Please disable singleton check or repartition data
        at scala.Predef$.require(Predef.scala:233)
        at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$9.apply(DistriOptimizer.scala:367)
        at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$9.apply(DistriOptimizer.scala:363)
        at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
        at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
        at org.apache.spark.CacheManager.getOrCompute(CacheManager.scala:69)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:268)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
        at org.apache.spark.scheduler.Task.run(Task.scala:89)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:227)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

Driver stacktrace:
        at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1431)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1419)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1418)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
        at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1418)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:799)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:799)
        at scala.Option.foreach(Option.scala:236)
        at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:799)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1640)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1599)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1588)
        at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
        at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:620)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:1832)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:1845)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:1858)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:1929)
        at org.apache.spark.rdd.RDD.count(RDD.scala:1157)

**Comment by jason-dai** [comment]
Please use node_number = 3 and core_number = 3 (to match your Spark configurations).

**Comment by kaiseu** [comment]
can you explain why core_number=3 while spark.executor.cores=4?

**Comment by jason-dai** [comment]
Sorry - typo. You should set the core_number per spark.executor.cores (4 for your example) and node_number per number of Spark executors (3 for your example). See https://github.com/intel-analytics/BigDL/wiki/Getting-Started#known-issues.

**Comment by kaiseu** [comment]
So one physical node suggested to start one executor? How about one node but have multi executors? Thanks.

**Comment by jason-dai** [comment]
You can do that, but it is not recommended due to extra network overheads.
