### ISSUE TITLE
[Nano] tf.keras.Model error when call by functional usage

### ISSUE THREAD

**Issue by zhentaocc** [intel-analytics/BigDL#4748]
Script that will raise error:
```python
from bigdl.nano.tf.keras import Model
from tensorflow.keras.applications.mobilenet_v2 import MobileNetV2
model = MobileNetV2(weights=None, input_shape=[40, 40, 3], classes=10)
Model(inputs=model.inputs, outputs=model.outputs)
Model()
```
Error message:
```shell
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/zhentaoc/PycharmProjects/BigDL/python/nano/src/bigdl/nano/tf/keras/Model.py", line 25, in __init__
    super().__init__(*args, **kwargs)
  File "/home/zhentaoc/anaconda3/envs/BigDL/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py", line 530, in _method_wrapper
    result = method(self, *args, **kwargs)
TypeError: __init__() missing 2 required positional arguments: 'inputs' and 'outputs'
```

Original keras can run successfully with the same usage with no error:
```python
import tensorflow as tf
from tensorflow.keras.applications.mobilenet_v2 import MobileNetV2
model = MobileNetV2(weights=None, input_shape=[40, 40, 3], classes=10)
tf.keras.Model(inputs=model.inputs, outputs=model.outputs)
tf.keras.Model()
```
@yangw1234 any idea of this error?

**Comment by zhentaocc** [comment]
The real usage can be :
```python
from bigdl.nano.tf.keras import Model
from tensorflow.keras.applications.mobilenet_v2 import MobileNetV2
model = MobileNetV2(weights=None, input_shape=[40, 40, 3], classes=10)
model = Model(inputs=model.inputs, outputs=model.outputs)
class MyModel(Model):
    def __init__(self):
        super().__init__()
        self.dense1 = tf.keras.layers.Dense(4, activation=tf.nn.relu)
        self.dense2 = tf.keras.layers.Dense(5, activation=tf.nn.softmax)
        self.dropout = tf.keras.layers.Dropout(0.5)

    def call(self, inputs, training=False):
        x = self.dense1(inputs)
        if training:
            x = self.dropout(x, training=training)
        return self.dense2(x)
mymodel = MyModel()
```

**Comment by yangw1234** [comment]
It looks like tensorflow will automatically change our `Model`'s base class to `Functional` (which requires `inputs` and `outputs`) when called in functional style.
https://github.com/keras-team/keras/blob/v2.7.0/keras/engine/training.py#L200

One idea (although not thought through) to solve this problem is to write our own `__new__` method mimicking tensorflow's `Model` [link](https://github.com/keras-team/keras/blob/v2.7.0/keras/engine/training.py#L177-L182) with our own `Functional` class.
