### ISSUE TITLE
Error for Pytorch example using bigdl defalut backend on MAC

### ISSUE THREAD

**Issue by yexinyinancy** [intel-analytics/BigDL#4800]
I am running PyTorch example ([website](https://bigdl.readthedocs.io/en/latest/doc/Orca/QuickStart/orca-pytorch-quickstart.html)) on MAC, and I meet with the following error. The version of the packages I use are the same as the example.
torch_distributed backend can run successfully, but bigdl backend fails.

<img width="1327" alt="Screen Shot 2022-06-09 at 11 10 21" src="https://user-images.githubusercontent.com/51090416/172756136-68a3e62c-e19a-4095-8050-44e5ef2391de.png">

**Comment by hkvision** [comment]
@qiuxin2012 Please take a look.

**Comment by qiuxin2012** [comment]
I meet an error when init orca context on our mac:
Please take a look @glorysdj 
```
>>> init_orca_context(cores=4, memory="10g")
Initializing orca context
Current pyspark location is : /Users/arda/anaconda3/envs/py37-test/lib/python3.7/site-packages/pyspark/__init__.py
Start to getOrCreate SparkContext
pyspark_submit_args is:  --driver-class-path /Users/arda/anaconda3/envs/py37-test/lib/python3.7/site-packages/bigdl/share/dllib/lib/bigdl-dllib-spark_2.4.6-2.0.0-jar-with-dependencies.jar:/Users/arda/anaconda3/envs/py37-test/lib/python3.7/site-packages/bigdl/share/orca/lib/bigdl-orca-spark_2.4.6-2.0.0-jar-with-dependencies.jar pyspark-shell 
2022-06-13 09:11:35 WARN  Utils:66 - Your hostname, zoo-imac resolves to a loopback address: 127.0.1.1; using 10.239.33.7 instead (on interface en0)
2022-06-13 09:11:35 WARN  Utils:66 - Set SPARK_LOCAL_IP if you need to bind to another address
2022-06-13 09:11:36 WARN  NativeCodeLoader:62 - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
2022-06-13 09:11:37 WARN  Utils:66 - Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
2022-06-13 09:11:37 WARN  Utils:66 - Service 'SparkUI' could not bind on port 4041. Attempting port 4042.
2022-06-13 09:11:37 WARN  Utils:66 - Service 'SparkUI' could not bind on port 4042. Attempting port 4043.
2022-06-13 09:11:37 WARN  Utils:66 - Service 'SparkUI' could not bind on port 4043. Attempting port 4044.
2022-06-13 09:11:37 WARN  Utils:66 - Service 'SparkUI' could not bind on port 4044. Attempting port 4045.
2022-06-13 09:11:37 WARN  Utils:66 - Service 'SparkUI' could not bind on port 4045. Attempting port 4046.
2022-06-13 09:11:37 WARN  Utils:66 - Service 'SparkUI' could not bind on port 4046. Attempting port 4047.
2022-06-13 09:11:37 WARN  Utils:66 - Service 'SparkUI' could not bind on port 4047. Attempting port 4048.
2022-06-13 09:11:37 WARN  Utils:66 - Service 'SparkUI' could not bind on port 4048. Attempting port 4049.
2022-06-13 09:11:37 WARN  Utils:66 - Service 'SparkUI' could not bind on port 4049. Attempting port 4050.
2022-06-13 09:11:37 WARN  Utils:66 - Service 'SparkUI' could not bind on port 4050. Attempting port 4051.
2022-06-13 09:11:37 WARN  Utils:66 - Service 'SparkUI' could not bind on port 4051. Attempting port 4052.
2022-06-13 09:11:39,559 Thread-3 WARN The bufferSize is set to 4000 but bufferedIo is false: false
2022-06-13 09:11:39,561 Thread-3 ERROR FileManager (/Users/arda/bigdl.log) java.io.FileNotFoundException: /Users/arda/bigdl.log (Permission denied) java.io.FileNotFoundException: /Users/arda/bigdl.log (Permission denied)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at org.apache.logging.log4j.core.appender.FileManager$FileManagerFactory.createManager(FileManager.java:438)
	at org.apache.logging.log4j.core.appender.FileManager$FileManagerFactory.createManager(FileManager.java:422)
	at org.apache.logging.log4j.core.appender.AbstractManager.getManager(AbstractManager.java:114)
	at org.apache.logging.log4j.core.appender.OutputStreamManager.getManager(OutputStreamManager.java:100)
	at org.apache.logging.log4j.core.appender.FileManager.getFileManager(FileManager.java:182)
	at org.apache.logging.log4j.core.appender.FileAppender$Builder.build(FileAppender.java:96)
	at org.apache.logging.log4j.core.appender.FileAppender.createAppender(FileAppender.java:240)
	at com.intel.analytics.bigdl.dllib.utils.LoggerFilter$.com$intel$analytics$bigdl$dllib$utils$LoggerFilter$$fileAppender(LoggerFilter.scala:63)
	at com.intel.analytics.bigdl.dllib.utils.LoggerFilter$.redirectSparkInfoLogs(LoggerFilter.scala:155)
	at com.intel.analytics.bigdl.dllib.utils.python.api.PythonBigDL.redirectSparkLogs(PythonBigDL.scala:2697)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:745)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/arda/anaconda3/envs/py37-test/lib/python3.7/site-packages/bigdl/orca/common.py", line 246, in init_orca_context
    sc = init_spark_on_local(cores, **spark_args)
  File "/Users/arda/anaconda3/envs/py37-test/lib/python3.7/site-packages/bigdl/dllib/nncontext.py", line 53, in init_spark_on_local
    python_location=python_location)
  File "/Users/arda/anaconda3/envs/py37-test/lib/python3.7/site-packages/bigdl/dllib/utils/spark.py", line 61, in init_spark_on_local
    redirect_spark_log=self.redirect_spark_log)
  File "/Users/arda/anaconda3/envs/py37-test/lib/python3.7/site-packages/bigdl/dllib/nncontext.py", line 614, in init_internal_nncontext
    redire_spark_logs()
  File "/Users/arda/anaconda3/envs/py37-test/lib/python3.7/site-packages/bigdl/dllib/utils/common.py", line 471, in redire_spark_logs
    callBigDlFunc(bigdl_type, "redirectSparkLogs", log_path)
  File "/Users/arda/anaconda3/envs/py37-test/lib/python3.7/site-packages/bigdl/dllib/utils/common.py", line 626, in callBigDlFunc
    raise e
  File "/Users/arda/anaconda3/envs/py37-test/lib/python3.7/site-packages/bigdl/dllib/utils/common.py", line 622, in callBigDlFunc
    result = callJavaFunc(api, *args)
  File "/Users/arda/anaconda3/envs/py37-test/lib/python3.7/site-packages/bigdl/dllib/utils/common.py", line 675, in callJavaFunc
    result = func(*args)
  File "/Users/arda/anaconda3/envs/py37-test/lib/python3.7/site-packages/py4j/java_gateway.py", line 1257, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/Users/arda/anaconda3/envs/py37-test/lib/python3.7/site-packages/py4j/protocol.py", line 328, in get_return_value
    format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling o41.redirectSparkLogs.
: java.lang.IllegalStateException: ManagerFactory [org.apache.logging.log4j.core.appender.FileManager$FileManagerFactory@1d267ee9] unable to create manager for [/Users/arda/bigdl.log] with data [org.apache.logging.log4j.core.appender.FileManager$FactoryData@451d20cb]
	at org.apache.logging.log4j.core.appender.AbstractManager.getManager(AbstractManager.java:116)
	at org.apache.logging.log4j.core.appender.OutputStreamManager.getManager(OutputStreamManager.java:100)
	at org.apache.logging.log4j.core.appender.FileManager.getFileManager(FileManager.java:182)
	at org.apache.logging.log4j.core.appender.FileAppender$Builder.build(FileAppender.java:96)
	at org.apache.logging.log4j.core.appender.FileAppender.createAppender(FileAppender.java:240)
	at com.intel.analytics.bigdl.dllib.utils.LoggerFilter$.com$intel$analytics$bigdl$dllib$utils$LoggerFilter$$fileAppender(LoggerFilter.scala:63)
	at com.intel.analytics.bigdl.dllib.utils.LoggerFilter$.redirectSparkInfoLogs(LoggerFilter.scala:155)
	at com.intel.analytics.bigdl.dllib.utils.python.api.PythonBigDL.redirectSparkLogs(PythonBigDL.scala:2697)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by qiuxin2012** [comment]
> 

Happened when bigdl.log already exist, but user doesn't have writable permission.

**Comment by qiuxin2012** [comment]
I can't reproduce your error, it works fine on my test environment.
You can try to upgrade jep to 3.9.1

**Comment by qiuxin2012** [comment]
@yexinyinancy [step 2](https://bigdl.readthedocs.io/en/latest/doc/Orca/QuickStart/orca-pytorch-quickstart.html#step-2-define-the-model) 's indent is not write, could you help to fix it?
And add a default cluster_mode `local` in [step 1](https://bigdl.readthedocs.io/en/latest/doc/Orca/QuickStart/orca-pytorch-quickstart.html#step-2-define-the-model).

**Comment by hkvision** [comment]
> 

Fixed.

**Comment by hkvision** [comment]
This error on mac is not reproducible currently. Record here and may need to handle this if other users report this as well.
