### ISSUE TITLE
ray.tune.error.TuneError: ('Trials did not complete'

### ISSUE THREAD

**Issue by hjsybyq** [intel-analytics/BigDL#4895]
Traceback (most recent call last):
  File "test.py", line 64, in <module>
    metric="rmse")
  File "/root/miniconda3/envs/bigdl/lib/python3.7/site-packages/bigdl/orca/automl/xgboost/auto_xgb.py", line 266, in fit
    label_cols=label_cols)
  File "/root/miniconda3/envs/bigdl/lib/python3.7/site-packages/bigdl/orca/automl/auto_estimator.py", line 206, in fit
    self.searcher.run()
  File "/root/miniconda3/envs/bigdl/lib/python3.7/site-packages/bigdl/orca/automl/search/ray_tune/ray_tune_search_engine.py", line 198, in run
    reuse_actors=True
  File "/root/miniconda3/envs/bigdl/lib/python3.7/site-packages/ray/tune/tune.py", line 620, in run
    raise TuneError("Trials did not complete", incomplete_trials)
ray.tune.error.TuneError: ('Trials did not complete', [train_func_f3b19_00000, train_func_f3b19_00001, train_func_f3b19_00002, train_func_f3b19_00003, train_func_f3b19_00004, train_func_f3b19_00005])
Stopping orca context

**Comment by TheaperDeng** [comment]
Thanks for your feedback!

Could you please paste some script(if possible) you run and the error.txt? The path to error.txt can be found in the output:

Sample output:
Trial name | # failures | error file
-- | -- | --
train_func_19925_00004 | 1 | /tmp/autots_estimator/autots_estimator/train_func_19925_00004/error.txt

**Comment by hjsybyq** [comment]
Failure # 1 (occurred at 2022-06-21_14-39-05)
Traceback (most recent call last):
  File "/root/miniconda3/envs/bigdl/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 924, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "/root/miniconda3/envs/bigdl/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 787, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/root/miniconda3/envs/bigdl/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/bigdl/lib/python3.7/site-packages/ray/worker.py", line 1713, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(TuneError): ray::ImplicitFunc.train_buffered() (pid=30671, ip=192.168.11.151, repr=<types.ImplicitFunc object at 0x7f7861ecf9d0>)
  File "/data03/yarn/nm/usercache/root/appcache/application_1651919200149_0382/container_1651919200149_0382_01_000002/python_env/lib/python3.7/site-packages/ray/tune/trainable.py", line 255, in train_buffered
    result = self.train()
  File "/data03/yarn/nm/usercache/root/appcache/application_1651919200149_0382/container_1651919200149_0382_01_000002/python_env/lib/python3.7/site-packages/ray/tune/trainable.py", line 314, in train
    result = self.step()
  File "/data03/yarn/nm/usercache/root/appcache/application_1651919200149_0382/container_1651919200149_0382_01_000002/python_env/lib/python3.7/site-packages/ray/tune/function_runner.py", line 381, in step
    self._report_thread_runner_error(block=True)
  File "/data03/yarn/nm/usercache/root/appcache/application_1651919200149_0382/container_1651919200149_0382_01_000002/python_env/lib/python3.7/site-packages/ray/tune/function_runner.py", line 532, in _report_thread_runner_error
    ("Trial raised an exception. Traceback:\n{}".format(err_tb_str)
ray.tune.error.TuneError: Trial raised an exception. Traceback:
ray::ImplicitFunc.train_buffered() (pid=30671, ip=192.168.11.151, repr=<types.ImplicitFunc object at 0x7f7861ecf9d0>)
  File "/data03/yarn/nm/usercache/root/appcache/application_1651919200149_0382/container_1651919200149_0382_01_000002/python_env/lib/python3.7/site-packages/ray/tune/function_runner.py", line 262, in run
    self._entrypoint()
  File "/data03/yarn/nm/usercache/root/appcache/application_1651919200149_0382/container_1651919200149_0382_01_000002/python_env/lib/python3.7/site-packages/ray/tune/function_runner.py", line 331, in entrypoint
    self._status_reporter.get_checkpoint())
  File "/root/miniconda3/envs/bigdl/lib/python3.7/site-packages/ray/tune/function_runner.py", line 597, in _trainable_func
  File "/root/miniconda3/envs/bigdl/lib/python3.7/site-packages/bigdl/orca/automl/search/ray_tune/ray_tune_search_engine.py", line 364, in train_func
  File "/data03/yarn/nm/usercache/root/appcache/application_1651919200149_0382/container_1651919200149_0382_01_000002/python_env/lib/python3.7/site-packages/bigdl/orca/automl/search/utils.py", line 72, in put_ckpt_hdfs
    if remote_ckpt_basename not in get_remote_list(remote_dir):
  File "/data03/yarn/nm/usercache/root/appcache/application_1651919200149_0382/container_1651919200149_0382_01_000002/python_env/lib/python3.7/site-packages/bigdl/orca/automl/search/utils.py", line 47, in get_remote_list
    s_output, _ = process(args)
  File "/data03/yarn/nm/usercache/root/appcache/application_1651919200149_0382/container_1651919200149_0382_01_000002/python_env/lib/python3.7/site-packages/bigdl/orca/automl/search/utils.py", line 38, in process
    raise Exception(err)
Exception: ERROR: ld.so: object 'python_env/lib/libpython3.7m.so' from LD_PRELOAD cannot be preloaded: ignored.
/bin/sh: hdfs: command not found
/bin/sh: awk: command not found

**Comment by yushan111** [comment]
Thanks for your issue. 

We assumed that each yarn container can execute `hdfs` and `awk` command. A temporary solution might be adding your `hdfs` and `awk` path in `spark.executorEnv.PATH` of spark conf, and pass to `init_orca_context`. You may need to install `hdfs` and `awk` on all yarn cluster nodes if they are not installed.
 
```python
from bigdl.orca import init_orca_context
conf = {...,
        "spark.executorEnv.PATH": 
        }
init_orca_context(conf=conf)
```

We will also look into the solution to support automatically detecting `hdfs` without explicitly specified in `PATH`, and may add a fix for that later.

**Comment by hjsybyq** [comment]
thank you for your help,The problem  has been solved with having " /bin/sh: hdfs: command not found
/bin/sh: awk: command not found"

> Thanks for your issue.
> 
> We assumed that each yarn container can execute `hdfs` and `awk` command. A temporary solution might be adding your `hdfs` and `awk` path in `spark.executorEnv.PATH` of spark conf, and pass to `init_orca_context`. You may need to install `hdfs` and `awk` on all yarn cluster nodes if they are not installed.
> 
> ```python
> from bigdl.orca import init_orca_context
> conf = {...,
>         "spark.executorEnv.PATH": 
>         }
> init_orca_context(conf=conf)
> ```
> 
> We will also look into the solution to support automatically detecting `hdfs` without explicitly specified in `PATH`, and may add a fix for that later.
thank you for your help, The problem is solved with your solution "/bin/sh: hdfs: command not found
/bin/sh: awk: command not found",but "ray.tune.error.TuneError: ('Trials did not complete" still appears ,do you or anyone else have a solution for it?

**Comment by yushan111** [comment]
> thank you for your help,The problem has been solved with having " /bin/sh: hdfs: command not found /bin/sh: awk: command not found"

Great!
