### ISSUE TITLE
[OCRA] "ray start --head" can't run successfully. Corresponding， the code "init_orca_context(cores=10, init_ray_on_spark=True)" can't init successfully.

### ISSUE THREAD

**Issue by yangqing-yq** [intel-analytics/BigDL#4914]
In Redhat9.0 OS, Ubuntu20.04 container, run Chronos with orca(stable release 2.0),

"ray start --head"  can't run successfully.  

Corresponding， the code "init_orca_context(cores=10, init_ray_on_spark=True)" can't init successfully. 

So this lead to the test cases run fail.

**Comment by TheaperDeng** [comment]
Thanks for your feedback!

Could you please paste the error log here?

**Comment by yangqing-yq** [comment]
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
================================================================= short test summary info ==================================================================
FAILED test/bigdl/chronos/autots/test_autotsestimator.py::TestAutoTrainer::test_autogener_best_cycle_length - redis.exceptions.ConnectionError: Connectio...
FAILED test/bigdl/chronos/autots/test_autotsestimator.py::TestAutoTrainer::test_fit_lstm_data_creator - redis.exceptions.ConnectionError: Connection clos...
FAILED test/bigdl/chronos/autots/test_autotsestimator.py::TestAutoTrainer::test_fit_lstm_feature - redis.exceptions.ConnectionError: Connection closed by...
FAILED test/bigdl/chronos/autots/test_autotsestimator.py::TestAutoTrainer::test_fit_seq2seq_feature - redis.exceptions.ConnectionError: Connection closed...
FAILED test/bigdl/chronos/autots/test_autotsestimator.py::TestAutoTrainer::test_fit_tcn_feature - redis.exceptions.ConnectionError: Connection closed by ...
FAILED test/bigdl/chronos/autots/test_autotsestimator.py::TestAutoTrainer::test_fit_third_party_data_creator - redis.exceptions.ConnectionError: Connecti...
FAILED test/bigdl/chronos/autots/test_autotsestimator.py::TestAutoTrainer::test_fit_third_party_feature - redis.exceptions.ConnectionError: Connection cl...
FAILED test/bigdl/chronos/autots/test_autotsestimator.py::TestAutoTrainer::test_future_list_input - redis.exceptions.ConnectionError: Connection closed b...
FAILED test/bigdl/chronos/autots/test_autotsestimator.py::TestAutoTrainer::test_select_feature - redis.exceptions.ConnectionError: Connection closed by s...

**Comment by yangqing-yq** [comment]
sent via private email

**Comment by qiyuangong** [comment]
> ## full log sent via private email~
> Successfully got a SparkContext Traceback (most recent call last): File "autots-TCN-84-12-autosota-AvgRate+total.py", line 80, in init_orca_context(cores=10, init_ray_on_spark=True) File "/usr/local/python3.7/lib/python3.7/site-packages/bigdl/orca/common.py", line 324, in init_orca_context ray_ctx.init(driver_cores=driver_cores) File "/usr/local/python3.7/lib/python3.7/site-packages/bigdl/orca/ray/raycontext.py", line 58, in init results = self._ray_on_spark_context.init(driver_cores=driver_cores) File "/usr/local/python3.7/lib/python3.7/site-packages/bigdl/orca/ray/ray_on_spark_context.py", line 555, in init self._address_info = ray.init(**init_params) File "/usr/local/python3.7/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper return func(*args, **kwargs) File "/usr/local/python3.7/lib/python3.7/site-packages/ray/worker.py", line 912, in init ray_params=ray_params) File "/usr/local/python3.7/lib/python3.7/site-packages/ray/node.py", line 215, in **init** self.start_head_processes() File "/usr/local/python3.7/lib/python3.7/site-packages/ray/node.py", line 902, in start_head_processes self.start_redis() File "/usr/local/python3.7/lib/python3.7/site-packages/ray/node.py", line 717, in start_redis port_denylist=self._ray_params.reserved_ports) File "/usr/local/python3.7/lib/python3.7/site-packages/ray/_private/services.py", line 942, in start_redis listen_to_localhost_only=(node_ip_address == "127.0.0.1")) File "/usr/local/python3.7/lib/python3.7/site-packages/ray/_private/services.py", line 1133, in _start_redis_instance ulimit_n - redis_client_buffer) File "/usr/local/python3.7/lib/python3.7/site-packages/redis/commands/core.py", line 671, in config_set return self.execute_command("CONFIG SET", name, value, **kwargs) File "/usr/local/python3.7/lib/python3.7/site-packages/redis/client.py", line 1180, in execute_command lambda error: self._disconnect_raise(conn, error), File "/usr/local/python3.7/lib/python3.7/site-packages/redis/retry.py", line 48, in call_with_retry fail(error) File "/usr/local/python3.7/lib/python3.7/site-packages/redis/client.py", line 1180, in lambda error: self._disconnect_raise(conn, error), File "/usr/local/python3.7/lib/python3.7/site-packages/redis/client.py", line 1166, in _disconnect_raise raise error File "/usr/local/python3.7/lib/python3.7/site-packages/redis/retry.py", line 45, in call_with_retry return do() File "/usr/local/python3.7/lib/python3.7/site-packages/redis/client.py", line 1178, in conn, command_name, *args, **options File "/usr/local/python3.7/lib/python3.7/site-packages/redis/client.py", line 1153, in _send_command_parse_response return self.parse_response(conn, command_name, **options) File "/usr/local/python3.7/lib/python3.7/site-packages/redis/client.py", line 1192, in parse_response response = connection.read_response() File "/usr/local/python3.7/lib/python3.7/site-packages/redis/connection.py", line 814, in read_response response = self._parser.read_response(disable_decoding=disable_decoding) File "/usr/local/python3.7/lib/python3.7/site-packages/redis/connection.py", line 468, in read_response self.read_from_socket() File "/usr/local/python3.7/lib/python3.7/site-packages/redis/connection.py", line 428, in read_from_socket raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR) redis.exceptions.ConnectionError: Connection closed by server. Stopping orca context

This error message indicates that redis (started by Ray) cannot be connected. In init stage, Ray ty to start redis for storage, but Ray cannot connect to that redis server.

Please check if port 6379 is already in use. Also, need to check redis related conf.

BTW, can you provide example and conf you are using? In that case, we can reproduce this error in our local env. :)

**Comment by yushan111** [comment]
> "ray start --head" can't run successfully.

It seems to be an issue for Ray.

Could you try `ray start --node-ip-address <node_ip_address>` to see whether that works?

**Comment by yangqing-yq** [comment]
> > "ray start --head" can't run successfully.
> 
> It seems to be an issue for Ray.
> 
> Could you try `ray start --node-ip-address--node-ip-address  <node_ip_address>` to see whether that works?

it is not because the parameters --node-ip-address .
I change one parameter by following command,  then it can be launched  successfully ,  however, the code "init_orca_context(cores=10, init_ray_on_spark=True)" still failed, from the printing messages , it show  that "Exception: Failed to read dashbord log: [Errno 2] No such file or directory: '/tmp/ray/session_2022-06-23_07-45-22_407846_36/logs/dashboard.log'

the full printing message as following:
Successfully got a SparkContext
Traceback (most recent call last):
  File "autots-TCN-84-12-autosota-AvgRate+total-ori.py", line 80, in <module>
    init_orca_context(cores=10, init_ray_on_spark=True)
  File "/usr/local/python3.7/lib/python3.7/site-packages/bigdl/orca/common.py", line 324, in init_orca_context
    ray_ctx.init(driver_cores=driver_cores)
  File "/usr/local/python3.7/lib/python3.7/site-packages/bigdl/orca/ray/raycontext.py", line 58, in init
    results = self._ray_on_spark_context.init(driver_cores=driver_cores)
  File "/usr/local/python3.7/lib/python3.7/site-packages/bigdl/orca/ray/ray_on_spark_context.py", line 555, in init
    self._address_info = ray.init(**init_params)
  File "/usr/local/python3.7/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/python3.7/lib/python3.7/site-packages/ray/worker.py", line 912, in init
    ray_params=ray_params)
  File "/usr/local/python3.7/lib/python3.7/site-packages/ray/node.py", line 215, in __init__
    self.start_head_processes()
  File "/usr/local/python3.7/lib/python3.7/site-packages/ray/node.py", line 912, in start_head_processes
    self.start_dashboard(require_dashboard=True)
  File "/usr/local/python3.7/lib/python3.7/site-packages/ray/node.py", line 759, in start_dashboard
    port=self._ray_params.dashboard_port)
  File "/usr/local/python3.7/lib/python3.7/site-packages/ray/_private/services.py", line 1345, in start_dashboard
    raise e from e
  File "/usr/local/python3.7/lib/python3.7/site-packages/ray/_private/services.py", line 1332, in start_dashboard
    raise Exception(f"Failed to read dashbord log: {e}")
Exception: Failed to read dashbord log: [Errno 2] No such file or directory: '/tmp/ray/session_2022-06-23_07-45-22_407846_36/logs/dashboard.log'
Stopping orca context

**Comment by yangqing-yq** [comment]
issue fixed.
