### ISSUE TITLE
[ORCA]: cannot find the state.pkl file with the spark backend and yarn cluster_mode

### ISSUE THREAD

**Issue by ForJadeForest** [intel-analytics/BigDL#4929]
I try to run the orca example `brainMRI` with the `spark` as `backend` and `yarn-client` as `cluster_mode`. For the `model_dir` parameter in `Estimator.from_torch`, I choose the `./`, `file:/// + os.getcwd()`, and `hdfs://`. But  all of them can not save the model. 

### The Python Code
```python

orca_estimator = Estimator.from_torch(model=model_creator,
                                        optimizer=optim_creator,
                                        loss=loss_creator,
                                        metrics=[Accuracy()],
                                        model_dir='file:///' + os.getcwd(),
                                        backend=args.backend,
                                        config=config,
                                        use_tqdm=True
                                        )

orca_estimator.fit(data=train_loader_creator, epochs=args.epochs, batch_size=batch_size)
```

### error information
For the `./`
```
Traceback (most recent call last):
  File "brainMRI4.py", line 173, in <module>
    orca_estimator.fit(data=train_loader_creator, epochs=args.epochs, batch_size=batch_size)
  File "/home/kai/anaconda3/envs/pyz/lib/python3.7/site-packages/bigdl/orca/learn/pytorch/pytorch_pyspark_estimator.py", line 262, in fit
    self.state_dict = PyTorchPySparkEstimator._get_state_dict_from_remote(self.model_dir)
  File "/home/kai/anaconda3/envs/pyz/lib/python3.7/site-packages/bigdl/orca/learn/pytorch/pytorch_pyspark_estimator.py", line 282, in _get_state_dict_from_remote
    over_write=True)
  File "/home/kai/anaconda3/envs/pyz/lib/python3.7/site-packages/bigdl/dllib/utils/file_utils.py", line 146, in get_remote_file_to_local
    callZooFunc("float", "getRemoteFileToLocal", remote_path, local_path, over_write)
  File "/home/kai/anaconda3/envs/pyz/lib/python3.7/site-packages/bigdl/dllib/utils/file_utils.py", line 227, in callZooFunc
    raise e
  File "/home/kai/anaconda3/envs/pyz/lib/python3.7/site-packages/bigdl/dllib/utils/file_utils.py", line 221, in callZooFunc
    java_result = api(*args)
  File "/home/kai/anaconda3/envs/pyz/lib/python3.7/site-packages/py4j/java_gateway.py", line 1257, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/home/kai/anaconda3/envs/pyz/lib/python3.7/site-packages/py4j/protocol.py", line 328, in get_return_value
    format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling o61.getRemoteFileToLocal.

```
For the `'file:///' + os.getcwd()`
```
org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/disk4/yarn/nm/usercache/root/appcache/application_1646614241228_0923/container_1646614241228_0923_01_000002/pyspark.zip/pyspark/worker.py", line 377, in main
    process()
  File "/disk4/yarn/nm/usercache/root/appcache/application_1646614241228_0923/container_1646614241228_0923_01_000002/pyspark.zip/pyspark/worker.py", line 372, in process
    serializer.dump_stream(func(split_index, iterator), outfile)
  File "/home/kai/anaconda3/envs/pyz/lib/python3.7/site-packages/pyspark/rdd.py", line 2465, in func
  File "/home/kai/anaconda3/envs/pyz/lib/python3.7/site-packages/bigdl/orca/learn/pytorch/pytorch_pyspark_estimator.py", line 260, in <lambda>
  File "/home/kai/anaconda3/envs/pyz/lib/python3.7/site-packages/bigdl/orca/learn/pytorch/pytorch_pyspark_estimator.py", line 257, in transform_func
  File "/disk4/yarn/nm/usercache/root/appcache/application_1646614241228_0923/container_1646614241228_0923_01_000002/python_env/lib/python3.7/site-packages/bigdl/orca/learn/pytorch/pytorch_pyspark_worker.py", line 133, in train_epochs
    save_pkl(state_dict, os.path.join(self.model_dir, "state.pkl"))
  File "/disk4/yarn/nm/usercache/root/appcache/application_1646614241228_0923/container_1646614241228_0923_01_000002/python_env/lib/python3.7/site-packages/bigdl/orca/learn/utils.py", line 380, in save_pkl
    with open(path, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '//home/kai/brain/state.pkl'


Traceback (most recent call last):
  File "brainMRI4.py", line 173, in <module>
    orca_estimator.fit(data=train_loader_creator, epochs=args.epochs, batch_size=batch_size)
  File "/home/kai/anaconda3/envs/pyz/lib/python3.7/site-packages/bigdl/orca/learn/pytorch/pytorch_pyspark_estimator.py", line 260, in fit
    lambda iter: transform_func(iter, init_params, params)).collect()
  File "/home/kai/anaconda3/envs/pyz/lib/python3.7/site-packages/pyspark/rdd.py", line 816, in collect
    sock_info = self.ctx._jvm.PythonRDD.collectAndServe(self._jrdd.rdd())
  File "/home/kai/anaconda3/envs/pyz/lib/python3.7/site-packages/py4j/java_gateway.py", line 1257, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/home/kai/anaconda3/envs/pyz/lib/python3.7/site-packages/py4j/protocol.py", line 328, in get_return_value
    format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.collectAndServe.
: org.apache.spark.SparkException: Job aborted due to stage failure: Could not recover from a failed barrier ResultStage. Most recent failure reason: Stage failed because barrier task ResultTask(5, 0) finished unsuccessfully.
org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/disk4/yarn/nm/usercache/root/appcache/application_1646614241228_0923/container_1646614241228_0923_01_000002/pyspark.zip/pyspark/worker.py", line 377, in main
    process()
  File "/disk4/yarn/nm/usercache/root/appcache/application_1646614241228_0923/container_1646614241228_0923_01_000002/pyspark.zip/pyspark/worker.py", line 372, in process
    serializer.dump_stream(func(split_index, iterator), outfile)
  File "/home/kai/anaconda3/envs/pyz/lib/python3.7/site-packages/pyspark/rdd.py", line 2465, in func
  File "/home/kai/anaconda3/envs/pyz/lib/python3.7/site-packages/bigdl/orca/learn/pytorch/pytorch_pyspark_estimator.py", line 260, in <lambda>
  File "/home/kai/anaconda3/envs/pyz/lib/python3.7/site-packages/bigdl/orca/learn/pytorch/pytorch_pyspark_estimator.py", line 257, in transform_func
  File "/disk4/yarn/nm/usercache/root/appcache/application_1646614241228_0923/container_1646614241228_0923_01_000002/python_env/lib/python3.7/site-packages/bigdl/orca/learn/pytorch/pytorch_pyspark_worker.py", line 133, in train_epochs
    save_pkl(state_dict, os.path.join(self.model_dir, "state.pkl"))
  File "/disk4/yarn/nm/usercache/root/appcache/application_1646614241228_0923/container_1646614241228_0923_01_000002/python_env/lib/python3.7/site-packages/bigdl/orca/learn/utils.py", line 380, in save_pkl
    with open(path, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '//home/kai/brain/state.pkl'
```

For the `hdfs`
```
TaskSetManager:66 - Lost task 0.0 in stage 5.0 (TID 20, Almaren-Node-131, executor 1): org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/disk2/yarn/nm/usercache/root/appcache/application_1646614241228_0924/container_1646614241228_0924_01_000002/pyspark.zip/pyspark/worker.py", line 377, in main
    process()
  File "/disk2/yarn/nm/usercache/root/appcache/application_1646614241228_0924/container_1646614241228_0924_01_000002/pyspark.zip/pyspark/worker.py", line 372, in process
    serializer.dump_stream(func(split_index, iterator), outfile)
  File "/home/kai/anaconda3/envs/pyz/lib/python3.7/site-packages/pyspark/rdd.py", line 2465, in func
  File "/home/kai/anaconda3/envs/pyz/lib/python3.7/site-packages/bigdl/orca/learn/pytorch/pytorch_pyspark_estimator.py", line 260, in <lambda>
  File "/home/kai/anaconda3/envs/pyz/lib/python3.7/site-packages/bigdl/orca/learn/pytorch/pytorch_pyspark_estimator.py", line 257, in transform_func
  File "/disk2/yarn/nm/usercache/root/appcache/application_1646614241228_0924/container_1646614241228_0924_01_000002/python_env/lib/python3.7/site-packages/bigdl/orca/learn/pytorch/pytorch_pyspark_worker.py", line 133, in train_epochs
    save_pkl(state_dict, os.path.join(self.model_dir, "state.pkl"))
  File "/disk2/yarn/nm/usercache/root/appcache/application_1646614241228_0924/container_1646614241228_0924_01_000002/python_env/lib/python3.7/site-packages/bigdl/orca/learn/utils.py", line 362, in save_pkl
    fs = pa.hdfs.connect(host=host_port[0], port=int(host_port[1]))
  File "/disk2/yarn/nm/usercache/root/appcache/application_1646614241228_0924/container_1646614241228_0924_01_000002/python_env/lib/python3.7/site-packages/pyarrow/hdfs.py", line 229, in connect
    extra_conf=extra_conf
  File "/disk2/yarn/nm/usercache/root/appcache/application_1646614241228_0924/container_1646614241228_0924_01_000002/python_env/lib/python3.7/site-packages/pyarrow/hdfs.py", line 239, in _connect
    extra_conf=extra_conf)
  File "/disk2/yarn/nm/usercache/root/appcache/application_1646614241228_0924/container_1646614241228_0924_01_000002/python_env/lib/python3.7/site-packages/pyarrow/hdfs.py", line 49, in __init__
    self._connect(host, port, user, kerb_ticket, extra_conf)
  File "pyarrow/_hdfsio.pyx", line 85, in pyarrow._hdfsio.HadoopFileSystem._connect
  File "pyarrow/error.pxi", line 115, in pyarrow.lib.check_status
OSError: Unable to load libhdfs: ./libhdfs.so: cannot open shared object file: No such file or directory


Traceback (most recent call last):
  File "brainMRI4.py", line 173, in <module>
    orca_estimator.fit(data=train_loader_creator, epochs=args.epochs, batch_size=batch_size)
  File "/home/kai/anaconda3/envs/pyz/lib/python3.7/site-packages/bigdl/orca/learn/pytorch/pytorch_pyspark_estimator.py", line 260, in fit
    lambda iter: transform_func(iter, init_params, params)).collect()
  File "/home/kai/anaconda3/envs/pyz/lib/python3.7/site-packages/pyspark/rdd.py", line 816, in collect
    sock_info = self.ctx._jvm.PythonRDD.collectAndServe(self._jrdd.rdd())
  File "/home/kai/anaconda3/envs/pyz/lib/python3.7/site-packages/py4j/java_gateway.py", line 1257, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/home/kai/anaconda3/envs/pyz/lib/python3.7/site-packages/py4j/protocol.py", line 328, in get_return_value
    format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.collectAndServe.
: org.apache.spark.SparkException: Job aborted due to stage failure: Could not recover from a failed barrier ResultStage. Most recent failure reason: Stage failed because barrier task ResultTask(5, 0) finished unsuccessfully.
org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/disk2/yarn/nm/usercache/root/appcache/application_1646614241228_0924/container_1646614241228_0924_01_000002/pyspark.zip/pyspark/worker.py", line 377, in main
    process()
  File "/disk2/yarn/nm/usercache/root/appcache/application_1646614241228_0924/container_1646614241228_0924_01_000002/pyspark.zip/pyspark/worker.py", line 372, in process
    serializer.dump_stream(func(split_index, iterator), outfile)
  File "/home/kai/anaconda3/envs/pyz/lib/python3.7/site-packages/pyspark/rdd.py", line 2465, in func
  File "/home/kai/anaconda3/envs/pyz/lib/python3.7/site-packages/bigdl/orca/learn/pytorch/pytorch_pyspark_estimator.py", line 260, in <lambda>
  File "/home/kai/anaconda3/envs/pyz/lib/python3.7/site-packages/bigdl/orca/learn/pytorch/pytorch_pyspark_estimator.py", line 257, in transform_func
  File "/disk2/yarn/nm/usercache/root/appcache/application_1646614241228_0924/container_1646614241228_0924_01_000002/python_env/lib/python3.7/site-packages/bigdl/orca/learn/pytorch/pytorch_pyspark_worker.py", line 133, in train_epochs
    save_pkl(state_dict, os.path.join(self.model_dir, "state.pkl"))
  File "/disk2/yarn/nm/usercache/root/appcache/application_1646614241228_0924/container_1646614241228_0924_01_000002/python_env/lib/python3.7/site-packages/bigdl/orca/learn/utils.py", line 362, in save_pkl
    fs = pa.hdfs.connect(host=host_port[0], port=int(host_port[1]))
  File "/disk2/yarn/nm/usercache/root/appcache/application_1646614241228_0924/container_1646614241228_0924_01_000002/python_env/lib/python3.7/site-packages/pyarrow/hdfs.py", line 229, in connect
    extra_conf=extra_conf
  File "/disk2/yarn/nm/usercache/root/appcache/application_1646614241228_0924/container_1646614241228_0924_01_000002/python_env/lib/python3.7/site-packages/pyarrow/hdfs.py", line 239, in _connect
    extra_conf=extra_conf)
  File "/disk2/yarn/nm/usercache/root/appcache/application_1646614241228_0924/container_1646614241228_0924_01_000002/python_env/lib/python3.7/site-packages/pyarrow/hdfs.py", line 49, in __init__
    self._connect(host, port, user, kerb_ticket, extra_conf)
  File "pyarrow/_hdfsio.pyx", line 85, in pyarrow._hdfsio.HadoopFileSystem._connect
  File "pyarrow/error.pxi", line 115, in pyarrow.lib.check_status
OSError: Unable to load libhdfs: ./libhdfs.so: cannot open shared object file: No such file or directory

```

### Target
I want to know how can I save the model successfully.

**Comment by hkvision** [comment]
@yushan111 @sgwhat Could you take a look at this issue?

**Comment by sgwhat** [comment]
`file://` instead of `file:///`

**Comment by yushan111** [comment]
`model_dir` should be a remote path in yarn cluster mode, so only `hdfs://` should work.

For `OSError: Unable to load libhdfs: ./libhdfs.so: cannot open shared object file: No such file or directory`
Potential solution:
```
1. use locate libhdfs.so to find libhdfs.so
2. export ARROW_LIBHDFS_DIR=/opt/cloudera/parcels/CDH-5.15.2-1.cdh5.15.2.p0.3/lib64 (replace with the result of locate libhdfs.so)
3. use --conf "spark.executorEnv.ARROW_LIBHDFS_DIR=/opt/cloudera/parcels/CDH-5.15.2-1.cdh5.15.2.p0.3/lib64" to export the environment variable to all executors.
```
If that works in yarn cluster_mode, I will add the solution to Orca Known Issues.

**Comment by ForJadeForest** [comment]
> `model_dir` should be a remote path in yarn cluster mode, so only `hdfs://` should work.
> 
> For `OSError: Unable to load libhdfs: ./libhdfs.so: cannot open shared object file: No such file or directory` Potential solution:
> 
> ```
> 1. use locate libhdfs.so to find libhdfs.so
> 2. export ARROW_LIBHDFS_DIR=/opt/cloudera/parcels/CDH-5.15.2-1.cdh5.15.2.p0.3/lib64 (replace with the result of locate libhdfs.so)
> 3. use --conf "spark.executorEnv.ARROW_LIBHDFS_DIR=/opt/cloudera/parcels/CDH-5.15.2-1.cdh5.15.2.p0.3/lib64" to export the environment variable to all executors.
> ```
> 
> If that works in yarn cluster_mode, I will add the solution to Orca Known Issues.

Where I use the --conf? Does it mean `spark-submit --conf "spark.executorEnv.ARROW_LIBHDFS_DIR=/opt/cloudera/parcels/CDH-5.15.2-1.cdh5.15.2.p0.3/lib64"`?

**Comment by sgwhat** [comment]
> > `model_dir` should be a remote path in yarn cluster mode, so only `hdfs://` should work.
> > For `OSError: Unable to load libhdfs: ./libhdfs.so: cannot open shared object file: No such file or directory` Potential solution:
> > ```
> > 1. use locate libhdfs.so to find libhdfs.so
> > 2. export ARROW_LIBHDFS_DIR=/opt/cloudera/parcels/CDH-5.15.2-1.cdh5.15.2.p0.3/lib64 (replace with the result of locate libhdfs.so)
> > 3. use --conf "spark.executorEnv.ARROW_LIBHDFS_DIR=/opt/cloudera/parcels/CDH-5.15.2-1.cdh5.15.2.p0.3/lib64" to export the environment variable to all executors.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If that works in yarn cluster_mode, I will add the solution to Orca Known Issues.
> 
> Where I use the --conf? Does it mean `spark-submit --conf "spark.executorEnv.ARROW_LIBHDFS_DIR=/opt/cloudera/parcels/CDH-5.15.2-1.cdh5.15.2.p0.3/lib64"`?

yes, `spark-submit --conf spark.executorEnv.ARROW_LIBHDFS_DIR=/opt/cloudera/parcels/CDH-5.15.2-1.cdh5.15.2.p0.3/lib64`

**Comment by yushan111** [comment]
If you are using `init_orca_context(cluster_mode="yarn-cluster")`, 
```python
conf = {"spark.executorEnv.ARROW_LIBHDFS_DIR": "/output/of/locate/libhdfs.so"}
init_orca_context(cluster_mode="yarn-cluster", conf=conf)
```


If you are using `init_orca_context(cluster_mode="spark-submit")`,
then yes,  you could add it to `spark-submit --conf`

**Comment by ForJadeForest** [comment]
I use the `yarn-client` as the `cluster_mode`.  And I add the `conf` parameter then occur the error
```
org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/disk2/yarn/nm/usercache/root/appcache/application_1646614241228_0932/container_1646614241228_0932_01_000002/pyspark.zip/pyspark/worker.py", line 377, in main
    process()
  File "/disk2/yarn/nm/usercache/root/appcache/application_1646614241228_0932/container_1646614241228_0932_01_000002/pyspark.zip/pyspark/worker.py", line 372, in process
    serializer.dump_stream(func(split_index, iterator), outfile)
  File "/home/kai/anaconda3/envs/pyz/lib/python3.7/site-packages/pyspark/rdd.py", line 2465, in func
  File "/home/kai/anaconda3/envs/pyz/lib/python3.7/site-packages/bigdl/orca/learn/pytorch/pytorch_pyspark_estimator.py", line 260, in <lambda>
  File "/home/kai/anaconda3/envs/pyz/lib/python3.7/site-packages/bigdl/orca/learn/pytorch/pytorch_pyspark_estimator.py", line 257, in transform_func
  File "/disk2/yarn/nm/usercache/root/appcache/application_1646614241228_0932/container_1646614241228_0932_01_000002/python_env/lib/python3.7/site-packages/bigdl/orca/learn/pytorch/pytorch_pyspark_worker.py", line 133, in train_epochs
    save_pkl(state_dict, os.path.join(self.model_dir, "state.pkl"))
  File "/disk2/yarn/nm/usercache/root/appcache/application_1646614241228_0932/container_1646614241228_0932_01_000002/python_env/lib/python3.7/site-packages/bigdl/orca/learn/utils.py", line 363, in save_pkl
    with fs.open(path, 'wb') as f:
  File "pyarrow/_hdfsio.pyx", line 409, in pyarrow._hdfsio.HadoopFileSystem.open
  File "pyarrow/error.pxi", line 113, in pyarrow.lib.check_status
PermissionError: [Errno 13] Opening HDFS file 'hdfs://172.16.0.105:8020/brain/state.pkl' failed. Detail: [errno 13] Permission denied
```

**Comment by yushan111** [comment]
model_dir should be an existing dir on hdfs.

**Comment by ForJadeForest** [comment]
Ok, It's fine. I change the model_dir to the existing dir.

**Comment by yushan111** [comment]
> Ok, It's fine. I change the model_dir to the existing dir.

Great!

**Comment by hkvision** [comment]
> `model_dir` should be a remote path in yarn cluster mode, so only `hdfs://` should work.
> 
> For `OSError: Unable to load libhdfs: ./libhdfs.so: cannot open shared object file: No such file or directory` Potential solution:
> 
> ```
> 1. use locate libhdfs.so to find libhdfs.so
> 2. export ARROW_LIBHDFS_DIR=/opt/cloudera/parcels/CDH-5.15.2-1.cdh5.15.2.p0.3/lib64 (replace with the result of locate libhdfs.so)
> 3. use --conf "spark.executorEnv.ARROW_LIBHDFS_DIR=/opt/cloudera/parcels/CDH-5.15.2-1.cdh5.15.2.p0.3/lib64" to export the environment variable to all executors.
> ```
> 
> If that works in yarn cluster_mode, I will add the solution to Orca Known Issues.

Can we wrap these steps in our code?

**Comment by yushan111** [comment]
> Can we wrap these steps in our code?

Maybe not very appropriate. Since it doesn't work for all circumstances. Users only need to specify `ARROW_LIBHDFS_DIR` when they use yarn-client mode on **Cloudera**. Otherwise, pyarrow automatically detects `libhdfs.so` in `$HADOOP_HOME/lib/native`. 

It might be also a little hard to implement. First, we need to detect the **Cloudera** environment. Then, the output of `locate libhdfs.so` is a list of paths, we need to identify the one used in CDH.

**Comment by yushan111** [comment]
> For `OSError: Unable to load libhdfs: ./libhdfs.so: cannot open shared object file: No such file or directory` Potential solution:
> 
> ```
> 1. use locate libhdfs.so to find libhdfs.so
> 2. export ARROW_LIBHDFS_DIR=/opt/cloudera/parcels/CDH-5.15.2-1.cdh5.15.2.p0.3/lib64 (replace with the result of locate libhdfs.so)
> 3. use --conf "spark.executorEnv.ARROW_LIBHDFS_DIR=/opt/cloudera/parcels/CDH-5.15.2-1.cdh5.15.2.p0.3/lib64" to export the environment variable to all executors.
> ```
> 
> If that works in yarn cluster_mode, I will add the solution to Orca Known Issues.

The issue has been added to Orca Known issues thru https://github.com/intel-analytics/BigDL/pull/4940
