### ISSUE TITLE
java.lang.UnsatisfiedLinkError,/tmp/libxgboost4j4468862148713195876.so: libgomp.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by 00-Luoshu** [intel-analytics/BigDL#5121]
When I tried to submit a spark job to run XGBoost-On-Criteo-click-logs-dataset example on k8s, using bigdl-k8s:latest image and meet the error: 
I have successfully run the example in local.
```
03:01:10.975 [spark-listener-group-shared] ERROR XGBoostTaskFailedListener - Training Task Failed during XGBoost Training: ExceptionFailure(java.lang.UnsatisfiedLinkError,/tmp/libxgboost4j4468862148713195876.so: libgomp.so.1: cannot open shared object file: No such file or directory,[Ljava.lang.StackTraceElement;@6a757fad,java.lang.UnsatisfiedLinkError: /tmp/libxgboost4j4468862148713195876.so: libgomp.so.1: cannot open shared object file: No such file or directory
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
        at java.lang.Runtime.load0(Runtime.java:809)
        at java.lang.System.load(System.java:1086)
        at ml.dmlc.xgboost4j.java.NativeLibLoader.loadLibraryFromJar(NativeLibLoader.java:71)
        at ml.dmlc.xgboost4j.java.NativeLibLoader.initXGBoost(NativeLibLoader.java:41)
        at ml.dmlc.xgboost4j.java.XGBoostJNI.<clinit>(XGBoostJNI.java:34)
        at ml.dmlc.xgboost4j.java.DMatrix.<init>(DMatrix.java:54)
        at ml.dmlc.xgboost4j.scala.DMatrix.<init>(DMatrix.scala:42)
        at ml.dmlc.xgboost4j.scala.spark.Watches$.$anonfun$buildWatches$1(XGBoost.scala:760)
        at scala.collection.Iterator$$anon$10.next(Iterator.scala:459)
        at scala.collection.Iterator.foreach(Iterator.scala:941)
        at scala.collection.Iterator.foreach$(Iterator.scala:941)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
        at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:62)
        at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:53)
        at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:105)
        at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:49)
        at scala.collection.TraversableOnce.to(TraversableOnce.scala:315)
        at scala.collection.TraversableOnce.to$(TraversableOnce.scala:313)
        at scala.collection.AbstractIterator.to(Iterator.scala:1429)
        at scala.collection.TraversableOnce.toBuffer(TraversableOnce.scala:307)
        at scala.collection.TraversableOnce.toBuffer$(TraversableOnce.scala:307)
        at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1429)
        at scala.collection.TraversableOnce.toArray(TraversableOnce.scala:294)
        at scala.collection.TraversableOnce.toArray$(TraversableOnce.scala:288)
        at scala.collection.AbstractIterator.toArray(Iterator.scala:1429)
        at ml.dmlc.xgboost4j.scala.spark.Watches$.buildWatches(XGBoost.scala:766)
        at ml.dmlc.xgboost4j.scala.spark.XGBoost$.$anonfun$trainForNonRanking$2(XGBoost.scala:467)
        at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2(RDD.scala:863)
        at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2$adapted(RDD.scala:863)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
        at org.apache.spark.rdd.RDD.$anonfun$getOrCompute$1(RDD.scala:386)
        at org.apache.spark.storage.BlockManager.$anonfun$doPutIterator$1(BlockManager.scala:1423)
        at org.apache.spark.storage.BlockManager.org$apache$spark$storage$BlockManager$$doPut(BlockManager.scala:1350)
        at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:1414)
        at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:1237)
        at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:384)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:335)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
        at org.apache.spark.scheduler.Task.run(Task.scala:131)
        at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
,Some(org.apache.spark.ThrowableSerializationWrapper@2f77fc87),Vector(AccumulableInfo(247,None,Some(205),None,false,true,None), AccumulableInfo(249,None,Some(0),None,false,true,None)),Vector(LongAccumulator(id: 247, name: Some(internal.metrics.executorRunTime), value: 205), LongAccumulator(id: 249, name: Some(internal.metrics.resultSize), value: 0)),WrappedArray(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)), stopping SparkContext
```
Guide and code comes from:
[https://github.com/intel-analytics/BigDL/tree/branch-2.0/scala/dllib/src/main/scala/com/intel/analytics/bigdl/dllib/example/nnframes/xgboost](https://github.com/intel-analytics/BigDL/tree/branch-2.0/scala/dllib/src/main/scala/com/intel/analytics/bigdl/dllib/example/nnframes/xgboost)
My Spark command:
```
${SPARK_HOME}/bin/spark-submit \
    --master k8s://https://10.239.158.52:6443 \
    --deploy-mode cluster \
    --name spark-xgboost \
    --class com.intel.analytics.bigdl.dllib.examples.nnframes.xgboost.xgbClassifierTrainingExampleOnCriteoClickLogsDataset \
    --conf spark.executor.instances=1 \
    --conf spark.rpc.netty.dispatcher.numThreads=32 \
    --conf spark.kubernetes.container.image=intelanalytics/bigdl-k8s:latest \
    --conf spark.kubernetes.authenticate.driver.serviceAccountName=spark \
    --conf spark.kubernetes.executor.deleteOnTermination=false \
    --conf spark.kubernetes.file.upload.path=file:///tmp \
    --conf spark.kubernetes.driverEnv.DRIVER_MEMORY=8g \
    --conf spark.executor.memory=8g \
    --conf spark.history.ui.port=18080 \
    --conf spark.eventLog.enabled=true \
    --conf spark.eventLog.dir=hdfs://10.239.158.52:9000/spark-events \
    --conf spark.history.fs.logDirectory=hdfs://10.239.158.52:9000/spark-events \
    --conf spark.task.cpus=16 \
    --conf spark.cores.max=16 \
    --executor-cores 16 \
    hdfs://10.239.158.52:9000/zhangyu/bigdl-dllib-spark_3.1.2-2.0.0-jar-with-dependencies.jar  \
hdfs://10.239.158.52:9000/zhangyu/xgboost_plain_1G hdfs://10.239.158.52:9000/zhangyu/xgboost_model 16 10 10
```
refer to the link:
[https://github.com/dmlc/xgboost/issues/1879](https://github.com/dmlc/xgboost/issues/1879)
it may be due to the lack of library  libgomp

**Comment by qiyuangong** [comment]
Nice trace. Please try to fix it by changing https://github.com/intel-analytics/BigDL/blob/main/docker/bigdl-k8s/Dockerfile#L131
