### ISSUE TITLE
[PPML]Encrypting data with SimpleKeyManagementService in a Graphene container prompts that the class cannot be found

### ISSUE THREAD

**Issue by ShanSimu** [intel-analytics/BigDL#5585]
https://bigdl.readthedocs.io/en/latest/doc/PPML/QuickStart/tpc-h_with_sparksql_on_k8s.html#:~:text=The%20example%20code%20of%20encrypt%20data%20with%20SimpleKeyManagementService%20is%20like%20below%3A
I refer to the above documentation for encryption. My script is below:
```bash
java -cp '$BIGDL_HOME/jars/bigdl-ppml-spark_3.1.2-2.1.0-SNAPSHOT.jar:$SPARK_HOME/conf/:$SPARK_HOME/jars/*' \
   -Xmx10g \
   com.intel.analytics.bigdl.ppml.examples.tpch.EncryptFiles \
   --inputPath xx/dbgen \
   --outputPath xx/dbgen-encrypted \
   --simpleAPPID xxxx \
   --simpleAPPKEY xxxx
```
I got this:
![image](https://user-images.githubusercontent.com/46640505/187391781-3c76bfb8-d823-441c-acd9-dcd4f8b6f7e9.png)
I am pretty sure that there is this class in the jar package:
![image](https://user-images.githubusercontent.com/46640505/187392079-e1c8505d-e98b-4414-aeda-79fcad99b8b3.png)

**Comment by ShanSimu** [comment]
The weird thing is:
If I move the file to another linux server, I can find the class when running the same command. 
Although it did not work in the end :(
```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:xxx/jars/log4j-slf4j-impl-2.17.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:xxx/jars/slf4j-reload4j-1.7.35.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
Exception in thread "main" java.lang.NoClassDefFoundError: scopt/OptionParser
        at com.intel.analytics.bigdl.ppml.examples.tpch.EncryptFiles$.main(EncryptFiles.scala:32)
        at com.intel.analytics.bigdl.ppml.examples.tpch.EncryptFiles.main(EncryptFiles.scala)
Caused by: java.lang.ClassNotFoundException: scopt.OptionParser
        at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 2 more

```

**Comment by glorysdj** [comment]
set $BIGDL_HOME and $SPARK_HOME, and add bigdl jars in the cp solve the issue
