### ISSUE TITLE
init_orca_context can't init successfully

### ISSUE THREAD

**Issue by Liu-Weijie** [intel-analytics/BigDL#5819]
Hi, all,
When I use init_orca_context(cores=10, init_ray_on_spark=True), I got the error as follow:
Traceback (most recent call last):
  File "Test_Trex_automl.py", line 61, in <module>
    init_orca_context(cores=10, init_ray_on_spark=True)
  File "/home/liuweijie/ns_training/myenv/lib/python3.7/site-packages/bigdl/orca/common.py", line 324, in init_orca_context
    ray_ctx.init(driver_cores=driver_cores)
  File "/home/liuweijie/ns_training/myenv/lib/python3.7/site-packages/bigdl/orca/ray/raycontext.py", line 58, in init
    results = self._ray_on_spark_context.init(driver_cores=driver_cores)
  File "/home/liuweijie/ns_training/myenv/lib/python3.7/site-packages/bigdl/orca/ray/ray_on_spark_context.py", line 555, in init
    self._address_info = ray.init(**init_params)
  File "/home/liuweijie/ns_training/myenv/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/liuweijie/ns_training/myenv/lib/python3.7/site-packages/ray/worker.py", line 912, in init
    ray_params=ray_params)
  File "/home/liuweijie/ns_training/myenv/lib/python3.7/site-packages/ray/node.py", line 215, in __init__
    self.start_head_processes()
  File "/home/liuweijie/ns_training/myenv/lib/python3.7/site-packages/ray/node.py", line 912, in start_head_processes
    self.start_dashboard(require_dashboard=True)
  File "/home/liuweijie/ns_training/myenv/lib/python3.7/site-packages/ray/node.py", line 759, in start_dashboard
    port=self._ray_params.dashboard_port)
  File "/home/liuweijie/ns_training/myenv/lib/python3.7/site-packages/ray/_private/services.py", line 1345, in start_dashboard
    raise e from e
  File "/home/liuweijie/ns_training/myenv/lib/python3.7/site-packages/ray/_private/services.py", line 1332, in start_dashboard
    raise Exception(f"Failed to read dashbord log: {e}")
Exception: Failed to read dashbord log: [Errno 2] No such file or directory: '/tmp/ray/session_2022-09-19_13-09-29_066820_63286/logs/dashboard.log'
Stopping orca context
I don't know how to fix it. I would appreciate if you could give me some help.

**Comment by sgwhat** [comment]
## Reason
This error occurs when initialize an orca context with `init_ray_on_spark=True`. It might be caused by an atypical python environment.

## Solution
### Option 1
If you need to use `ray_on_spark`, please follow the steps below: 
1. Try to check if you could successfully start a ray cluster by `ray start --head`.
2. Please re-install bigdl-orca and ray in your conda env: pip install --pre --upgrade bigdl-orca[ray]

### Option 2
If you only need to use functions in ray, please follow the steps below:
1. Start a ray cluster by ray start --head. If you already have a ray cluster started, please direcetly jump to step 2.
2. Initialize an orca context with runtime="ray".
  ```
  init_orca_context(runtime="ray")
  ```

**Comment by Liu-Weijie** [comment]
Thanks, I will try it. because I use AutoTSEstimator, I need to use ray_on_spark. By the way, if I use venv to create virtual environment, I want to know whether it matters

**Comment by sgwhat** [comment]
> Thanks, I will try it. because I use AutoTSEstimator, I need to use ray_on_spark. By the way, if I use venv to create virtual environment, I want to know whether it matters

BigDL also supports users to use venv env, you could follow option1 to fix the error.

**Comment by Liu-Weijie** [comment]
Hi, Maybe my problem still exists. I still get the same error. I can't get the dashboard.log. I can't see this file in my folder. When I view the website of dashboard, I can't see anything. I use official release 2.0.0 bigdl-chronos and bigdl-orca

**Comment by sgwhat** [comment]
> Hi, Maybe my problem still exists. I still get the same error. I can't get the dashboard.log. I can't see this file in my folder. When I view the website of dashboard, I can't see anything. I use official release 2.0.0 bigdl-chronos and bigdl-orca

Would you mind describing how you install `bigdl-orca` and `ray`?

**Comment by Liu-Weijie** [comment]
Sure, I use python3.7 -m venv myven to create a virtual environment
pip3 install bigdl-chronos[all]==2.0.0
pip3 install bigdl-orca[ray]==2.0.0

**Comment by sgwhat** [comment]
> Sure, I use python3.7 -m venv myven to create a virtual environment pip3 install bigdl-chronos[all]==2.0.0 pip3 install bigdl-orca[ray]==2.0.0

Seems using venv to call `ray.init( )` directly will not generate `dashboard.log`, so that caused this error. We are working on finding solutions to fix it. By the way,  is it possible for you to use conda for instead?

**Comment by Liu-Weijie** [comment]
Of course, I will use conda to try again. Thank you very much.

**Comment by sgwhat** [comment]
Hey, sorry for the later reply. I have discussed with my co-workers,  and we don't recommend users to use `venv` to run bigdl programs since they may get troubles. Meanwhile, BigDL has fully supported `conda` environment, so we recommend you to use `conda` instead 😀.

**Comment by Liu-Weijie** [comment]
Thanks, I see. I used bigDL in conda environment successfully.
