### ISSUE TITLE
PPML: ModuleNotFoundError: No module named 'bigdl.dllib'

### ISSUE THREAD

**Issue by SEULiyao** [intel-analytics/BigDL#6067]
lines in [__init__.py](https://github.com/intel-analytics/BigDL/blob/main/python/ppml/src/bigdl/ppml/api/__init__.py#L18-L20) will raise ModuleNotFoundError.
```
Traceback (most recent call last):
  File "simple_query_example.py", line 19, in <module>
    from bigdl.ppml.ppml_context import *
  File "/ppml/trusted-big-data-ml/work/examples/BigDL/python/ppml/src/bigdl/ppml/ppml_context.py", line 17, in <module>
    from bigdl.ppml.api import *
  File "/ppml/trusted-big-data-ml/work/examples/BigDL/python/ppml/src/bigdl/ppml/api/__init__.py", line 18, in <module>
    from bigdl.dllib.nncontext import *
ModuleNotFoundError: No module named 'bigdl.dllib'
```
[BigDL/python/ppml/src/bigdl](https://github.com/intel-analytics/BigDL/tree/main/python/ppml/src/bigdl): no dllib.

**Comment by Uxito-Ada** [comment]
Fixed now and closed.
