### ISSUE TITLE
Inception v1 model failed with java.util.NoSuchElementException: None.get

### ISSUE THREAD

**Issue by kaiseu** [intel-analytics/BigDL#609]
Train inception V1 model on spark1.6 standalone mode, failed with  java.util.NoSuchElementException: None.get:

[Stage 225411:===============================================>      (7 + 1) / 8]^M[Stage 225411:===============================================>      (7 + 1) / 8]2017-03-17 14:36:25 ERROR TaskSchedulerImpl:74 - Lost executor 0 on bw-node2: worker lost
^M[Stage 225411:===============================================>      (7 + 1) / 8]2017-03-17 14:37:01 ERROR TaskSetManager:74 - Task 2 in stage 225411.0 failed 1 times; aborting job
Exception in thread "main" org.apache.spark.SparkException: Job aborted due to stage failure: Task 2 in stage 225411.0 failed 1 times, most recent failure: Lost task 2.0 in stage 225411.0 (TID 902776, bw-node4): java.util.concurrent.ExecutionException: java.util.NoSuchElementException: None.get
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at com.intel.analytics.bigdl.parameters.FutureResult$$anonfun$waitResult$1.apply(AllReduceParameter.scala:234)
        at com.intel.analytics.bigdl.parameters.FutureResult$$anonfun$waitResult$1.apply(AllReduceParameter.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.Iterator$class.foreach(Iterator.scala:727)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
        at scala.collection.AbstractTraversable.map(Traversable.scala:105)
        at com.intel.analytics.bigdl.parameters.FutureResult.waitResult(AllReduceParameter.scala:234)
        at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$4.apply(DistriOptimizer.scala:146)
        at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$4.apply(DistriOptimizer.scala:125)
        at org.apache.spark.rdd.ZippedPartitionsRDD2.compute(ZippedPartitionsRDD.scala:88)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
        at org.apache.spark.scheduler.Task.run(Task.scala:89)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:227)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.NoSuchElementException: None.get
        at scala.None$.get(Option.scala:313)
        at scala.None$.get(Option.scala:311)
        at com.intel.analytics.bigdl.parameters.AllReduceParameter$$anonfun$3$$anon$2$$anonfun$4.apply(AllReduceParameter.scala:144)
        at com.intel.analytics.bigdl.parameters.AllReduceParameter$$anonfun$3$$anon$2$$anonfun$4.apply(AllReduceParameter.scala:144)
        at scala.Option.getOrElse(Option.scala:120)
        at com.intel.analytics.bigdl.parameters.AllReduceParameter$$anonfun$3$$anon$2.call(AllReduceParameter.scala:143)
        at com.intel.analytics.bigdl.parameters.AllReduceParameter$$anonfun$3$$anon$2.call(AllReduceParameter.scala:138)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        ... 3 more

Driver stacktrace:
        at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1431)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1419)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1418)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
        at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1418)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:799)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:799)
        at scala.Option.foreach(Option.scala:236)
        at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:799)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1640)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1599)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1588)
        at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
        at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:620)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:1832)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:1952)
        at org.apache.spark.rdd.RDD$$anonfun$reduce$1.apply(RDD.scala:1025)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:150)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:111)
        at org.apache.spark.rdd.RDD.withScope(RDD.scala:316)
        at org.apache.spark.rdd.RDD.reduce(RDD.scala:1007)
        at com.intel.analytics.bigdl.optim.DistriOptimizer$.optimize(DistriOptimizer.scala:221)
        at com.intel.analytics.bigdl.optim.DistriOptimizer.optimize(DistriOptimizer.scala:534)
        at com.intel.analytics.bigdl.models.inception.TrainInceptionV1$$anonfun$main$1.apply(Train.scala:115)
        at com.intel.analytics.bigdl.models.inception.TrainInceptionV1$$anonfun$main$1.apply(Train.scala:38)
        at scala.Option.map(Option.scala:145)
        at com.intel.analytics.bigdl.models.inception.TrainInceptionV1$.main(Train.scala:38)
        at com.intel.analytics.bigdl.models.inception.TrainInceptionV1.main(Train.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

Caused by: java.util.NoSuchElementException: None.get
        at scala.None$.get(Option.scala:313)
        at scala.None$.get(Option.scala:311)
        at com.intel.analytics.bigdl.parameters.AllReduceParameter$$anonfun$3$$anon$2$$anonfun$4.apply(AllReduceParameter.scala:144)
        at com.intel.analytics.bigdl.parameters.AllReduceParameter$$anonfun$3$$anon$2$$anonfun$4.apply(AllReduceParameter.scala:144)
        at scala.Option.getOrElse(Option.scala:120)
        at com.intel.analytics.bigdl.parameters.AllReduceParameter$$anonfun$3$$anon$2.call(AllReduceParameter.scala:143)
        at com.intel.analytics.bigdl.parameters.AllReduceParameter$$anonfun$3$$anon$2.call(AllReduceParameter.scala:138)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        ... 3 more

**Comment by dding3** [comment]
The exception is caused by AllReduceParameter failed to get remote bytes and it should be caused by one worker is lost, see log "Lost executor 0 on bw-node2: worker lost" at the beginning. Could you check why bw-node2 is lost (check the log in bw-node2), we will start from that.

**Comment by kaiseu** [comment]
actually bw-node2 is ok, it still running well, but I found below log in the worker log:
17/03/17 14:36:30 INFO Worker: Master with url spark://bw-node1:7077 requested this worker to reconnect.
17/03/17 14:36:30 INFO Worker: Master with url spark://bw-node1:7077 requested this worker to reconnect.
17/03/17 14:36:30 INFO Worker: Connecting to master bw-node1:7077...
17/03/17 14:36:30 INFO Worker: Not spawning another attempt to register with the master, since there is an attempt scheduled already.
17/03/17 14:36:30 INFO Worker: Master with url spark://bw-node1:7077 requested this worker to reconnect.
17/03/17 14:36:30 INFO Worker: Not spawning another attempt to register with the master, since there is an attempt scheduled already.
17/03/17 14:36:30 INFO Worker: Master with url spark://bw-node1:7077 requested this worker to reconnect.

**Comment by dding3** [comment]
Thank you for the log. It shows this worker's information is lost from master side and master is asking this worker to re-register. The lost should be caused by no respond to master(eg. heartbeat) or the worker is disassociated etc. You may check the master log to see the reason and please share it with us. Besides, could you share us the command you used to submit the job and the cluster settings(worker numbers, memory/Core number per node), we suspect inappropriate settings causes the worker in an unhealthy state.

**Comment by kaiseu** [comment]
only found below error in master's log, but the time is much earlier than it fails,  not know what cause this exceptions. Any suggestions? 

17/03/14 22:13:12 INFO Master: Launching executor app-20170314221312-0004/6 on worker worker-20170311135327-192.168.10.3-46575
17/03/14 22:13:12 INFO Master: Launching executor app-20170314221312-0004/7 on worker worker-20170311135327-192.168.10.8-39488
17/03/15 12:10:13 WARN AbstractHttpConnection: Failed UTF-8 decode for request path, trying ISO-8859-1
17/03/15 12:10:13 WARN AbstractHttpConnection: Failed UTF-8 decode for request path, trying ISO-8859-1
17/03/15 12:10:13 WARN AbstractHttpConnection: Failed UTF-8 decode for request path, trying ISO-8859-1
17/03/15 12:10:13 WARN AbstractHttpConnection: Failed UTF-8 decode for request path, trying ISO-8859-1
17/03/15 12:10:13 WARN AbstractHttpConnection: Failed UTF-8 decode for request path, trying ISO-8859-1
17/03/15 12:10:13 WARN AbstractHttpConnection: Failed UTF-8 decode for request path, trying ISO-8859-1
17/03/15 12:10:47 WARN AbstractHttpConnection: Failed UTF-8 decode for request path, trying ISO-8859-1
17/03/15 12:10:48 WARN AbstractHttpConnection: Failed UTF-8 decode for request path, trying ISO-8859-1
17/03/15 12:10:48 WARN AbstractHttpConnection: /scripts/..%c0%qf..%c0%qf..%c0%qf..%c0%qf..%c0%qfwinnt/system32/pentnt.exe
java.lang.NumberFormatException: qf
        at org.spark-project.jetty.util.TypeUtil.parseInt(TypeUtil.java:319)
        at org.spark-project.jetty.http.HttpURI.getDecodedPath(HttpURI.java:655)
        at org.spark-project.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:471)
        at org.spark-project.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:973)
        at org.spark-project.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1035)
        at org.spark-project.jetty.http.HttpParser.parseNext(HttpParser.java:641)
        at org.spark-project.jetty.http.HttpParser.parseAvailable(HttpParser.java:231)
        at org.spark-project.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
        at org.spark-project.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
        at org.spark-project.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
        at org.spark-project.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
        at org.spark-project.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
        at java.lang.Thread.run(Thread.java:745)
17/03/15 12:10:48 WARN AbstractHttpConnection: Failed UTF-8 decode for request path, trying ISO-8859-1
17/03/15 12:10:48 WARN AbstractHttpConnection: /scripts/..%c0%9v..%c0%9v..%c0%9v..%c0%9v..%c0%9vwinnt/system32/pentnt.exe
java.lang.NumberFormatException: 9v
        at org.spark-project.jetty.util.TypeUtil.parseInt(TypeUtil.java:319)
        at org.spark-project.jetty.http.HttpURI.getDecodedPath(HttpURI.java:655)
        at org.spark-project.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:471)
        at org.spark-project.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:973)
        at org.spark-project.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1035)
        at org.spark-project.jetty.http.HttpParser.parseNext(HttpParser.java:641)
        at org.spark-project.jetty.http.HttpParser.parseAvailable(HttpParser.java:231)
        at org.spark-project.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
        at org.spark-project.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
        at org.spark-project.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
        at org.spark-project.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
        at org.spark-project.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
        at java.lang.Thread.run(Thread.java:745)

**Comment by dding3** [comment]
I think the exception in above master log is from a previous application and it's not related with None.get exception, see the exception time is 17/03/15 12:10:48 while None.get happened at 2017-03-17 14:37:01. Actually when executor is lost, master will print log (eg. "xxx got disassociated" or "Removing xxx" etc) other than throw exception. Besides, we still want to have a look at the command you used to submit the job and the cluster settings(worker numbers, memory/Core number per node) to make sure the unhealthy worker is not caused by incorrect param settings for bigdl.

**Comment by kaiseu** [comment]
in fact during this time only one application has been submitted to the cluster, the application took long time. above log is part of the master log, here is the continuing part.  
intended to know the difference of setting physical cores and vcores in the command, this issue occurs when using vcores, for the hyper threading is enabled, I think we should think  why using vcores would cause this issue, or it must be physical cores.

17/03/15 12:11:42 WARN AbstractHttpConnection: /..%%35%63..%%35%63..%%35%63..%%35%63..%%35%63/winnt/system32/netstat.exe?/c
java.lang.NumberFormatException: %3
        at org.spark-project.jetty.util.TypeUtil.parseInt(TypeUtil.java:319)
        at org.spark-project.jetty.http.HttpURI.getDecodedPath(HttpURI.java:655)
        at org.spark-project.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:471)
        at org.spark-project.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:973)
        at org.spark-project.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1035)
        at org.spark-project.jetty.http.HttpParser.parseNext(HttpParser.java:641)
        at org.spark-project.jetty.http.HttpParser.parseAvailable(HttpParser.java:231)
        at org.spark-project.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
        at org.spark-project.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
        at org.spark-project.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
        at org.spark-project.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
        at org.spark-project.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
        at java.lang.Thread.run(Thread.java:745)
17/03/15 12:11:42 WARN AbstractHttpConnection: Failed UTF-8 decode for request path, trying ISO-8859-1
17/03/15 12:11:42 WARN AbstractHttpConnection: /..%%35%63..%%35%63..%%35%63..%%35%63..%%35%63../winnt/system32/netstat.exe?/c
java.lang.NumberFormatException: %3
        at org.spark-project.jetty.util.TypeUtil.parseInt(TypeUtil.java:319)
        at org.spark-project.jetty.http.HttpURI.getDecodedPath(HttpURI.java:655)
        at org.spark-project.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:471)
        at org.spark-project.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:973)
        at org.spark-project.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1035)
        at org.spark-project.jetty.http.HttpParser.parseNext(HttpParser.java:641)
        at org.spark-project.jetty.http.HttpParser.parseAvailable(HttpParser.java:231)
        at org.spark-project.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
        at org.spark-project.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
        at org.spark-project.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
        at org.spark-project.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
        at org.spark-project.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
        at java.lang.Thread.run(Thread.java:745)
17/03/15 12:11:43 WARN AbstractHttpConnection: Failed UTF-8 decode for request path, trying ISO-8859-1
17/03/15 12:11:43 WARN AbstractHttpConnection: Failed UTF-8 decode for request path, trying ISO-8859-1
17/03/15 12:15:34 WARN AbstractHttpConnection: Failed UTF-8 decode for request path, trying ISO-8859-1
17/03/15 12:16:33 WARN AbstractHttpConnection: Failed UTF-8 decode for request path, trying ISO-8859-1
17/03/17 14:36:25 WARN Master: Removing worker-20170311135327-192.168.10.2-45720 because we got no heartbeat in 60 seconds
17/03/17 14:36:25 INFO Master: Removing worker worker-20170311135327-192.168.10.2-45720 on 192.168.10.2:45720
17/03/17 14:36:25 INFO Master: Telling app of lost executor: 0
17/03/17 14:36:30 WARN Master: Got heartbeat from unregistered worker worker-20170311135327-192.168.10.2-45720. Asking it to re-register.
17/03/17 14:36:30 WARN Master: Got heartbeat from unregistered worker worker-20170311135327-192.168.10.2-45720. Asking it to re-register.
17/03/17 14:36:30 WARN Master: Got heartbeat from unregistered worker worker-20170311135327-192.168.10.2-45720. Asking it to re-register.
17/03/17 14:36:30 WARN Master: Got heartbeat from unregistered worker worker-20170311135327-192.168.10.2-45720. Asking it to re-register.
17/03/17 14:36:30 WARN Master: Got heartbeat from unregistered worker worker-20170311135327-192.168.10.2-45720. Asking it to re-register.
17/03/17 14:36:30 WARN Master: Got heartbeat from unregistered worker worker-20170311135327-192.168.10.2-45720. Asking it to re-register.
17/03/17 14:36:30 WARN Master: Got heartbeat from unregistered worker worker-20170311135327-192.168.10.2-45720. Asking it to re-register.

**Comment by dding3** [comment]
Ok. I see, it makes sense since inception V1 training takes a long time. About why must physical cores, @yiheng Any inputs here?
For why losting the node, I think the remaining master log is meaningful. See "17/03/17 14:36:25 WARN Master: Removing worker-20170311135327-192.168.10.2-45720 because we got no heartbeat in 60 seconds", looks like 192.168.10.2 is quite busy and didn't send back heartbeat on time. One quickest way to avoid this is setting a larger worker timeout (config "spark.worker.timeout") . 

By the way, we support resume training from last exception if you have set checkpoint directory when submiting job. You can resume it by append "--state ./checkpointdir/lastest_state --model checkpointdir/lastest_model" to your command.
