### ISSUE TITLE
Saved torch model cannot be loaded

### ISSUE THREAD

**Issue by jenniew** [intel-analytics/BigDL#629]
Use BigDL to save a model to Torch model file, and cannot be loaded with Module.loadTorch method. Got java.lang.NullPointerException exception.
Execution code:
val module = Sequential[Double]()
module.add(SpatialConvolution[Double](3, 4, 2, 2).setName("conv"))
module.add(SpatialConvolution[Double](4, 3, 2, 2).setName("conv2"))
module.add(Linear[Double](2, 27, withBias = false).setName("ip"))
module.saveTorch("/home/jwang/model/test1.t7")
val model1 = Module.loadTorch[Double]("/home/jwang/model/test1.t7")

java.lang.NullPointerException
	at com.intel.analytics.bigdl.tensor.DenseTensor$.copy(DenseTensor.scala:2224)
	at com.intel.analytics.bigdl.tensor.DenseTensor.copy(DenseTensor.scala:369)
	at com.intel.analytics.bigdl.utils.TorchFile$.readLinearWithType(TorchFile.scala:913)
	at com.intel.analytics.bigdl.utils.TorchFile$.readModuleWithType(TorchFile.scala:149)
	at com.intel.analytics.bigdl.utils.TorchFile$.readModule(TorchFile.scala:192)
	at com.intel.analytics.bigdl.utils.TorchFile$.readObject(TorchFile.scala:236)
	at com.intel.analytics.bigdl.utils.TorchFile$.readTable(TorchFile.scala:756)
	at com.intel.analytics.bigdl.utils.TorchFile$.readObject(TorchFile.scala:246)
	at com.intel.analytics.bigdl.utils.TorchFile$.readTable(TorchFile.scala:756)
	at com.intel.analytics.bigdl.utils.TorchFile$.readObject(TorchFile.scala:246)
	at com.intel.analytics.bigdl.utils.TorchFile$.readModule(TorchFile.scala:187)
	at com.intel.analytics.bigdl.utils.TorchFile$.readObject(TorchFile.scala:236)
	at com.intel.analytics.bigdl.utils.TorchFile$.load(TorchFile.scala:78)
	at com.intel.analytics.bigdl.utils.File$.loadTorch(File.scala:36)
	at com.intel.analytics.bigdl.nn.Module$.loadTorch(Module.scala:32)
	at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:36)
	at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:41)
	at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:43)
	at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:45)
	at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:47)
	at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:49)
	at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:51)
	at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:53)
	at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:55)
	at $iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:57)
	at $iwC$$iwC$$iwC$$iwC.<init>(<console>:59)
	at $iwC$$iwC$$iwC.<init>(<console>:61)
	at $iwC$$iwC.<init>(<console>:63)
	at $iwC.<init>(<console>:65)
	at <init>(<console>:67)
	at .<init>(<console>:71)
	at .<clinit>(<console>)
	at .<init>(<console>:7)
	at .<clinit>(<console>)
	at $print(<console>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.repl.SparkIMain$ReadEvalPrint.call(SparkIMain.scala:1065)
	at org.apache.spark.repl.SparkIMain$Request.loadAndRun(SparkIMain.scala:1346)
	at org.apache.spark.repl.SparkIMain.loadAndRunReq$1(SparkIMain.scala:840)
	at org.apache.spark.repl.SparkIMain.interpret(SparkIMain.scala:871)
	at org.apache.spark.repl.SparkIMain.interpret(SparkIMain.scala:819)
	at org.apache.spark.repl.SparkILoop.reallyInterpret$1(SparkILoop.scala:857)
	at org.apache.spark.repl.SparkILoop.interpretStartingWith(SparkILoop.scala:902)
	at org.apache.spark.repl.SparkILoop.command(SparkILoop.scala:814)
	at org.apache.spark.repl.SparkILoop.processLine$1(SparkILoop.scala:657)
	at org.apache.spark.repl.SparkILoop.innerLoop$1(SparkILoop.scala:665)
	at org.apache.spark.repl.SparkILoop.org$apache$spark$repl$SparkILoop$$loop(SparkILoop.scala:670)
	at org.apache.spark.repl.SparkILoop$$anonfun$org$apache$spark$repl$SparkILoop$$process$1.apply$mcZ$sp(SparkILoop.scala:997)
	at org.apache.spark.repl.SparkILoop$$anonfun$org$apache$spark$repl$SparkILoop$$process$1.apply(SparkILoop.scala:945)
	at org.apache.spark.repl.SparkILoop$$anonfun$org$apache$spark$repl$SparkILoop$$process$1.apply(SparkILoop.scala:945)
	at scala.tools.nsc.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:135)
	at org.apache.spark.repl.SparkILoop.org$apache$spark$repl$SparkILoop$$process(SparkILoop.scala:945)
	at org.apache.spark.repl.SparkILoop.process(SparkILoop.scala:1059)
	at org.apache.spark.repl.Main$.main(Main.scala:31)
	at org.apache.spark.repl.Main.main(Main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

**Comment by qiuxin2012** [comment]
This issue is caused by the noBias Linear, I will add a support for this Linear.
