### ISSUE TITLE
Nano:self.internal.trace(accelerator="openvino")

### ISSUE THREAD

**Issue by smurf-1119** [intel-analytics/BigDL#6297]
When I write the function `build_openvino` in `bigdl.chronos.forecaster.tf.base_forecaster`, I call the api `self.internal.trace(accelerator="openvino")`. Then I encounter some errors as follows.
```
2022-10-26 13:00:25.345256: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING:tensorflow:Skipping full serialization of Keras layer <keras.layers.core.dropout.Dropout object at 0x7f2941e5fb90>, because it is not built.
WARNING:tensorflow:Skipping full serialization of Keras layer <keras.layers.core.dropout.Dropout object at 0x7f2908cd2150>, because it is not built.
WARNING:tensorflow:Skipping full serialization of Keras layer <keras.layers.core.dropout.Dropout object at 0x7f2908cdaa50>, because it is not built.
WARNING:tensorflow:Skipping full serialization of Keras layer <keras.layers.core.dropout.Dropout object at 0x7f2908ce1a50>, because it is not built.
WARNING:tensorflow:Skipping full serialization of Keras layer <keras.layers.core.dropout.Dropout object at 0x7f2908cec4d0>, because it is not built.
WARNING:tensorflow:Skipping full serialization of Keras layer <keras.layers.core.dropout.Dropout object at 0x7f2908c721d0>, because it is not built.
WARNING:tensorflow:Skipping full serialization of Keras layer <keras.layers.core.dropout.Dropout object at 0x7f2908c77d50>, because it is not built.
WARNING:tensorflow:Skipping full serialization of Keras layer <keras.layers.core.dropout.Dropout object at 0x7f2908c7ecd0>, because it is not built.
WARNING:tensorflow:Skipping full serialization of Keras layer <keras.layers.convolutional.Conv1D object at 0x7f2941e5f550>, because it is not built.
2022-10-26 13:00:28.907583: W tensorflow/python/util/util.cc:368] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
WARNING:absl:Found untraced functions such as conv1d_layer_call_fn, conv1d_layer_call_and_return_conditional_losses, activation_layer_call_fn, activation_layer_call_and_return_conditional_losses, conv1d_1_layer_call_fn while saving (showing 5 of 115). These functions will not be directly callable after loading.
Traceback (most recent call last):
  File "/disk3/qp/tf_forecaster/test.py", line 9, in <module>
    forecaster.build_openvino()
  File "/disk3/qp/tf_forecaster/base_forecaster.py", line 369, in build_openvino
    self.openvino_fp32 = self.internal.trace(accelerator="openvino")
  File "/home/cpx/miniconda3/envs/qp/lib/python3.7/site-packages/bigdl/nano/tf/keras/inference_utils.py", line 117, in trace
    return KerasOpenVINOModel(self, input_sample)
  File "/home/cpx/miniconda3/envs/qp/lib/python3.7/site-packages/bigdl/nano/deps/openvino/openvino_api.py", line 54, in KerasOpenVINOModel
    return KerasOpenVINOModel(model)
  File "/home/cpx/miniconda3/envs/qp/lib/python3.7/site-packages/bigdl/nano/deps/openvino/tf/model.py", line 41, in __init__
    export(model, str(dir / 'tmp.xml'))
  File "/home/cpx/miniconda3/envs/qp/lib/python3.7/site-packages/bigdl/nano/deps/openvino/tf/utils.py", line 34, in export
    model.save(str(folder))
  File "/home/cpx/miniconda3/envs/qp/lib/python3.7/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/cpx/miniconda3/envs/qp/lib/python3.7/site-packages/tensorflow/python/saved_model/save.py", line 1061, in _write_object_proto
    registered_name = registration.get_registered_name(obj)
AttributeError: module 'tensorflow.python.saved_model.registration' has no attribute 'get_registered_name'
```

The following code is the function `bigdl.chronos.forecaster.tf.base_forecaster.build_openvino`:
```
    def build_openvino(self, thread_num=None):
        '''
        Build openvino model to speed up inference and reduce latency.
        The method is Not required to call before predict_with_openvino.
        It is recommended to use when you want to:
        | 1. Strictly control the thread to be used during inferencing.
        | 2. Alleviate the cold start problem when you call predict_with_openvino
             for the first time.
        :param thread_num: int, the num of thread limit. The value is set to None by
               default where no limit is set.
        '''
        from bigdl.chronos.pytorch import TSInferenceOptimizer as InferenceOptimizer
        from bigdl.nano.utils.log4Error import invalidInputError

        if self.distributed:
            invalidInputError(False,
                              "build_openvino has not been supported for distributed "
                              "forecaster. You can call .to_local() to transform the "
                              "forecaster to a non-distributed version.")
        self.openvino_fp32 = self.internal.trace(accelerator="openvino")
```

When testing, I run the code as follows:

```
from tcn_forecaster import TCNForecaster

forecaster = TCNForecaster(past_seq_len=48,
                           future_seq_len=1,
                           input_feature_num=1,
                           output_feature_num=1,
                           lr=0.001)

forecaster.build_openvino()
openvino_tcn = forecaster.openvino_fp32
```

**Comment by TheaperDeng** [comment]
issue noticed, working on this
