### ISSUE TITLE
clone() method throw exception

### ISSUE THREAD

**Issue by zhichao-li** [intel-analytics/BigDL#641]
```
   val tensor: Tensor[Float] = Tensor.ones[Float](10)
   val cloneTensor = tensor.clone()
```

java.lang.ArrayStoreException was thrown.
java.lang.ArrayStoreException
	at java.lang.System.arraycopy(Native Method)
	at com.intel.analytics.bigdl.tensor.DenseTensor$.copy(DenseTensor.scala:2229)
	at com.intel.analytics.bigdl.tensor.DenseTensor$.newClone(DenseTensor.scala:2032)
	at com.intel.analytics.bigdl.tensor.DenseTensor.clone(DenseTensor.scala:365)

cc @zhangxiaoli73 @yiheng

**Comment by yiheng** [comment]
Can't reproduce this.
