### ISSUE TITLE
Error when save XGBoost model to HDFS 

### ISSUE THREAD

**Issue by lalalapotter** [intel-analytics/BigDL#6460]
Save XGBoost model to HDFS with both scala and python XGBoost API, and get the following errors:

- Python API
```shell
Traceback (most recent call last):
  File "train.py", line 65, in <module>    best_model.save_model("hdfs:///user/kai/zcg/model/xgb_automl.model")
  File "/disk5/yarn/nm/usercache/kai/appcache/application_1665967342034_0327/container_1665967342034_0327_01_000001/environment/lib/python3.7/site-packages/xgboost/sklearn.py", line 726, in save_model
    self.get_booster().save_model(fname)
  File "/disk5/yarn/nm/usercache/kai/appcache/application_1665967342034_0327/container_1665967342034_0327_01_000001/environment/lib/python3.7/site-packages/xgboost/core.py", line 2240, in save_model
    self.handle, c_str(fname)))
  File "/disk5/yarn/nm/usercache/kai/appcache/application_1665967342034_0327/container_1665967342034_0327_01_000001/environment/lib/python3.7/site-packages/xgboost/core.py", line 246, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: [09:51:03] ../dmlc-core/src/io.cc:50: Please compile with DMLC_USE_HDFS=1 to use hdfs
```
- Scala API
```shell
Traceback (most recent call last):
  File "xgb_train.py", line 31, in <module>
    xgbmodel.saveModel("hdfs:///user/kai/zcg/model/xgb_model")
  File "/disk5/yarn/nm/usercache/kai/appcache/application_1665967342034_0324/container_1665967342034_0324_01_000001/environment/lib/python3.7/site-packages/bigdl/dllib/nnframes/tree_model.py", line 96, in saveModel
    callZooFunc("float", "saveXGBClassifierModel", self.value, path)
  File "/disk5/yarn/nm/usercache/kai/appcache/application_1665967342034_0324/container_1665967342034_0324_01_000001/environment/lib/python3.7/site-packages/bigdl/dllib/utils/file_utils.py", line 264, in callZooFunc
    invalidOperationError(False, str(e), cause=e)
  File "/disk5/yarn/nm/usercache/kai/appcache/application_1665967342034_0324/container_1665967342034_0324_01_000001/environment/lib/python3.7/site-packages/bigdl/dllib/utils/log4Error.py", line 40, in invalidOperationError
    raise cause
  File "/disk5/yarn/nm/usercache/kai/appcache/application_1665967342034_0324/container_1665967342034_0324_01_000001/environment/lib/python3.7/site-packages/bigdl/dllib/utils/file_utils.py", line 258, in callZooFunc
    java_result = api(*args)
  File "/disk5/yarn/nm/usercache/kai/appcache/application_1665967342034_0324/container_1665967342034_0324_01_000001/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
  File "/disk5/yarn/nm/usercache/kai/appcache/application_1665967342034_0324/container_1665967342034_0324_01_000001/pyspark.zip/pyspark/sql/utils.py", line 63, in deco
  File "/disk5/yarn/nm/usercache/kai/appcache/application_1665967342034_0324/container_1665967342034_0324_01_000001/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o67.saveXGBClassifierModel.
: ml.dmlc.xgboost4j.java.XGBoostError: [09:43:13] /workspace/dmlc-core/src/io.cc:50: Please compile with DMLC_USE_HDFS=1 to use hdfs
```

**Comment by songhappy** [comment]
currently, BigDL does not have a document to support saving xgboost models to HDFS. 
Will add steps of details to build and save

**Comment by songhappy** [comment]
Use bindings of HDFS, S3, etc. to pass model files around. Here are the steps (taking HDFS as an example):

Create a new file with
val outputStream = fs.create("hdfs_path")
where “fs” is an instance of [org.apache.hadoop.fs.FileSystem](https://hadoop.apache.org/docs/stable/api/org/apache/hadoop/fs/FileSystem.html) class in Hadoop.
Pass the returned OutputStream in the first step to nativeBooster.saveModel():

xgbClassificationModel.nativeBooster.saveModel(outputStream)
Download file in other languages from HDFS and load with the pre-built (without the requirement of libhdfs.so) version of XGBoost. (The function “download_from_hdfs” is a helper function to be implemented by the user)

import xgboost as xgb
bst = xgb.Booster({'nthread': 4})
local_path = download_from_hdfs("hdfs_path")
bst.load_model(local_path)

**Comment by lalalapotter** [comment]
Temporarily meet the needs of customers, and further related documents may need to be added
