### ISSUE TITLE
An error while using the orca pytorch estimator

### ISSUE THREAD

**Issue by Tazzy9** [intel-analytics/BigDL#6623]
Traceback (most recent call last):
  File "recall_train.py", line 91, in <module>
    est.fit(data=train_data, epochs=5, batch_size=512, feature_cols=["features"], label_cols=['label'])
  File "/Users/taozhuoqun/opt/anaconda3/envs/bigdl_spark3/lib/python3.7/site-packages/bigdl/orca/learn/pytorch/pytorch_spark_estimator.py", line 167, in fit
    val_fset, self.metrics, batch_size)
  File "/Users/taozhuoqun/opt/anaconda3/envs/bigdl_spark3/lib/python3.7/site-packages/bigdl/dllib/estimator/estimator.py", line 147, in train
    validation_method, batch_size)
  File "/Users/taozhuoqun/opt/anaconda3/envs/bigdl_spark3/lib/python3.7/site-packages/bigdl/dllib/utils/file_utils.py", line 264, in callZooFunc
    invalidOperationError(False, str(e), cause=e)
  File "/Users/taozhuoqun/opt/anaconda3/envs/bigdl_spark3/lib/python3.7/site-packages/bigdl/dllib/utils/log4Error.py", line 40, in invalidOperationError
    raise cause
  File "/Users/taozhuoqun/opt/anaconda3/envs/bigdl_spark3/lib/python3.7/site-packages/bigdl/dllib/utils/file_utils.py", line 258, in callZooFunc
    java_result = api(*args)
  File "/Users/taozhuoqun/opt/anaconda3/envs/bigdl_spark3/lib/python3.7/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1305, in __call__
  File "/Users/taozhuoqun/opt/anaconda3/envs/bigdl_spark3/lib/python3.7/site-packages/pyspark/sql/utils.py", line 111, in deco
    return f(*a, **kw)
  File "/Users/taozhuoqun/opt/anaconda3/envs/bigdl_spark3/lib/python3.7/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o60.estimatorTrain.
: com.intel.analytics.bigdl.dllib.utils.InvalidOperationException
	at com.intel.analytics.bigdl.dllib.utils.Log4Error$.invalidOperationError(Log4Error.scala:38)
	at com.intel.analytics.bigdl.dllib.keras.models.InternalDistriOptimizer.train(Topology.scala:1161)
	at com.intel.analytics.bigdl.dllib.keras.models.InternalDistriOptimizer.train(Topology.scala:1302)
	at com.intel.analytics.bigdl.dllib.keras.models.InternalDistriOptimizer.train(Topology.scala:969)
	at com.intel.analytics.bigdl.dllib.estimator.Estimator.train(Estimator.scala:193)
	at com.intel.analytics.bigdl.dllib.estimator.python.PythonEstimator.estimatorTrain(PythonEstimator.scala:102)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.reflect.InvocationTargetException

**Comment by hkvision** [comment]
Hi @Tazzy9 

Thanks for raising the issue. Could you please provide more of your code segments if possible and more details about your model and data so that we can look into it?

**Comment by hkvision** [comment]
@qiuxin2012 Please follow up this issue.

**Comment by Tazzy9** [comment]
Thanks for your reply. I'm trying to train a pytorch twin model (DSSM) on my local machine with bigdl installed (I'm using an virtual Conda environment with only bigdl installed - via pip install -i https://pypi.tuna.tsinghua.edu.cn/simple bigdl-spark3). Here is my python code (met the error above on "est.fit"):

model = DSSM(user_vec_dim, user_cate_dim, [len(cate_map) for cate_map in cate_maps],
             pos_vec_dim, pos_cate_dim, [len(cate_map) for cate_map in pos_cate_maps],
             16, 16, 10)
optimizer = torch.optim.Adam(model.parameters(), lr=1e-4, weight_decay=1e-2)
lr_scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, 50)
criterion = Loss()

est = Estimator.from_torch(model=model, optimizer=optimizer, loss=criterion, metrics=[Accuracy()], workers_per_node=args.cores)
est.fit(data=train_data, epochs=5, batch_size=256, feature_cols=["features"], label_cols=['label'])
results = est.evaluate(data=test_data, batch_size=256, feature_cols=["features"], label_cols=['label'])

Thanks for any reply ~

**Comment by jason-dai** [comment]
@jenniew please take a look

**Comment by helenlly** [comment]
@qiuxin2012 pls have a look

**Comment by jenniew** [comment]
@Tazzy9 I tried on our side with a simple pytorch model, and used spark dataframe as input data, but no error raised. Which pytorch version were you using? Would you mind to share the complete code?

**Comment by qiuxin2012** [comment]
@Tazzy9  It seems some important log and error message is missing. I try to reproduce a similar error contains the error message you provided.
Is your model DSSM's definition in a seperate file in current folder, not in conda environment? The simple way to solve this, it move them to your conda env, like /opt/anaconda3/envs/torch3/lib/python3.7/site-packages
```
22-11-17 14:16:21 [Thread-4] INFO  InternalDistriOptimizer$:1009 - TorchModel[91cde2d4] isTorch is true
22-11-17 14:16:21 [Thread-4] INFO  InternalDistriOptimizer$:1016 - torch model will use 1 OMP threads.
22-11-17 14:16:21 [Thread-4] INFO  DistriOptimizer$:830 - caching training rdd ...
22-11-17 14:16:43 [Thread-4] INFO  DistriOptimizer$:655 - Cache thread models...
22-11-17 14:16:44 [Executor task launch worker for task 0.0 in stage 5.0 (TID 5)] INFO  ThreadPool$:95 - Set mkl threads to 1 on thread 78
22-11-17 14:16:44 [Executor task launch worker for task 0.0 in stage 5.0 (TID 5)] INFO  ThreadPool$:95 - Set mkl threads to 1 on thread 78
22-11-17 14:16:44 [Executor task launch worker for task 0.0 in stage 5.0 (TID 5)] INFO  DistriOptimizer$:638 - model thread pool size is 1
2022-11-17 14:16:44 WARN  BlockManager:69 - Asked to remove block test_0weights0, which does not exist
2022-11-17 14:16:44 WARN  BlockManager:69 - Asked to remove block test_0gradients0, which does not exist
22-11-17 14:16:44 [Thread-4] INFO  DistriOptimizer$:657 - Cache thread models... done
22-11-17 14:16:44 [Thread-4] INFO  DistriOptimizer$:163 - Count dataset
22-11-17 14:16:52 [Thread-4] INFO  DistriOptimizer$:167 - Count dataset complete. Time elapsed: 8.502830047s
22-11-17 14:17:00 [Thread-4] WARN  DistriOptimizer$:171 - If the dataset is built directly from RDD[Minibatch], the data in each minibatch is fixed, and a single minibatch is randomly selected in each partition. If the dataset is transformed from RDD[Sample], each minibatch will be constructed on the fly from random samples, which is better for convergence.
22-11-17 14:17:00 [Thread-4] INFO  DistriOptimizer$:175 - config  {
	computeThresholdbatchSize: 100
	maxDropPercentage: 0.0
	warmupIterationNum: 200
	isLayerwiseScaled: false
	dropPercentage: 0.0
 }
22-11-17 14:17:00 [Thread-4] INFO  DistriOptimizer$:179 - Shuffle data
22-11-17 14:17:00 [Thread-4] INFO  DistriOptimizer$:182 - Shuffle data complete. Takes 2.89467E-4s
22-11-17 14:17:01 [Executor task launch worker for task 0.0 in stage 8.0 (TID 8)] INFO  Log4Error$:46 - 

****************************Usage Error************************
jep.JepException: jep.JepException: <class 'ModuleNotFoundError'>: No module named 'lenet'
22-11-17 14:17:01 [Executor task launch worker for task 0.0 in stage 8.0 (TID 8)] INFO  Log4Error$:52 - 

****************************Call Stack*************************
2022-11-17 14:17:01 ERROR Executor:94 - Exception in task 0.0 in stage 8.0 (TID 8)
com.intel.analytics.bigdl.dllib.utils.UnKnownException: jep.JepException: jep.JepException: <class 'ModuleNotFoundError'>: No module named 'lenet'
	at com.intel.analytics.bigdl.dllib.utils.Log4Error$.unKnowExceptionError(Log4Error.scala:60)
	at com.intel.analytics.bigdl.dllib.utils.ThreadPool.invokeAndWait2(ThreadPool.scala:175)
	at com.intel.analytics.bigdl.dllib.optim.DistriOptimizer$.$anonfun$optimize$4(DistriOptimizer.scala:261)
	at org.apache.spark.rdd.ZippedPartitionsRDD2.compute(ZippedPartitionsRDD.scala:89)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.ExecutionException: jep.JepException: jep.JepException: <class 'ModuleNotFoundError'>: No module named 'lenet'
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.intel.analytics.bigdl.dllib.utils.ThreadPool.invokeAndWait2(ThreadPool.scala:172)
	... 12 more
Caused by: jep.JepException: jep.JepException: <class 'ModuleNotFoundError'>: No module named 'lenet'
	at com.intel.analytics.bigdl.orca.utils.PythonInterpreter$.threadExecute(PythonInterpreter.scala:97)
	at com.intel.analytics.bigdl.orca.utils.PythonInterpreter$.exec(PythonInterpreter.scala:107)
	at com.intel.analytics.bigdl.orca.net.TorchModel.load$lzycompute(TorchModel.scala:71)
	at com.intel.analytics.bigdl.orca.net.TorchModel.load(TorchModel.scala:51)
	at com.intel.analytics.bigdl.orca.net.TorchModel.training(TorchModel.scala:251)
	at com.intel.analytics.bigdl.orca.net.TorchModel.training(TorchModel.scala:35)
	at com.intel.analytics.bigdl.dllib.optim.DistriOptimizer$.$anonfun$optimize$7(DistriOptimizer.scala:265)
	at scala.runtime.java8.JFunction0$mcI$sp.apply(JFunction0$mcI$sp.java:23)
	at com.intel.analytics.bigdl.dllib.utils.ThreadPool$$anon$4.call(ThreadPool.scala:161)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
Caused by: jep.JepException: <class 'ModuleNotFoundError'>: No module named 'lenet'
	at /opt/anaconda3/envs/torch3/lib/python3.7/site-packages/torch/serialization._load(serialization.py:853)
	at /opt/anaconda3/envs/torch3/lib/python3.7/site-packages/torch/serialization.load(serialization.py:594)
	at <string>.<module>(<string>:12)
	at jep.Jep.exec(Native Method)
	at jep.Jep.exec(Jep.java:478)
	at com.intel.analytics.bigdl.orca.utils.PythonInterpreter$.$anonfun$exec$1(PythonInterpreter.scala:105)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	... 4 more
2022-11-17 14:17:01 WARN  TaskSetManager:69 - Lost task 0.0 in stage 8.0 (TID 8) (xin-dev.sh.intel.com executor driver): com.intel.analytics.bigdl.dllib.utils.UnKnownException: jep.JepException: jep.JepException: <class 'ModuleNotFoundError'>: No module named 'lenet'
	at com.intel.analytics.bigdl.dllib.utils.Log4Error$.unKnowExceptionError(Log4Error.scala:60)
	at com.intel.analytics.bigdl.dllib.utils.ThreadPool.invokeAndWait2(ThreadPool.scala:175)
	at com.intel.analytics.bigdl.dllib.optim.DistriOptimizer$.$anonfun$optimize$4(DistriOptimizer.scala:261)
	at org.apache.spark.rdd.ZippedPartitionsRDD2.compute(ZippedPartitionsRDD.scala:89)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.ExecutionException: jep.JepException: jep.JepException: <class 'ModuleNotFoundError'>: No module named 'lenet'
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.intel.analytics.bigdl.dllib.utils.ThreadPool.invokeAndWait2(ThreadPool.scala:172)
	... 12 more
Caused by: jep.JepException: jep.JepException: <class 'ModuleNotFoundError'>: No module named 'lenet'
	at com.intel.analytics.bigdl.orca.utils.PythonInterpreter$.threadExecute(PythonInterpreter.scala:97)
	at com.intel.analytics.bigdl.orca.utils.PythonInterpreter$.exec(PythonInterpreter.scala:107)
	at com.intel.analytics.bigdl.orca.net.TorchModel.load$lzycompute(TorchModel.scala:71)
	at com.intel.analytics.bigdl.orca.net.TorchModel.load(TorchModel.scala:51)
	at com.intel.analytics.bigdl.orca.net.TorchModel.training(TorchModel.scala:251)
	at com.intel.analytics.bigdl.orca.net.TorchModel.training(TorchModel.scala:35)
	at com.intel.analytics.bigdl.dllib.optim.DistriOptimizer$.$anonfun$optimize$7(DistriOptimizer.scala:265)
	at scala.runtime.java8.JFunction0$mcI$sp.apply(JFunction0$mcI$sp.java:23)
	at com.intel.analytics.bigdl.dllib.utils.ThreadPool$$anon$4.call(ThreadPool.scala:161)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
Caused by: jep.JepException: <class 'ModuleNotFoundError'>: No module named 'lenet'
	at /opt/anaconda3/envs/torch3/lib/python3.7/site-packages/torch/serialization._load(serialization.py:853)
	at /opt/anaconda3/envs/torch3/lib/python3.7/site-packages/torch/serialization.load(serialization.py:594)
	at <string>.<module>(<string>:12)
	at jep.Jep.exec(Native Method)
	at jep.Jep.exec(Jep.java:478)
	at com.intel.analytics.bigdl.orca.utils.PythonInterpreter$.$anonfun$exec$1(PythonInterpreter.scala:105)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	... 4 more

2022-11-17 14:17:01 ERROR TaskSetManager:73 - Task 0 in stage 8.0 failed 1 times; aborting job
22-11-17 14:17:01 [Thread-4] INFO  Log4Error$:52 - 

****************************Call Stack*************************


****************************Usage Error************************
An error occurred while calling o60.estimatorTrainMiniBatch.
: com.intel.analytics.bigdl.dllib.utils.InvalidOperationException
	at com.intel.analytics.bigdl.dllib.utils.Log4Error$.invalidOperationError(Log4Error.scala:38)
	at com.intel.analytics.bigdl.dllib.keras.models.InternalDistriOptimizer.train(Topology.scala:1161)
	at com.intel.analytics.bigdl.dllib.keras.models.InternalDistriOptimizer.train(Topology.scala:1302)
	at com.intel.analytics.bigdl.dllib.keras.models.InternalDistriOptimizer.train(Topology.scala:969)
	at com.intel.analytics.bigdl.dllib.estimator.Estimator.train(Estimator.scala:193)
	at com.intel.analytics.bigdl.dllib.estimator.python.PythonEstimator.estimatorTrainMiniBatch(PythonEstimator.scala:119)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intel.analytics.bigdl.dllib.keras.layers.utils.KerasUtils$.invokeMethod(KerasUtils.scala:317)
	at com.intel.analytics.bigdl.dllib.keras.layers.utils.KerasUtils$.invokeMethodWithEv(KerasUtils.scala:344)
	at com.intel.analytics.bigdl.dllib.keras.models.InternalOptimizerUtil$.optimizeModels(Topology.scala:886)
	at com.intel.analytics.bigdl.dllib.keras.models.InternalDistriOptimizer.train(Topology.scala:1089)
	... 15 more
Caused by: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 8.0 failed 1 times, most recent failure: Lost task 0.0 in stage 8.0 (TID 8) (xin-dev.sh.intel.com executor driver): com.intel.analytics.bigdl.dllib.utils.UnKnownException: jep.JepException: jep.JepException: <class 'ModuleNotFoundError'>: No module named 'lenet'
	at com.intel.analytics.bigdl.dllib.utils.Log4Error$.unKnowExceptionError(Log4Error.scala:60)
	at com.intel.analytics.bigdl.dllib.utils.ThreadPool.invokeAndWait2(ThreadPool.scala:175)
	at com.intel.analytics.bigdl.dllib.optim.DistriOptimizer$.$anonfun$optimize$4(DistriOptimizer.scala:261)
	at org.apache.spark.rdd.ZippedPartitionsRDD2.compute(ZippedPartitionsRDD.scala:89)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.ExecutionException: jep.JepException: jep.JepException: <class 'ModuleNotFoundError'>: No module named 'lenet'
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.intel.analytics.bigdl.dllib.utils.ThreadPool.invokeAndWait2(ThreadPool.scala:172)
	... 12 more
Caused by: jep.JepException: jep.JepException: <class 'ModuleNotFoundError'>: No module named 'lenet'
	at com.intel.analytics.bigdl.orca.utils.PythonInterpreter$.threadExecute(PythonInterpreter.scala:97)
	at com.intel.analytics.bigdl.orca.utils.PythonInterpreter$.exec(PythonInterpreter.scala:107)
	at com.intel.analytics.bigdl.orca.net.TorchModel.load$lzycompute(TorchModel.scala:71)
	at com.intel.analytics.bigdl.orca.net.TorchModel.load(TorchModel.scala:51)
	at com.intel.analytics.bigdl.orca.net.TorchModel.training(TorchModel.scala:251)
	at com.intel.analytics.bigdl.orca.net.TorchModel.training(TorchModel.scala:35)
	at com.intel.analytics.bigdl.dllib.optim.DistriOptimizer$.$anonfun$optimize$7(DistriOptimizer.scala:265)
	at scala.runtime.java8.JFunction0$mcI$sp.apply(JFunction0$mcI$sp.java:23)
	at com.intel.analytics.bigdl.dllib.utils.ThreadPool$$anon$4.call(ThreadPool.scala:161)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more

```

**Comment by qiuxin2012** [comment]
The best way is to use "torch_distributed", "spark" backend, as "bigdl" backend will be removed in the future. See this example https://github.com/intel-analytics/BigDL/tree/v2.0.0/python/orca/example/learn/pytorch/fashion_mnist

**Comment by jason-dai** [comment]
> The best way is to use "torch_distributed", "spark" backend, as "bigdl" backend will be removed in the future. See this example https://github.com/intel-analytics/BigDL/tree/v2.0.0/python/orca/example/learn/pytorch/fashion_mnist

We should set "spark" or "torch_distributed" backend as default, and deprecate "bigdl" backend @hkvision
