### ISSUE TITLE
TypeError: 'NoneType' object is not callable when run TF2 Estimator ray backend

### ISSUE THREAD

**Issue by hkvision** [intel-analytics/BigDL#6838]
```
Stopping orca context
Exception ignored in: <function SparkXShards.__del__ at 0x7f522a93add0>
Traceback (most recent call last):
  File "/home/yingzhe/anaconda3/envs/bigdl_spark3/lib/python3.7/site-packages/bigdl/orca/data/shard.py", line 811, in __del__
  File "/home/yingzhe/anaconda3/envs/bigdl_spark3/lib/python3.7/site-packages/bigdl/orca/data/shard.py", line 238, in uncache
  File "/home/yingzhe/anaconda3/envs/bigdl_spark3/lib/python3.7/site-packages/pyspark/rdd.py", line 315, in unpersist
  File "/home/yingzhe/anaconda3/envs/bigdl_spark3/lib/python3.7/site-packages/py4j/java_gateway.py", line 1296, in __call__
  File "/home/yingzhe/anaconda3/envs/bigdl_spark3/lib/python3.7/site-packages/py4j/java_gateway.py", line 1260, in _build_args
  File "/home/yingzhe/anaconda3/envs/bigdl_spark3/lib/python3.7/site-packages/py4j/java_gateway.py", line 1246, in _get_args
  File "/home/yingzhe/anaconda3/envs/bigdl_spark3/lib/python3.7/site-packages/py4j/java_collections.py", line 490, in can_convert
  File "/home/yingzhe/anaconda3/envs/bigdl_spark3/lib/python3.7/abc.py", line 139, in __instancecheck__
TypeError: 'NoneType' object is not callable
Exception ignored in: <function SparkXShards.__del__ at 0x7f522a93add0>
Traceback (most recent call last):
  File "/home/yingzhe/anaconda3/envs/bigdl_spark3/lib/python3.7/site-packages/bigdl/orca/data/shard.py", line 811, in __del__
  File "/home/yingzhe/anaconda3/envs/bigdl_spark3/lib/python3.7/site-packages/bigdl/orca/data/shard.py", line 238, in uncache
  File "/home/yingzhe/anaconda3/envs/bigdl_spark3/lib/python3.7/site-packages/pyspark/rdd.py", line 315, in unpersist
  File "/home/yingzhe/anaconda3/envs/bigdl_spark3/lib/python3.7/site-packages/py4j/java_gateway.py", line 1296, in __call__
  File "/home/yingzhe/anaconda3/envs/bigdl_spark3/lib/python3.7/site-packages/py4j/java_gateway.py", line 1260, in _build_args
  File "/home/yingzhe/anaconda3/envs/bigdl_spark3/lib/python3.7/site-packages/py4j/java_gateway.py", line 1246, in _get_args
  File "/home/yingzhe/anaconda3/envs/bigdl_spark3/lib/python3.7/site-packages/py4j/java_collections.py", line 490, in can_convert
  File "/home/yingzhe/anaconda3/envs/bigdl_spark3/lib/python3.7/abc.py", line 139, in __instancecheck__
TypeError: 'NoneType' object is not callable
```

Issue observed for ray backend only. But it appears after the termination (after stop_orca_context), doesn't impact the running. Need to investigate if this needs to be resolved.

**Comment by hkvision** [comment]
Seems we can't reproduce this issue now? @lalalapotter

**Comment by lalalapotter** [comment]
None of the recent tests encountered similar issues, shall we still need to investigate the reason? Maybe of relatively lower priority?

**Comment by hkvision** [comment]
If we can't reproduce this issue at present, we can just leave it.

**Comment by lalalapotter** [comment]
Sure.

**Comment by hamham223** [comment]
Reproduce this issue stably on clx cluster

+ script: https://github.com/intel-analytics/BigDL/blob/main/python/orca/tutorial/NCF/tf_resume_train_xshards.py 
+ backend: spark (need to run train in spark backend first)
+ `stop_orca_context` does not throw out any exception, all spark resources are shutdowned. So I guess exception comes from the memory free when python program ends? Xshards is trying to uncache something does not exist?

**Comment by hamham223** [comment]
Two sparkxshards objects are created from train_data and test_data
```python
train_data = XShards.load_pickle(os.path.join(args.data_dir, "train_processed_xshards"))
⬇️       
<bigdl.orca.data.shard.SparkXShards object at 0x7ff1c023add0>
MapPartitionsRDD[1] at objectFile at NativeMethodAccessorImpl.java:0

test_data = XShards.load_pickle(os.path.join(args.data_dir, "test_processed_xshards"))
⬇️ 
<bigdl.orca.data.shard.SparkXShards object at 0x7ff1c023ea50>
MapPartitionsRDD[4] at objectFile at NativeMethodAccessorImpl.java:0
```

**Comment by hamham223** [comment]
Seems the behavior is different on different machines?

+ on clx cluster: accessing `self.rdd` -> `NoneType object is not callable`
+ on my dev machine: `self.rdd` can be reached, but `self.rdd.unpersist()` -> `Py4JError`

```python
Exception ignored in: <function SparkXShards.__del__ at 0x7fac93869dd0>
Traceback (most recent call last):
  File "/home/yinchen/BigDL/python/orca/src/bigdl/orca/data/shard.py", line 852, in __del__
  File "/home/yinchen/BigDL/python/orca/src/bigdl/orca/data/shard.py", line 292, in uncache
  File "/home/yinchen/anaconda3/envs/yinchen/lib/python3.7/site-packages/pyspark/rdd.py", line 315, in unpersist
  File "/home/yinchen/anaconda3/envs/yinchen/lib/python3.7/site-packages/py4j/java_gateway.py", line 1305, in __call__
  File "/home/yinchen/anaconda3/envs/yinchen/lib/python3.7/site-packages/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o114.unpersist.
: java.lang.NullPointerException
        at org.apache.spark.storage.BlockManagerMaster.removeRdd(BlockManagerMaster.scala:162)
        at org.apache.spark.SparkContext.unpersistRDD(SparkContext.scala:1906)
        at org.apache.spark.rdd.RDD.unpersist(RDD.scala:222)
        at org.apache.spark.api.java.JavaRDD.unpersist(JavaRDD.scala:78)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:282)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:238)
        at java.lang.Thread.run(Thread.java:748)
```
Is this issue also related to `Try to unpersist an uncached rdd`?
