### ISSUE TITLE
pillow failed when reading images on HDFS

### ISSUE THREAD

**Issue by songhappy** [intel-analytics/BigDL#7114]
Summary:
serializers failed when reading images on HDFS, it works fine on local 

steps to reproduce:
1. log almaren 107
2. cd /opt/work/guoqiong/BigDL/python/orca/tutorial/xshards
3. conda activate bigdl_song
4. python cat_dog_classification_bk.py

error message:
data_shard = bigdl.orca.data.image.read_images(path)
  File "/root/anaconda3/envs/bigdl_song/lib/python3.7/site-packages/bigdl/orca/data/image/preprocessing.py", line 69, in read_images
    return SparkXShards(im_rdd)
  File "/root/anaconda3/envs/bigdl_song/lib/python3.7/site-packages/bigdl/orca/data/shard.py", line 176, in __init__
    self.compute()
  File "/root/anaconda3/envs/bigdl_song/lib/python3.7/site-packages/bigdl/orca/data/shard.py", line 278, in compute
    self.rdd.count()
  File "/root/anaconda3/envs/bigdl_song/lib/python3.7/site-packages/pyspark/rdd.py", line 1055, in count
    return self.mapPartitions(lambda i: [sum(1 for _ in i)]).sum()
  File "/root/anaconda3/envs/bigdl_song/lib/python3.7/site-packages/pyspark/rdd.py", line 1046, in sum
    return self.mapPartitions(lambda x: [sum(x)]).fold(0, operator.add)
  File "/root/anaconda3/envs/bigdl_song/lib/python3.7/site-packages/pyspark/rdd.py", line 917, in fold
    vals = self.mapPartitions(func).collect()
  File "/root/anaconda3/envs/bigdl_song/lib/python3.7/site-packages/pyspark/rdd.py", line 816, in collect
    sock_info = self.ctx._jvm.PythonRDD.collectAndServe(self._jrdd.rdd())
  File "/root/anaconda3/envs/bigdl_song/lib/python3.7/site-packages/py4j/java_gateway.py", line 1257, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/root/anaconda3/envs/bigdl_song/lib/python3.7/site-packages/py4j/protocol.py", line 328, in get_return_value
    format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.collectAndServe.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 9 in stage 0.0 failed 4 times, most recent failure: Lost task 9.3 in stage 0.0 (TID 61, Almaren-Node-134, executor 1): org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/disk1/yarn/nm/usercache/root/appcache/application_1668477395550_0223/container_1668477395550_0223_01_000002/pyspark.zip/pyspark/worker.py", line 377, in main
    process()
  File "/disk1/yarn/nm/usercache/root/appcache/application_1668477395550_0223/container_1668477395550_0223_01_000002/pyspark.zip/pyspark/worker.py", line 372, in process
    serializer.dump_stream(func(split_index, iterator), outfile)
  File "/disk1/yarn/nm/usercache/root/appcache/application_1668477395550_0223/container_1668477395550_0223_01_000002/pyspark.zip/pyspark/serializers.py", line 404, in dump_stream
    bytes = self.serializer.dumps(vs)
  File "/disk1/yarn/nm/usercache/root/appcache/application_1668477395550_0223/container_1668477395550_0223_01_000002/pyspark.zip/pyspark/serializers.py", line 583, in dumps
    return pickle.dumps(obj, protocol)
  File "/disk1/yarn/nm/usercache/root/appcache/application_1668477395550_0223/container_1668477395550_0223_01_000002/python_env/lib/python3.7/site-packages/PIL/Image.py", line 703, in __getstate__
    return [self.info, self.mode, self.size, self.getpalette(), self.tobytes()]
  File "/disk1/yarn/nm/usercache/root/appcache/application_1668477395550_0223/container_1668477395550_0223_01_000002/python_env/lib/python3.7/site-packages/PIL/Image.py", line 1473, in getpalette
    self.load()
  File "/disk1/yarn/nm/usercache/root/appcache/application_1668477395550_0223/container_1668477395550_0223_01_000002/python_env/lib/python3.7/site-packages/PIL/ImageFile.py", line 229, in load
    seek(offset)

**Comment by songhappy** [comment]
test code 
```
sc = init_orca_context("yarn", cores=executor_cores,
                  num_nodes=num_executor, memory=executor_memory,
                  driver_cores=driver_cores, driver_memory=driver_memory, conf=conf)

path = "hdfs://172.16.0.105:8020/dogs-vs-cats/small/dog.6311.jpg"

def load_image1(f):
    image = open_image(f)
    return {'filename': f, 'x': image}

def get_label(im):
    filename = im['filename']
    label = [1] if 'dog' in filename.split('/')[-1] else [0]
    return {'x': im['x'], 'y': label}

def crop(data):
    im = data['x']
    width, height = im.size  # Get dimensions
    left = width / 4
    top = height / 4
    right = 3 * width / 4
    bottom = 3 * height / 4
    cropped = im.crop((left, top, right, bottom))
    return {'x': cropped, 'y': data['y']}


def resize(im):
    size = (80, 80)
    return {'x': im['x'].resize(size), 'y': im['y']}

image = open_image(path)
print(image)
print(type(image))
image = load_image1(path)
print(image)
print(type(image))
with_label = get_label(image)
print(with_label)
croped = crop(with_label)
print(croped)
resized = resize(croped)
```

error message narrow down
  File "test1.py", line 123, in <module>
    croped = crop(with_label)
  File "test1.py", line 107, in crop
    cropped = im.crop((left, top, right, bottom))
  File "/root/anaconda3/envs/bigdl_song/lib/python3.7/site-packages/PIL/Image.py", line 1175, in crop
    self.load()
  File "/root/anaconda3/envs/bigdl_song/lib/python3.7/site-packages/PIL/ImageFile.py", line 228, in load
    seek(offset)
  File "pyarrow/io.pxi", line 308, in pyarrow.lib.NativeFile.seek
  File "pyarrow/io.pxi", line 205, in pyarrow.lib.NativeFile.get_random_access_file
  File "pyarrow/io.pxi", line 222, in pyarrow.lib.NativeFile._assert_readable
  File "pyarrow/io.pxi", line 219, in pyarrow.lib.NativeFile._assert_open
ValueError: I/O operation on closed file

**Comment by songhappy** [comment]
fixed in PR-7229

**Comment by hkvision** [comment]
Great!
Seems for pyarrow Image.open is lazy and actually haven't read the image before pyarrow exits.
