### ISSUE TITLE
chronos  

### ISSUE THREAD

**Issue by YUKUN-XIAO** [intel-analytics/BigDL#7127]
Traceback (most recent call last):
  File "autolstm_nyc_taxi.py", line 21, in <module>
    from bigdl.chronos.data import get_public_dataset
ImportError: cannot import name 'get_public_dataset' from 'bigdl.chronos.data'

**Comment by hkvision** [comment]
@TheaperDeng Please take a look.

**Comment by hkvision** [comment]
@YUKUN-XIAO Thank you for raising this issue.
I tested on my machine using the latest nightly build and seems can't reproduce this:
![image](https://user-images.githubusercontent.com/21994046/210029694-941c1eac-1bf9-4122-95a1-85b8f4bcc928.png)
![image](https://user-images.githubusercontent.com/21994046/210029713-5be1069d-420b-45a5-b0e6-1320e34d7fde.png)

Could you provide more information on this? E.g. which chronos version are you using. Or can you upgrade to the latest nightly build version with `pip install --pre --upgrade bigdl-chronos`?

**Comment by YUKUN-XIAO** [comment]
> @YUKUN-XIAO Thank you for raising this issue. I tested on my machine using the latest nightly build and seems can't reproduce this: ![image](https://user-images.githubusercontent.com/21994046/210029694-941c1eac-1bf9-4122-95a1-85b8f4bcc928.png) ![image](https://user-images.githubusercontent.com/21994046/210029713-5be1069d-420b-45a5-b0e6-1320e34d7fde.png)
> 
> Could you provide more information on this? E.g. which chronos version are you using. Or can you upgrade to the latest nightly build version with `pip install --pre --upgrade bigdl-chronos`?

![image](https://user-images.githubusercontent.com/58495241/210031892-fd252eb0-b613-4d47-b25a-c94dc8cc43c9.png)

![image](https://user-images.githubusercontent.com/58495241/210031959-a6f0b8e9-3d22-4512-90b2-59fa961ba015.png)

![image](https://user-images.githubusercontent.com/58495241/210031975-9056cf50-6a04-4353-be57-ecfd0e8df202.png)

Traceback (most recent call last):
  File "autolstm_nyc_taxi.py", line 21, in <module>
    from bigdl.chronos.data import get_public_dataset
  File "/root/miniconda3/envs/chronos_env/lib/python3.7/site-packages/bigdl/chronos/data/__init__.py", line 18, in <module>
    from .repo_dataset import get_public_dataset, gen_synthetic_data
  File "/root/miniconda3/envs/chronos_env/lib/python3.7/site-packages/bigdl/chronos/data/repo_dataset.py", line 19, in <module>
    from bigdl.chronos.data.utils.public_dataset import PublicDataset
  File "/root/miniconda3/envs/chronos_env/lib/python3.7/site-packages/bigdl/chronos/data/utils/public_dataset.py", line 20, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

谢谢，刚刚升级了一下，重新运行了一次，又报了错误。

**Comment by hkvision** [comment]
Could you `pip install requests` in your environment and have another try?

**Comment by YUKUN-XIAO** [comment]
> 
OK, I solved it according to your method.  
![image](https://user-images.githubusercontent.com/58495241/210032619-b2139cdf-1e99-4e28-9cf2-764a760b0b7f.png)

![image](https://user-images.githubusercontent.com/58495241/210032491-071640e3-a4ff-4e75-9d03-ae32ff70fc81.png)
After pip installation orca, errors will still be reported

**Comment by hkvision** [comment]
You need to install `pip install --pre --upgrade bigdl-orca` not other orca packages.

**Comment by YUKUN-XIAO** [comment]
> You need to install `pip install --pre --upgrade bigdl-orca` not other orca packages.

![image](https://user-images.githubusercontent.com/58495241/210032957-84ef49e4-ae73-4750-9fed-76ddf68a2418.png)

Do I need to run pip install -- pre -- upgrade ray or pip install -- pre -- upgrade ray

**Comment by hkvision** [comment]
You can `pip install --pre --upgrade bigdl-orca[ray]`

**Comment by YUKUN-XIAO** [comment]
> You can `pip install --pre --upgrade bigdl-orca[automl]` This command will install ray and related dependencies.
![image](https://user-images.githubusercontent.com/58495241/210033698-2acf9c7a-4e00-4baf-9944-db028e07886d.png)
![image](https://user-images.githubusercontent.com/58495241/210033711-651cf000-3d6e-4177-9ce7-bc5674c964e2.png)

Do I need to install Java

**Comment by hkvision** [comment]
Yes, you can follow the instructions here to install java: https://bigdl.readthedocs.io/en/latest/doc/Orca/Overview/install.html#install-java

**Comment by YUKUN-XIAO** [comment]
> Yes, you can follow the instructions here to install java: https://bigdl.readthedocs.io/en/latest/doc/Orca/Overview/install.html#install-java

![image](https://user-images.githubusercontent.com/58495241/210057083-83b3ff22-58b8-4b87-a597-e8d3afe09833.png)
 I run this command pip install  pytorch_lightning  -i http://pypi.douban.com/simple --trusted-host pypi.douban.com
to solve the problem

**Comment by YUKUN-XIAO** [comment]
> > Yes, you can follow the instructions here to install java: https://bigdl.readthedocs.io/en/latest/doc/Orca/Overview/install.html#install-java
> 
> ![image](https://user-images.githubusercontent.com/58495241/210057083-83b3ff22-58b8-4b87-a597-e8d3afe09833.png) I run this command pip install pytorch_lightning -i http://pypi.douban.com/simple --trusted-host pypi.douban.com to solve the problem

![image](https://user-images.githubusercontent.com/58495241/210059753-eaee1e36-e606-4b91-b093-c876025cf0d1.png)

A new problem has arisen

**Comment by jason-dai** [comment]
To install Chronos, I would suggest you follow the guide at https://bigdl.readthedocs.io/en/latest/doc/Chronos/Overview/install.html. 

> (You may need to install Java as described at https://bigdl.readthedocs.io/en/latest/doc/UserGuide/python.html#install).

**Comment by YUKUN-XIAO** [comment]
> To install Chronos, I would suggest you follow the guide at https://bigdl.readthedocs.io/en/latest/doc/Chronos/Overview/install.html.
> 
> > (You may need to install Java as described at https://bigdl.readthedocs.io/en/latest/doc/UserGuide/python.html#install).

thank you

**Comment by YUKUN-XIAO** [comment]
Can chronos run on the ray cluster I built myself ?
