### ISSUE TITLE
Pytorch Pyspark Estimator cannot load checkpoint from hdfs

### ISSUE THREAD

**Issue by jenniew** [intel-analytics/BigDL#7574]
Pytorch Pyspark Estimator cannot load checkpoint from hdfs.

The error is like below:
Traceback (most recent call last):
  File "/opt/work/jwang/BigDL-jennie-2/python/orca/example/learn/pytorch/bert/sentiment_huggingface.py", line 1263, in <module>
    main()
  File "/opt/work/jwang/BigDL-jennie-2/python/orca/example/learn/pytorch/bert/sentiment_huggingface.py", line 1085, in main
    est.load_checkpoint("hdfs://almaren-node-105:8020/user/root/jwang/sst2/a.ckpt")
  File "/opt/work/jwang/BigDL-jennie-2/dist/lib/bigdl-friesian-spark_3.1.3-2.3.0-SNAPSHOT-python-api.zip/bigdl/orca/learn/pytorch/pytorch_pyspark_estimator.py", line 702, in load_checkpoint
  File "/opt/work/jwang/BigDL-jennie-2/dist/lib/bigdl-friesian-spark_3.1.3-2.3.0-SNAPSHOT-python-api.zip/bigdl/orca/learn/pytorch/core/modelIO.py", line 62, in load_checkpoint
  File "/opt/work/jwang/wj-transformer/lib/python3.8/site-packages/torch/serialization.py", line 771, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/opt/work/jwang/wj-transformer/lib/python3.8/site-packages/torch/serialization.py", line 275, in _open_file_like
    return _open_buffer_reader(name_or_buffer)
  File "/opt/work/jwang/wj-transformer/lib/python3.8/site-packages/torch/serialization.py", line 260, in __init__
    _check_seekable(buffer)
  File "/opt/work/jwang/wj-transformer/lib/python3.8/site-packages/torch/serialization.py", line 348, in _check_seekable
    f.seek(f.tell())
  File "pyarrow/io.pxi", line 274, in pyarrow.lib.NativeFile.tell
  File "pyarrow/io.pxi", line 206, in pyarrow.lib.NativeFile.get_random_access_file
  File "pyarrow/io.pxi", line 235, in pyarrow.lib.NativeFile._assert_seekable
OSError: only valid on seekable file

Example code:
est = Estimator.from_torch(...)
est.save_checkpoint("hdfs://xxx/xx.ckpt")
est.load_checkpoint("hdfs://xxx/xx.ckpt")

**Comment by sgwhat** [comment]
I didn't catch this error when loading a ckpt file, what's your pytorch and pyarrow version?

**Comment by sgwhat** [comment]
We should re-write this part to avoid the error.

**Comment by sgwhat** [comment]
https://github.com/intel-analytics/BigDL/pull/7619 this pr may be able to solve this issue.

**Comment by jenniew** [comment]
The pytorch version is: 1.13.1, and pyarrow is 11.0.0
