### ISSUE TITLE
TF2 estimator use more memory with spark backend then ray backend when training in YARN Cluster.

### ISSUE THREAD

**Issue by lalalapotter** [intel-analytics/BigDL#7650]
Test [multi-task example](https://github.com/lalalapotter/bigdl-example/tree/main/mastercard/multi-task) in Almaren Yarn Cluster(cluster mode), with 100,000 rows dataset(1.7GB) generated by [scripts](https://github.com/lalalapotter/bigdl-example/blob/main/mastercard/multi-task/data.py). Found that tf2 estimator with spark backend need more memory then the one with ray backend. Corresponding test results are as following:
<img width="1285" alt="image" src="https://user-images.githubusercontent.com/27332689/220553485-f2ec5bc1-995e-493b-a9d6-b7799da215d0.png">
Otherwise, the application reported error:
```shell
Traceback (most recent call last):
  File "multi_task.py", line 134, in <module>
    steps_per_epoch=train_rows // batch_size)
  File "/disk2/yarn/nm/usercache/kai/appcache/application_1668477395550_1113/container_1668477395550_1113_01_000001/environment/lib/python3.7/site-packages/bigdl/orca/learn/tf2/pyspark_estimator.py", line 238, in fit
    lambda iter: transform_func(iter, init_params, params)).collect()
  File "/disk2/yarn/nm/usercache/kai/appcache/application_1668477395550_1113/container_1668477395550_1113_01_000001/pyspark.zip/pyspark/rdd.py", line 816, in collect
  File "/disk2/yarn/nm/usercache/kai/appcache/application_1668477395550_1113/container_1668477395550_1113_01_000001/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
  File "/disk2/yarn/nm/usercache/kai/appcache/application_1668477395550_1113/container_1668477395550_1113_01_000001/pyspark.zip/pyspark/sql/utils.py", line 63, in deco
  File "/disk2/yarn/nm/usercache/kai/appcache/application_1668477395550_1113/container_1668477395550_1113_01_000001/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.collectAndServe.
: org.apache.spark.SparkException: Job aborted due to stage failure: Could not recover from a failed barrier ResultStage. Most recent failure reason: Stage failed because barrier task ResultTask(8, 0) finished unsuccessfully.
ExecutorLostFailure (executor 1 exited caused by one of the running tasks) Reason: Container killed by YARN for exceeding memory limits.  4.2 GB of 4 GB physical memory used. Consider boosting spark.yarn.executor.memoryOverhead or disabling yarn.nodemanager.vmem-check-enabled because of YARN-4714.
```
Is there a reasonable explanation for this phenomenon, or how can we optimize it? @jenniew 
Related links: 
- [application_1668477395550_1110](http://172.16.0.105:8088/cluster/app/application_1668477395550_1110)
- [application_1668477395550_1114](http://172.16.0.105:8088/cluster/app/application_1668477395550_1114)
- [application_1668477395550_1113](http://172.16.0.105:8088/cluster/app/application_1668477395550_1113)

**Comment by hkvision** [comment]
@jenniew Previously you have done some memory optimization on train as well right? Take a look.

**Comment by jenniew** [comment]
I think the more memory overhead may be that pyspark estimator need to do repartition and collect all data on each partition. I will do try some optimization and test.

**Comment by jenniew** [comment]
list(iter) is not easy to avoid because we need to zip training rdd and validation rdd,  thus the two rdds need to have same elements on each partition. Another solution is create file reader generator, and call fit with this generator as input data.

**Comment by hkvision** [comment]
Need to prioritize this issue per customer request.
