### ISSUE TITLE
Use BigDL with AWS EMR Notebook

### ISSUE THREAD

**Issue by Ishitori** [intel-analytics/BigDL#7764]
I am trying to launch an AWS EMR Notebook with BigDL support. I cannot restart Spark cluster and cannot administer it in any way. I can only connect to it using a notebook (or Livy if needed). I am installing BigDL packages as external jars/zips using the following notebook configuration:

```
%%configure -f
{
    "conf": {
        "spark.jars": "<s3_path>/bigdl-dllib-spark_3.1.2-2.1.0-jar-with-dependencies.jar",
        "spark.submit.pyFiles": "<s3_path>/bigdl-dllib-spark_3.1.2-2.1.0-python-api.zip",
        "spark.driver.extraJavaOptions": "-Dbigdl.engineType=mkldnn",
        "spark.executor.extraJavaOptions": "-Dbigdl.engineType=mkldnn",
        "spark.pyspark.python": "python3",
        "spark.pyspark.virtualenv.enabled": "true",
        "spark.pyspark.virtualenv.type":"native",
        "spark.pyspark.virtualenv.bin.path":"/usr/bin/virtualenv",
        <...other configurations...>
     }
}
```

This allowed to import python classes and it seems like all dependencies are resolved.  Unfortunately, when I launch the following example code:

```
import pyspark.sql.types as T
from bigdl.dllib.nn.layer import *
from bigdl.dllib.nn.criterion import *
from bigdl.dllib.utils.common import *
from bigdl.dllib.nnframes.nn_classifier import *
from bigdl.dllib.feature.common import *

data = sc.parallelize([
    ((2.0, 1.0), (1.0, 2.0)),
    ((1.0, 2.0), (2.0, 1.0)),
    ((2.0, 1.0), (1.0, 2.0)),
    ((1.0, 2.0), (2.0, 1.0))])

schema = T.StructType([
    T.StructField("features", T.ArrayType(T.DoubleType(), False), False),
    T.StructField("label", T.ArrayType(T.DoubleType(), False), False)])

df = spark.createDataFrame(data, schema)
model = Sequential().add(Linear(2, 2))
criterion = MSECriterion()
estimator = NNEstimator(model, criterion, SeqToTensor([2]), ArrayToTensor([2])).setBatchSize(5).setLearningRate(0.2).setMaxEpoch(40)
nnModel = estimator.fit(df)
res = nnModel.transform(df)
```

I get the following error:

```
An error was encountered:
An error occurred while calling o558.fit.
: org.apache.spark.SparkException: Job aborted due to stage failure: 
Aborting TaskSet 29.0 because task 2 (partition 2)
cannot run anywhere due to node and executor excludeOnFailure.
Most recent failure:
Lost task 4.2 in stage 29.0 (TID 17622) (ip-10-103-53-33.ec2.internal executor 10): java.lang.NullPointerException
	at com.intel.analytics.bigdl.dllib.models.utils.ModelBroadcastImp.value(ModelBroadcast.scala:165)
	at com.intel.analytics.bigdl.dllib.optim.DistriOptimizer$.$anonfun$initThreadModels$2(DistriOptimizer.scala:618)
	at com.intel.analytics.bigdl.dllib.optim.DistriOptimizer$.$anonfun$initThreadModels$2$adapted(DistriOptimizer.scala:617)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
	at scala.collection.immutable.Range.foreach(Range.scala:158)
	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at com.intel.analytics.bigdl.dllib.optim.DistriOptimizer$.$anonfun$initThreadModels$1(DistriOptimizer.scala:617)
```

Do I need to setup something else for BigDL to work on a notebook?

**Comment by qiuxin2012** [comment]
The exception looks like this old issue https://github.com/intel-analytics/BigDL/issues/2727
You can try to add `"spark.serializer": "org.apache.spark.serializer.JavaSerializer"` to your conf.

**Comment by Ishitori** [comment]
This actually helps in a sense that now exception is different. Now it is:

```
n error was encountered:
An error occurred while calling o158.fit.
: com.intel.analytics.bigdl.dllib.utils.InvalidOperationException
	at com.intel.analytics.bigdl.dllib.utils.Log4Error$.invalidOperationError(Log4Error.scala:38)
	at com.intel.analytics.bigdl.dllib.keras.models.InternalDistriOptimizer.train(Topology.scala:1161)
	at com.intel.analytics.bigdl.dllib.keras.models.InternalDistriOptimizer.train(Topology.scala:1302)
	at com.intel.analytics.bigdl.dllib.nnframes.NNEstimator.internalFit(NNEstimator.scala:494)
	at com.intel.analytics.bigdl.dllib.nnframes.NNEstimator.internalFit(NNEstimator.scala:202)
	at org.apache.spark.ml.DLEstimatorBase.fit(DLEstimatorBase.scala:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intel.analytics.bigdl.dllib.keras.layers.utils.KerasUtils$.invokeMethod(KerasUtils.scala:317)
	at com.intel.analytics.bigdl.dllib.keras.layers.utils.KerasUtils$.invokeMethodWithEv(KerasUtils.scala:344)
	at com.intel.analytics.bigdl.dllib.keras.models.InternalOptimizerUtil$.optimizeModels(Topology.scala:886)
	at com.intel.analytics.bigdl.dllib.keras.models.InternalDistriOptimizer.train(Topology.scala:1089)
	... 15 more
```

What is the proper way to setup BigDL with AWS EMR Notebook? Is there an example for that?

**Comment by Ishitori** [comment]
I also see a warning:

```
UserWarning: Find both SPARK_HOME and pyspark. You may need to check whether they match with each other. SPARK_HOME environment variable is set to: ., and pyspark is found in: /mnt/yarn/usercache/livy/appcache/application_1663192032239_10815/container_1663192032239_10815_01_000001/pyspark.zip/pyspark/__init__.py. If they are unmatched, please use one source only to avoid conflict. For example, you can unset SPARK_HOME and use pyspark only.
```

Can I do something about it only using configuration from the example above?

**Comment by qiuxin2012** [comment]
@Ishitori  Sorry, our BigDL AWS EMR document is very old, it's for bigdl 0.1.0. But we have a guide for aws databricks https://bigdl.readthedocs.io/en/latest/doc/UserGuide/databricks.html. Is it useful for you? and could you use aws databricks?

Looks like you have both SPARK binaries and pyspark on the EMR, you should find who is the default, and uninstall another one.

**Comment by Ishitori** [comment]
Unfortunately, DataBricks approach assumes that you have control over initialization script of the cluster, and I don't have it. 

Well, in the end I made it work for the simplest case by doing conversion of the graph to MKLDNN (by calling `to_graph()`). The warning is still there, but I don't see it preventing model from training/inferencing, so I will ignore it for now (I cannot really uninstall anything on the cluster :( ).

I couldn't install `analytics_zoo` (https://pypi.org/project/analytics-zoo/) from pip though, because it cannot find the dependency of `bigdl.util`. Not sure if this package version is outdated, because `bigdl.util` seems to exist only in the previous versions... I probably can still use core version of BigDL estimator, if I figure out how to pass different features to different layers of the model. Is there a doc for that?

**Comment by Ishitori** [comment]
Got it, thanks!
