### ISSUE TITLE
ResNet 50 throw exception: index out of bound.

### ISSUE THREAD

**Issue by i8run** [intel-analytics/BigDL#783]
Error message is below,

```
2017-04-16 13:24:55 ERROR ThreadPool$:98 - Error: java.lang.IllegalArgumentException: requirement failed: index out of bound
        at scala.Predef$.require(Predef.scala:233)
        at com.intel.analytics.bigdl.tensor.DenseTensor.com$intel$analytics$bigdl$tensor$DenseTensor$$getOffset(DenseTensor.scala:566)
        at com.intel.analytics.bigdl.tensor.DenseTensor.valueAt(DenseTensor.scala:519)
        at com.intel.analytics.bigdl.nn.ClassNLLCriterion$mcF$sp$$anonfun$updateOutput$mcF$sp$3.apply(ClassNLLCriterion.scala:93)
        at com.intel.analytics.bigdl.nn.ClassNLLCriterion$mcF$sp$$anonfun$updateOutput$mcF$sp$3.apply(ClassNLLCriterion.scala:92)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
        at com.intel.analytics.bigdl.utils.ThreadPool$$anon$1.execute(ThreadPool.scala:191)
        at scala.concurrent.impl.Future$.apply(Future.scala:31)
        at scala.concurrent.Future$.apply(Future.scala:485)
        at com.intel.analytics.bigdl.utils.ThreadPool.invoke(ThreadPool.scala:156)
        at com.intel.analytics.bigdl.nn.ClassNLLCriterion$mcF$sp.updateOutput$mcF$sp(ClassNLLCriterion.scala:92)
        at com.intel.analytics.bigdl.nn.ClassNLLCriterion$mcF$sp.updateOutput(ClassNLLCriterion.scala:67)
        at com.intel.analytics.bigdl.nn.ClassNLLCriterion$mcF$sp.updateOutput(ClassNLLCriterion.scala:56)
        at com.intel.analytics.bigdl.nn.abstractnn.AbstractCriterion.forward(AbstractCriterion.scala:70)
        at com.intel.analytics.bigdl.optim.LocalOptimizer$$anonfun$5$$anonfun$apply$1.apply$mcD$sp(LocalOptimizer.scala:114)
        at com.intel.analytics.bigdl.optim.LocalOptimizer$$anonfun$5$$anonfun$apply$1.apply(LocalOptimizer.scala:107)
        at com.intel.analytics.bigdl.optim.LocalOptimizer$$anonfun$5$$anonfun$apply$1.apply(LocalOptimizer.scala:107)
        at com.intel.analytics.bigdl.utils.ThreadPool$$anonfun$invokeAndWait$1$$anonfun$apply$2.apply(ThreadPool.scala:95)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by i8run** [comment]
Because for ResNet_50 on ImageNet, we should make `"dataset"` to `DatasetType.ImageNet`. The default value of `dataset` is Cifar10.
