### ISSUE TITLE
com.intel.analytics.bigdl.tags.Integration tests fail on clean build

### ISSUE THREAD

**Issue by srowen** [intel-analytics/BigDL#810]
On a fresh checkout today and build with `-Pspark_2.1` on Ubuntu 17, I get 4 legitimate failures:

```
Lenet model train and validate
- should be correct *** FAILED ***
  java.lang.NumberFormatException: null
  at java.lang.Integer.parseInt(Integer.java:542)
  at java.lang.Integer.parseInt(Integer.java:615)
  at scala.collection.immutable.StringLike$class.toInt(StringLike.scala:272)
  at scala.collection.immutable.StringOps.toInt(StringOps.scala:29)
  at com.intel.analytics.bigdl.integration.SparkModeSpec$$anonfun$1.apply$mcV$sp(SparkModeSpec.scala:31)
  ...
Vgg model train and validate
- should be correct *** FAILED ***
  java.lang.NumberFormatException: null
  at java.lang.Integer.parseInt(Integer.java:542)
  at java.lang.Integer.parseInt(Integer.java:615)
  at scala.collection.immutable.StringLike$class.toInt(StringLike.scala:272)
  at scala.collection.immutable.StringOps.toInt(StringOps.scala:29)
  at com.intel.analytics.bigdl.integration.SparkModeSpec$$anonfun$2.apply$mcV$sp(SparkModeSpec.scala:37)

  ...

HdfsSpec:
save and load model from hdfs
- should be correct *** FAILED ***
  java.lang.IllegalArgumentException: requirement failed: hdfs path null/lenet.obj should have prefix 'hdfs:'
  ...
load minist from hdfs
- should be correct *** FAILED ***
  java.io.FileNotFoundException: File null/t10k-images-idx3-ubyte does not exist
  ...
```

In all cases the tests are expecting some system properties to be set that aren't, pointing to data locations. These are also the only two tagged as `com.intel.analytics.bigdl.tags.Integration` tests, and I see several build profiles try to exclude them, but they are not by default.

Should they be excluded by default somehow?

**Comment by yiheng** [comment]
Looks like this is related with https://github.com/intel-analytics/BigDL/pull/741. 

@luchy0120, please take a look at it.

**Comment by luchy0120** [comment]
@srowen , could you please show  me the complete maven command you use ?

**Comment by luchy0120** [comment]
@srowen , this issue is the same as #804 .

**Comment by srowen** [comment]
@luchy0120 Oh, the problem is that `activeByDefault` profiles are not active if any profile is specified. And I need to run with at least `-Pmac` which disables this profile then. Really, I think this needs to be flipped such that integration tests don't run unless a profile is turned on?

**Comment by srowen** [comment]
Oh, I think this was actually resolved just recently by https://github.com/intel-analytics/BigDL/commit/2a70a2836c037a48a47d8ed4139ced4897ce58a9 which removes this profile anyway.
