### ISSUE TITLE
Missing bigdl python dependencies in trusted bigdata

### ISSUE THREAD

**Issue by Uxito-Ada** [intel-analytics/BigDL#8183]
Expected to init a python PPMLContext in trusted bigdata container, but found dependencies missing:

```
root@d980a8550fa6:/ppml# python
Python 3.8.10 (default, Mar 13 2023, 10:26:41)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from bigdl.ppml.ppml_context import *
path extended
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/ppml/bigdl-ppml/src/bigdl/ppml/ppml_context.py", line 17, in <module>
    from bigdl.ppml.api import *
  File "/ppml/bigdl-ppml/src/bigdl/ppml/api/__init__.py", line 18, in <module>
    from bigdl.dllib.nncontext import *
ModuleNotFoundError: No module named 'bigdl.dllib'
```

Encountered when submitting python codes in both jupyter notebook and python CLI.
@ShanSimu

**Comment by Uxito-Ada** [comment]
Seems only `/ppml/bigdl-ppml` in `PYTHONPATH`:
```
root@d980a8550fa6:/ppml/bigdl-ppml# echo $PYTHONPATH
/usr/lib/python3.8:/usr/lib/python3.8/lib-dynload:/usr/local/lib/python3.8/dist-packages:/usr/lib/python3/dist-packages:/ppml/bigdl-ppml/src
```

While the other bigdl python codes are still unziped:
```
root@d980a8550fa6:/ppml# ls $BIGDL_HOME/python/
bigdl-dllib-spark_3.1.3-2.4.0-SNAPSHOT-python-api.zip     bigdl-spark_3.1.3-2.4.0-SNAPSHOT-python-api.zip
bigdl-friesian-spark_3.1.3-2.4.0-SNAPSHOT-python-api.zip  requirements/
bigdl-orca-spark_3.1.3-2.4.0-SNAPSHOT-python-api.zip      start-fgboost-server.py
bigdl-ppml-spark_3.1.3-2.4.0-SNAPSHOT-python-api.zip      start-fl-server.py
bigdl-serving-spark_3.1.3-2.4.0-SNAPSHOT-python-api.zip
```
@ShanSimu

**Comment by ShanSimu** [comment]
![image](https://github.com/intel-analytics/BigDL/assets/46640505/deaff072-292a-4937-8079-a9e4915da957)

fixed by https://github.com/intel-analytics/BigDL/pull/8195
