### ISSUE TITLE
Error when generating Imagenet sequence file

### ISSUE THREAD

**Issue by jzhusc** [intel-analytics/BigDL#825]
I am following the inception example
```
java -cp BigDL/dist/lib/bigdl-0.2.0-SNAPSHOT-jar-with-dependencies.jar com.intel.analytics.bigdl.models.utils.ImageNetSeqFileGenerator -f imagenet2/ -o imagenetSeq -p 4
```
The error is
```
Exception in thread "main" java.lang.NoClassDefFoundError: scala/Product
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at com.intel.analytics.bigdl.models.utils.ImageNetSeqFileGenerator.main(ImageNetSeqFileGenerator.scala)
Caused by: java.lang.ClassNotFoundException: scala.Product
	at java.net.URLClassLoader$1.run(URLClassLoader.java:359)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 13 more
```
I build BigDL using
```
bash make-dist.sh -P spark_2.0 -P scala_2.11
```
Also I can run cifar and lenet examples successfully.

**Comment by psyyz10** [comment]
Could you try to replace `BigDL/dist/lib/bigdl-0.2.0-SNAPSHOT-jar-with-dependencies.jar` with `BigDL/spark/dl/target/bigdl-0.2.0-SNAPSHOT-jar-with-dependencies-and-spark.jar`
Or using spark-submit to run this job.

**Comment by jzhusc** [comment]
@psyyz10 
Thx! That works!
Also, Does BigDL have official performance benchmark? I am running BigDL on a yarn cluster but don't if the speed (executor 100 core per executor 4 batch size 3200 speed 500+ records per second) is normal?
