### ISSUE TITLE
throw exception when running rnn example with cluster

### ISSUE THREAD

**Issue by zhangxiaoli73** [intel-analytics/BigDL#831]
throw exception when running rnn example with cluster

017-04-28 13:07:55 INFO  ThreadPool$:79 - Set mkl threads to 1 on thread 1
2017-04-28 13:08:00 INFO  Engine$:98 - Auto detect executor number and executor cores number
2017-04-28 13:08:00 INFO  Engine$:100 - Executor number is 4 and executor cores number is 28
2017-04-28 13:08:00 INFO  Engine$:279 - Find existing spark context. Checking the spark conf...
[Stage 0:=========================================>             (84 + 28) / 112]2017-04-28 13:08:03 ERROR TaskSetManager:70 - Task 3 in stage 1.0 failed 1 times; aborting job
Exception in thread "main" org.apache.spark.SparkException: Job aborted due to stage failure: Task 3 in stage 1.0 failed 1 times, most recent failure: Lost task 3.0 in stage 1.0 (TID 115, 172.168.2.159): java.io.FileNotFoundException: /root/zl/rnn/en-sent.bin (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at com.intel.analytics.bigdl.dataset.text.SentenceSplitter$$anonfun$apply$1.apply(SentenceSplitter.scala:60)
	at com.intel.analytics.bigdl.dataset.text.SentenceSplitter$$anonfun$apply$1.apply(SentenceSplitter.scala:55)

**Comment by yiheng** [comment]
looks like some file can't be found
java.io.FileNotFoundException: /root/zl/rnn/en-sent.bin (No such file or directory)

**Comment by zhangxiaoli73** [comment]
Yeah, I input the right file path, but the rnn example not loads file on driver, but on every executor. So there is file not found exception.
