### ISSUE TITLE
LLM: Come Across undefined symbol `ggml_compute_forward_mul_mat_q_fp32` in when inferencing gptq2ggml model

### ISSUE THREAD

**Issue by leonardozcm** [intel-analytics/BigDL#8397]
To reproduce:
```bash
llm-convert ./vicuna-13B-1.1-GPTQ-4bit-128g --model-format gptq --model-family llama --outfile out
python test_gptq.py
```
test_gptq.py:
```python
from bigdl.llm.ggml.model.llama import Llama
# from llama_cpp import Llama
Llama(model_path="/root/changmin/BigDL/python/llm/out/bigdl_llm_llama_int4_from_gptq.bin")
```
output:
```
(changmin-chatllm) [root@spr-bkc-pc llm]# python test_gptq.py 
Traceback (most recent call last):
  File "/root/changmin/BigDL/python/llm/test_gptq.py", line 21, in <module>
    from bigdl.llm.ggml.model.llama import Llama
  File "/root/changmin/BigDL/python/llm/src/bigdl/llm/ggml/model/llama/__init__.py", line 22, in <module>
    from .llama_cpp import *
  File "/root/changmin/BigDL/python/llm/src/bigdl/llm/ggml/model/llama/llama_cpp.py", line 999, in <module>
    _lib.ggml_compute_forward_mul_mat_q_fp32.argtypes = [
  File "/opt/anaconda3/envs/changmin-chatllm/lib/python3.9/ctypes/__init__.py", line 395, in __getattr__
    func = self.__getitem__(name)
  File "/opt/anaconda3/envs/changmin-chatllm/lib/python3.9/ctypes/__init__.py", line 400, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /root/changmin/BigDL/python/llm/src/bigdl/llm/libs/libllama_avx512.so: undefined symbol: ggml_compute_forward_mul_mat_q_fp32
```
This may have something to do with pybinding? for if we apply `from llama_cpp import Llama`, this gptq model works.
```python
from llama_cpp import Llama
Llama(model_path="/root/changmin/BigDL/python/llm/out/bigdl_llm_llama_int4_from_gptq.bin")
```
@qiuxin2012

**Comment by rnwang04** [comment]
It seems that you used a old libllama_avx512.so which don't have `ggml_compute_forward_mul_mat_q_fp32`.
Just pip install nightly version may solve this

**Comment by leonardozcm** [comment]
> It seems that you used a old libllama_avx512.so which don't have `ggml_compute_forward_mul_mat_q_fp32`. Just pip install nightly version may solve this

That is right, we have fixed this, thanks a lot.

**Comment by leonardozcm** [comment]
Validate gptq model works fine, will close this issue.
