### ISSUE TITLE
Optimize Bert_Large with int8_ipex by BigDL NANO

### ISSUE THREAD

**Issue by Hanyu-Jin** [intel-analytics/BigDL#8466]
When I try to optimze Bert_large with int8_ipex by InferenceOptimizer.optimize(), I meet the following errors.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/bigdl/nano/pytorch/inference/optimizer.py", line 486, in optimize
    latency_calculate_helper(latency_sample_num, baseline_time,
  File "/usr/local/lib/python3.8/dist-packages/bigdl/nano/utils/common/optimizer/latency.py", line 29, in latency_calculate_helper
    func(*args)
  File "/usr/local/lib/python3.8/dist-packages/bigdl/nano/pytorch/inference/optimizer.py", line 471, in func_test
    model(input_sample)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1199, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/bigdl/nano/pytorch/model.py", line 34, in forward
    outputs = self.forward_step(*inputs, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/bigdl/nano/pytorch/model.py", line 46, in forward_step
    return self.model(*inputs, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1199, in _call_impl
    return forward_call(*input, **kwargs)
RuntimeError: forward() Expected a value of type 'Tensor' for argument 'x' but instead found type 'dict'.
Position: 1
Value: {'input_ids': tensor([[  101,  2023, 16958,  2204,  1012,   102,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0]])}
Declaration: forward(__torch__.intel_extension_for_pytorch.quantization._quantize_utils.___torch_mangle_2900.QuantizationDispatchModule self, Tensor x, Tensor x, Tensor x) -> Dict(str, Tensor)
Cast error details: Unable to cast {'input_ids': tensor([[  101,  2023, 16958,  2204,  1012,   102,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0]])} to Tensor
----------static_int8_ipex failed to forward----------


==========================Optimization Results==========================
 -------------------------------- ---------------------- --------------
|             method             |        status        | latency(ms)  |
 -------------------------------- ---------------------- --------------
|            original            |      successful      |    489.19    |
|        static_int8_ipex        |   fail to forward    |     None     |
 -------------------------------- ---------------------- --------------
Optimization cost 80.3s in total.
===========================Stop Optimization===========================
2023-07-06 04:01:44,219 - bigdl.nano.utils.common.log4Error - ERROR -

****************************Usage Error************************
Unable to get the specified model as it doesn't exist in optimized_model_dict.
2023-07-06 04:01:44,219 - bigdl.nano.utils.common.log4Error - ERROR -

****************************Call Stack*************************

```

It seems that NANO wrap the dict with tuple which causes the forward fuction error.

The code is here:
```
import ast
import torch
import logging
import transformers
from torch import nn
import os
import json
import pandas as pd
import numpy as np
from bigdl.nano.pytorch import InferenceOptimizer
from torch.utils.data.dataset import TensorDataset
from torch.utils.data import DataLoader, Dataset

from transformers import AutoModelForSequenceClassification, AutoTokenizer, BertForSequenceClassification, BertTokenizer
from transformers import BertTokenizer, BertModel, AdamW
import intel_extension_for_pytorch as ipex

class NeuralNetwork(nn.Module):

    def __init__(self, model_dir):
        super(NeuralNetwork, self).__init__()
        # TODO: fix this
        self.bert_encoder = AutoModelForSequenceClassification.from_pretrained(model_dir)

    def forward(self, x=None, *args, **kwargs):
        if isinstance(x, tuple):
            if isinstance(x[0], dict):
                bert_output = self.bert_encoder(**(x[0]))
            else:
                bert_output = self.bert_encoder(*x)
        elif isinstance(x, dict):
            bert_output = self.bert_encoder(**x)
        else:
            bert_output = self.bert_encoder(*args, **kwargs)
        return bert_output

cls_model_dir = 
save_dir = 
device = 'cpu'

cls_model = NeuralNetwork(cls_model_dir)
cls_model.to(device)
cls_model.eval()

max_seq_len = 55
batch_size = 1

# load tokenizer
tokenizer = BertTokenizer.from_pretrained(model_dir)

texts = "This tastes good."
encoded_input = tokenizer(texts,
                      padding='max_length',
                      truncation=True,
                      max_length=55,
                      return_tensors='pt')
encoded_input_dict = dict(encoded_input)
encoded_input_tuple = tuple(encoded_input_dict.values())
cls_model.to(device)
cls_model.eval()

optimizer = InferenceOptimizer()
optimizer.optimize(
    cls_model,
    training_data=encoded_input_dict,
    input_sample=encoded_input_dict,
    includes=['static_int8_ipex'], thread_num=1)
for method in InferenceOptimizer.ALL_INFERENCE_ACCELERATION_METHOD.keys():
    try:
        InferenceOptimizer.save(optimizer.get_model(method), os.path.join(save_dir, method))
        # print(method)
    except:
        pass
```

**Comment by rnwang04** [comment]
Thansk for reporting this issue!
After my debugging, I found actually this case has exposed many new problems.
At first, above error was caused by ipex quantized model itself doesn't support such dict input in version 1.13.
So, you need to upgrade to torch/ipex 2.0 first by `pip install --pre bigdl-nano[pytorch_20]`.
Then after several internal bugs were solve by https://github.com/intel-analytics/BigDL/pull/8473, this remains a very strange problem here:
**ipex quantized bert model has some potential  conflict with torch.inference_mode()**
For example, below code will cause `RuntimeError: bad optional access`
```python
# way1, fails
ipex_quantize_bert = ...
with torch.inference_mode():
    ipex_quantize_bert(input_sample)
    ipex_quantize_bert(input_sample)
```
However, below two cases work fine.
```python
# way2, ok
ipex_quantize_bert = ...
with torch.no_grad():
    ipex_quantize_bert(input_sample)
    ipex_quantize_bert(input_sample)
```
```python
# way3, ok
ipex_quantize_bert = ...
ipex_quantize_bert(input_sample)
ipex_quantize_bert(input_sample)
with torch.inference_mode():
    ipex_quantize_bert(input_sample)
    ipex_quantize_bert(input_sample)
```

Now I take a workaround like above way3 in Nano to make it work now, and I will raise a related issue for ipex regarding this problem.
This problem is hard to cope with as we can't replace `torch.inference_mode()` with `torch.no_grad()` as some known performance issue.
