### ISSUE TITLE
Initializing orca context p4javaerror with code - init_orca_context(init_ray_on_spark=True)

### ISSUE THREAD

**Issue by Madhustat** [intel-analytics/BigDL#8588]
Initializing orca context
Current pyspark location is : /home/ubuntu/spark-3.2.2-bin-hadoop3.2/python/lib/pyspark.zip/pyspark/__init__.py
Start to getOrCreate SparkContext
pyspark_submit_args is: --jars '/opt/easydata-app/external-jars/hadoop-common-3.2.1.jar,/opt/easydata-app/external-jars/hadoop-aws-3.3.1.jar,/opt/easydata-app/external-jars/spark-nlp_2.12-4.0.2.jar,/opt/easydata-app/external-jars/snowflake-jdbc-3.13.10.jar,/opt/easydata-app/external-jars/spark-snowflake_2.12-2.10.0-spark_3.2.jar,/opt/easydata-app/external-jars/tensorflow-cpu_2.12-0.4.2.jar,/opt/easydata-app/external-jars/xgboost4j-spark_2.12-1.7.5.jar,/opt/easydata-app/external-jars/xgboost4j_2.12-1.7.5.jar' --driver-class-path /home/ubuntu/.local/lib/python3.9/site-packages/bigdl/share/dllib/lib/bigdl-dllib-spark_2.4.6-2.4.0-SNAPSHOT-jar-with-dependencies.jar:/home/ubuntu/.local/lib/python3.9/site-packages/bigdl/share/core/lib/all-2.4.0-20230420.050641-1.jar:/home/ubuntu/.local/lib/python3.9/site-packages/bigdl/share/friesian/lib/bigdl-friesian-spark_2.4.6-2.4.0-SNAPSHOT-jar-with-dependencies.jar:/home/ubuntu/.local/lib/python3.9/site-packages/bigdl/share/orca/lib/bigdl-orca-spark_2.4.6-2.4.0-SNAPSHOT-jar-with-dependencies.jar pyspark-shell
/home/ubuntu/.local/lib/python3.9/site-packages/bigdl/orca/common.py:225: Warning: Cores not specified, using 2 cores per node by default.
  warnings.warn("Cores not specified, using 2 cores per node by default.", Warning)
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/home/ubuntu/spark-3.2.2-bin-hadoop3.2/jars/spark-unsafe_2.12-3.2.2.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2023-07-20 07:51:27 WARN  NativeCodeLoader:60 - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
2023-07-20 07:51:28 WARN  Utils:69 - Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.

****************************Usage Error************************
An error occurred while calling o46.initEngine.
: java.lang.NoClassDefFoundError: scala/Product$class
	at com.intel.analytics.bigdl.dllib.utils.MklBlas$.<init>(Engine.scala:37)
	at com.intel.analytics.bigdl.dllib.utils.MklBlas$.<clinit>(Engine.scala)
	at com.intel.analytics.bigdl.dllib.utils.Engine$.<init>(Engine.scala:225)
	at com.intel.analytics.bigdl.dllib.utils.Engine$.<clinit>(Engine.scala)
	at com.intel.analytics.bigdl.dllib.utils.python.api.PythonBigDL.initEngine(PythonBigDL.scala:2517)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassNotFoundException: scala.Product$class
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 17 more

****************************Call Stack*************************
2023-07-20 07:51:31,520 Thread-4 WARN The bufferSize is set to 4000 but bufferedIo is false: false
2023-07-20 07:51:31,522 Thread-4 WARN The bufferSize is set to 4000 but bufferedIo is false: false
2023-07-20 07:51:31,522 Thread-4 WARN The bufferSize is set to 4000 but bufferedIo is false: false
2023-07-20 07:51:31,523 Thread-4 WARN The bufferSize is set to 4000 but bufferedIo is false: false
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
Cell In[2], line 1
----> 1 init_orca_context(init_ray_on_spark=True)

File ~/.local/lib/python3.9/site-packages/bigdl/orca/common.py:262, in init_orca_context(cluster_mode, runtime, cores, memory, num_nodes, init_ray_on_spark, **kwargs)
    260         spark_args["python_location"] = kwargs["python_location"]
    261     from bigdl.dllib.nncontext import init_spark_on_local
--> 262     sc = init_spark_on_local(cores, **spark_args)
    263 elif cluster_mode == "spark-submit" or cluster_mode == "bigdl-submit":
    264     from bigdl.dllib.nncontext import init_nncontext

File ~/.local/lib/python3.9/site-packages/bigdl/dllib/nncontext.py:53, in init_spark_on_local(cores, conf, python_location, spark_log_level, redirect_spark_log)
     50 runner = SparkRunner(spark_log_level=spark_log_level,
     51                      redirect_spark_log=redirect_spark_log)
     52 set_python_home()
---> 53 return runner.init_spark_on_local(cores=cores, conf=conf,
     54                                   python_location=python_location)

File ~/.local/lib/python3.9/site-packages/bigdl/dllib/utils/spark.py:63, in SparkRunner.init_spark_on_local(self, cores, conf, python_location)
     61 master = "local[{}]".format(cores)
     62 zoo_conf = init_spark_conf(conf).setMaster(master)
---> 63 sc = init_internal_nncontext(conf=zoo_conf, spark_log_level=self.spark_log_level,
     64                              redirect_spark_log=self.redirect_spark_log)
     65 print("Successfully got a SparkContext")
     66 return sc

File ~/.local/lib/python3.9/site-packages/bigdl/dllib/nncontext.py:671, in init_internal_nncontext(conf, spark_log_level, redirect_spark_log)
    669     redire_spark_logs()
    670     show_bigdl_info_logs()
--> 671 init_engine()
    672 set_python_home()
    673 return sc

File ~/.local/lib/python3.9/site-packages/bigdl/dllib/utils/common.py:444, in init_engine(bigdl_type)
    443 def init_engine(bigdl_type="float"):
--> 444     callBigDlFunc(bigdl_type, "initEngine")
    445     # Spark context is supposed to have been created when init_engine is called
    446     get_spark_context()._jvm.org.apache.spark.bigdl.api.python.BigDLSerDe.initialize()

File ~/.local/lib/python3.9/site-packages/bigdl/dllib/utils/common.py:634, in callBigDlFunc(bigdl_type, name, *args)
    632     # if the invoked method exist but something else went wrong, throw the exception
    633     if not re.match(r'.*Method.*does not exist', str(e), flags=re.DOTALL):
--> 634         invalidOperationError(False, str(e), cause=e)
    635 else:
    636     return result

File ~/.local/lib/python3.9/site-packages/bigdl/dllib/utils/log4Error.py:40, in invalidOperationError(condition, errMsg, fixMsg, cause)
     38 outputUserMessage(errMsg, fixMsg)
     39 if cause:
---> 40     raise cause
     41 else:
     42     raise RuntimeError(errMsg)

File ~/.local/lib/python3.9/site-packages/bigdl/dllib/utils/common.py:629, in callBigDlFunc(bigdl_type, name, *args)
    627 try:
    628     api = getattr(jinvoker, name)
--> 629     result = callJavaFunc(api, *args)
    630 except Exception as e:
    631     error = e

File ~/.local/lib/python3.9/site-packages/bigdl/dllib/utils/common.py:683, in callJavaFunc(func, *args)
    681 """ Call Java Function """
    682 gateway = _get_gateway()
--> 683 result = func(*args)
    684 return _java2py(gateway, result)

File ~/spark-3.2.2-bin-hadoop3.2/python/lib/py4j-0.10.9.5-src.zip/py4j/java_gateway.py:1321, in JavaMember.__call__(self, *args)
   1315 command = proto.CALL_COMMAND_NAME +\
   1316     self.command_header +\
   1317     args_command +\
   1318     proto.END_COMMAND_PART
   1320 answer = self.gateway_client.send_command(command)
-> 1321 return_value = get_return_value(
   1322     answer, self.gateway_client, self.target_id, self.name)
   1324 for temp_arg in temp_args:
   1325     temp_arg._detach()

File ~/spark-3.2.2-bin-hadoop3.2/python/lib/py4j-0.10.9.5-src.zip/py4j/protocol.py:326, in get_return_value(answer, gateway_client, target_id, name)
    324 value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
    325 if answer[1] == REFERENCE_TYPE:
--> 326     raise Py4JJavaError(
    327         "An error occurred while calling {0}{1}{2}.\n".
    328         format(target_id, ".", name), value)
    329 else:
    330     raise Py4JError(
    331         "An error occurred while calling {0}{1}{2}. Trace:\n{3}\n".
    332         format(target_id, ".", name, value))

Py4JJavaError: An error occurred while calling o46.initEngine.
: java.lang.NoClassDefFoundError: scala/Product$class
	at com.intel.analytics.bigdl.dllib.utils.MklBlas$.<init>(Engine.scala:37)
	at com.intel.analytics.bigdl.dllib.utils.MklBlas$.<clinit>(Engine.scala)
	at com.intel.analytics.bigdl.dllib.utils.Engine$.<init>(Engine.scala:225)
	at com.intel.analytics.bigdl.dllib.utils.Engine$.<clinit>(Engine.scala)
	at com.intel.analytics.bigdl.dllib.utils.python.api.PythonBigDL.initEngine(PythonBigDL.scala:2517)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassNotFoundException: scala.Product$class
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 17 more

**Comment by qiuxin2012** [comment]
Looks like your spark version and bigdl version are not matched.
BigDL you installed is builded with spark2.4, but you has installed spark 3.2.2 too.
You You could uninstall all the packages of BigDL as follows:
```
pip uninstall bigdl-dllib bigdl-core bigdl-tf bigdl-math bigdl-orca bigdl-chronos bigdl-friesian bigdl-nano bigdl-serving bigdl
```
and install bigdl with spark3 , see https://bigdl.readthedocs.io/en/latest/doc/UserGuide/python.html#bigdl-on-spark-3

**Comment by hkvision** [comment]
'PYTHONPATH': '/home/ubuntu/spark-3.2.2-bin-hadoop3.2/python/lib/pyspark.zip:/home/ubuntu/spark-3.2.2-bin-hadoop3.2/python/lib/py4j-0.10.9.5-src.zip'
Seems the pyspark is set to your pythonpath, can you remove this setting in your environment?
BTW, seems you are not using conda environment. Conda is recommended and mainly used/tested by us, is it possible for you to switch to a conda environment?

**Comment by hkvision** [comment]
```
thd = ThresholdDetector()
thd.set_params(trend_threshold=(0, 85))
```
@plusbang Could you take a look at it for the lastest API?

**Comment by plusbang** [comment]
> ```
> thd = ThresholdDetector()
> thd.set_params(trend_threshold=(0, 85))
> ```
> 
> @plusbang Could you take a look at it for the lastest API?

yeah, we changed API of `ThresholdDetector` before, the latest usage is as you listed. More details can be found in https://bigdl.readthedocs.io/en/latest/doc/PythonAPI/Chronos/anomaly_detectors.html#bigdl.chronos.detector.anomaly.th_detector.ThresholdDetector.set_params.

**Comment by Madhustat** [comment]
Yes after update of Chronos library this is working

**Comment by hkvision** [comment]
Thanks for the confirmation, will close this issue first. We will follow-up on the new issue.
