### ISSUE TITLE
openllama 13b model with BigdlNativeForCausalLM use transformer int4 will cause error during generate

### ISSUE THREAD

**Issue by ZhaoqiongZ** [intel-analytics/BigDL#8615]
model: openllama-13b:  https://huggingface.co/openlm-research/open_llama_13b
usage:
```
from bigdl.llm.transformers import BigdlNativeForCausalLM
from transformers import AutoTokenizer
import time

from bigdl.llm.transformers import AutoModelForCausalLM


llm = BigdlNativeForCausalLM.from_pretrained(

        pretrained_model_name_or_path="/home/zhaoqion/llm/openllama-out/bigdl_llm_llama_q4_0.bin",

        model_family="llama",

        n_threads=16)

# # llm = AutoModelForCausalLM.from_pretrained("/home/zhaoqion/llm/open_llama_13b", load_in_4bit=True)
# # llm.save_low_bit("/home/zhaoqion/llm/openllama_int4")
# llm = AutoModelForCausalLM.load_low_bit("/home/zhaoqion/llm/openllama_int4")

tokenizer = AutoTokenizer.from_pretrained("/home/zhaoqion/llm/open_llama_13b")

start = time.time()

tokens_id = tokenizer("Q: What is the book you recommend for learning math?\nA:",  return_tensors="pt").input_ids
token_time = time.time()
# print("token input",tokens_id)
output_tokens_id = llm.generate(tokens_id, max_new_tokens=256)
generate_time = time.time()

output = tokenizer.batch_decode(output_tokens_id)
```

BigdlNativeForCausalLM will trigger the error

```
bigdl-llm: loading model from /home/zhaoqion/llm/openllama-out/bigdl_llm_llama_q4_0.bin
loading bigdl-llm model: format     = ggjt v3 (latest)
loading bigdl-llm model: n_vocab    = 32000
loading bigdl-llm model: n_ctx      = 512
loading bigdl-llm model: n_embd     = 5120
loading bigdl-llm model: n_mult     = 256
loading bigdl-llm model: n_head     = 40
loading bigdl-llm model: n_layer    = 40
loading bigdl-llm model: n_rot      = 128
loading bigdl-llm model: ftype      = 2 (mostly Q4_0)
loading bigdl-llm model: n_ff       = 13824
loading bigdl-llm model: n_parts    = 1
loading bigdl-llm model: model size = 13B
loading bigdl-llm model: ggml ctx size = 6595.81 MB
loading bigdl-llm model: mem required  = 8643.81 MB (+ 1608.00 MB per state)
....................................................................................................
loading bigdl-llm model: kv self size  =  400.00 MB
AVX = 1 | AVX2 = 1 | AVX512 = 1 | AVX512_VBMI = 0 | AVX512_VNNI = 1 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 | 
You are using the legacy behaviour of the <class 'transformers.models.llama.tokenization_llama.LlamaTokenizer'>. This means that tokens that come after special tokens will not be properly handled. We recommend you to read the related pull request available at https://github.com/huggingface/transformers/pull/24565
Traceback (most recent call last):
  File "/home/zhaoqion/llm/openllama_generator_int4.py", line 27, in <module>
    output_tokens_id = llm.generate(tokens_id, max_new_tokens=256)
  File "/home/zhaoqion/miniconda3/envs/bigdl-llm/lib/python3.9/site-packages/bigdl/llm/ggml/model/generation/utils.py", line 143, in generate
    if inputs and len(inputs) > 0:
RuntimeError: Boolean value of Tensor with more than one value is ambiguous
```

with AutoModelForCausalLM.load_low_bit("/home/zhaoqion/llm/openllama_int4") , the inference works but there is memory issue, FP32 has a 50GB memory peak , but INT4 will have a 54GB memory peak

**Comment by leonardozcm** [comment]
> with AutoModelForCausalLM.load_low_bit("/home/zhaoqion/llm/openllama_int4") , the inference works but there is memory issue, FP32 has a 50GB memory peak , but INT4 will have a 54GB memory peak

hi zhaoqiong, for this problem this fix may help https://github.com/intel-analytics/BigDL/pull/8600, may you try the latest bigdl-llm?

**Comment by plusbang** [comment]
About the RuntimeError of using `BigdlNativeForCausalLM`, you can change `tokens_id = tokenizer("Q: What is the book you recommend for learning math?\nA:",  return_tensors="pt").input_ids` to `tokens_id = tokenizer("Q: What is the book you recommend for learning math?\nA:").input_ids` to workaround. BTW, we will fix the bug of `generate` when the input `token_ids` is tensor as soon as possible.

**Comment by ZhaoqiongZ** [comment]
Hi @leonardozcm , sure I will try it!

**Comment by ZhaoqiongZ** [comment]
Hi @plusbang , thanks for the workaround， I will try it and look forward to your future work!

**Comment by hkvision** [comment]
Is this issue OK to close?

**Comment by shane-huang** [comment]
PR #8620  fixed this issue so close it.
