### ISSUE TITLE
wrong with bigdl nano Accelerate PyTorch Inference using Intel ARC series dGPU 

### ISSUE THREAD

**Issue by wiiliam-china** [intel-analytics/BigDL#8675]
When I following the operation in 'bigdl.readthedocs.io/en/latest/doc/Nano', I came across a wrong when I use  'Accelerate PyTorch Inference using Intel ARC series dGPU'  . 
The warning is
"/usr/local/lib/python3.10/dist-packages/intel_extension_for_pytorch/frontend.py:447: UserWarning: For XPU device, the split master weight is unsupported for now, so temp to disable it
  warnings.warn("For XPU device, the split master weight is unsupported for now, so temp to disable it")
/usr/local/lib/python3.10/dist-packages/intel_extension_for_pytorch/frontend.py:457: UserWarning: For XPU device to save valuable device memory, temp to do optimization on inplaced model, so    make inplace to be true warnings.warn( 
/usr/local/lib/python3.10/dist-packages/intel_extension_for_pytorch/frontend.py:464: UserWarning: For XPU, the weight prepack and sample input are disabled. The onednn layout  is automatically chosen to use"
So how can solve the problem?

**Comment by rnwang04** [comment]
Hi, thanks for reporting! Actually, they are not errors, intel_extension_for_pytorch will raise some warnings which is a common behavior.
Usually, if these warnings do not affect your program's execution, you can ignore them.
If the results/performance you obtain are not normal, you can make corresponding corrections based on these warnings.
Can your current program run normally?

**Comment by wiiliam-china** [comment]
> Hi, thanks for reporting! Actually, they are not errors, intel_extension_for_pytorch will raise some warnings which is a common behavior. Usually, if these warnings do not affect your program's execution, you can ignore them. If the results/performance you obtain are not normal, you can make corresponding corrections based on these warnings. Can your current program run normally?

I want use my intel arcGPU device, but with bigdlnano package I can't run code like "InferenceOptimizer.trace(model, device="GPU", use_ipex=True)". I have no idea about what happen and what should I deal with it.

**Comment by rnwang04** [comment]
> I want use my intel arcGPU device, but with bigdlnano package I can't run code like "InferenceOptimizer.trace(model, device="GPU", use_ipex=True)". I have no idea about what happen and what should I deal with it.

Could you please kindly provide more dedails about your OS / bigdlnano version  / model, and a complete error message?

**Comment by wiiliam-china** [comment]
> > I want use my intel arcGPU device, but with bigdlnano package I can't run code like "InferenceOptimizer.trace(model, device="GPU", use_ipex=True)". I have no idea about what happen and what should I deal with it.
> 
> Could you please kindly provide more dedails about your OS / bigdlnano version / model, and a complete error message?

My code below:

import torch
from torchvision import transforms
from torchvision.models import resnet18
from bigdl.nano.pytorch import InferenceOptimizer

image=Image.open('./XX.jpg')
input_tensor=preprocess(image)
input_batch=input_tensor.unsqueeze(0)

model = resnet18(pretrained=True)
acc_model = InferenceOptimizer.trace(model, device="GPU", use_ipex=True)
predictions = acc_model(input_batch)

and my code run erro is:
"usr/local/lib/python3.10/dist-packages/intel_extension_for_pytorch/frontend.py:447: UserWarning: For XPU device, the split master weight is unsupported for now, so temp to disable it
  warnings.warn("For XPU device, the split master weight is unsupported for now, so temp to disable it")
/usr/local/lib/python3.10/dist-packages/intel_extension_for_pytorch/frontend.py:457: UserWarning: For XPU device to save valuable device memory, temp to do optimization on inplaced model, so                     make inplace to be true
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/intel_extension_for_pytorch/frontend.py:464: UserWarning: For XPU, the weight prepack and sample input are disabled. The onednn layout                     is automatically chosen to use
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/intel_extension_for_pytorch/frontend.py:486: UserWarning: Conv BatchNorm folding failed during the optimize process.
  warnings.warn("Conv BatchNorm folding failed during the optimize process.")
Traceback (most recent call last):
  File "/tmp/resnet_bigdlnano_gpu_test.py", line 51, in <module>
    predictions = acc_model(input_batch)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/bigdl/nano/deps/ipex/ipex_inference_xpu_model.py", line 63, in forward
    return self.model(*inputs, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/fx/graph_module.py", line 658, in call_wrapped
    return self._wrapped_call(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/fx/graph_module.py", line 277, in __call__
    raise e
  File "/usr/local/lib/python3.10/dist-packages/torch/fx/graph_module.py", line 267, in __call__
    return super(self.cls, obj).__call__(*args, **kwargs)  # type: ignore[misc]
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "<eval_with_key>.2", line 5, in forward
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: could not create an engine"

**Comment by rnwang04** [comment]
@wiiliam-china Thanks, and could you please provide your os info / bigdl-nano version as well ?

**Comment by wiiliam-china** [comment]
> @wiiliam-china Thanks, and could you please provide your os info / bigdl-nano version as well ?

I use docker run from image:"docker pull intel/oneapi-basekit" , OS version is ubuntu 22.04
my python version is 3.10.12 ,
bigdl-nano by "pip install --pre bigdl-nano[pytorch_113_xpu] -f https://developer.intel.com/ipex-whl-stable-xpu"

**Comment by rnwang04** [comment]
Sorry for this late relay!
Although I don't reproduce the same issue, but I think it's maybe caused by the out-of-date ipex/torch version.
I have updated related dependency in BigDL-Nano with [this pr](https://github.com/intel-analytics/BigDL/pull/8774).
So, you can re-installation BigDL-Nano and test your code again tomorrow as this code change can be accessed as soon as tomorrow.
```bash
pip install --pre --upgrade bigdl-nano[pytorch_113_xpu] -f https://developer.intel.com/ipex-whl-stable-xpu
source bigdl-nano-init --gpu
```
or 
```bash
pip install --pre --upgrade bigdl-nano[pytorch_20_xpu] -f https://developer.intel.com/ipex-whl-stable-xpu
source bigdl-nano-init --gpu
```
