### ISSUE TITLE
LLaMA2 Native INT4 limits output tokens 512

### ISSUE THREAD

**Issue by KiwiHana** [intel-analytics/BigDL#8721]
LLaMA2 Native INT4 limits output tokens when set max_tokens=500 in llm(prompt, temperature=0.95,top_p=0.8,stream=True,max_tokens=500) 

```
******************** load model from local ************************
bigdl-llm: loading model from D:\PC_LLM_UI\benchmark\checkpoint\bigdl_llm_llama2_13b_q4_0.bin
loading bigdl-llm model: format     = ggjt v3 (latest)
loading bigdl-llm model: n_vocab    = 32000
loading bigdl-llm model: n_ctx      = 512
loading bigdl-llm model: n_embd     = 5120
loading bigdl-llm model: n_mult     = 256
loading bigdl-llm model: n_head     = 40
loading bigdl-llm model: n_layer    = 40
loading bigdl-llm model: n_rot      = 128
loading bigdl-llm model: ftype      = 2 (mostly Q4_0)
loading bigdl-llm model: n_ff       = 13824
loading bigdl-llm model: n_parts    = 1
loading bigdl-llm model: model size = 13B
loading bigdl-llm model: ggml ctx size = 6595.81 MB
loading bigdl-llm model: mem required  = 8643.81 MB (+ 1608.00 MB per state)
....................................................................................................
loading bigdl-llm model: kv self size  =  400.00 MB
AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 |
model load time (s)=  2.5879454612731934
inf_way =  4.1
llama 2 native INT4
--------------------  fast forward stream --------------------


****************************Usage Error************************
Requested tokens exceed context window of 512.


****************************Call Stack*************************
Traceback (most recent call last):
  File "D:\PC_LLM_UI\no_ui_LLM_demo_v0.4.py", line 330, in <module>
    for chunk in output:
  File "C:\Users\BigDL-LLM\miniconda3\envs\ui_llm\lib\site-packages\bigdl\llm\ggml\model\llama\llama.py", line 701, in _create_completion
    invalidInputError(len(prompt_tokens) + max_tokens <= int(llama_cpp.llama_n_ctx(self.ctx)),
  File "C:\Users\BigDL-LLM\miniconda3\envs\ui_llm\lib\site-packages\bigdl\llm\utils\common\log4Error.py", line 32, in invalidInputError
    raise RuntimeError(errMsg)
RuntimeError: Requested tokens exceed context window of 512.
```

```
def load(model_path, model_family, n_threads):
    from bigdl.llm.transformers import BigdlNativeForCausalLM
    llm = BigdlNativeForCausalLM.from_pretrained(
        pretrained_model_name_or_path=model_path,
        model_family=model_family,
        n_threads=n_threads)
    return llm

llm = load(model_path="D:\\PC_LLM_UI\\benchmark\\checkpoint\\bigdl_llm_llama2_13b_q4_0.bin",
model_family='llama',
n_threads=20)

prompt = "Once upon a time, there existed a little girl who liked to have adventures. She wanted to go to places and meet new people, and have fun"

output = llm(prompt, temperature=0.95,top_p=0.8,stream=True,max_tokens=500) # 
    for chunk in output:
        response += chunk["choices"][0]["text"]
```

**Comment by jason-dai** [comment]
I think we may need set `ctx_n` in `BigdlNativeForCausalLM`? @plusbang please take a look.

**Comment by plusbang** [comment]
When set `max_tokens=500`, token number of prompt and output is larger than maximum context size (default to be 512). Please specify `n_ctx` is larger than token number of prompt and output when calling `BigdlNativeForCausalLM.from_pretrained`, for example:

```python
llm = BigdlNativeForCausalLM.from_pretrained(
        pretrained_model_name_or_path=model_path,
        model_family=model_family,
        n_threads=n_threads,
        n_ctx=1024)
```

Note:

**Comment by KiwiHana** [comment]
@plusbang  Dear, Can I set max_tokens=2048, n_ctx=4096 ?

**Comment by plusbang** [comment]
> @plusbang Dear, Can I set max_tokens=2048, n_ctx=4096 ?

Sure.

**Comment by jason-dai** [comment]
> When set `max_tokens=500`, token number of prompt and output is larger than maximum context size (specify it through parameter `n_ctx`, default to be 512). Please make sure `n_ctx` is larger than token number of prompt and output when calling `BigdlNativeForCausalLM.from_pretrained`, for example:
> 
> ```python
> llm = BigdlNativeForCausalLM.from_pretrained(
>         pretrained_model_name_or_path=model_path,
>         model_family=model_family,
>         n_threads=n_threads,
>         n_ctx=1024)
> ```

Need to update the python doc with these parameters
