### ISSUE TITLE
IllegalArgumentException when enabling Spark dynamic allocation

### ISSUE THREAD

**Issue by ZeweiChen11** [intel-analytics/BigDL#879]
When training vgg model enabling Spark dynamic allocation on Spark 2.1, we encountered java.lang.IllegalArgumentException as following. Although we set spark.dynamicAllocation.minExecutors and spark.dynamicAllocation.maxExecutors properly, it also throws exception related to  spark.dynamicAllocation.maxExecutors.

17/05/12 14:55:46 INFO utils.ThreadPool$: Set mkl threads to 1 on thread 1
17/05/12 14:56:17 INFO utils.Engine$: Auto detect executor number and executor cores number
Exception in thread "main" java.lang.IllegalArgumentException: requirement failed: Engine.init: spark.dynamicAllocation.maxExecutors and spark.dynamicAllocation.minExecutors must be identical in dynamic allocation for BigDL
        at scala.Predef$.require(Predef.scala:224)
        at com.intel.analytics.bigdl.utils.Engine$.dynamicAllocationExecutor(Engine.scala:327)
        at com.intel.analytics.bigdl.utils.Engine$.sparkExecutorAndCore(Engine.scala:386)
        at com.intel.analytics.bigdl.utils.Engine$.init(Engine.scala:99)
        at com.intel.analytics.bigdl.models.inception.TrainInceptionV1$$anonfun$main$1.apply(Train.scala:37)
        at com.intel.analytics.bigdl.models.inception.TrainInceptionV1$$anonfun$main$1.apply(Train.scala:32)
        at scala.Option.map(Option.scala:146)
        at com.intel.analytics.bigdl.models.inception.TrainInceptionV1$.main(Train.scala:32)
        at com.intel.analytics.bigdl.models.inception.TrainInceptionV1.main(Train.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:743)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:187)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:212)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:126)

        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

**Comment by srowen** [comment]
How are you setting these values? it has worked for me.
Or, why enable dynamic allocation?

**Comment by jason-dai** [comment]
BigDL actually does not use dynamic allocation; as mentioned in the error message, "spark.dynamicAllocation.maxExecutors and spark.dynamicAllocation.minExecutors must be identical in dynamic allocation for BigDL"

**Comment by jack1981** [comment]
That was because your "spark.dynamicAllocation.enabled" was "true"
Turn it off if BigDL does not require 
--conf spark.dynamicAllocation.enabled=false

**Comment by chen116** [comment]
Hi,
As of now, BigDL is not able to run with dynamic resource allocation. is there any way to make it possible? I wish to have such ability for BigDL so I can test out my new mechanism for dynamic executor allocation for spark streaming application.

Thanks
