### ISSUE TITLE
langchain TransformersLLM does not work for latest pydantic

### ISSUE THREAD

**Issue by yangw1234** [intel-analytics/BigDL#8806]
The following error occurred when importing `TransformersLLM`.

Downgrading pydantic to 1.10.12 worked.
```
Traceback (most recent call last):
  File "/home/yang/BigDL/python/llm/example/langchain/transformers_int4/voiceassistant.py", line 26, in <module>
    from bigdl.llm.langchain.llms import TransformersLLM
  File "/home/yang/BigDL/python/llm/src/bigdl/llm/langchain/llms/__init__.py", line 26, in <module>
    from .bigdlllm import BigdlNativeLLM
  File "/home/yang/BigDL/python/llm/src/bigdl/llm/langchain/llms/bigdlllm.py", line 57, in <module>
    class BigdlNativeLLM(LLM):
  File "/home/yang/BigDL/python/llm/src/bigdl/llm/langchain/llms/bigdlllm.py", line 159, in BigdlNativeLLM
    @root_validator()
  File "/root/anaconda3/envs/yang-llm/lib/python3.9/site-packages/pydantic/deprecated/class_validators.py", line 228, in root_validator
    raise PydanticUserError(
pydantic.errors.PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.

For further information visit https://errors.pydantic.dev/2.3/u/root-validator-pre-skip
```

**Comment by shane-huang** [comment]
@Oscilloscope98 please take a look and see if we need to put this into tips and known issues.

**Comment by Oscilloscope98** [comment]
Refer to the document provided by `langchain` here: https://github.com/langchain-ai/langchain/blob/master/docs/extras/guides/pydantic_compatibility.md?plain=1, `langchain` continues to use `pydantic` v1 behavior.

If we use latest `langchain 0.0.277` (I have tested it with all examples except the voice assistant ones and it works), we could 
- either fix `pydantic` to `1.*` as shown [here](https://docs.pydantic.dev/latest/migration/#continue-using-pydantic-v1-features)
- or we could in our code, specify
   https://github.com/intel-analytics/BigDL/blob/main/python/llm/src/bigdl/llm/langchain/embeddings/bigdlllm.py#L52
   ```python
   from pydantic.v1 import BaseModel, Extra, Field, root_validator
   ```
   https://github.com/intel-analytics/BigDL/blob/main/python/llm/src/bigdl/llm/langchain/llms/bigdlllm.py#L51
   ```python
   from pydantic.v1 import Field, root_validator
   ```
   with `pydantic 2.*`

However, it seems that latest `chromadb 0.4.8` requires `pydantic>=1.9,<2.0`, we may need to choose the first option.
