### ISSUE TITLE
Resnet example fails on the latest master branch

### ISSUE THREAD

**Issue by fanshiqing** [intel-analytics/BigDL#882]
The [Resnet example](https://github.com/intel-analytics/BigDL/tree/master/spark/dl/src/main/scala/com/intel/analytics/bigdl/models/resnet) works well on [branch-0.1](https://github.com/intel-analytics/BigDL/tree/branch-0.1), but fails on the latest master branch.
Env: Spark-2.1.0, java-1.8.0, scala-2.11, OS: CentOS-7.1
Building command:
``$ bash make-dist.sh -P spark_2.1 -P scala_2.11``

Runing command:
```
dist/bin/bigdl.sh -- spark-submit --master yarn --driver-memory 6g --executor-memory 6g --num-executors 3 --executor-cores 8 --class com.intel.analytics.bigdl.models.resnet.Train dist/lib/bigdl-0.2.0-SNAPSHOT-jar-with-dependencies.jar -f cifar-10/ --batchSize 360 --optnet true --depth 20 --classes 10 --shortcutType A --nEpochs 6 --learningRate 0.1
```
The exception is as follows:
```
17/05/13 13:43:16 INFO ThreadPool$: Set mkl threads to 1 on thread 1
17/05/13 13:43:35 INFO Engine$: Auto detect executor number and executor cores number
17/05/13 13:43:35 INFO Engine$: Executor number is 3 and executor cores number is 8
17/05/13 13:43:35 INFO Engine$: Find existing spark context. Checking the spark conf...
17/05/13 13:43:48 INFO ResNet$:  | ResNet-20 CIFAR-10
17/05/13 13:43:48 INFO ResNet$: Share gradients in ResNet
17/05/13 13:43:48 INFO ResNet$: Initialize ResNet
17/05/13 13:43:48 INFO DistriOptimizer$: caching training rdd ...
17/05/13 13:43:55 INFO DistriOptimizer$: Cache thread models...
17/05/13 13:43:56 INFO DistriOptimizer$: Cache thread models... done
17/05/13 13:43:56 INFO DistriOptimizer$: config  {
	maxDropPercentage: 0.0
	computeThresholdbatchSize: 100
	warmupIterationNum: 200
	dropPercentage: 0.0
 }
17/05/13 13:43:56 INFO DistriOptimizer$: Shuffle data
17/05/13 13:43:56 INFO DistriOptimizer$: Shuffle data complete. Takes 0.045236s
[Stage 7:>                                                          (0 + 3) / 3]2017-05-13 13:43:59 ERROR TaskSetManager:70 - Task 2 in stage 7.0 failed 4 times; aborting job
17/05/13 13:43:59 ERROR DistriOptimizer$: Error: org.apache.spark.SparkException: Job aborted due to stage failure: Task 2 in stage 7.0 failed 4 times, most recent failure: Lost task 2.3 in stage 7.0 (TID 42, simple23, executor 1): java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: requirement failed
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$4$$anonfun$7.apply(DistriOptimizer.scala:212)
	at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$4$$anonfun$7.apply(DistriOptimizer.scala:212)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$4.apply(DistriOptimizer.scala:212)
	at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$4.apply(DistriOptimizer.scala:155)
	at org.apache.spark.rdd.ZippedPartitionsRDD2.compute(ZippedPartitionsRDD.scala:89)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:282)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: requirement failed
	at scala.Predef$.require(Predef.scala:212)
	at com.intel.analytics.bigdl.nn.Concat.updateGradInput(Concat.scala:156)
	at com.intel.analytics.bigdl.nn.Concat.updateGradInput(Concat.scala:42)
	at com.intel.analytics.bigdl.nn.Sequential.updateGradInput(Sequential.scala:50)
	at com.intel.analytics.bigdl.nn.ConcatTable.updateGradInput(ConcatTable.scala:136)
	at com.intel.analytics.bigdl.nn.ConcatTable.updateGradInput(ConcatTable.scala:34)
	at com.intel.analytics.bigdl.nn.abstractnn.AbstractModule.backward(AbstractModule.scala:174)
	at com.intel.analytics.bigdl.nn.Sequential.backward(Sequential.scala:85)
	at com.intel.analytics.bigdl.nn.Sequential.backward(Sequential.scala:85)
	at com.intel.analytics.bigdl.nn.Sequential.backward(Sequential.scala:82)
	at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$4$$anonfun$5$$anonfun$apply$2.apply$mcI$sp(DistriOptimizer.scala:203)
	at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$4$$anonfun$5$$anonfun$apply$2.apply(DistriOptimizer.scala:194)
	at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$4$$anonfun$5$$anonfun$apply$2.apply(DistriOptimizer.scala:194)
	at com.intel.analytics.bigdl.utils.ThreadPool$$anonfun$1$$anon$4.call(ThreadPool.scala:112)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1435)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1423)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1422)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1422)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:802)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:802)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:802)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1650)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1605)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1594)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:628)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1918)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1981)
	at org.apache.spark.rdd.RDD$$anonfun$reduce$1.apply(RDD.scala:1025)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:362)
	at org.apache.spark.rdd.RDD.reduce(RDD.scala:1007)
	at com.intel.analytics.bigdl.optim.DistriOptimizer$.optimize(DistriOptimizer.scala:256)
	at com.intel.analytics.bigdl.optim.DistriOptimizer.optimize(DistriOptimizer.scala:742)
	at com.intel.analytics.bigdl.models.resnet.Train$$anonfun$main$1.apply(Train.scala:92)
	at com.intel.analytics.bigdl.models.resnet.Train$$anonfun$main$1.apply(Train.scala:38)
	at scala.Option.map(Option.scala:146)
	at com.intel.analytics.bigdl.models.resnet.Train$.main(Train.scala:38)
	at com.intel.analytics.bigdl.models.resnet.Train.main(Train.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:738)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:187)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:212)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:126)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: requirement failed
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$4$$anonfun$7.apply(DistriOptimizer.scala:212)
	at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$4$$anonfun$7.apply(DistriOptimizer.scala:212)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$4.apply(DistriOptimizer.scala:212)
	at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$4.apply(DistriOptimizer.scala:155)
	at org.apache.spark.rdd.ZippedPartitionsRDD2.compute(ZippedPartitionsRDD.scala:89)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:282)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: requirement failed
	at scala.Predef$.require(Predef.scala:212)
	at com.intel.analytics.bigdl.nn.Concat.updateGradInput(Concat.scala:156)
	at com.intel.analytics.bigdl.nn.Concat.updateGradInput(Concat.scala:42)
	at com.intel.analytics.bigdl.nn.Sequential.updateGradInput(Sequential.scala:50)
	at com.intel.analytics.bigdl.nn.ConcatTable.updateGradInput(ConcatTable.scala:136)
	at com.intel.analytics.bigdl.nn.ConcatTable.updateGradInput(ConcatTable.scala:34)
	at com.intel.analytics.bigdl.nn.abstractnn.AbstractModule.backward(AbstractModule.scala:174)
	at com.intel.analytics.bigdl.nn.Sequential.backward(Sequential.scala:85)
	at com.intel.analytics.bigdl.nn.Sequential.backward(Sequential.scala:85)
	at com.intel.analytics.bigdl.nn.Sequential.backward(Sequential.scala:82)
	at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$4$$anonfun$5$$anonfun$apply$2.apply$mcI$sp(DistriOptimizer.scala:203)
	at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$4$$anonfun$5$$anonfun$apply$2.apply(DistriOptimizer.scala:194)
	at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$4$$anonfun$5$$anonfun$apply$2.apply(DistriOptimizer.scala:194)
	at com.intel.analytics.bigdl.utils.ThreadPool$$anonfun$1$$anon$4.call(ThreadPool.scala:112)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more

17/05/13 13:43:59 INFO DistriOptimizer$: Failed to recover since no model snapshotcheckpoint path is not set
```

**Comment by yiheng** [comment]
This is duplicated with #782

**Comment by yiheng** [comment]
We're investigating.
