### ISSUE TITLE
java.lang.NoSuchMethodError when training Inception v1 and VGG on spark 2.1.1

### ISSUE THREAD

**Issue by ZeweiChen11** [intel-analytics/BigDL#883]
BigDL train InceptionV1  with apache Spark2.1.1, spark is download from official website directly, training failed with below error. Build spark manually:
`./dev/make-distribution.sh  --tgz -Pyarn  -Phadoop-2.7  -Dhadoop.version=2.7.3  -DskipTests`
But we encountered the following issue when training both Inception v1 and VGG.
We trained with bigdl latest master branch using spark yarn-client mode.
BigDL building commands:
 `bash make-dist.sh -P spark_2.1`
Running command to train vgg: 
`./dist/bin/bigdl.sh -- spark-submit --class com.intel.analytics.bigdl.models.vgg.Train --master yarn --deploy-mode client --executor-cores=44 --num-executors=8 --executor-memory=300g --conf "spark.yarn.executor.memoryOverhead=60g" /opt/BigDL/dist/lib/bigdl-0.2.0-SNAPSHOT-jar-with-dependencies.jar --batchSize 1408 -f /root/workspace/dataset/cifar-10/ --checkpoint /mnt/disk2/vgg_cifar10_Spark2.1.1_yarn_client/`

Running command to train Inception v1: 
`./dist/bin/bigdl.sh -- spark-submit --class com.intel.analytics.bigdl.models.inception.TrainInceptionV1 --master yarn --deploy-mode client --executor-cores=44 --num-executors=8 --executor-memory=300g --conf "spark.yarn.executor.memoryOverhead=60g" /opt/BigDL/dist/lib/bigdl-0.2.0-SNAPSHOT-jar-with-dependencies.jar --batchSize 1408 -f hdfs:///user/root/sequence/ --checkpoint /mnt/disk2/inceptionV1_Spark2.1.1_yarn_client/  --learningRate 0.0896
`

17/05/12 15:15:21 INFO utils.ThreadPool$: Set mkl threads to 1 on thread 1
17/05/12 15:15:33 INFO utils.Engine$: Auto detect executor number and executor cores number
17/05/12 15:15:33 INFO utils.Engine$: Executor number is 8 and executor cores number is 44
17/05/12 15:15:33 INFO utils.Engine$: Find existing spark context. Checking the spark conf...
17/05/12 15:15:34 INFO optim.DistriOptimizer$: caching training rdd ...
17/05/12 15:18:00 INFO optim.DistriOptimizer$: Cache thread models...
[Stage 3:>                                                          (0 + 8) / 8]2017-05-12 15:18:06 ERROR TaskSetManager:70 - Task 7 in stage 3.0 failed 1 times; aborting job
Exception in thread "main" org.apache.spark.SparkException: Job aborted due to stage failure: Task 7 in stage 3.0 failed 1 times, most recent failure: Lost task 7.0 in stage 3.0 (TID 2025, bd16, executor 5): java.lang.NoSuchMethodError: org.apache.spark.storage.BlockManager.putBytes(Lorg/apache/spark/storage/BlockId;Lorg/apache/spark/util/io/ChunkedByteBuffer;Lorg/apache/spark/storage/StorageLevel;ZLscala/reflect/ClassTag;)Z
        at org.apache.spark.storage.BlockManagerWrapper$.putBytes(BlockManagerWrapper.scala:32)
        at com.intel.analytics.bigdl.parameters.AllReduceParameter.init(AllReduceParameter.scala:126)
        at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$12.apply(DistriOptimizer.scala:516)
        at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$12.apply(DistriOptimizer.scala:483)
        at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:797)
        at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:797)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
        at org.apache.spark.rdd.RDD$$anonfun$8.apply(RDD.scala:336)
        at org.apache.spark.rdd.RDD$$anonfun$8.apply(RDD.scala:334)
        at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1005)
        at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:996)
        at org.apache.spark.storage.BlockManager.doPut(BlockManager.scala:936)
        at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:996)
        at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:700)
        at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:334)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:285)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
        at org.apache.spark.scheduler.Task.run(Task.scala:99)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:322)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

Driver stacktrace:
        at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1435)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1423)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1422)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
        at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1422)
       at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:802)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:802)
        at scala.Option.foreach(Option.scala:257)
        at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:802)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1650)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1605)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1594)
        at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
        at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:628)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:1925)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:1938)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:1951)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:1965)
        at org.apache.spark.rdd.RDD.count(RDD.scala:1158)
        at com.intel.analytics.bigdl.optim.DistriOptimizer$.com$intel$analytics$bigdl$optim$DistriOptimizer$$initThreadModels(DistriOptimizer.scala:531)
        at com.intel.analytics.bigdl.optim.DistriOptimizer.optimize(DistriOptimizer.scala:718)
        at com.intel.analytics.bigdl.models.inception.TrainInceptionV1$$anonfun$main$1.apply(Train.scala:115)
        at com.intel.analytics.bigdl.models.inception.TrainInceptionV1$$anonfun$main$1.apply(Train.scala:32)
        at scala.Option.map(Option.scala:146)
        at com.intel.analytics.bigdl.models.inception.TrainInceptionV1$.main(Train.scala:32)
        at com.intel.analytics.bigdl.models.inception.TrainInceptionV1.main(Train.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:743)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:187)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:212)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:126)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

**Comment by ZeweiChen11** [comment]
We trained with bigdl latest master branch using spark yarn-client mode.
BigDL building commands:
 `bash make-dist.sh -P spark_2.1`
Running command to train vgg: 
`./dist/bin/bigdl.sh -- spark-submit --class com.intel.analytics.bigdl.models.vgg.Train --master yarn --deploy-mode client --executor-cores=44 --num-executors=8 --executor-memory=300g --conf "spark.yarn.executor.memoryOverhead=60g" /opt/BigDL/dist/lib/bigdl-0.2.0-SNAPSHOT-jar-with-dependencies.jar --batchSize 1408 -f /root/workspace/dataset/cifar-10/ --checkpoint /mnt/disk2/vgg_cifar10_Spark2.1.1_yarn_client/`

Running command to train Inception v1: 
`./dist/bin/bigdl.sh -- spark-submit --class com.intel.analytics.bigdl.models.inception.TrainInceptionV1 --master yarn --deploy-mode client --executor-cores=44 --num-executors=8 --executor-memory=300g --conf "spark.yarn.executor.memoryOverhead=60g" /opt/BigDL/dist/lib/bigdl-0.2.0-SNAPSHOT-jar-with-dependencies.jar --batchSize 1408 -f hdfs:///user/root/sequence/ --checkpoint /mnt/disk2/inceptionV1_Spark2.1.1_yarn_client/  --learningRate 0.0896
`

**Comment by yiheng** [comment]
Spark 2.1.1 was released this month, we haven't tested on it yet.

I notice the API **BlockManager.putBytes** is changed with an extra option parameter

https://github.com/apache/spark/blob/v2.1.0/core/src/main/scala/org/apache/spark/storage/BlockManager.scala#L758

https://github.com/apache/spark/blob/v2.1.1/core/src/main/scala/org/apache/spark/storage/BlockManager.scala#L758

Please use Spark 2.1.0

**Comment by ZeweiChen11** [comment]
We modified spark version in pom.xml. It still behaves like above exception.

**Comment by yiheng** [comment]
Just try and it worked on our side. Mmm, let me prepare a patch for this
