### ISSUE TITLE
Python level xpu time profiling for int4 operators (LinearQuant layers)

### ISSUE THREAD

**Issue by z71258847** [intel-analytics/BigDL#8868]
Hi team,

Currently I'm working on benchmarking [GPT-J](https://github.com/intel-analytics/BigDL/blob/main/python/llm/example/transformers/transformers_int4/GPU/gpt-j/generate.py) on ATSM with bigdl. I've checked that bigdl will replace torch.linear with LinearQuant in the GPT-J models. I'm wondering if there is a way on the python level to benchmark the xpu time of int4 operators (LinearQuant layers): currently the torch.profile from the IPEX front-end cannot capture the int4 operators of these layers.

**Comment by hkvision** [comment]
@rnwang04 Take a look?

**Comment by rnwang04** [comment]
We have supported this in today's PR, and you may access it as soon as tonight we release new wheel for bigdl-core-xe : )

**Comment by z71258847** [comment]
Hi,
With the latest build bigdl-llm-2.4.0b20230913 I've encountered the following issue while running GPT-J:

(ipex) gta@DUT7145ATSM:~/BigDL/python/llm/example/gpu/hf-transformers-models/gpt-j$ python generate.py
/home/gta/miniconda3/envs/ipex/lib/python3.9/site-packages/intel_extension_for_pytorch/frontend.py:611: UserWarning: Conv BatchNorm folding failed during the optimize process.
  warnings.warn(
/home/gta/miniconda3/envs/ipex/lib/python3.9/site-packages/intel_extension_for_pytorch/frontend.py:618: UserWarning: Linear BatchNorm folding failed during the optimize process.
  warnings.warn(
Traceback (most recent call last):
  File "/home/gta/BigDL/python/llm/example/gpu/hf-transformers-models/gpt-j/generate.py", line 48, in <module>
    model = ipex.optimize(model.eval(), dtype="float16", inplace=True)
  File "/home/gta/miniconda3/envs/ipex/lib/python3.9/site-packages/intel_extension_for_pytorch/frontend.py", line 637, in optimize
    utils._model_convert.replace_transformer_with_ipex_transformer(optimized_model)
  File "/home/gta/miniconda3/envs/ipex/lib/python3.9/site-packages/intel_extension_for_pytorch/nn/utils/_model_convert.py", line 130, in replace_transformer_with_ipex_transformer
    replace_transformer_with_ipex_transformer(child)
  File "/home/gta/miniconda3/envs/ipex/lib/python3.9/site-packages/intel_extension_for_pytorch/nn/utils/_model_convert.py", line 130, in replace_transformer_with_ipex_transformer
    replace_transformer_with_ipex_transformer(child)
  File "/home/gta/miniconda3/envs/ipex/lib/python3.9/site-packages/intel_extension_for_pytorch/nn/utils/_model_convert.py", line 127, in replace_transformer_with_ipex_transformer
    ipex_block = IPEXGPTJBlock(child)
  File "/home/gta/miniconda3/envs/ipex/lib/python3.9/site-packages/intel_extension_for_pytorch/nn/utils/_transformers.py", line 254, in __init__
    self.attn = IPEXGPTJAttention(module.attn)
  File "/home/gta/miniconda3/envs/ipex/lib/python3.9/site-packages/intel_extension_for_pytorch/nn/utils/_transformers.py", line 84, in __init__
    self.embed_positions = module.embed_positions
  File "/home/gta/miniconda3/envs/ipex/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'GPTJAttention' object has no attribute 'embed_positions'

**Comment by rnwang04** [comment]
Hi, @z71258847 .
I have verified on my side again, and this gpt-j examples works fine for me.
This is my version:
```bash
bigdl-core-xe               2.4.0b20230913
bigdl-llm                   2.4.0b20230913
intel-extension-for-pytorch 2.0.110+xpu
torch                       2.0.1a0+cxx11.abi
torchvision                 0.15.2a0+cxx11.abi
```
Are you sure your script and packge version is exactly the same with ours?

**Comment by z71258847** [comment]
Thanks for the reply! Just checked the code and found out that my transformers module is outdated. Updated the transformers package and it works now.
Also tried the torch profiling tool and it captures bigdl_qlinear_forward kernel now. Thanks for the help!
