### ISSUE TITLE
Pytorch/TF Estimator with Ray backend cannot run on Databricks

### ISSUE THREAD

**Issue by jenniew** [intel-analytics/BigDL#8870]
When create PyTorch/TF Estimator with Ray backend, it will give this error:

Py4JJavaError                             Traceback (most recent call last)
<command-3809454374114932> in <module>
     17 criterion = nn.CrossEntropyLoss()
     18 
---> 19 estimator = Estimator.from_torch(model=model_creator,
     20                                  optimizer=optimizer_creator,
     21                                  loss=criterion,

/databricks/python/lib/python3.8/site-packages/bigdl/orca/learn/pytorch/estimator.py in from_torch(model, optimizer, loss, metrics, backend, config, workers_per_node, scheduler_creator, use_tqdm, model_dir, sync_stats, log_level, log_to_driver)
     92         if backend in {"horovod", "ray"}:
     93             from bigdl.orca.learn.pytorch.pytorch_ray_estimator import PyTorchRayEstimator
---> 94             return PyTorchRayEstimator(model_creator=model,
     95                                        optimizer_creator=optimizer,  # type:ignore
     96                                        loss_creator=loss,

/databricks/python/lib/python3.8/site-packages/bigdl/orca/learn/pytorch/pytorch_ray_estimator.py in __init__(self, model_creator, optimizer_creator, loss_creator, metrics, scheduler_creator, config, use_tqdm, backend, workers_per_node, sync_stats, log_level)
    109 
    110         # todo remove ray_ctx to run on workers
--> 111         ray_ctx = OrcaRayContext.get()
    112         if not isinstance(model_creator, types.FunctionType):  # Torch model is also callable.
    113             invalidInputError(False,

/databricks/python/lib/python3.8/site-packages/bigdl/orca/ray/raycontext.py in get(cls, initialize)
    101             ray_ctx = OrcaRayContext._active_ray_context
    102             if initialize and not ray_ctx.initialized:
--> 103                 ray_ctx.init()
    104             return ray_ctx
    105         else:

/databricks/python/lib/python3.8/site-packages/bigdl/orca/ray/raycontext.py in init(self, driver_cores)
     75                 results = ray.init(**self.ray_args)
     76         else:
---> 77             results = self._ray_on_spark_context.init(driver_cores=driver_cores)
     78             self.num_ray_nodes = self._ray_on_spark_context.num_ray_nodes  # type: ignore
     79             self.ray_node_cpu_cores = self._ray_on_spark_context.ray_node_cpu_cores  # type: ignore

/databricks/python/lib/python3.8/site-packages/bigdl/orca/ray/ray_on_spark_context.py in init(self, driver_cores)
    602             else:
    603                 self.cluster_ips = self._gather_cluster_ips()
--> 604                 redis_address = self._start_cluster()
    605                 self._address_info = self._start_driver(num_cores=driver_cores,
    606                                                         redis_address=redis_address)

/databricks/python/lib/python3.8/site-packages/bigdl/orca/ray/ray_on_spark_context.py in _start_cluster(self)
    630             print("Launching Ray on cluster with Spark barrier mode")
    631             # The first ip would be used to launch ray master.
--> 632             process_infos = ray_rdd.barrier().mapPartitions(
    633                 self.ray_service.gen_ray_start(self.cluster_ips[0])).collect()
    634         else:

/databricks/spark/python/pyspark/rdd.py in collect(self)
    965         # Default path used in OSS Spark / for non-credential passthrough clusters:
    966         with SCCallSiteSync(self.context) as css:
--> 967             sock_info = self.ctx._jvm.PythonRDD.collectAndServe(self._jrdd.rdd())
    968         return list(_load_from_socket(sock_info, self._jrdd_deserializer))
    969 

/databricks/spark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1302 
   1303         answer = self.gateway_client.send_command(command)
-> 1304         return_value = get_return_value(
   1305             answer, self.gateway_client, self.target_id, self.name)
   1306 

/databricks/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
    115     def deco(*a, **kw):
    116         try:
--> 117             return f(*a, **kw)
    118         except py4j.protocol.Py4JJavaError as e:
    119             converted = convert_exception(e.java_exception)

/databricks/spark/python/lib/py4j-0.10.9-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    324             value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
    325             if answer[1] == REFERENCE_TYPE:
--> 326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
    328                     format(target_id, ".", name), value)

Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.collectAndServe.
: org.apache.spark.SparkException: Job aborted due to stage failure: Could not recover from a failed barrier ResultStage. Most recent failure reason: Stage failed because barrier task ResultTask(9, 1) finished unsuccessfully.
org.apache.spark.api.python.PythonException: 'RuntimeError: python_loc should be a valid directory path.'. Full traceback below:
Traceback (most recent call last):
  File "/databricks/spark/python/pyspark/worker.py", line 754, in main
    process()
  File "/databricks/spark/python/pyspark/worker.py", line 746, in process
    serializer.dump_stream(out_iter, outfile)
  File "/databricks/spark/python/pyspark/serializers.py", line 267, in dump_stream
    vs = list(itertools.islice(iterator, batch))
  File "/databricks/python/lib/python3.8/site-packages/bigdl/orca/ray/ray_on_spark_context.py", line 322, in _start_ray_services
    process_info = self._start_ray_node(command=self._gen_master_command(),
  File "/databricks/python/lib/python3.8/site-packages/bigdl/orca/ray/ray_on_spark_context.py", line 234, in _start_ray_node
    RayServiceFuncGenerator.start_ray_daemon(self.python_loc,
  File "/databricks/python/lib/python3.8/site-packages/bigdl/orca/ray/ray_on_spark_context.py", line 215, in start_ray_daemon
    invalidInputError(os.path.isdir(python_loc),
  File "/databricks/python/lib/python3.8/site-packages/bigdl/dllib/utils/log4Error.py", line 33, in invalidInputError
    raise RuntimeError(errMsg)
RuntimeError: python_loc should be a valid directory path.

	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.handlePythonException(PythonRunner.scala:642)
	at org.apache.spark.api.python.PythonRunner$$anon$3.read(PythonRunner.scala:830)
	at org.apache.spark.api.python.PythonRunner$$anon$3.read(PythonRunner.scala:812)
	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.hasNext(PythonRunner.scala:595)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at org.apache.spark.InterruptibleIterator.foreach(InterruptibleIterator.scala:28)
	at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:62)
	at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:53)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:105)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:49)
	at scala.collection.TraversableOnce.to(TraversableOnce.scala:315)
	at scala.collection.TraversableOnce.to$(TraversableOnce.scala:313)
	at org.apache.spark.InterruptibleIterator.to(InterruptibleIterator.scala:28)
	at scala.collection.TraversableOnce.toBuffer(TraversableOnce.scala:307)
	at scala.collection.TraversableOnce.toBuffer$(TraversableOnce.scala:307)
	at org.apache.spark.InterruptibleIterator.toBuffer(InterruptibleIterator.scala:28)
	at scala.collection.TraversableOnce.toArray(TraversableOnce.scala:294)
	at scala.collection.TraversableOnce.toArray$(TraversableOnce.scala:288)
	at org.apache.spark.InterruptibleIterator.toArray(InterruptibleIterator.scala:28)
	at org.apache.spark.rdd.RDD.$anonfun$collect$2(RDD.scala:1073)
	at org.apache.spark.scheduler.ResultTask.$anonfun$runTask$3(ResultTask.scala:75)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.ResultTask.$anonfun$runTask$1(ResultTask.scala:75)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:55)
	at org.apache.spark.scheduler.Task.doRunTask(Task.scala:150)
	at org.apache.spark.scheduler.Task.$anonfun$run$1(Task.scala:119)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.Task.run(Task.scala:91)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$13(Executor.scala:819)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1657)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:822)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:678)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2978)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2925)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2919)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2919)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskCompletion(DAGScheduler.scala:2676)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:3183)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:3127)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:3115)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:1123)
	at org.apache.spark.SparkContext.runJobInternal(SparkContext.scala:2500)
	at org.apache.spark.rdd.RDD.$anonfun$collect$1(RDD.scala:1071)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:165)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:125)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:454)
	at org.apache.spark.rdd.RDD.collect(RDD.scala:1069)
	at org.apache.spark.api.python.PythonRDD$.collectAndServe(PythonRDD.scala:260)
	at org.apache.spark.api.python.PythonRDD.collectAndServe(PythonRDD.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
	at py4j.Gateway.invoke(Gateway.java:295)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:251)
	at java.lang.Thread.run(Thread.java:750)

**Comment by sgwhat** [comment]
Seems `python_loc` is a file but not a directory in databricks, we may modify this in `ray_on_spark`.
