### ISSUE TITLE
Error msg: TypeError: 'JavaPackage' object is not callable when using orca library

### ISSUE THREAD

**Issue by SjeYinTeoIntel** [intel-analytics/BigDL#8889]
Hi, I'm execute below python code and facing the JavaPackage error message. 

python code:
from bigdl.orca import init_orca_context
init_orca_context(cluster_mode="local", cores=1

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[6], line 12
     10 ray.shutdown()
     11 print(ray.__version__)
---> 12 init_orca_context(cluster_mode="local", cores=1)

File ~/.local/lib/python3.9/site-packages/bigdl/orca/common.py:251, in init_orca_context(cluster_mode, runtime, cores, memory, num_nodes, init_ray_on_spark, **kwargs)
    248         warnings.warn("Use an existing SparkContext, " +
    249                       "cluster_mode is determined by the existing SparkContext", Warning)
    250     from bigdl.dllib.nncontext import init_nncontext
--> 251     sc = init_nncontext(conf=None, spark_log_level="WARN", redirect_spark_log=True)
    252 else:
    253     cluster_mode = "local" if cluster_mode is None else cluster_mode

File ~/.local/lib/python3.9/site-packages/bigdl/dllib/nncontext.py:540, in init_nncontext(conf, cluster_mode, spark_log_level, redirect_spark_log, **kwargs)
    538     spark_args.update(conf.getAll())
    539 if cluster_mode == "spark-submit":
--> 540     sc = init_internal_nncontext(conf, spark_log_level, redirect_spark_log)
    541 elif cluster_mode == "local":
    542     if conf:

File ~/.local/lib/python3.9/site-packages/bigdl/dllib/nncontext.py:669, in init_internal_nncontext(conf, spark_log_level, redirect_spark_log)
    667 check_version()
    668 if redirect_spark_log:
--> 669     redire_spark_logs()
    670     show_bigdl_info_logs()
    671 init_engine()

File ~/.local/lib/python3.9/site-packages/bigdl/dllib/utils/common.py:477, in redire_spark_logs(bigdl_type, log_path)
    470 def redire_spark_logs(bigdl_type="float", log_path=os.getcwd() + "/bigdl.log"):
    471     """
    472     Redirect spark logs to the specified path.
    473     :param bigdl_type: "double" or "float"
    474     :param log_path: the file path to be redirected to; the default file is under the current
    475      workspace named `bigdl.log`.
    476     """
--> 477     callBigDlFunc(bigdl_type, "redirectSparkLogs", log_path)

File ~/.local/lib/python3.9/site-packages/bigdl/dllib/utils/common.py:624, in callBigDlFunc(bigdl_type, name, *args)
    622 args = [_py2java(gateway, a) for a in args]
    623 error = Exception("Cannot find function: %s" % name)
--> 624 for jinvoker in JavaCreator.instance(bigdl_type, gateway).value:
    625     # hasattr(jinvoker, name) always return true here,
    626     # so you need to invoke the method to check if it exist or not
    627     try:
    628         api = getattr(jinvoker, name)

File ~/.local/lib/python3.9/site-packages/bigdl/dllib/utils/common.py:59, in SingletonMixin.instance(cls, bigdl_type, *args)
     57     with cls._lock:
     58         if not cls._instance:
---> 59             cls._instance = cls(bigdl_type, *args)
     60 return cls._instance

File ~/.local/lib/python3.9/site-packages/bigdl/dllib/utils/common.py:109, in JavaCreator.__init__(self, bigdl_type, gateway)
    107 jclass = getattr(gateway.jvm, creator_class)
    108 if bigdl_type == "float":
--> 109     self.value.append(getattr(jclass, "ofFloat")())
    110 elif bigdl_type == "double":
    111     self.value.append(getattr(jclass, "ofDouble")())

TypeError: 'JavaPackage' object is not callable

_____________________________________________________________________________________________________________________________________________
library version using:
> python3.9 -m pip install pip install bigdl==2.4.0b20230829
> java --version
openjdk 11.0.15 2022-04-19
OpenJDK Runtime Environment 18.9 (build 11.0.15+10)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.15+10, mixed mode, sharing)
>pyspark  version: 2.4.6
______________________________________________________________________________________________________________________________________________
have tried below command
'''
apt-get install openjdk-11-jre
export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64/
export PATH=$PATH:$JAVA_HOME/bin
'''
Getting below error message:

****************************Usage Error************************
An error occurred while calling o44.initEngine.
: java.lang.NoClassDefFoundError: scala/Product$class
        at com.intel.analytics.bigdl.dllib.utils.MklBlas$.<init>(Engine.scala:37)
        at com.intel.analytics.bigdl.dllib.utils.MklBlas$.<clinit>(Engine.scala)
        at com.intel.analytics.bigdl.dllib.utils.Engine$.<init>(Engine.scala:225)
        at com.intel.analytics.bigdl.dllib.utils.Engine$.<clinit>(Engine.scala)
        at com.intel.analytics.bigdl.dllib.utils.python.api.PythonBigDL.initEngine(PythonBigDL.scala:2517)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:282)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
        at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassNotFoundException: scala.Product$class
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)
        ... 17 more

****************************Call Stack*************************
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/dist-packages/bigdl/orca/common.py", line 266, in init_orca_context
    sc = init_spark_on_local(cores, **spark_args)
  File "/usr/local/lib/python3.9/dist-packages/bigdl/dllib/nncontext.py", line 53, in init_spark_on_local
    return runner.init_spark_on_local(cores=cores, conf=conf,
  File "/usr/local/lib/python3.9/dist-packages/bigdl/dllib/utils/spark.py", line 64, in init_spark_on_local
    sc = init_internal_nncontext(conf=zoo_conf, spark_log_level=self.spark_log_level,
  File "/usr/local/lib/python3.9/dist-packages/bigdl/dllib/nncontext.py", line 671, in init_internal_nncontext
    init_engine()
  File "/usr/local/lib/python3.9/dist-packages/bigdl/dllib/utils/common.py", line 444, in init_engine
    callBigDlFunc(bigdl_type, "initEngine")
  File "/usr/local/lib/python3.9/dist-packages/bigdl/dllib/utils/common.py", line 634, in callBigDlFunc
    invalidOperationError(False, str(e), cause=e)
  File "/usr/local/lib/python3.9/dist-packages/bigdl/dllib/utils/log4Error.py", line 40, in invalidOperationError
    raise cause
  File "/usr/local/lib/python3.9/dist-packages/bigdl/dllib/utils/common.py", line 629, in callBigDlFunc
    result = callJavaFunc(api, *args)
  File "/usr/local/lib/python3.9/dist-packages/bigdl/dllib/utils/common.py", line 683, in callJavaFunc
    result = func(*args)
  File "/usr/local/lib/python3.9/dist-packages/py4j/java_gateway.py", line 1256, in __call__
    return_value = get_return_value(
  File "/usr/local/lib/python3.9/dist-packages/py4j/protocol.py", line 326, in get_return_value
    raise Py4JJavaError(
py4j.protocol.Py4JJavaError: An error occurred while calling o44.initEngine.
: java.lang.NoClassDefFoundError: scala/Product$class
        at com.intel.analytics.bigdl.dllib.utils.MklBlas$.<init>(Engine.scala:37)
        at com.intel.analytics.bigdl.dllib.utils.MklBlas$.<clinit>(Engine.scala)
        at com.intel.analytics.bigdl.dllib.utils.Engine$.<init>(Engine.scala:225)
        at com.intel.analytics.bigdl.dllib.utils.Engine$.<clinit>(Engine.scala)
        at com.intel.analytics.bigdl.dllib.utils.python.api.PythonBigDL.initEngine(PythonBigDL.scala:2517)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:282)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
        at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassNotFoundException: scala.Product$class
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)
        ... 17 more

**Comment by hkvision** [comment]
`java.lang.NoClassDefFoundError: scala/Product$class` this error should come from mismatch of spark versions.
@lalalapotter please check with Sje Yin for more details.

**Comment by lalalapotter** [comment]
After taking following workaround, issue currently resolved(confirmed offline with user).
+ match spark version and bigdl version, using spark 3.1.3 and bigdl-spark3.
+ use `--jars ${BIGDL_HOME}/jars/bigdl-assembly-spark_${SPARK_VERSION}-${BIGDL_VERSION}-jar-with-dependencies.jar \` in spark-submit command to add jar dependency package to both driver and executer classpath.

**Comment by hkvision** [comment]
Closing this issue. Follow-up issues will be tracked in https://github.com/intel-analytics/BigDL/issues/8895
