### ISSUE TITLE
Fail while installing  tensorboard on VirtualEnv

### ISSUE THREAD

**Issue by zhichao-li** [intel-analytics/BigDL#891]
```
(venv3) root@Gondolin-Node-030:~/zhichao/work/testBranch_0.1_3.5# pip3 install tensorboard=1.0.0a6

(venv3) root@Gondolin-Node-030:~/zhichao/work/testBranch_0.1_3.5# tensorboard
Traceback (most recent call last):
  File "/root/zhichao/work/testBranch_0.1_3.5/python3_env/venv3/bin/tensorboard", line 152, in <module>
    Main()
  File "/root/zhichao/work/testBranch_0.1_3.5/python3_env/venv3/bin/tensorboard", line 102, in Main
    module_space = FindModuleSpace()
  File "/root/zhichao/work/testBranch_0.1_3.5/python3_env/venv3/bin/tensorboard", line 69, in FindModuleSpace
    for mod in site.getsitepackages():
AttributeError: 'module' object has no attribute 'getsitepackages'
```
@qiuxin2012 @jenniew

**Comment by yiheng** [comment]
This is covered in PR https://github.com/intel-analytics/BigDL/pull/975
