### ISSUE TITLE
ValueError: Dataframe must have columns "ds" and "y" with the dates and values respectively.

### ISSUE THREAD

**Issue by SjeYinTeoIntel** [intel-analytics/BigDL#8941]
Hi, facing this error when execute AutoProphet(). is it a must to rename the date column as 'ds' and target value as 'y' colume?
______________________________________________________________________________________________________________________________
2023-09-11 03:02:55,393	ERROR trial_runner.py:958 -- Trial train_func_aec86_00007: Error processing event.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.9/site-packages/ray/tune/trial_runner.py", line 924, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/ray/tune/ray_trial_executor.py", line 787, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/ray/worker.py", line 1713, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(TuneError): ray::ImplicitFunc.train_buffered()(pid=786442, ip=172.31.28.99, repr=<types.ImplicitFunc object at 0x7f32458c1f70>)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/ray/tune/trainable.py", line 255, in train_buffered
    result = self.train()
  File "/home/ubuntu/.local/lib/python3.9/site-packages/ray/tune/trainable.py", line 314, in train
    result = self.step()
  File "/home/ubuntu/.local/lib/python3.9/site-packages/ray/tune/function_runner.py", line 381, in step
    self._report_thread_runner_error(block=True)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/ray/tune/function_runner.py", line 531, in _report_thread_runner_error
    raise TuneError(
ray.tune.error.TuneError: Trial raised an exception. Traceback:
ray::ImplicitFunc.train_buffered()(pid=786442, ip=172.31.28.99, repr=<types.ImplicitFunc object at 0x7f32458c1f70>)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/ray/tune/function_runner.py", line 262, in run
    self._entrypoint()
  File "/home/ubuntu/.local/lib/python3.9/site-packages/ray/tune/function_runner.py", line 330, in entrypoint
    return self._trainable_func(self.config, self._status_reporter,
  File "/home/ubuntu/.local/lib/python3.9/site-packages/ray/tune/function_runner.py", line 597, in _trainable_func
    output = fn()
  File "/home/ubuntu/.local/lib/python3.9/site-packages/bigdl/orca/automl/search/ray_tune/ray_tune_search_engine.py", line 346, in train_func
    result = trial_model.fit_eval(data=train_data,
  File "/home/ubuntu/.local/lib/python3.9/site-packages/bigdl/chronos/model/prophet.py", line 87, in fit_eval
    self._fit(data, **config)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/bigdl/chronos/model/prophet.py", line 67, in _fit
    self.model.fit(data)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/prophet/forecaster.py", line 1117, in fit
    raise ValueError(
ValueError: Dataframe must have columns "ds" and "y" with the dates and values respectively.

**Comment by plusbang** [comment]
Yes, Chronos is verified on prophet 1.1 and the prophet package only works when the input dataframe follows the format: ds and y.

**Comment by SjeYinTeoIntel** [comment]
ok noted, thanks !
