### ISSUE TITLE
Whisper got error "expected scalar type Byte but found Half"  using load_low_bit 

### ISSUE THREAD

**Issue by violet17** [intel-analytics/BigDL#8942]
Whisper got error "expected scalar type Byte but found Half"  using `load_low_bit`  version `2.4.0b20230910` on A770.
no error using `from_pretrained`

runing log:
```
$ python test_whisper.py  --whisper-repo-id-or-model-path ./whisper-medium-int4-0910/
/home/a/miniconda3/envs/llm/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: ''If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
Converting and loading models...
loading whisper----1
loading whisper----2
loading whisper----Done
audio_file:  /home/a/crystal/llm/pyaudio_out.wav
audio:  <speech_recognition.audio.AudioData object at 0x7f8ec0bf1bb0> frame_data:  [0.         0.         0.         ... 0.00015259 0.         0.00054932]
/home/a/miniconda3/envs/llm/lib/python3.9/site-packages/transformers/generation/utils.py:1369: UserWarning: Using `max_length`'s default (448) to control the generation length. This behaviour is deprecated and will be removed from the config in v5 of Transformers -- we recommend using `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
Traceback (most recent call last):
  File "/home/a/crystal/llm/test_whisper.py", line 168, in <module>
    predicted_ids = whisper.generate(input_features)
  File "/home/a/miniconda3/envs/llm/lib/python3.9/site-packages/transformers/models/whisper/modeling_whisper.py", line 1749, in generate
    outputs = super().generate(
  File "/home/a/miniconda3/envs/llm/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/a/miniconda3/envs/llm/lib/python3.9/site-packages/transformers/generation/utils.py", line 1538, in generate
    return self.greedy_search(
  File "/home/a/miniconda3/envs/llm/lib/python3.9/site-packages/transformers/generation/utils.py", line 2362, in greedy_search
    outputs = self(
  File "/home/a/miniconda3/envs/llm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/a/miniconda3/envs/llm/lib/python3.9/site-packages/transformers/models/whisper/modeling_whisper.py", line 1506, in forward
    lm_logits = self.proj_out(outputs[0])
  File "/home/a/miniconda3/envs/llm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/a/miniconda3/envs/llm/lib/python3.9/site-packages/bigdl/llm/transformers/low_bit_linear.py", line 318, in forward
    result = linear_q4_0.forward_new(x_2d, x0, self.qtype)
RuntimeError: expected scalar type Byte but found Half
```

version:
```
$ pip list | grep bigdl
bigdl-core-xe               2.4.0b20230910
bigdl-llm                   2.4.0b20230910
$ pip list | grep transformer
transformers                4.31.0
```

runing Scripts:
```

# pip install bigdl-llm[xpu] -f https://developer.intel.com/ipex-whl-stable-xpu
# pip install bigdl-core-xe
# pip install librosa soundfile datasets
# pip install accelerate
# pip install SpeechRecognition sentencepiece colorama



# export USE_XETLA=OFF
# export SYCL_PI_LEVEL_ZERO_USE_IMMEDIATE_COMMANDLISTS=1 ENABLE_SDP_FUSION=1

# python generate.py --whisper-repo-id-or-model-path /home/wid/.ipc/yina/models/whisper-small --audio-dir /home/wid/.ipc/yina/IPEX_DPCPP --n-predict 128 

# 进terminal后需要source /opt/intel/oneapi/setvars.sh  #注意： 需要oneAPI 2023.2，要不然会出错

 
# audio-dir 是放音频文件的dir
# 音频文件需要时16k采样，转换为16k方法： ffmpeg -i input.wav -ar 16000 output.wav



import os
import torch
import time
import argparse
import numpy as np


from bigdl.llm.transformers import AutoModelForSpeechSeq2Seq
import intel_extension_for_pytorch as ipex
from transformers import WhisperProcessor
import speech_recognition as sr


def get_input_features(r, audio_file):
    print("audio_file: ", audio_file)
    with sr.AudioFile(audio_file) as source:
        audio = r.record(source)  # read the entire audio file
    frame_data = np.frombuffer(audio.frame_data, np.int16).flatten().astype(np.float32) / 32768.0
    print("audio: ", audio, "frame_data: ", frame_data)
    input_features = processor(frame_data, sampling_rate=audio.sample_rate, return_tensors="pt").input_features
    input_features = input_features.half().contiguous().to('xpu')
    return input_features


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Predict Tokens using `generate()` API for Llama2 model')
    parser.add_argument('--whisper-repo-id-or-model-path', type=str, default="/home/adc2/crystal/llm/whisper-medium-int4",                    
                        help='The huggingface repo id for the Whisper (e.g. `openai/whisper-small` and `openai/whisper-medium`) to be downloaded'
                             ', or the path to the huggingface checkpoint folder')
    parser.add_argument('--audio-dir', type=str, default="~/crystal/whisper/", help="The path to the audio directory.")
    parser.add_argument('--audio', type=str, default="/home/adc2/crystal/llm/pyaudio_out.wav", help="The absolute path to the audio directory.")#绝对路径
    parser.add_argument('--n-predict', type=int, default=128,
                        help='Max tokens to predict')

    args = parser.parse_args()
    whisper_model_path = args.whisper_repo_id_or_model_path

    print("Converting and loading models...")
    print("loading whisper----1")
    processor = WhisperProcessor.from_pretrained(whisper_model_path)

    # generate token ids
    print("loading whisper----2")
#    whisper =  AutoModelForSpeechSeq2Seq.from_pretrained(whisper_model_path, load_in_4bit=True, optimize_model=False)
    whisper =  AutoModelForSpeechSeq2Seq.load_low_bit(whisper_model_path, trust_remote_code=True, optimize_model=False)
    whisper.config.forced_decoder_ids = None
    #whisper = whisper.half().to('xpu')
    whisper = whisper.to('xpu')
#    whisper.save_low_bit("./whisper-medium-int4-0910/")
#    processor.save_pretrained("./whisper-medium-int4-0910/", trust_remote_code=True)
    print("loading whisper----Done")


    audio_dir = args.audio_dir
    audio = args.audio
    r = sr.Recognizer()

    with torch.inference_mode():
        # warm up
        input_features = get_input_features(r, audio)
        torch.xpu.synchronize()
        predicted_ids = whisper.generate(input_features)
        torch.xpu.synchronize()
        output_str = processor.batch_decode(predicted_ids, skip_special_tokens=True)
        output_str = output_str[0]
        print("output_str: ", output_str)
```

**Comment by cyita** [comment]
The loaded model has a weight shape mismatch from the converted int4 model.
@leonardozcm Please take a look.
The code to reproduce on CPU:
```python
from bigdl.llm.transformers import AutoModelForSpeechSeq2Seq
from datasets import load_dataset, load_from_disk
from transformers import WhisperProcessor

dataset_path = "hf-internal-testing/librispeech_asr_dummy"
model_path = "/mnt/disk1/models/whisper-small"

ds = load_dataset(dataset_path, "clean", split="validation")
processor = WhisperProcessor.from_pretrained(model_path)

sample = ds[0]["audio"]
# for transformer == 4.30.2
input_features = processor(sample["array"], sampling_rate=sample["sampling_rate"], return_tensors="pt").input_features

whisper =  AutoModelForSpeechSeq2Seq.from_pretrained(model_path, load_in_4bit=True, optimize_model=False)
whisper.config.forced_decoder_ids = None

predicted_ids = whisper.generate(input_features)
output_str = processor.batch_decode(predicted_ids, skip_special_tokens=True)
print(output_str)

whisper.save_low_bit("whisper-small-int4-910")
whisper =  AutoModelForSpeechSeq2Seq.load_low_bit("whisper-small-int4-910", optimize_model=False, trust_remote_code=True,)
whisper.config.forced_decoder_ids = None

predicted_ids = whisper.generate(input_features)
output_str = processor.batch_decode(predicted_ids, skip_special_tokens=True)
print(output_str)
```
The underlined number is the `weight.size(0)` (whisper-medium)
1. The loaded model (load_low_bit)
<img width="220" alt="image" src="https://github.com/intel-analytics/BigDL/assets/33650826/5bc0d9ee-48a0-4a39-bf4d-96b8b9a24025">
2. The converted model (from_pretained)
<img width="151" alt="image" src="https://github.com/intel-analytics/BigDL/assets/33650826/ef73864c-f42c-494a-88bd-15cdb764b5b1">

**Comment by leonardozcm** [comment]
Sure, I will take a look.

**Comment by violet17** [comment]
Hi， I use bigdl-llm and bigdl-core-xe 0913 version to run whisper with 
```
 whisper =  AutoModelForSpeechSeq2Seq.from_pretrained(whisper_model_path, load_in_4bit=True, optimize_model=False)
 and get no output results.
```
Use
`whisper =  AutoModelForSpeechSeq2Seq.load_low_bit(whisper_model_path, trust_remote_code=True, optimize_model=False,tie_word_embeddings=False)`
get a lot of "!".(0912 also gets a lot of "!")

Same scripts in my first comment.
Thanks.

**Comment by violet17** [comment]
@leonardozcm @cyita 
Hi，I find the reason of 0912 gets a lot of "!" . It is caused by putting model to xpu before save low bit weights.

**Comment by cyita** [comment]
Since we converted the original q4_0 format into a new q4_0 format when using `.to('xpu')`, we need to call `.to('cpu')` before saving the model @leonardozcm.
