### ISSUE TITLE
Chatglm2 get exception at the 4th generation if export SYCL_PI_LEVEL_ZERO_USE_IMMEDIATE_COMMANDLISTS=1

### ISSUE THREAD

**Issue by qiuxin2012** [intel-analytics/BigDL#9019]
On our i9 13900k, and A770 machine. (the 12900k and A770 can't repoduce this error, the driver and s)
Chatglm2 will get below error at the 4th generation when run the benchmark script all-in-one/run.py
```
Traceback (most recent call last):
  File "/home/arda/xin/BigDL/python/llm/dev/benchmark/all-in-one/run.py", line 406, in <module>
    run_model(model, api, conf['in_out_pairs'], conf['local_model_hub'], conf['warm_up'], conf['num_trials'])
  File "/home/arda/xin/BigDL/python/llm/dev/benchmark/all-in-one/run.py", line 45, in run_model
    result = run_transformer_int4_gpu(repo_id, local_model_hub, in_out_pairs, warm_up, num_trials)
  File "/home/arda/xin/BigDL/python/llm/dev/benchmark/all-in-one/run.py", line 329, in run_transformer_int4_gpu
    output = tokenizer.batch_decode(output_ids)
  File "/home/arda/anaconda3/envs/xin-llm/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 3485, in batch_decode
    return [
  File "/home/arda/anaconda3/envs/xin-llm/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 3486, in <listcomp>
    self.decode(
  File "/home/arda/anaconda3/envs/xin-llm/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 3525, in decode
    return self._decode(
  File "/home/arda/anaconda3/envs/xin-llm/lib/python3.9/site-packages/transformers/tokenization_utils.py", line 931, in _decode
    filtered_tokens = self.convert_ids_to_tokens(token_ids, skip_special_tokens=skip_special_tokens)
  File "/home/arda/anaconda3/envs/xin-llm/lib/python3.9/site-packages/transformers/tokenization_utils.py", line 912, in convert_ids_to_tokens
    tokens.append(self._convert_id_to_token(index))
  File "/home/arda/.cache/huggingface/modules/transformers_modules/chatglm2-6b/tokenization_chatglm.py", line 113, in _convert_id_to_token
    return self.tokenizer.convert_id_to_token(index)
  File "/home/arda/.cache/huggingface/modules/transformers_modules/chatglm2-6b/tokenization_chatglm.py", line 60, in convert_id_to_token
    return self.sp_model.IdToPiece(index)
  File "/home/arda/anaconda3/envs/xin-llm/lib/python3.9/site-packages/sentencepiece/__init__.py", line 1045, in _batched_func
    return _func(self, arg)
  File "/home/arda/anaconda3/envs/xin-llm/lib/python3.9/site-packages/sentencepiece/__init__.py", line 1038, in _func
    raise IndexError('piece id is out of range.')
IndexError: piece id is out of range.
```

If run another test script below:
```
# This is to test latest ipex version, model is chatglm2
import torch
import intel_extension_for_pytorch as ipex
import os
import time
from bigdl.llm.transformers import AutoModel
from transformers import AutoTokenizer
import numpy as np
from itertools import chain
import pathlib
import argparse
import json
from benchmark_util import BenchmarkWrapper


if __name__ == '__main__':
    parser = argparse.ArgumentParser('OPT generation script', add_help=False)
    parser.add_argument('-m', '--model-dir', default="/mnt/disk1/models/chatglm2-6b", type=str)
    parser.add_argument('--max-new-tokens', default=32, type=int, help="output max new tokens")
    parser.add_argument('--input-tokens', default='32', type=str)
    args = parser.parse_args()
    print(args)

    prompt_32 = "我总是在晚上失眠,这个症状已经持续很长时间,所以晚上睡不着到底应该怎么处理,请告诉我一些可行的建议与方法,越详细越好"
    prompt_1024 = "It is done, and submitted. You can play 'Survival of the Tastiest' on Android, and on the web. Playing on the web works, but you have to simulate multiple touch for table moving and that can be a bit confusing. There is a lot I'd like to talk about. I will go through every topic, insted of making the typical what went right/wrong list. Concept Working over the theme was probably one of the hardest tasks which I had to face. Originally, I had an idea of what kind of game I wanted to develop, gameplay wise - something with a lot of enemies/actors, simple graphics, maybe set in space, controlled from a top-down view. I was confident that I could fit any theme around it. In the end, the problem with a theme like 'Evolution' in a game is that evolution is unassisted. It happens through several seemingly random mutations over time, with the most apt permutation surviving. This genetic car simulator is, in my opinion, a great example of actual evolution of a species facing a challenge. But is it a game? In a game, you need to control something to reach an objective. That control goes against what evolution is supposed to be like. If you allow the user to pick how to evolve something, it's not evolution anymore - it's the equivalent of intelligent design, the fable invented by creationists to combat the idea of evolution. Being agnostic and a Pastafarian, that's not something that rubbed me the right way. Hence, my biggest dillema when deciding what to create was not with what I wanted to create, but with what I did not. I didn't want to create an 'intelligent design' simulator and wrongly call it evolution. This is a problem, of course, every other contestant also had to face. And judging by the entries submitted, not many managed to work around it. I'd say the only real solution was through the use of artificial selection, somehow. So far, I haven't seen any entry using this at its core gameplay. Alas, this is just a fun competition and after a while I decided not to be as strict with the game idea, and allowed myself to pick whatever I thought would work out. My initial idea was to create something where humanity tried to evolve to a next level, but had some kind of foe trying to stop them from doing so. I kind of had this image of human souls flying in space towards a monolith or a space baby (all based in 2001: A Space Odyssey of course) but I couldn't think of compelling (read: serious) mechanics for that. Borgs were my next inspiration, as their whole hypothesis fit pretty well into the evolution theme. But how to make it work? Are you the borg, or fighting the Borg? The third and final idea came to me through my girlfriend, who somehow gave me the idea of making something about the evolution of Pasta. The more I thought about it the more it sounded like it would work, so I decided to go with it. Conversations with my inspiring co-worker Roushey (who also created the 'Mechanical Underdogs' signature logo for my intros) further matured the concept, as it involved into the idea of having individual pieces of pasta flying around and trying to evolve until they became all-powerful. A secondary idea here was that the game would work to explain how the Flying Spaghetti Monster came to exist - by evolving from a normal dinner table. So the idea evolved more or less into this: you are sitting a table. You have your own plate, with is your 'base'. There are 5 other guests at the table, each with their own plate. Your plate can spawn little pieces of pasta. You do so by 'ordering' them through a menu. Some pastas are better than others; some are faster, some are stronger. They have varying 'costs', which are debited from your credits (you start with a number of credits). Once spawned, your pastas start flying around. Their instinct is to fly to other plates, in order to conquer them (the objective of the game is having your pasta conquer all the plates on the table). But they are really autonomous, so after being spawned, you have no control over your pasta (think DotA or LoL creeps). Your pasta doesn't like other people's pasta, so if they meet, they shoot sauce at each other until one dies. You get credits for other pastas your own pasta kill. Once a pasta is in vicinity of a plate. You get credits for other pastas your own pasta kill. Once a pasta is in vicinity of a plate.You get credits for other pastas your own pasta kill. Once a pasta is in vicinity of a plate.You get credits for"
    prompt = prompt_32

    print(f"Test {args.model_dir}...")
    # load_in_4bit=True in bigdl.llm.transformers will convert
    # the relevant layers in the model into int4 format
    # model = AutoModel.from_pretrained(args.model_dir, trust_remote_code=True)
    model = AutoModel.from_pretrained(args.model_dir, trust_remote_code=True, load_in_low_bit="sym_int4")
    # model = AutoModel.from_pretrained(args.model_dir, load_in_low_bit="sym_int8", trust_remote_code=True)
    model = model.to('xpu')
    print(model.dtype)
    print(model)
    model = BenchmarkWrapper(model, do_print=True)
    print(model.dtype, model.device)
    tokenizer = AutoTokenizer.from_pretrained(args.model_dir, trust_remote_code=True)
    inputs = tokenizer([prompt], return_tensors="pt").to('xpu')
    print(inputs["input_ids"].shape)

    total_list = []
    e2e_time = []
    with torch.inference_mode():
        for i in range(5):
            torch.xpu.synchronize()
            st = time.time()
            #inputs = tokenizer([prompt], return_tensors="pt").to('xpu')
            inputs = tokenizer.encode(prompt, return_tensors="pt").to('xpu')
            # print(inputs["input_ids"].shape)
            #output = model.generate(**inputs, do_sample=False, max_new_tokens=32)
            output = model.generate(inputs, do_sample=False, max_new_tokens=32)
            gen_ids = output[0]
            gen_text = tokenizer.batch_decode(gen_ids, skip_special_tokens=True)
            torch.xpu.synchronize()
            end = time.time()
            e2e_time.append(end-st)

    print('Prompt:', prompt)
    print('Output:', gen_text)
    print(f'Inference time: {end-st} s')
    print(e2e_time)
    # print("mean e2e time is : ", np.mean(e2e_time[2:]))

    # input_ids = tokenizer.encode(prompt, return_tensors="pt").to('xpu')
    # output = model.generate(input_ids[:, :1], do_sample=False, max_new_tokens=1)
    # output = model.generate(input_ids[:, :1], do_sample=False, max_new_tokens=1)
    # output = model.generate(input_ids[:, :1], do_sample=False, max_new_tokens=1)

    # with torch.autograd.profiler_legacy.profile(use_xpu=True) as p:
    #     output = model.generate(input_ids[:, :1], do_sample=False, max_new_tokens=1)
    # print(p.key_averages().table(sort_by="self_xpu_time_total", row_limit=-1))

    # with torch.autograd.profiler_legacy.profile(use_xpu=True) as p:
    #     output = model.generate(input_ids[:, :1], do_sample=False, max_new_tokens=1)
    # print(p.key_averages().table(sort_by="self_xpu_time_total", row_limit=-1))
```
will get:
```
torch.float32 xpu:0
torch.Size([1, 32])
2023-09-21 08:22:01,378 - benchmark_util - WARNING - The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
2023-09-21 08:22:01,378 - benchmark_util - WARNING - Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
/home/arda/anaconda3/envs/xin-llm/lib/python3.9/site-packages/bigdl/llm/transformers/models/chatglm2.py:124: UserWarning: IPEX XPU dedicated fusion passes are enabled in ScriptGraph non profiling execution mode. Please enable profiling execution mode to retrieve device guard. 
 (Triggered internally at /build/intel-pytorch-extension/csrc/gpu/jit/fusion_pass.cpp:826.)
  query_layer = apply_rotary_pos_emb(query_layer, rotary_pos_emb)
=========First token cost 0.6787 s=========
=========Rest tokens cost average 0.0166 s (31 tokens in all)=========
2023-09-21 08:22:02,638 - benchmark_util - WARNING - The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
2023-09-21 08:22:02,639 - benchmark_util - WARNING - Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
=========First token cost 0.1044 s=========
=========Rest tokens cost average 0.0160 s (31 tokens in all)=========
2023-09-21 08:22:03,241 - benchmark_util - WARNING - The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
2023-09-21 08:22:03,241 - benchmark_util - WARNING - Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
=========First token cost 0.1044 s=========
=========Rest tokens cost average 0.0160 s (31 tokens in all)=========
2023-09-21 08:22:03,842 - benchmark_util - WARNING - The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
2023-09-21 08:22:03,842 - benchmark_util - WARNING - Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Traceback (most recent call last):
  File "/home/arda/xin/BigDL/python/llm/dev/benchmark/test.py", line 53, in <module>
    output = model.generate(inputs, do_sample=False, max_new_tokens=32)
  File "/home/arda/anaconda3/envs/xin-llm/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/arda/xin/BigDL/python/llm/dev/benchmark/benchmark_util.py", line 1564, in generate
    return self.greedy_search(
  File "/home/arda/xin/BigDL/python/llm/dev/benchmark/benchmark_util.py", line 2382, in greedy_search
    model_inputs = self.prepare_inputs_for_generation(input_ids, **model_kwargs)
  File "/home/arda/xin/BigDL/python/llm/dev/benchmark/benchmark_util.py", line 528, in prepare_inputs_for_generation
    return self.model.prepare_inputs_for_generation(*args, **kwargs)
  File "/home/arda/.cache/huggingface/modules/transformers_modules/chatglm2-6b/modeling_chatglm.py", line 816, in prepare_inputs_for_generation
    position_ids = self.get_position_ids(input_ids, device=input_ids.device)
  File "/home/arda/.cache/huggingface/modules/transformers_modules/chatglm2-6b/modeling_chatglm.py", line 644, in get_position_ids
    position_ids = torch.arange(seq_length, dtype=torch.long, device=device).unsqueeze(0).repeat(batch_size, 1)
RuntimeError: Allocation is out of device memory on current platform.
```

The caused by `export SYCL_PI_LEVEL_ZERO_USE_IMMEDIATE_COMMANDLISTS=1`, but we don't set this env, the 2nd  time will increase 1ms/token.

Another solution is use
```
inputs = tokenizer([prompt], return_tensors="pt").to('xpu')
output = model.generate(**inputs, do_sample=False, max_new_tokens=32)
```
instead of 
```
inputs = tokenizer.encode(prompt, return_tensors="pt").to('xpu')
output = model.generate(inputs, do_sample=False, max_new_tokens=32)
```

**Comment by jason-dai** [comment]
It seems `SYCL_PI_LEVEL_ZERO_USE_IMMEDIATE_COMMANDLISTS` is now enabled by default; maybe check with the Arc team @shane-huang?
