### ISSUE TITLE
How to run bark (TTS API) on dGPU？

### ISSUE THREAD

**Issue by violet17** [intel-analytics/BigDL#9023]
Hi, I run  [synthesize_speech.py ](https://github.com/intel-analytics/BigDL/blob/main/python/llm/example/pytorch-models/bark/synthesize_speech.py) with bigdl-llm 2.4.0b20230920, and find that it can not use GPU.
And how to run this demo on Arc dGPU?

Thanks.

**Comment by shane-huang** [comment]
First you need to install xpu related dependencies, follow the llama2 example install section for how to https://github.com/intel-analytics/BigDL/blob/main/python/llm/example/gpu/hf-transformers-models/llama2/README.md. 

In the original code, you can try add `model.to('xpu')` to load the model to ARC, and add `output = output.cpu()` move the generated results back to CPU, like below:

```python
    # Load model
    model.load_checkpoint(config, checkpoint_dir=model_path, eval=True)
    ## move to ARC
    model.to('xpu')
    # With only one line to enable BigDL-LLM optimization on model
    model = optimize_model(model)
    # generate results
    output_dict = model.synthesize(text, config, speaker_id="random", voice_dirs=None)
    # remove results back to CPU
     output_dict = output_dict .cpu()
```

**Comment by violet17** [comment]
Hi @shane-huang  Thanks for you reply.

I put the model to arc, then get error with bigdl-llm 2.4.0b20230920 and TTS 0.17.4 :
```
====== torch.float16 torch.float32
Traceback (most recent call last):
  File "/home/a770/crystal/llm/bark_bigdl2.py", line 36, in <module>
    output_dict = model.synthesize(text, config, speaker_id="random", voice_dirs=None) # with random speaker
  File "/home/a770/miniconda3/envs/llm2/lib/python3.9/site-packages/TTS/tts/models/bark.py", line 220, in synthesize
    outputs = self.generate_audio(text, history_prompt=history_prompt, **kwargs)
  File "/home/a770/miniconda3/envs/llm2/lib/python3.9/site-packages/TTS/tts/models/bark.py", line 153, in generate_audio
    x_semantic = self.text_to_semantic(
  File "/home/a770/miniconda3/envs/llm2/lib/python3.9/site-packages/TTS/tts/models/bark.py", line 87, in text_to_semantic
    x_semantic = generate_text_semantic(
  File "/home/a770/miniconda3/envs/llm2/lib/python3.9/site-packages/TTS/tts/layers/bark/inference_funcs.py", line 244, in generate_text_semantic
    logits, kv_cache = model.semantic_model(
  File "/home/a770/miniconda3/envs/llm2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/a770/miniconda3/envs/llm2/lib/python3.9/site-packages/TTS/tts/layers/bark/model.py", line 223, in forward
    x, kv = block(x, past_kv=past_layer_kv, use_cache=use_cache)
  File "/home/a770/miniconda3/envs/llm2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/a770/miniconda3/envs/llm2/lib/python3.9/site-packages/TTS/tts/layers/bark/model.py", line 128, in forward
    attn_output, prev_kvs = self.attn(self.ln_1(x), past_kv=past_kv, use_cache=use_cache)
  File "/home/a770/miniconda3/envs/llm2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/a770/miniconda3/envs/llm2/lib/python3.9/site-packages/TTS/tts/layers/bark/model.py", line 56, in forward
    q, k, v = self.c_attn(x).split(self.n_embd, dim=2)
  File "/home/a770/miniconda3/envs/llm2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/a770/miniconda3/envs/llm2/lib/python3.9/site-packages/bigdl/llm/transformers/low_bit_linear.py", line 359, in forward
    result = linear_q4_0.forward_new(x_2d, self.weight.data, self.weight.qtype)
RuntimeError: expected scalar type Byte but found Float

```

**Comment by shane-huang** [comment]
@plusbang please take a look.

**Comment by violet17** [comment]
The script I used is:

```
import scipy
import time
import argparse

 

from TTS.tts.configs.bark_config import BarkConfig
from TTS.tts.models.bark import Bark
from bigdl.llm import optimize_model

 

import torch
import intel_extension_for_pytorch as ipex

 

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Synthesize speech with the given input text using Bark model')
    parser.add_argument('--model-path', type=str, default="/opt/WD/888/LLM/bark",
                        help='The local path to the Bark model checkpoint folder')
    parser.add_argument('--text', type=str, default="This is an example text for synthesize speech.",
                        help='Text to synthesize speech')

 

    args = parser.parse_args()
    model_path = args.model_path

 

 

    # Load model
    config = BarkConfig()
    print("config: ", config)
    model = Bark.init_from_config(config)
    model.load_checkpoint(config, checkpoint_dir=model_path, eval=True)

 

    model = model.to("xpu")
    # With only one line to enable BigDL-LLM optimization on model
    model = optimize_model(model)

 

    # Synthesize speech with the given input
    text = args.text
    st = time.time()
    output_dict = model.synthesize(text, config, speaker_id="random", voice_dirs=None) # with random speaker
    end = time.time()
    print(f'Time cost: {end-st} s')

 

    output_dict = output_dict.cpu()
    # Save the speech as a .wav file using scipy
    sampling_rate = model.config.sample_rate
    scipy.io.wavfile.write("bark_out.wav", rate=sampling_rate, data=output_dict["wav"].squeeze())
```

**Comment by plusbang** [comment]
Hi @violet17.
1) The TTS API usage in [synthesize_speech.py](https://github.com/intel-analytics/BigDL/blob/main/python/llm/example/pytorch-models/bark/synthesize_speech.py) is for `bark` instead of `bark-small`. In the [internal implementation](https://github.com/coqui-ai/TTS/blob/dev/TTS/tts/models/bark.py#L269), the bark model checkpoint is strictly checked and downloaded.
2) There exists conflict of torch version between TTS and IPEX. I used the torchaudio built by you and below script for `bark` works fine:
```python
import intel_extension_for_pytorch as ipex
import scipy
import time
import argparse

from TTS.tts.configs.bark_config import BarkConfig
from TTS.tts.models.bark import Bark
from bigdl.llm import optimize_model


text = "This is an example text for synthesize speech."
model_path = "/mnt/disk1/models/bark"

# Load model
config = BarkConfig()
model = Bark.init_from_config(config)
model.load_checkpoint(config, checkpoint_dir=model_path, eval=True)
    
# With only one line to enable BigDL-LLM optimization on model
model = optimize_model(model)
model = model.to('xpu')

st = time.time()
output_dict = model.synthesize(text, config, speaker_id="random", voice_dirs=None) # with random speaker
end = time.time()
print(f'Time cost: {end -st} s.')

# Save the speech as a .wav file using scipy
sampling_rate = model.config.sample_rate
scipy.io.wavfile.write("bark_out.wav", rate=sampling_rate, data=output_dict["wav"].squeeze())
```
Please have a try.

**Comment by jason-dai** [comment]
> **I think your error is caused by the order of `model.to('xpu')` and `optimize_model(model)`**.

We should check the device type inside `optimize_model`

**Comment by violet17** [comment]
> 
> **I think your error is caused by the order of `model.to('xpu')` and `optimize_model(model)`**.Please have a try.

Hi @plusbang ， thanks. 
I tried your code. It works.
We should optimize the model by `optimize_model` before putting model to device.
And no need to use `output_dict = output_dict.cpu()`
Thanks again.

**Comment by shane-huang** [comment]
> > **I think your error is caused by the order of `model.to('xpu')` and `optimize_model(model)`**.Please have a try.
> 
> Hi @plusbang ， thanks. I tried your code. It works. We should optimize the model by `optimize_model` before putting model to device. And no need to use `output_dict = output_dict.cpu()` Thanks again.

If the model output is tensor you may still need to use `output.cpu()`, e.g. when you're using transformers lib.

**Comment by violet17** [comment]
> > > **I think your error is caused by the order of `model.to('xpu')` and `optimize_model(model)`**.Please have a try.
> > 
> > 
> > Hi @plusbang ， thanks. I tried your code. It works. We should optimize the model by `optimize_model` before putting model to device. And no need to use `output_dict = output_dict.cpu()` Thanks again.
> 
> If the model output is tensor you may still need to use `output.cpu()`, e.g. when you're using transformers lib.

Thanks shane.
