### ISSUE TITLE
Failed to load cpm_kernels:No module named 'cpm_kernels'

### ISSUE THREAD

**Issue by aoke79** [intel-analytics/BigDL#9049]
I've tried to run chatglm2 int4 version based-on example on CPU side, however, I met a problem like below. my envornoment is win11, i7-12700H.

C:\lin\AIGC\github\venv_bigdl\Scripts\python.exe generate.py --repo-id-or-model-path .\models_int4\ --prompt "what is AI"
2023-09-25 15:04:23,720 - WARNING - Failed to load cpm_kernels:No module named 'cpm_kernels'
'gcc' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
2023-09-25 15:04:23,737 - WARNING - Compile parallel cpu kernel gcc -O3 -fPIC -pthread -fopenmp -std=c99 C:\Users\lin\.cache\huggingface\modules\transformers_modules\quantization_kernels_parallel.c -shared -o C:\Users\lin\.cache\huggingface\modules\transformers_modules\quantization_kernels_parallel.so failed.
'gcc' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
2023-09-25 15:04:23,737 - WARNING - Compile cpu kernel gcc -O3 -fPIC -std=c99 C:\Users\lin\.cache\huggingface\modules\transformers_modules\quantization_kernels.c -shared -o C:\Users\lin\.cache\huggingface\modules\transformers_modules\quantization_kernels.so failed.
Traceback (most recent call last):
  File "C:\lin\AIGC\github\BigDL_main\python\llm\example\transformers\transformers_int4\chatglm2\generate.py", line 44, in <module>
    model = AutoModel.from_pretrained(model_path,
  File "C:\lin\AIGC\github\venv_bigdl\lib\site-packages\bigdl\llm\transformers\model.py", line 95, in from_pretrained
    model = cls.load_convert(q_k, optimize_model, *args, **kwargs)
  File "C:\lin\AIGC\github\venv_bigdl\lib\site-packages\bigdl\llm\transformers\model.py", line 116, in load_convert
    model = cls.HF_Model.from_pretrained(*args, **kwargs)
  File "C:\lin\AIGC\github\venv_bigdl\lib\site-packages\transformers\models\auto\auto_factory.py", line 488, in from_pretrained
    return model_class.from_pretrained(
  File "C:\lin\AIGC\github\venv_bigdl\lib\site-packages\transformers\modeling_utils.py", line 2700, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "C:\Users\lin/.cache\huggingface\modules\transformers_modules\modeling_chatglm.py", line 859, in __init__
    self.quantize(self.config.quantization_bit, empty_init=True)
  File "C:\Users\lin/.cache\huggingface\modules\transformers_modules\modeling_chatglm.py", line 1191, in quantize
    self.transformer.encoder = quantize(self.transformer.encoder, bits, empty_init=empty_init, device=device,
  File "C:\Users\lin/.cache\huggingface\modules\transformers_modules\quantization.py", line 511, in quantize
    layer.self_attention.query_key_value = QuantizedLinear(
  File "C:\Users\lin/.cache\huggingface\modules\transformers_modules\quantization.py", line 494, in __init__
    self.weight = Parameter(self.weight.to(device), requires_grad=False)
  File "C:\lin\AIGC\github\venv_bigdl\lib\site-packages\torch\nn\modules\module.py", line 1632, in __setattr__
    self.register_parameter(name, value)
  File "C:\lin\AIGC\github\venv_bigdl\lib\site-packages\accelerate\big_modeling.py", line 105, in register_empty_parameter
    module._parameters[name] = param_cls(module._parameters[name].to(device), **kwargs)
  File "C:\lin\AIGC\github\venv_bigdl\lib\site-packages\torch\nn\parameter.py", line 36, in __new__
    return torch.Tensor._make_subclass(cls, data, requires_grad)
RuntimeError: Only Tensors of floating point and complex dtype can require gradients

**Comment by plusbang** [comment]
Hi, @aoke79 
'Failed to load cpm_kernels' is a warning and it seems not be the root cause.
Based on your command, are you use the chatglm2 int4 model files and directly use the python example script? The parameter `--repo-id-or-model-path` of the python example script is expected to be path of the chatglm2 huggingface checkpoint folder.

**Comment by aoke79** [comment]
thanks for quick feedback.
Yes, I've downloaded the hugging face into my local folder, so how is the parameter for that?
thanks,

**Comment by aoke79** [comment]
one more question, should I use chatglm2-6b or chatglm2-6b-int4?
thanks

**Comment by plusbang** [comment]
> thanks for quick feedback. Yes, I've downloaded the hugging face into my local folder, so how is the parameter for that? thanks,

well, as introduced in [our example](https://github.com/intel-analytics/BigDL/tree/main/python/llm/example/transformers/transformers_int4/chatglm2#2-run), the argument `--repo-id-or-model-path` defines the huggingface repo id for the ChatGLM2 model to be downloaded, or the path to the local huggingface checkpoint folder. 
If you have downloaded it to your local folder, please directly specify it to your local path.


> one more question, should I use chatglm2-6b or chatglm2-6b-int4?

You need to use chatglm2-6b, the huggingface link is https://huggingface.co/THUDM/chatglm2-6b .

**Comment by aoke79** [comment]
I just do it, and it appears error, might you please show me how to directly specify it to my local path?
thanks

**Comment by plusbang** [comment]
> I just do it, and it appears error, might you please show me how to directly specify it to my local path? thanks

you just need to change `YOUR_LOCAL_FOLDER` in the following command to your actual local path:
```python
python generate.py --repo-id-or-model-path 'YOUR_LOCAL_FOLDER' --prompt "what is AI?"
```

**BUT, please make sure you are using the chatglm2-6b instead of chatglm2-6b-int4.**

**Comment by aoke79** [comment]
fixed, thanks a lot
