### ISSUE TITLE
An java.lang.ArrayIndexOutOfBoundsException error occurred when I tried to build a simple LSTM model

### ISSUE THREAD

**Issue by gdg1212** [intel-analytics/BigDL#9051]
val data: Array[Tensor[Float]] = Array(
  Tensor[Float](Array(1, 2, 3)),
  Tensor[Float](Array(2, 0, 4))
)
val labels: Array[Tensor[Float]] = Array(
  Tensor[Float](Array(1)),
  Tensor[Float](Array(2))
)

val samples: Array[Sample[Float]] = (data zip labels).map { case (feature, label) =>
  Sample[Float](feature, label)
}
val samplesRDD: RDD[Sample[Float]] = spark.sparkContext.parallelize(samples)

val optimizer = Optimizer(model = model,
  sampleRDD = samplesRDD,
  criterion = MSECriterion[Float](),
  batchSize = 1)
optimizer.optimize()

An error occurred when I attempted to run the above code
23/09/22 20:00:37 ERROR [main] DistriOptimizer$: Error: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 5.0 failed 1 times, most recent failure: Lost task 0.0 in stage 5.0 (TID 18)  executor driver): java.lang.ArrayIndexOutOfBoundsException
        at java.lang.System.arraycopy(Native Method)
        at com.intel.analytics.bigdl.tensor.TensorNumericMath$TensorNumeric$NumericFloat$.arraycopy$mcF$sp(TensorNumeric.scala:721)
        at com.intel.analytics.bigdl.tensor.TensorNumericMath$TensorNumeric$NumericFloat$.arraycopy(TensorNumeric.scala:715)
        at com.intel.analytics.bigdl.tensor.TensorNumericMath$TensorNumeric$NumericFloat$.arraycopy(TensorNumeric.scala:503)
        at com.intel.analytics.bigdl.dataset.MiniBatch$.copy(MiniBatch.scala:464)
        at com.intel.analytics.bigdl.dataset.MiniBatch$.copyWithPadding(MiniBatch.scala:380)
        at com.intel.analytics.bigdl.dataset.ArrayTensorMiniBatch.set(MiniBatch.scala:209)
        at com.intel.analytics.bigdl.dataset.ArrayTensorMiniBatch.set(MiniBatch.scala:111)
        at com.intel.analytics.bigdl.dataset.SampleToMiniBatch$$anon$2.next(Transformer.scala:348)
        at com.intel.analytics.bigdl.dataset.SampleToMiniBatch$$anon$2.next(Transformer.scala:323)
        at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
        at scala.collection.Iterator.foreach(Iterator.scala:943)
        at scala.collection.Iterator.foreach$(Iterator.scala:943)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
        at scala.collection.TraversableOnce.reduceLeft(TraversableOnce.scala:237)
        at scala.collection.TraversableOnce.reduceLeft$(TraversableOnce.scala:220)
        at scala.collection.AbstractIterator.reduceLeft(Iterator.scala:1431)
        at org.apache.spark.rdd.RDD.$anonfun$reduce$2(RDD.scala:1097)
        at org.apache.spark.SparkContext.$anonfun$runJob$6(SparkContext.scala:2322)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
        at org.apache.spark.scheduler.Task.run(Task.scala:136)
        at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1516)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)

**Comment by qiuxin2012** [comment]
Can you increase the number of samples(2 currently), it seems your data size is smaller than your core number, some of models get an empty dataset.

**Comment by gdg1212** [comment]
> Can you increase the number of samples(2 currently), it seems your data size is smaller than your core number, some of models get an empty dataset.

Engine.init(1, 1, true)   I have specified the number of cores as 1

**Comment by gdg1212** [comment]
> Can you increase the number of samples(2 currently), it seems your data size is smaller than your core number, some of models get an empty dataset.

And  I tried four samples, but it didn't work
    Engine.init(1, 1, true)
    val data: Array[Tensor[Float]] = Array(
      Tensor[Float](Array(1, 2, 3)),
      Tensor[Float](Array(2, 0, 4)),
      Tensor[Float](Array(1, 1, 4)),
      Tensor[Float](Array(2, 1, 4))
    )
    val labels: Array[Tensor[Float]] = Array(
      Tensor[Float](Array(1)),
      Tensor[Float](Array(2)),
      Tensor[Float](Array(2)),
      Tensor[Float](Array(1))
    )

**Comment by gdg1212** [comment]
> Can you increase the number of samples(2 currently), it seems your data size is smaller than your core number, some of models get an empty dataset.
May I know your email number？I want to explain more code details

**Comment by qiuxin2012** [comment]
I know what happening now. Your usage of creating a tensor with provided value is incorrect.
Tensor[Float](Array(2, 0, 4)) is calling https://github.com/intel-analytics/BigDL/blob/e54cd071e8ca710b0a47ea077aca6cfe4a1b8ea0/scala/dllib/src/main/scala/com/intel/analytics/bigdl/dllib/tensor/Tensor.scala#L967 .
The right way is 
```
import com.intel.analytics.bigdl.dllib.utils.T
val data: Array[Tensor[Float]] = Array(
      Tensor[Float](T(1f, 2f, 3f)),
      Tensor[Float](T(2f, 0f, 4f))
)
val labels: Array[Tensor[Float]] = Array(
      Tensor[Float](T(0f)),
      Tensor[Float](T(1f)
)
```
Or
```
    val data: Array[Tensor[Float]] = Array(
      Tensor[Float](Array(1f, 2, 3), Array(3)),
      Tensor[Float](Array(2f, 0, 4), Array(3))
    )
    val labels: Array[Tensor[Float]] = Array(
      Tensor[Float](Array(0f), Array(1)),
      Tensor[Float](Array(1f), Array(1))
    )
```

**Comment by hkvision** [comment]
@gdg1212 Is it ok to close the issue?

**Comment by gdg1212** [comment]
> @gdg1212 Is it ok to close the issue?

Sure
