### ISSUE TITLE
Qwen-7B transformer INT4 model's 2nd avg token 160ms/token on 13900H 

### ISSUE THREAD

**Issue by KiwiHana** [intel-analytics/BigDL#9075]
Qwen-7B transformer INT4 model's 2nd avg token 160ms/token on 13900H win11 by bigdl-llm 20230927.
The performance is not good.

attach code:
```
import torch
import time
import argparse

from bigdl.llm.transformers import AutoModelForCausalLM
#from transformers import AutoModelForCausalLM
from transformers import AutoTokenizer
#from bigdl.llm import optimize_model
from transformers import TextIteratorStreamer

# you could tune the prompt based on your own model
QWEN_PROMPT_FORMAT = "<human>{prompt} <bot>"

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Predict Tokens using `generate()` API for Qwen model')
    parser.add_argument('--repo-id-or-model-path', type=str, default="./checkpoint/Qwen-7B-Chat",
                        help='The huggingface repo id for the Qwen model to be downloaded'
                             ', or the path to the huggingface checkpoint folder')
    parser.add_argument('--prompt', type=str, default="AI是什么？",
                        help='Prompt to infer')
    parser.add_argument('--n-predict', type=int, default=32,
                        help='Max tokens to predict')

    args = parser.parse_args()
    model_path = args.repo_id_or_model_path

    # Load model in 4 bit,
    # which convert the relevant layers in the model into INT4 format

    model = AutoModelForCausalLM.from_pretrained(model_path, load_in_4bit=True, trust_remote_code=True)
                                         #        use_cache=True)
 #   model = model.to('cpu')

    # Load tokenizer
    tokenizer = AutoTokenizer.from_pretrained(model_path,trust_remote_code=True)

    with torch.inference_mode():
        prompt = QWEN_PROMPT_FORMAT.format(prompt=args.prompt)
      #  model=BenchmarkWrapper(model)
      #  model = optimize_model(model)
        inputs = tokenizer(prompt, return_tensors="pt")
        streamer = TextIteratorStreamer(tokenizer, skip_prompt=True, skip_special_tokens=True)
        response = ""
        timeFirstRecord = False
        timeStart = time.time() 
   
        generate_kwargs = dict(**inputs,streamer=streamer,temperature=0.9, top_p=0.9, max_new_tokens=args.n_predict)
        from threading import Thread
        thread = Thread(target=model.generate, kwargs=generate_kwargs)
        thread.start()

        for new_text in streamer:
            response += new_text
          #  print(response)
            if timeFirstRecord == False:
               	timeFirst = time.time() - timeStart
                timeFirstRecord = True
        timeCost = time.time() - timeStart
        token_count_input = len(tokenizer.tokenize(prompt))
        token_count_output = len(tokenizer.tokenize(response))

        ms_first_token = timeFirst * 1000
        ms_after_token = (timeCost - timeFirst) / (token_count_output - 1) * 1000
        print("token count input: ", token_count_input)
        print("token count output: ", token_count_output)
        print("time cost(s): ", timeCost)
        print("First token latency(ms): ", ms_first_token)
        print("After token latency(ms/token)", ms_after_token)
```

**Comment by qiuxin2012** [comment]
You can try our latest nightly >= 2.4.0b20231006, we has improved qwen's performance in https://github.com/intel-analytics/BigDL/pull/9079

**Comment by KiwiHana** [comment]
Qwen 7B i9-13900H, 1st token: 303ms, rest token latency: 141 ms/token (BigDL-LLM 20231009)

**Comment by Oscilloscope98** [comment]
Could you kindly provide more detailed info regarding your memory device, including your memory speed?

**Comment by KiwiHana** [comment]
> @KiwiHana Could you kindly provide more detailed info regarding your memory device, including your memory speed?

Sure. Memory 16GB, 4800MHz, 13900H PC

**Comment by biyuehuang** [comment]
I download Qwen-7B-Chat on Sep.27
bigdl-llm 20231009

I try to use benchmark\all-in-one script, but failed.
https://github.com/intel-analytics/BigDL/blob/main/python/llm/dev/benchmark/all-in-one/run.py

```
(fwhisper) PS C:\Users\llm\Desktop\PC_LLM_UI\benchmark\all-in-one> python .\run.py
2023-10-11 17:21:54,972 - WARNING - Warning: please make sure that you are using the latest codes and checkpoints, especially if you used Qwen-7B before 09.25.2023.请使用最新模型和代码，尤其如果你在9月25日前已经开始使用Qwen-7B，千万注意不要使用错误代码和模型。
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 21.65it/s]
>> loading of model costs 14.276855300000001s
<class 'transformers_modules.Qwen-7B-Chat.modeling_qwen.QWenLMHeadModel'>
Traceback (most recent call last):
  File "C:\Users\llm\Desktop\PC_LLM_UI\benchmark\all-in-one\run.py", line 527, in <module>
    run_model(model, api, conf['in_out_pairs'], conf['local_model_hub'], conf['warm_up'], conf['num_trials'])
  File "C:\Users\llm\Desktop\PC_LLM_UI\benchmark\all-in-one\run.py", line 48, in run_model
    result = run_optimize_model(repo_id, local_model_hub, in_out_pairs, warm_up, num_trials)
  File "C:\Users\llm\Desktop\PC_LLM_UI\benchmark\all-in-one\run.py", line 289, in run_optimize_model
    output_ids = model.generate(input_ids, do_sample=False, max_new_tokens=out_len)
  File "C:\Users\llm\miniconda3\envs\fwhisper\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\llm\Desktop\PC_LLM_UI\benchmark\all-in-one\..\benchmark_util.py", line 1561, in generate
    return self.greedy_search(
  File "C:\Users\llm\Desktop\PC_LLM_UI\benchmark\all-in-one\..\benchmark_util.py", line 2382, in greedy_search
    outputs = self(
  File "C:\Users\llm\Desktop\PC_LLM_UI\benchmark\all-in-one\..\benchmark_util.py", line 531, in __call__
    return self.model(*args, **kwargs)
  File "C:\Users\llm\miniconda3\envs\fwhisper\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\llm/.cache\huggingface\modules\transformers_modules\Qwen-7B-Chat\modeling_qwen.py", line 1104, in forward
    transformer_outputs = self.transformer(
  File "C:\Users\llm\miniconda3\envs\fwhisper\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\llm/.cache\huggingface\modules\transformers_modules\Qwen-7B-Chat\modeling_qwen.py", line 934, in forward
    outputs = block(
  File "C:\Users\llm\miniconda3\envs\fwhisper\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\llm/.cache\huggingface\modules\transformers_modules\Qwen-7B-Chat\modeling_qwen.py", line 635, in forward
    attn_outputs = self.attn(
  File "C:\Users\llm\miniconda3\envs\fwhisper\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
TypeError: qwen_attention_forward() got an unexpected keyword argument 'registered_causal_mask'
```

**Comment by rnwang04** [comment]
@biyuehuang , would you mind try it again with commenting [this line](https://github.com/intel-analytics/BigDL/blob/main/python/llm/dev/benchmark/all-in-one/run.py#L264) to see whether it will raise error at line 289 ?

**Comment by KiwiHana** [comment]
> @biyuehuang , would you mind try it again with commenting [this line](https://github.com/intel-analytics/BigDL/blob/main/python/llm/dev/benchmark/all-in-one/run.py#L264) to see whether it will raise error at line 289 ?

I have commented all this line "model = BenchmarkWrapper(model)" but still failed.

```
(fwhisper) PS C:\Users\llm\Desktop\PC_LLM_UI\benchmark\all-in-one> python .\run.py
2023-10-11 22:16:01,369 - WARNING - Warning: please make sure that you are using the latest codes and checkpoints, especially if you used Qwen-7B before 09.25.2023.请使用最新模型和代码，尤其如果你在9月25日前已经开始使用Qwen-7B，千万注意不要使用错误代码和模型。
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 21.99it/s]
>> loading of model costs 14.199363199999999s
Traceback (most recent call last):
  File "C:\Users\llm\Desktop\PC_LLM_UI\benchmark\all-in-one\run.py", line 528, in <module>
    run_model(model, api, conf['in_out_pairs'], conf['local_model_hub'], conf['warm_up'], conf['num_trials'])
  File "C:\Users\llm\Desktop\PC_LLM_UI\benchmark\all-in-one\run.py", line 48, in run_model
    result = run_optimize_model(repo_id, local_model_hub, in_out_pairs, warm_up, num_trials)
  File "C:\Users\llm\Desktop\PC_LLM_UI\benchmark\all-in-one\run.py", line 289, in run_optimize_model
    output_ids = model.generate(input_ids, do_sample=False, max_new_tokens=out_len)
  File "C:\Users\llm/.cache\huggingface\modules\transformers_modules\Qwen-7B-Chat\modeling_qwen.py", line 1314, in generate
    return super().generate(
  File "C:\Users\llm\miniconda3\envs\fwhisper\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\llm\miniconda3\envs\fwhisper\lib\site-packages\transformers\generation\utils.py", line 1538, in generate
    return self.greedy_search(
  File "C:\Users\llm\miniconda3\envs\fwhisper\lib\site-packages\transformers\generation\utils.py", line 2362, in greedy_search
    outputs = self(
  File "C:\Users\llm\miniconda3\envs\fwhisper\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\llm/.cache\huggingface\modules\transformers_modules\Qwen-7B-Chat\modeling_qwen.py", line 1104, in forward
    transformer_outputs = self.transformer(
  File "C:\Users\llm\miniconda3\envs\fwhisper\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\llm/.cache\huggingface\modules\transformers_modules\Qwen-7B-Chat\modeling_qwen.py", line 934, in forward
    outputs = block(
  File "C:\Users\llm\miniconda3\envs\fwhisper\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\llm/.cache\huggingface\modules\transformers_modules\Qwen-7B-Chat\modeling_qwen.py", line 635, in forward
    attn_outputs = self.attn(
  File "C:\Users\llm\miniconda3\envs\fwhisper\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
TypeError: qwen_attention_forward() got an unexpected keyword argument 'registered_causal_mask'
```

**Comment by biyuehuang** [comment]
（1）config.yaml optimize api 把[run.py#L259](https://github.com/intel-analytics/BigDL/blob/main/python/llm/dev/benchmark/all-in-one/run.py#L259)  model = optimize_model(model) 注释掉，可以运行，昨晚跑了7个小时，测试结果32-32是18s/token，1024-128是21s/token。
（2）transformer INT4 api 把run.py#L159改成input_ids = tokenizer.encode(input_str, return_tensors="pt").to('cpu')，测试结果32-32是0.333s/token，1024-128是0.199s/token

**Comment by rnwang04** [comment]
Have located the root caused of `TypeError: qwen_attention_forward() got an unexpected keyword argument 'registered_causal_mask'`, which is caused by model file update of qwen.
I will raise a PR to update our qwen attention implementation.

**Comment by rnwang04** [comment]
Hi @KiwiHana , this error is fixed, could you please try it again with latest version tomorrow (so that new bigdl-llm package is released)?

**Comment by KiwiHana** [comment]
> Hi @KiwiHana , this error is fixed, could you please try it again with latest version tomorrow (so that new bigdl-llm package is released)?
config.yaml optimize api  by bigdl-llm 1012 version on 13900H 16GB 4800MHz memory.
32-32 99.6ms/token
1024-128 134.5ms/token

Is it reasonable？
