### ISSUE TITLE
run_model get error when benchmark native int4 on CPU

### ISSUE THREAD

**Issue by violet17** [intel-analytics/BigDL#9196]
```
Traceback (most recent call last):
  File "/home/a770/crystal/benchmark/all-in-one/run.py", line 544, in <module>
    run_model(model, api, conf['in_out_pairs'], conf['local_model_hub'], conf['warm_up'], conf['num_trials'], conf['num_beams'])
  File "/home/a770/crystal/benchmark/all-in-one/run.py", line 60, in run_model
    np.mean(result[in_out_pair], axis=0)[0],
UnboundLocalError: local variable 'result' referenced before assignment
```

benchmark native int4 on CPU:
`python run.py`

bigdl-llm  version:                  2.4.0b20231015

**Comment by shane-huang** [comment]
@qiuxin2012 please kindly take a look.

**Comment by qiuxin2012** [comment]
PR https://github.com/intel-analytics/BigDL/pull/9163 can skip this error.
We need to improve the output of native int api by https://github.com/intel-analytics/BigDL/issues/9133 .

**Comment by qiuxin2012** [comment]
#9163 is merged, you can update your `run.py` to upstream, and try again.

**Comment by violet17** [comment]
Thanks.  @qiuxin2012 which version should I use?

**Comment by qiuxin2012** [comment]
> Thanks. @qiuxin2012 which version should I use?

The latest https://github.com/intel-analytics/BigDL/blob/main/python/llm/dev/benchmark/all-in-one/run.py
