### ISSUE TITLE
llama2-7b load_low_bit error on MTL iGPU

### ISSUE THREAD

**Issue by violet17** [intel-analytics/BigDL#9227]
error message:
```
Traceback (most recent call last):
  File "C:\Users\Administrator\Documents\LLM_models\example3.py", line 29, in <module>
    model =  AutoModelForCausalLM.load_low_bit(model_path, trust_remote_code=True, optimize_model=False).eval()
  File "C:\ProgramData\miniconda3\envs\llm\lib\site-packages\bigdl\llm\transformers\model.py", line 296, in load_low_bit
    ) = model_class._load_pretrained_model(
  File "C:\ProgramData\miniconda3\envs\llm\lib\site-packages\transformers\modeling_utils.py", line 3125, in _load_pretrained_model
    model.apply(model._initialize_weights)
  File "C:\ProgramData\miniconda3\envs\llm\lib\site-packages\torch\nn\modules\module.py", line 884, in apply
    module.apply(fn)
  File "C:\ProgramData\miniconda3\envs\llm\lib\site-packages\torch\nn\modules\module.py", line 885, in apply
    fn(self)
  File "C:\ProgramData\miniconda3\envs\llm\lib\site-packages\transformers\modeling_utils.py", line 1261, in _initialize_weights
    self._init_weights(module)
  File "C:\ProgramData\miniconda3\envs\llm\lib\site-packages\transformers\models\llama\modeling_llama.py", line 466, in _init_weights
    module.weight.data.normal_(mean=0.0, std=std)
RuntimeError: "normal_kernel_cpu" not implemented for 'Byte'
```

runing code:

```

import torch
import intel_extension_for_pytorch as ipex

from bigdl.llm.transformers import AutoModelForCausalLM, AutoModel
from transformers import AutoTokenizer

import time
import numpy as np
# from gpu_benchmark_util import BenchmarkWrapper



model_path = r"C:\Users\Administrator\Documents\LLM_models\Llama-2-7b-chat-hf-int4"


prompt = "Once upon a time, there existed a little girl who liked to have adventures. She wanted to go to places and meet new people, and have fun"
tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)


model =  AutoModelForCausalLM.load_low_bit(model_path, trust_remote_code=True, optimize_model=False).eval()


input_ids = tokenizer.encode(prompt, return_tensors="pt")
print("finish to load")

model = model.to('xpu')
model.model.embed_tokens.to('cpu')
input_ids = input_ids.to('xpu')

print("finish to xpu")

# model = BenchmarkWrapper(model)

with torch.inference_mode():
    # wamup two times as use ipex
    for i in range(7):
        st = time.time()
        output = model.generate(input_ids, num_beams=1, do_sample=False, max_new_tokens=32)
        end = time.time()
        print(f'Inference time: {end-st} s')
        output_str = tokenizer.decode(output[0], skip_special_tokens=True)
        print(output_str)

```

env:
windows 11
python 3.9
bigdl  1009
ipex  from yishuo

Thanks.

**Comment by leonardozcm** [comment]
hi @violet17 , what is the version of transformers you are using?

**Comment by violet17** [comment]
transformers==4.31.0

**Comment by leonardozcm** [comment]
I can not reproduce this issue on both windows and linux, and I suspect there might be some unnoticed errors during the installation of the environment or while preparing the model. Maybe you can try:

1. Check your deployment environments again, here is my configs:
On Ultra 5 125H, windows 11, python 3.9, and pip whl lists as follow:
```
(changmin-llm) C:\Users\Administrator\project>pip list
Package                     Version
--------------------------- ------------------
accelerate                  0.21.0
bigdl-llm                   2.4.0b20231009
intel-extension-for-pytorch 2.0.110+gitba7f6c1
safetensors                 0.4.0
sentencepiece               0.1.99
torch                       2.0.0a0+gitc6a572f
transformers                4.31.0
```
2.  Save a new lowbit model with bigdl-llm==2.4.0b20231009 and try it.

**Comment by violet17** [comment]
Thanks @leonardozcm. 
I use AutoModel to load llama2 then cause this error.
