### ISSUE TITLE
[SPR+Flex170]llama2 failed to run on latest bigdl-1019 release based on SPR+Flex170 env

### ISSUE THREAD

**Issue by Yanli2190** [intel-analytics/BigDL#9235]
llama2 failed to run on latest bigdl-1019 release based on SPR+Flex170 env, no such issue with SPR+Max1100 or ICX+Flex170
Steps: 
conda create -n bigdl_llm_1019 python=3.9
conda activate bigdl_llm_1019
pip install --pre --upgrade bigdl-llm[xpu]==2.4.0b20231019 -f https://developer.intel.com/ipex-whl-stable-xpu
wget https://github.com/intel-analytics/esimd_linear/tree/main/benchmark/int4

(bigdl_llm_1019) yanli@a4bf019497e8:~/debug/esimd_linear-main/benchmark/int4$ python llama2.py
/home/yanli/miniconda3/envs/bigdl_llm_1019/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: ''If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
Test /home/yanli/.cache/huggingface/hub/models--meta-llama--Llama-2-7b-chat-hf/snapshots/08751db2aca9bf2f7f80d2e516117a53d7450235/...
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 25.40it/s]
load converted model
torch.float32
<class 'transformers.models.llama.modeling_llama.LlamaForCausalLM'>
input length is:  32
onednn_verbose,info,oneDNN v3.2.0 (commit 67bc621a2da4aefc51f0a59b2af2398fa1d3e1c8)
onednn_verbose,info,cpu,runtime:threadpool,nthr:56
onednn_verbose,info,cpu,isa:Intel AVX-512 with float16, Intel DL Boost and bfloat16 support and Intel AMX with bfloat16 and 8-bit integer support
onednn_verbose,info,gpu,runtime:DPC++
onednn_verbose,info,gpu,engine,0,backend:Level Zero,name:Intel(R) Data Center GPU Flex 170,driver_version:1.3.26516,binary_kernels:enabled
onednn_verbose,info,experimental features are enabled
onednn_verbose,info,use batch_normalization stats one pass is enabled
onednn_verbose,info,prim_template:operation,engine,primitive,implementation,prop_kind,memory_descriptors,attributes,auxiliary,problem_desc,exec_time
onednn_verbose,error,level_zero,errcode 1879048196
Traceback (most recent call last):
  File "/home/yanli/debug/esimd_linear-main/benchmark/int4/llama2.py", line 32, in <module>
    output = llama_model.generate(input_ids, do_sample=False, max_new_tokens=32)
  File "/home/yanli/miniconda3/envs/bigdl_llm_1019/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/yanli/debug/esimd_linear-main/benchmark/int4/benchmark_util.py", line 1564, in generate
    return self.greedy_search(
  File "/home/yanli/debug/esimd_linear-main/benchmark/int4/benchmark_util.py", line 2385, in greedy_search
    outputs = self(
  File "/home/yanli/debug/esimd_linear-main/benchmark/int4/benchmark_util.py", line 531, in __call__
    return self.model(*args, **kwargs)
  File "/home/yanli/miniconda3/envs/bigdl_llm_1019/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/yanli/miniconda3/envs/bigdl_llm_1019/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 806, in forward
    outputs = self.model(
  File "/home/yanli/miniconda3/envs/bigdl_llm_1019/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/yanli/miniconda3/envs/bigdl_llm_1019/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 693, in forward
    layer_outputs = decoder_layer(
  File "/home/yanli/miniconda3/envs/bigdl_llm_1019/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/yanli/miniconda3/envs/bigdl_llm_1019/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 408, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/yanli/miniconda3/envs/bigdl_llm_1019/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/yanli/miniconda3/envs/bigdl_llm_1019/lib/python3.9/site-packages/bigdl/llm/transformers/models/llama.py", line 106, in llama_attention_forward_4_31
    query_states = self.q_proj(hidden_states)
  File "/home/yanli/miniconda3/envs/bigdl_llm_1019/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/yanli/miniconda3/envs/bigdl_llm_1019/lib/python3.9/site-packages/bigdl/llm/transformers/low_bit_linear.py", line 368, in forward
    result = linear_q4_0.forward_new(x_2d, self.weight.data, self.weight.qtype,
RuntimeError: could not create a primitive

I have both Flex and Max GPU inserted to same SPR server, "export ONEAPI_DEVICE_SELECTOR=level_zero:0" will select Flex GPU, it will meet above error, "export ONEAPI_DEVICE_SELECTOR=level_zero:2" will select Max GPU, it works well with same env

**Comment by rnwang04** [comment]
Hi @Yanli2190, I have reproduced this error, but I found on such test case, just run ipex fp16 will cause the same error:
```bash
  File "/home/yanli/miniconda3/envs/bigdl_llm_1019/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: could not create a primitive
```

Would you mind raise this issue to ipex team?

**Comment by Yanli2190** [comment]
I have filed ipex ticket to track this issue -  https://jira.devtools.intel.com/browse/PYTORCHDGQ-3537 
At the same time, I have sent the request to US lab admin to see whether this issue will disappear if we unplug the Max GPU and only insert Flex170 to this SPR server, will update the status later
