### ISSUE TITLE
issues track for running bigdl-llm on cpu/xpu with python3.10

### ISSUE THREAD

**Issue by liu-shaojun** [intel-analytics/BigDL#9270]

**Comment by Jasonzzt** [comment]
On spr-01, I followed [all-in-one](https://github.com/intel-analytics/BigDL/blob/main/python/llm/dev/benchmark/all-in-one/README.md) to run bigdl-llm on Intel CPU with python3.10.
```
python                      3.10.13
bigdl-llm                   2.4.0b20231024
``` 
I tested the models `chatglm2-6b`, `Llama-2-7b-chat-hf`, `Baichuan2-7B-Chat`, `Llama-2-13b-chat-hf` and `mpt-7b-chat`. Except for the `chatglm2-6b` model, all other models are fine to run bigdl-llm on cpu with python3.10.
When running bigdl-llm on cpu with chatglm2-6b, I got the following problem
```
Traceback (most recent call last):
  File "/root/ziteng/BigDL/python/llm/dev/benchmark/all-in-one/./run.py", line 552, in <module>
    run_model(model, api, conf['in_out_pairs'], conf['local_model_hub'], conf['warm_up'], conf['num_trials'], conf['num_beams'], conf['low_bit'])
  File "/root/ziteng/BigDL/python/llm/dev/benchmark/all-in-one/./run.py", line 45, in run_model
    result = run_transformer_int4(repo_id, local_model_hub, in_out_pairs, warm_up, num_trials, num_beams, low_bit)
  File "/root/ziteng/BigDL/python/llm/dev/benchmark/all-in-one/./run.py", line 144, in run_transformer_int4
    model = AutoModelForCausalLM.from_pretrained(model_path, load_in_low_bit=low_bit, trust_remote_code=True,
  File "/root/anaconda3/envs/ziteng-310/lib/python3.10/site-packages/bigdl/llm/transformers/model.py", line 97, in from_pretrained
    model = cls.load_convert(q_k, optimize_model, *args, **kwargs)
  File "/root/anaconda3/envs/ziteng-310/lib/python3.10/site-packages/bigdl/llm/transformers/model.py", line 120, in load_convert
    model = cls.HF_Model.from_pretrained(*args, **kwargs)
  File "/root/anaconda3/envs/ziteng-310/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 496, in from_pretrained
    raise ValueError(
ValueError: Unrecognized configuration class <class 'transformers_modules.chatglm2-6b.configuration_chatglm.ChatGLMConfig'> for this kind of AutoModel: AutoModelForCausalLM.
Model type should be one of BartConfig, BertConfig, BertGenerationConfig, BigBirdConfig, BigBirdPegasusConfig, BioGptConfig, BlenderbotConfig, BlenderbotSmallConfig, BloomConfig, CamembertConfig, CodeGenConfig, CpmAntConfig, CTRLConfig, Data2VecTextConfig, ElectraConfig, ErnieConfig, FalconConfig, GitConfig, GPT2Config, GPT2Config, GPTBigCodeConfig, GPTNeoConfig, GPTNeoXConfig, GPTNeoXJapaneseConfig, GPTJConfig, LlamaConfig, MarianConfig, MBartConfig, MegaConfig, MegatronBertConfig, MusicgenConfig, MvpConfig, OpenLlamaConfig, OpenAIGPTConfig, OPTConfig, PegasusConfig, PLBartConfig, ProphetNetConfig, QDQBertConfig, ReformerConfig, RemBertConfig, RobertaConfig, RobertaPreLayerNormConfig, RoCBertConfig, RoFormerConfig, RwkvConfig, Speech2Text2Config, TransfoXLConfig, TrOCRConfig, XGLMConfig, XLMConfig, XLMProphetNetConfig, XLMRobertaConfig, XLMRobertaXLConfig, XLNetConfig, XmodConfig.
```
Running on version 3.9 also encountered this issue.
It seemed that this was a problem with the model itself.  A related problem was found in Chatglm's issue. https://github.com/THUDM/ChatGLM-6B/issues/37#issuecomment-1704036282   The trainer of huggingface tends to save only the model rather than both model with tokenizer. 

Aside from this issue, There is no other problem running bigdl-llm on cpu with python 3.10.

**Comment by Jasonzzt** [comment]
It runs ok when I load `THUDM/chatglm2-6b` from Huggingface.

**Comment by liu-shaojun** [comment]
## Issue2 on xpu with python 3.10
on Arc05, I followed https://github.com/intel-analytics/BigDL/blob/main/python/llm/example/GPU/HF-Transformers-AutoModels/Model/mpt/README.md to run mpt-7b-chat with BigDL-LLM on Intel GPUs, got the following error:
```
(llm-py310) arda@arda-arc05:~/shaojun/BigDL/python/llm/example/GPU/HF-Transformers-AutoModels/Model/llama2$ python ./generate.py --repo-id-or-model-path /mnt/disk1/models/mpt-7b-chat/
/opt/anaconda3/envs/llm-py310/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: ''If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
Instantiating an MPTForCausalLM model from /home/arda/.cache/huggingface/modules/transformers_modules/modeling_mpt.py
You are using config.init_device='cpu', but you can also use config.init_device="meta" with Composer + FSDP for fast initialization.
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████| 2/2 [00:27<00:00, 13.97s/it]
2023-10-27 13:27:54,304 - bigdl.llm.transformers.utils - INFO - Converting the current model to sym_int4 format......
The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization.
The tokenizer class you load from this checkpoint is 'GPTNeoXTokenizer'.
The class this function is called from is 'LlamaTokenizer'.
You are using the legacy behaviour of the <class 'transformers.models.llama.tokenization_llama.LlamaTokenizer'>. This means that tokens that come after special tokens will not be properly handled. We recommend you to read the related pull request available at https://github.com/huggingface/transformers/pull/24565
Traceback (most recent call last):
  File "/home/arda/shaojun/BigDL/python/llm/example/GPU/HF-Transformers-AutoModels/Model/llama2/./generate.py", line 66, in <module>
    tokenizer = LlamaTokenizer.from_pretrained(model_path, trust_remote_code=True)
  File "/opt/anaconda3/envs/llm-py310/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1841, in from_pretrained
    return cls._from_pretrained(
  File "/opt/anaconda3/envs/llm-py310/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2004, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/opt/anaconda3/envs/llm-py310/lib/python3.10/site-packages/transformers/models/llama/tokenization_llama.py", line 144, in __init__
    self.sp_model.Load(vocab_file)
  File "/opt/anaconda3/envs/llm-py310/lib/python3.10/site-packages/sentencepiece/__init__.py", line 905, in Load
    return self.LoadFromFile(model_file)
  File "/opt/anaconda3/envs/llm-py310/lib/python3.10/site-packages/sentencepiece/__init__.py", line 310, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
TypeError: not a string
```

**Comment by liu-shaojun** [comment]
The output of [Llama-2-7b-chat-hf](https://huggingface.co/meta-llama/Llama-2-7b-chat-hf) and [meta-llama/Llama-2-13b-chat-hf](https://huggingface.co/meta-llama/Llama-2-13b-chat-hf) is as expected as described in https://github.com/intel-analytics/BigDL/blob/main/python/llm/example/GPU/HF-Transformers-AutoModels/Model/llama2/README.md.

**Comment by liu-shaojun** [comment]
## Issue2 [Baichuan2-7B-Chat](https://huggingface.co/baichuan-inc/Baichuan2-7B-Chat) on xpu with python 3.10
on Arc05, I followed https://github.com/intel-analytics/BigDL/blob/main/python/llm/example/GPU/HF-Transformers-AutoModels/Model/baichuan2/README.md to run [Baichuan2-7B-Chat](https://huggingface.co/baichuan-inc/Baichuan2-7B-Chat) with BigDL-LLM on Intel GPUs, got the following error, there is no output:
```
(llm-py310) arda@arda-arc05:~/shaojun/BigDL/python/llm/example/GPU/HF-Transformers-AutoModels/Model/llama2$ python ./generate.py --repo-id-or-model-path /mnt/disk1/models/Baichuan2-7B-Chat/
/opt/anaconda3/envs/llm-py310/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: ''If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
2023-10-27 13:46:47,429 - transformers_modules.modeling_baichuan - WARNING - Xformers is not installed correctly. If you want to use memory_efficient_attention to accelerate training use the following command to install Xformers
pip install xformers.
2023-10-27 13:47:20,754 - bigdl.llm.transformers.utils - INFO - Converting the current model to sym_int4 format......
2023-10-27 13:47:26,479 - bigdl.llm.transformers.models.baichuan2 - WARNING - Xformers is not installed correctly. If you want to use memory_efficient_attention to accelerate training use the following command to install Xformers
pip install xformers.
The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization.
The tokenizer class you load from this checkpoint is 'BaichuanTokenizer'.
The class this function is called from is 'LlamaTokenizer'.
You are using the legacy behaviour of the <class 'transformers.models.llama.tokenization_llama.LlamaTokenizer'>. This means that tokens that come after special tokens will not be properly handled. We recommend you to read the related pull request available at https://github.com/huggingface/transformers/pull/24565
Inference time: 0.12397480010986328 s
-------------------- Prompt --------------------
<s>[INST] <<SYS>>

<</SYS>>

What is AI? [/INST]
-------------------- Output --------------------
[INST] <<SYS>>

<</SYS>>

What is AI? [/INST]
```

**Comment by liu-shaojun** [comment]
The following models had been tested for python3.11 on Arc05/xpu, the output is as expected as described in https://github.com/intel-analytics/BigDL/blob/main/python/llm/example/GPU/HF-Transformers-AutoModels/Model/:

baichuan-inc/Baichuan2-13B-Chat       
meta-llama/Llama-2-7b-chat-hf    
meta-llama/Llama-2-13b-chat-hf   
Qwen/Qwen-7B-Chat  
Qwen/Qwen-14B-Chat 
Qwen/Qwen-VL-Chat          
databricks/dolly-v1-6b  
databricks/dolly-v2-12b 
databricks/dolly-v2-7b     
internlm/internlm-chat-20b    
internlm/internlm-chat-7b-8k   
THUDM/chatglm2-6b

**Comment by liu-shaojun** [comment]
Currently **Python 3.12** is not supported for bigdl-llm since the dependency intel_extension_for_pytorch==2.0.110+xpu only supports up to python 3.11.

**Comment by Romanticoseu** [comment]
## The following models had been tested on CPU with python 3.11

- THUDM/chatglm2-6b
- THUDM/chatglm-6b
- /mpt-7b-chat
- /Llama-2-7b-chat-hf
- /Llama-2-13b-chat-hf
- /Baichuan2-7B-Chat
- /Baichuan2-13B-Chat
On spr-01, I use this `script` to test on python 3.11 
```bash
#!/bin/bash
source bigdl-llm-init
export OMP_NUM_THREADS=48

# set following parameters according to the actual specs of the test machine
numactl -C 0-47 -m 0 python $(dirname "$0")/run.py
```
