### ISSUE TITLE
loading native low-bit(sym_int4) model in fastchat

### ISSUE THREAD

**Issue by junruizh2021** [intel-analytics/BigDL#9273]
BigDL fastchat can load LLM models with BF16 precision downloaded from Hugging Face, such as chatGLM, Llama, and Llama2. These models can then be computed in memory with int4 or int8 precision to reduce inference latency. 

In order to save local disk space and network bandwidth, we want to directly load pre-converted int4 precision models from the local system. **How can we load the pre-converted int4 precision models directly from the local system?** 

We have encountered the following error while attempting to load an int4 precision model.

```
2023-10-26 01:31:22 | INFO | model_worker | Loading the model ['chatglm-6b-tran-int4'] on worker 1fad7da1 ...
2023-10-26 01:31:22 | ERROR | bigdl.llm.utils.common.log4Error |

 

****************************Usage Error************************
Detected model is a low-bit(sym_int4) model, Please use load_low_bit to load this model.
2023-10-26 01:31:22 | ERROR | bigdl.llm.utils.common.log4Error |

 

****************************Call Stack*************************
2023-10-26 01:31:22 | ERROR | stderr | Traceback (most recent call last):
2023-10-26 01:31:22 | ERROR | stderr |   File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
2023-10-26 01:31:22 | ERROR | stderr |     return _run_code(code, main_globals, None,
2023-10-26 01:31:22 | ERROR | stderr |   File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
2023-10-26 01:31:22 | ERROR | stderr |     exec(code, run_globals)
2023-10-26 01:31:22 | ERROR | stderr |   File "/llm/FastChat/fastchat/serve/model_worker.py", line 571, in <module>
2023-10-26 01:31:22 | ERROR | stderr |     args, worker = create_model_worker()
2023-10-26 01:31:22 | ERROR | stderr |   File "/llm/FastChat/fastchat/serve/model_worker.py", line 548, in create_model_worker
2023-10-26 01:31:22 | ERROR | stderr |     worker = ModelWorker(
2023-10-26 01:31:22 | ERROR | stderr |   File "/llm/FastChat/fastchat/serve/model_worker.py", line 229, in __init__
2023-10-26 01:31:22 | ERROR | stderr |     self.model, self.tokenizer = load_model(
2023-10-26 01:31:22 | ERROR | stderr |   File "/llm/FastChat/fastchat/model/model_adapter.py", line 279, in load_model
2023-10-26 01:31:22 | ERROR | stderr |     model, tokenizer = adapter.load_model(model_path, kwargs)
2023-10-26 01:31:22 | ERROR | stderr |   File "/llm/FastChat/fastchat/model/model_adapter.py", line 735, in load_model
2023-10-26 01:31:22 | ERROR | stderr |     model = AutoModel.from_pretrained(
2023-10-26 01:31:22 | ERROR | stderr |   File "/usr/local/lib/python3.9/dist-packages/bigdl/llm/transformers/model.py", line 75, in from_pretrained
2023-10-26 01:31:22 | ERROR | stderr |     invalidInputError(not bigdl_transformers_low_bit,
2023-10-26 01:31:22 | ERROR | stderr |   File "/usr/local/lib/python3.9/dist-packages/bigdl/llm/utils/common/log4Error.py", line 32, in invalidInputError
2023-10-26 01:31:22 | ERROR | stderr |     raise RuntimeError(errMsg)
2023-10-26 01:31:22 | ERROR | stderr | RuntimeError: Detected model is a low-bit(sym_int4) model, Please use load_low_bit to load this model.
```

**Comment by gc-fu** [comment]
We have added this feature just now.  It will work for ChatGLM2 models.

Problem will occurs when using with chatGLM model, we are working on it.

**Comment by junruizh2021** [comment]
Thanks for your efforts.
