### ISSUE TITLE
chatglm-int4 mode expect input to have scalar type of BFloat16

### ISSUE THREAD

**Issue by junruizh2021** [intel-analytics/BigDL#9274]
When we use the chatglm-int4 model for inference in fastchat, after inputting a question, the model returns an error message saying "expect input to have scalar type of BFloat16".
![MicrosoftTeams-image (7)](https://github.com/intel-analytics/BigDL/assets/91523811/2a856b03-b992-446e-8b15-d2c8090efa15)

**Comment by qiyuangong** [comment]
This issue can be reproduced on Xeon with ChatGLM-6B

Load model and save low bit
```python
model = AutoModel.from_pretrained(model_path, load_in_low_bit='sym_int4', trust_remote_code=True)
tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)


model.save_low_bit(save_path)
tokenizer.save_pretrained(save_path)
```

Inference with low bit

```python
model = AutoModel.load_low_bit(load_path, trust_remote_code=True)
tokenizer = AutoTokenizer.from_pretrained(load_path, trust_remote_code=True)

 with torch.inference_mode():
        prompt = CHATGLM_V1_PROMPT_FORMAT.format(prompt=input_str)
        input_ids = tokenizer.encode(prompt, return_tensors="pt")
        st = time.time()
        output = model.generate(input_ids,
                                max_new_tokens=32)
        end = time.time()
        output_str = tokenizer.decode(output[0], skip_special_tokens=True)
        print(f'Inference time: {end-st} s')
        print('-'*20, 'Prompt', '-'*20)
        print(prompt)
        print('-'*20, 'Output', '-'*20)
        print(output_str)
```



Errors
```bash
Traceback (most recent call last):
  File "/home/qiyuan/chatglm_low_bit_infer.py", line 42, in <module>
    output = model.generate(input_ids,
  File "/root/anaconda3/envs/zhengjin-llm/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/anaconda3/envs/zhengjin-llm/lib/python3.9/site-packages/transformers/generation/utils.py", line 1538, in generate
    return self.greedy_search(
  File "/root/anaconda3/envs/zhengjin-llm/lib/python3.9/site-packages/transformers/generation/utils.py", line 2362, in greedy_search
    outputs = self(
  File "/root/anaconda3/envs/zhengjin-llm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm-6b-tran-int4/modeling_chatglm.py", line 1190, in forward
    transformer_outputs = self.transformer(
  File "/root/anaconda3/envs/zhengjin-llm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm-6b-tran-int4/modeling_chatglm.py", line 996, in forward
    layer_ret = layer(
  File "/root/anaconda3/envs/zhengjin-llm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm-6b-tran-int4/modeling_chatglm.py", line 624, in forward
    attention_input = self.input_layernorm(hidden_states)
  File "/root/anaconda3/envs/zhengjin-llm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/anaconda3/envs/zhengjin-llm/lib/python3.9/site-packages/torch/nn/modules/normalization.py", line 190, in forward
    return F.layer_norm(
  File "/root/anaconda3/envs/zhengjin-llm/lib/python3.9/site-packages/torch/nn/functional.py", line 2515, in layer_norm
    return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: mixed dtype (CPU): expect input to have scalar type of BFloat16

```

**Comment by Jasonzzt** [comment]
This issue is related to the type of tensor. And it can be solved by tranferring model to bf16 before inferencing.
Add the following code works for me.
```model.to(torch.bfloat16)```

Inference with low bit:
```
model = AutoModel.load_low_bit(load_path, trust_remote_code=True)
tokenizer = AutoTokenizer.from_pretrained(load_path, trust_remote_code=True)
model.to(torch.bfloat16)
 with torch.inference_mode():
        prompt = CHATGLM_V1_PROMPT_FORMAT.format(prompt=input_str)
        input_ids = tokenizer.encode(prompt, return_tensors="pt")
        st = time.time()
        output = model.generate(input_ids,
                                max_new_tokens=32)
        end = time.time()
        output_str = tokenizer.decode(output[0], skip_special_tokens=True)
        print(f'Inference time: {end-st} s')
        print('-'*20, 'Prompt', '-'*20)
        print(prompt)
        print('-'*20, 'Output', '-'*20)
        print(output_str)
```
Then I get the following result:
```
(ziteng-309) [root@spr01 ziteng]# python chatglm_low_bit_infer.py --load-path "/root/ziteng/low_bit_chatglm-6b-01"
Inference time: 2.54229998588562 s
-------------------- Prompt --------------------
Question：Once upon a time, there existed a little girl who liked to have adventures. She wanted to go to places and meet new people, and have fun

Answer：
-------------------- Output --------------------
Question:Once upon a time, there existed a little girl who liked to have adventures. She wanted to go to places and meet new people, and have fun

Answer: That's me! I'm an adventurer at heart, always looking for new and exciting places to visit and meet new people. I love to explore
```

**Comment by Jasonzzt** [comment]
> When we use the chatglm-int4 model for inference in fastchat, after inputting a question, the model returns an error message saying "expect input to have scalar type of BFloat16". ![MicrosoftTeams-image (7)](https://user-images.githubusercontent.com/91523811/278206992-2a856b03-b992-446e-8b15-d2c8090efa15.png)

Actually, the issue on chatglm-int4 model for inference in fastchat is related to  https://github.com/lm-sys/FastChat/blob/09e4357f3cc518ba34f29988d52123c3a5b59f94/fastchat/model/model_adapter.py#L733C28-L733C28
The package `fastchat` has not adapted for it.

But you can modify the relevant code of fastchat to use the chatglm-int4 model for inference in fastchat.

First, use `pip show fschat` to find the path to package fastchat and
 ```
vim "path to package fastchat"/fastchat/model/model_adapter.py
```
Add the following command in `model_adapter.py`
 ```
from bigdl.llm.transformers import AutoModel as AutoModel_Intel
```
Then, modify `load_model` like the following
```
def load_model(self, model_path: str, from_pretrained_kwargs: dict):
     revision = from_pretrained_kwargs.get("revision", "main")
     tokenizer = AutoTokenizer.from_pretrained(
         model_path, trust_remote_code=True, revision=revision
     )
     if("int4" in model_path.lower()):
         model = AutoModel_Intel.load_low_bit(
             model_path, trust_remote_code=True,  **from_pretrained_kwargs
         )
         model.to(torch.bfloat16)
     else:
         model = AutoModel.from_pretrained(
             model_path, trust_remote_code=True, **from_pretrained_kwargs
         )
     return model, tokenizer
```
At the end, I can get the following results
```
(ziteng-309) [root@spr01 ~]# python3 -m fastchat.serve.cli --model-path "/root/ziteng/chatglm-6b-int4/" --device cpu
问: 介绍一下中国地理
答: 中国是一个拥有悠久历史和丰富文化遗产的国家，也是一个拥有广阔地域的国家。中国地理涵盖了中国的自然环境、人文历史、经济发展等多个方面。

中国地理的主要特点包括：

1. 多山多水，地貌复杂：中国地形以平原、高原为主，但也有一些盆地、山地和丘陵。中国还拥有世界上最长的河流——长江和黄河，以及世界上最长的湖泊——鄱阳湖。

2. 气候多样：中国的气候类型包括温带、亚热带、热带、高原气候等，同时中国还拥有世界上最高的山峰——珠穆朗玛峰。

3. 多元文化：中国拥有多元的文化，包括汉族文化、少数民族文化等。中国的各个地区都有不同的方言、习俗和节日。

4. 经济发展：中国经济发展迅速，不同地区的经济状况和发展水平也存在差异。

中国地理是一个多元、复杂而又丰富多彩的地理领域，对于理解中国的自然环境、人文历史、经济发展等方面都有很大的帮助。

```
