### ISSUE TITLE
QloRA finetuning for llama2-70b on sys-821 - Timed out initializing process group in store based barrier on rank: 0

### ISSUE THREAD

**Issue by ywang30intel** [intel-analytics/BigDL#9288]
2023-10-26 14:48:55,606 - INFO - Waiting in store based barrier to initialize process group for rank: 1, key: store_based_barrier_key:2 (world_size=8, worker_count=2, timeout=0:30:00)
2023-10-26 14:49:05,483 - INFO - Waiting in store based barrier to initialize process group for rank: 0, key: store_based_barrier_key:2 (world_size=8, worker_count=2, timeout=0:30:00)
2023-10-26 14:49:05,613 - INFO - Waiting in store based barrier to initialize process group for rank: 1, key: store_based_barrier_key:2 (world_size=8, worker_count=2, timeout=0:30:00)
2023-10-26 14:49:15,492 - INFO - Waiting in store based barrier to initialize process group for rank: 0, key: store_based_barrier_key:2 (world_size=8, worker_count=2, timeout=0:30:00)
2023-10-26 14:49:15,622 - INFO - Waiting in store based barrier to initialize process group for rank: 1, key: store_based_barrier_key:2 (world_size=8, worker_count=2, timeout=0:30:00)
Traceback (most recent call last):
  File "/home/ywang30/workspace_bigdl_QloRA/bigdl-qlora-alpaca/finetune.py", line 310, in <module>
    fire.Fire(train)
  File "/home/ywang30/miniconda3/envs/bigdl_qlora/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/ywang30/miniconda3/envs/bigdl_qlora/lib/python3.9/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/ywang30/miniconda3/envs/bigdl_qlora/lib/python3.9/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/ywang30/workspace_bigdl_QloRA/bigdl-qlora-alpaca/finetune.py", line 300, in train
    trainer.train(resume_from_checkpoint=resume_from_checkpoint)
  File "/home/ywang30/miniconda3/envs/bigdl_qlora/lib/python3.9/site-packages/transformers/trainer.py", line 1591, in train
    return inner_training_loop(
  File "/home/ywang30/miniconda3/envs/bigdl_qlora/lib/python3.9/site-packages/transformers/trainer.py", line 1726, in _inner_training_loop
    model, self.optimizer = self.accelerator.prepare(self.model, self.optimizer)
  File "/home/ywang30/miniconda3/envs/bigdl_qlora/lib/python3.9/site-packages/accelerate/accelerator.py", line 1280, in prepare
    result = self._prepare_deepspeed(*args)
  File "/home/ywang30/miniconda3/envs/bigdl_qlora/lib/python3.9/site-packages/accelerate/accelerator.py", line 1662, in _prepare_deepspeed
    engine, optimizer, _, lr_scheduler = deepspeed.initialize(**kwargs)
  File "/home/ywang30/miniconda3/envs/bigdl_qlora/lib/python3.9/site-packages/deepspeed/__init__.py", line 171, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/home/ywang30/miniconda3/envs/bigdl_qlora/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 262, in __init__
    self._configure_distributed_model(model)
  File "/home/ywang30/miniconda3/envs/bigdl_qlora/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 1110, in _configure_distributed_model
    self.data_parallel_group = groups._get_data_parallel_group()
  File "/home/ywang30/miniconda3/envs/bigdl_qlora/lib/python3.9/site-packages/deepspeed/utils/groups.py", line 360, in _get_data_parallel_group
    return _clone_world_group()
  File "/home/ywang30/miniconda3/envs/bigdl_qlora/lib/python3.9/site-packages/deepspeed/utils/groups.py", line 320, in _clone_world_group
    _WORLD_GROUP = dist.new_group(ranks=range(dist.get_world_size()))
  File "/home/ywang30/miniconda3/envs/bigdl_qlora/lib/python3.9/site-packages/deepspeed/comm/comm.py", line 185, in new_group
    return cdb.new_group(ranks)
  File "/home/ywang30/miniconda3/envs/bigdl_qlora/lib/python3.9/site-packages/deepspeed/comm/torch.py", line 332, in new_group
    return torch.distributed.new_group(ranks)
  File "/home/ywang30/miniconda3/envs/bigdl_qlora/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 3545, in new_group
    _store_based_barrier(global_rank, default_store, timeout)
  File "/home/ywang30/miniconda3/envs/bigdl_qlora/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 470, in _store_based_barrier
    raise RuntimeError(
RuntimeError: Timed out initializing process group in store based barrier on rank: 0, for key: store_based_barrier_key:2 (world_size=8, worker_count=2, timeout=0:30:00)
Traceback (most recent call last):
  File "/home/ywang30/workspace_bigdl_QloRA/bigdl-qlora-alpaca/finetune.py", line 310, in <module>

**Comment by hkvision** [comment]
@rnwang04 Could please take a look at it?

**Comment by rnwang04** [comment]
I have reproduced this issue.
On that machine, llama2-7b can finetune on 8 card 16 nodes, and llama2-70b can finetune on 1 card, but if we finetune llama2-70b on more than 1 card, it will hang.
Still no idea about the root cause, @ywang30intel will try to downgrade the driver version first.

**Comment by ywang30intel** [comment]
Downgrade the driver to 682.38 (https://dgpu-docs.intel.com/releases/production_682.38_20230929.html) solved the issue. We can close it now.
thanks.
-Yang
