### ISSUE TITLE
model save will trigger a bug when model continue training

### ISSUE THREAD

**Issue by SeaOfOcean** [intel-analytics/BigDL#929]
The code is like the following

```
"save model" should "work properly" in {
    val model = Sequential[Float]()
    model.add(ConcatTable().add(Identity()).add(Identity()))
    model.add(ParallelTable().add(Reshape(Array(3, 2))).add(Reshape(Array(3, 2))))
    model.add(FlattenTable())
    model.add(ConcatTable().add(Identity()))
    val input = Tensor[Float](2, 3)
    model.forward(input)
    model.backward(input, model.output)

    model.save("/tmp/tmpmodel", true)
    val input2 = Tensor[Float](2, 3)
    model.forward(input2)
    model.backward(input2, model.output)
  }
```
It throws exception

```
java.lang.ArrayIndexOutOfBoundsException was thrown.
java.lang.ArrayIndexOutOfBoundsException
	at java.lang.System.arraycopy(Native Method)
	at com.intel.analytics.bigdl.tensor.DenseTensor$.copy(DenseTensor.scala:2243)
	at com.intel.analytics.bigdl.tensor.DenseTensor.copy(DenseTensor.scala:374)
	at com.intel.analytics.bigdl.nn.ConcatTable.copyTable(ConcatTable.scala:77)
	at com.intel.analytics.bigdl.nn.ConcatTable.copyTable(ConcatTable.scala:81)
	at com.intel.analytics.bigdl.nn.ConcatTable.updateGradInput(ConcatTable.scala:128)
	at com.intel.analytics.bigdl.nn.ConcatTable.updateGradInput(ConcatTable.scala:34)
	at com.intel.analytics.bigdl.nn.abstractnn.AbstractModule.backward(AbstractModule.scala:186)
	at com.intel.analytics.bigdl.nn.Sequential.backward(Sequential.scala:82)
	at com.intel.analytics.bigdl.pipeline.ssd.example.TrainSpec$$anonfun$7.apply$mcV$sp(TrainSpec.scala:509)
	at com.intel.analytics.bigdl.pipeline.ssd.example.TrainSpec$$anonfun$7.apply(TrainSpec.scala:496)
	at com.intel.analytics.bigdl.pipeline.ssd.example.TrainSpec$$anonfun$7.apply(TrainSpec.scala:496)
	at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
```

**Comment by SeaOfOcean** [comment]
Because Reshape use view to get GradInput, which reuse the storage but in different tensor.

So when the former tensor with the same storage is set, this tensor has the original size and dim but no storage. In this case, tensor resize cannot work properly

**Comment by qiuxin2012** [comment]
I reproduced this issue, seems a bug of ConcatTable's clearState(). ConcatTable's clearState() doesn't clear its gradInput, when gradInput is a Table.
