### ISSUE TITLE
Export QLoRA merged model Failed

### ISSUE THREAD

**Issue by Ariadne330** [intel-analytics/BigDL#9312]
### Test Env: 
- Machine Arc14
- bigdl-llm2.4.0b20231026
- intel-extension-for-pytorch   2.0.110+xpu
- Information about driver  
   ```Shell
      [opencl:acc:0] Intel(R) FPGA Emulation Platform for OpenCL(TM), Intel(R) FPGA Emulation Device 1.2 [2023.16.7.0.21_160000]
      [opencl:cpu:1] Intel(R) OpenCL, 13th Gen Intel(R) Core(TM) i9-13900K 3.0 [2023.16.7.0.21_160000]
      [opencl:gpu:2] Intel(R) OpenCL Graphics, Intel(R) Arc(TM) A770 Graphics 3.0 [23.17.26241.33]
      [ext_oneapi_level_zero:gpu:0] Intel(R) Level-Zero, Intel(R) Arc(TM) A770 Graphics 1.3 [1.3.26241]
   ```

### Test Model:
[Llama-2-7b-hf](https://huggingface.co/meta-llama/Llama-2-7b-hf)

### Error Detail

When verifying the finetune example in [GPU example](https://github.com/intel-analytics/BigDL/tree/main/python/llm/example/GPU/QLoRA-FineTuning), I can successfully export the QLoRA model with  `fqlora_finetuning.py`, but when it comes to `export_merged_model.py` an error raised:
```Shell
python export_merged_model.py --repo-id-or-model-path /mnt/disk1/models/Llama-2-7b-hf --adapter_path outputs/checkpoint-200 --output_path outputs/checkpoint-200-merged_new
```

```Shell
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00,  6.22it/s]
/home/arda/anaconda3/envs/yining-llm-qlora/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: ''If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
Traceback (most recent call last):
  File "/home/arda/Yining/qlora/export_merged_model_ori.py", line 64, in <module>
    lora_model = PeftModel.from_pretrained(
  File "/home/arda/anaconda3/envs/yining-llm-qlora/lib/python3.9/site-packages/bigdl/llm/transformers/qlora.py", line 202, in from_pretrained
    model = PeftModel.from_pretrained(*args, **kwargs)
  File "/home/arda/anaconda3/envs/yining-llm-qlora/lib/python3.9/site-packages/peft/peft_model.py", line 278, in from_pretrained
    model.load_adapter(model_id, adapter_name, is_trainable=is_trainable, **kwargs)
  File "/home/arda/anaconda3/envs/yining-llm-qlora/lib/python3.9/site-packages/peft/peft_model.py", line 577, in load_adapter
    max_memory = get_balanced_memory(
  File "/home/arda/anaconda3/envs/yining-llm-qlora/lib/python3.9/site-packages/accelerate/utils/modeling.py", line 740, in get_balanced_memory
    [
  File "/home/arda/anaconda3/envs/yining-llm-qlora/lib/python3.9/site-packages/accelerate/utils/modeling.py", line 743, in <listcomp>
    if (torch.device(d).type == "xpu" or torch.xpu.get_device_properties(d).dev_type == "gpu")
  File "/home/arda/anaconda3/envs/yining-llm-qlora/lib/python3.9/site-packages/intel_extension_for_pytorch/xpu/__init__.py", line 238, in get_device_properties
    device = _get_device_index(device, optional=True)
  File "/home/arda/anaconda3/envs/yining-llm-qlora/lib/python3.9/site-packages/torch/_utils.py", line 715, in _get_device_index
    raise ValueError("Expected a non cpu device, but got: {}".format(device))
ValueError: Expected a non cpu device, but got: cpu

```

And current workaround is putting the model on xpu to enable the merging process with two lines changed:
```Python
   base_model = AutoModelForCausalLM.from_pretrained(
        base_model,
        # load_in_low_bit="nf4", # should load the orignal model
        torch_dtype=torch.float16,
        device_map={"": "xpu"},
    )
   lora_model = PeftModel.from_pretrained(
        base_model,
        adapter_path,
        device_map={"": "xpu"},
        torch_dtype=torch.float16,
    )

```

**Comment by Ariadne330** [comment]
And Cheen Hau has the same problem when verifying this script. Can you help us fix this? @yangw1234

**Comment by rnwang04** [comment]
This script works fine for me. Would you mind testing it again with `accelerate==0.23.0` ?

**Comment by Ariadne330** [comment]
It just works! Thanks a lot ~
```
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 41.94it/s]
/home/arda/anaconda3/envs/yining-llm-qlora/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: ''If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
2023-10-31 09:59:40,601 - INFO - We will use 90% of the memory on device 0 for storing the model, and 10% for the buffer to avoid OOM. You can set `max_memory` in to a higher value to use more memory (at your own risk).
Using pad_token, but it is not set yet.
Using pad_token, but it is not set yet.
```

**Comment by qiuxin2012** [comment]
@rnwang04 should we update accelerate to 0.23.0 in setup.py?

**Comment by rnwang04** [comment]
Plan to update example first, change of setup may need more verification.
