### ISSUE TITLE
llama2-7b inference  out of memeory on PVC 1100

### ISSUE THREAD

**Issue by HoppeDeng** [intel-analytics/BigDL#9383]
sw version:
bigdl-core-xe               2.4.0b20231106
bigdl-core-xe-esimd         2.4.0b20231106
bigdl-llm                   2.4.0b20231106

inference code:(token in 1024: token out: 1024)
# Load model
    model = AutoModelForCausalLM.from_pretrained(model_path,
                                                 trust_remote_code=True,
                                                 torch_dtype='auto',
                                                 low_cpu_mem_usage=True)

    # With only one line to enable BigDL-LLM optimization on model
    model = optimize_model(model, low_bit="fp16")

    model = model.to('xpu')

    # Load tokenizer
    tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
    
    # Generate predicted tokens
    with torch.inference_mode():
        prompt = LLAMA2_PROMPT_FORMAT.format(prompt=args.prompt)
        input_ids = tokenizer.encode(prompt, return_tensors="pt").to('xpu')
        # ipex model needs a warmup, then inference time can be accurate
        output = model.generate(input_ids,
                                max_new_tokens=args.n_predict)
        torch.xpu.synchronize()

output:
Traceback (most recent call last):                                                                                                              
  File "/home/hpdeng/bigdl_llm/./gen.py", line 72, in <module>                                                                                  
    output = model.generate(input_ids,                                                                                                          
  File "/home/hpdeng/anaconda3/envs/bigdl_llm/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context            
    return func(*args, **kwargs)                                                                                                                
  File "/home/hpdeng/anaconda3/envs/bigdl_llm/lib/python3.9/site-packages/transformers/generation/utils.py", line 1324, in generate             
    model_kwargs["attention_mask"] = self._prepare_attention_mask_for_generation(                                                               
  File "/home/hpdeng/anaconda3/envs/bigdl_llm/lib/python3.9/site-packages/transformers/generation/utils.py", line 605, in _prepare_attention_mas
k_for_generation                                                                                                                                                          "DNP1" 10:30 08-Nov-23
    is_pad_token_in_inputs = (pad_token_id is not None) and (pad_token_id in inputs)
  File "/home/hpdeng/anaconda3/envs/bigdl_llm/lib/python3.9/site-packages/torch/_tensor.py", line 997, in __contains__
    return (element == self).any().item()  # type: ignore[union-attr]
RuntimeError: Allocation is out of device memory on current platform.

**Comment by hkvision** [comment]
@rnwang04 Please take a look?

**Comment by HoppeDeng** [comment]
I have tested the new code and OOM happened again.
