### ISSUE TITLE
Unable to run Mistral on Arc A770 on Ubuntu 23.04

### ISSUE THREAD

**Issue by prakal** [intel-analytics/BigDL#9411]
New to LLM's and Intel ML ecosystem. I have oneAPI installed and am able to run stable diffusion using my GPU pretty smoothly. However I am running into issues running Mistral. I followed instructions and used `transformers-4.34.0`. `torch` at 2.0.1a0+cxx11.abi and `intel-extension-for-pytorch` at 2.0.110+xpu

```
$ python generate.py --prompt 'What is AI?'
/home/pk/miniconda3/envs/llm/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: ''If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:13<00:00,  6.75s/it]
2023-11-09 11:39:54,075 - bigdl.llm.transformers.utils - INFO - Converting the current model to sym_int4 format......
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Traceback (most recent call last):
  File "/home/pk/miniconda3/mistral/generate.py", line 59, in <module>
    output = model.generate(input_ids,
  File "/home/pk/miniconda3/envs/llm/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/pk/miniconda3/envs/llm/lib/python3.9/site-packages/transformers/generation/utils.py", line 1606, in generate
    return self.greedy_search(
  File "/home/pk/miniconda3/envs/llm/lib/python3.9/site-packages/transformers/generation/utils.py", line 2454, in greedy_search
    outputs = self(
  File "/home/pk/miniconda3/envs/llm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/pk/miniconda3/envs/llm/lib/python3.9/site-packages/transformers/models/mistral/modeling_mistral.py", line 1045, in forward
    outputs = self.model(
  File "/home/pk/miniconda3/envs/llm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/pk/miniconda3/envs/llm/lib/python3.9/site-packages/transformers/models/mistral/modeling_mistral.py", line 932, in forward
    layer_outputs = decoder_layer(
  File "/home/pk/miniconda3/envs/llm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/pk/miniconda3/envs/llm/lib/python3.9/site-packages/transformers/models/mistral/modeling_mistral.py", line 621, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/pk/miniconda3/envs/llm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/pk/miniconda3/envs/llm/lib/python3.9/site-packages/bigdl/llm/transformers/models/mistral.py", line 79, in mistral_attention_forward
    query_states = self.q_proj(hidden_states)
  File "/home/pk/miniconda3/envs/llm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/pk/miniconda3/envs/llm/lib/python3.9/site-packages/bigdl/llm/transformers/low_bit_linear.py", line 424, in forward
    import linear_q4_0
ImportError: libdnnl.so.3: cannot open shared object file: No such file or directory
```
I see that it is unable to find `libdnnl.so.3` which looks like it should be [installed as part of oneDNN (oneAPI)](https://oneapi-src.github.io/oneDNN/dev_guide_link.html#linux), but I don't find it anywhere. I re-installed oneAPI as well but same error. Has anyone else run into this issue?

**Comment by prakal** [comment]
Solved, I had to add the correct location to the `LD_LIBRARY_PATH`: `export LD_LIBRARY_PATH=/opt/intel/oneapi/dnnl/2023.2.0/cpu_dpcpp_gpu_dpcpp/lib:$LD_LIBRARY_PATH`. Inference is still slow-ish but it works.
