### ISSUE TITLE
Error when run AquilaChat2-7B on iGPU

### ISSUE THREAD

**Issue by KiwiHana** [intel-analytics/BigDL#9464]
OS: windows 
MTL iGPU
intel-extension-for-pytorch 2.0.110+gitba7f6c1
bigdl-core-xe               2.4.0.dev0
bigdl-llm                   2.4.0b20231029
```
>python example3.py
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 3/3 [00:23<00:00,  7.94s/it]
2023-11-15 10:32:17,286 - bigdl.llm.transformers.utils - INFO - Converting the current model to sym_int4 format......
finish to load
finish to xpu
<class 'transformers_modules.AquilaChat2-7B.modeling_aquila.AquilaForCausalLM'>
stream_chat-----input_ids: {'input_ids': tensor([[20018,  4278,   262,  1325,    12,  1185, 24303,   262,  3282,  6153,
          1285, 19450,   318,   749, 53620,    14,  3032,  5967,   318,  1050,
           318,  9535,   323,  4992,  1504,  1963,    12,   323,   749,  1606]],
       device='xpu:0'), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1]], device='xpu:0')}
C:\Users\Administrator\Documents\LLM_Demo\benchmark_util.py:1293: UserWarning: You have modified the pretrained model configuration to control generation. This is a deprecated strategy to control generation and will be removed soon, in a future version. Please use a generation configuration file (see https://huggingface.co/docs/transformers/main_classes/text_generation)
  warnings.warn(
Exception in thread Thread-4:
Traceback (most recent call last):
  File "C:\ProgramData\miniconda3\envs\audio-whisper\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\miniconda3\envs\audio-whisper\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ProgramData\miniconda3\envs\audio-whisper\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Administrator\Documents\LLM_Demo\benchmark_util.py", line 1561, in generate
    return self.greedy_search(
  File "C:\Users\Administrator\Documents\LLM_Demo\benchmark_util.py", line 2382, in greedy_search
    outputs = self(
  File "C:\Users\Administrator\Documents\LLM_Demo\benchmark_util.py", line 531, in __call__
    return self.model(*args, **kwargs)
  File "C:\ProgramData\miniconda3\envs\audio-whisper\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Administrator/.cache\huggingface\modules\transformers_modules\AquilaChat2-7B\modeling_aquila.py", line 832, in forward
    outputs = self.model(
  File "C:\ProgramData\miniconda3\envs\audio-whisper\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Administrator/.cache\huggingface\modules\transformers_modules\AquilaChat2-7B\modeling_aquila.py", line 720, in forward
    layer_outputs = decoder_layer(
  File "C:\ProgramData\miniconda3\envs\audio-whisper\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Administrator/.cache\huggingface\modules\transformers_modules\AquilaChat2-7B\modeling_aquila.py", line 433, in forward
    hidden_states = self.input_layernorm(hidden_states)
  File "C:\ProgramData\miniconda3\envs\audio-whisper\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\ProgramData\miniconda3\envs\audio-whisper\lib\site-packages\bigdl\llm\transformers\models\llama.py", line 80, in llama_rms_norm_forward
    hidden_states, _ = torch.ops.torch_ipex.rms_norm(hidden_states,
  File "C:\ProgramData\miniconda3\envs\audio-whisper\lib\site-packages\torch\_ops.py", line 502, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: torch_ipex::rms_norm() expected at most 3 argument(s) but received 4 argument(s). Declaration: torch_ipex::rms_norm.xpu(Tensor _0, int[] _1, Tensor _2) -> (Tensor _0, Tensor _1)
```

**Comment by Oscilloscope98** [comment]
Hi, this is due to that you are using a specific ipex version for iGPU. There is a workaround to solve this problem:

In `bigdl/llm/transformers/models/llama.py`, find function [llama_rms_norm_forward](https://github.com/intel-analytics/BigDL/blob/main/python/llm/src/bigdl/llm/transformers/models/llama.py#L76). Here you need to ensure that even ipex version is `2.0.110+gitba7f6c1`, we still go into the first `if` option. i.e., you could add an `elif` option:

```python
        if ipex_version == "2.0.110+xpu":
            hidden_states, _ = torch.ops.torch_ipex.rms_norm(hidden_states,
                                                             [self.weight.size(0)], self.weight)
        elif ipex_version == "2.0.110+gitba7f6c1":
            hidden_states, _ = torch.ops.torch_ipex.rms_norm(hidden_states,
                                                             [self.weight.size(0)], self.weight)
        else:
            hidden_states, _ = torch.ops.torch_ipex.rms_norm(hidden_states,
                                                             [self.weight.size(0)], self.weight,
                                                             self.variance_epsilon)
```

**Comment by KiwiHana** [comment]
Solved! Thanks!
