### ISSUE TITLE
Baichuan2-13B  get RuntimeError: Native API failed. Native API returns: -5 (PI_ERROR_OUT_OF_RESOURCES) -5 (PI_ERROR_OUT_OF_RESOURCES)

### ISSUE THREAD

**Issue by violet17** [intel-analytics/BigDL#9467]
code: 

```
import torch
import intel_extension_for_pytorch as ipex

from bigdl.llm.transformers import AutoModelForCausalLM, AutoModel
from transformers import AutoTokenizer

import time
import numpy as np
from benchmark_util import BenchmarkWrapper
from transformers import TextIteratorStreamer
def stream_chat(model, tokenizer, prompt, max_new_tokens, history=[], device="xpu"):
    # format conversation context as prompt through chat history
    #prompt = CHATGLM_V2_PROMPT_FORMAT.format(prompt=input_str)
    #prompt = LLAMA2_PROMPT_FORMAT.format(prompt=input)
    input_ids = tokenizer([prompt], return_tensors='pt').to(device)
    print("stream_chat-----input_ids:", input_ids)

    streamer = TextIteratorStreamer(tokenizer,
                                    skip_prompt=True, # skip prompt in the generated tokens
                                    skip_special_tokens=True)

    generate_kwargs = dict(
        input_ids,
        streamer=streamer,
        num_beams=1,
        do_sample=False,
        max_new_tokens=max_new_tokens
    )

    # to ensure non-blocking access to the generated text, generation process should be ran in a separate thread
    from threading import Thread

    thread = Thread(target=model.generate, kwargs=generate_kwargs)
    thread.start()
    history = []

    output_str = ""
    for stream_output in streamer:
        output_str += stream_output
        yield output_str, history


model_path = r"C:\Users\Administrator\Documents\LLM_Demo\checkpoint\Baichuan2-13B-Chat-int4"


prompt = "Once upon a time, there existed a little girl who liked to have adventures. She wanted to go to places and meet new people, and have fun"
tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)

# model = AutoModelForCausalLM.from_pretrained(model_path, trust_remote_code=True, optimize_model=True, load_in_4bit=True).eval()
model = AutoModelForCausalLM.load_low_bit(model_path, trust_remote_code=True, optimize_model=False).eval()
#model = AutoModel.from_pretrained(model_path, trust_remote_code=True, optimize_model=True, load_in_4bit=True).eval()

input_ids = tokenizer.encode(prompt, return_tensors="pt")
print("finish to load")

model = model.to('xpu')
model.model.embed_tokens.to('cpu')
#model.transformer.embedding.to('cpu')
input_ids = input_ids.to('xpu')

print("finish to xpu")

model = BenchmarkWrapper(model)

# with torch.inference_mode():
#     # wamup two times as use ipex
#     for i in range(7):
#         st = time.time()
#         output = model.generate(input_ids, num_beams=1, do_sample=False, max_new_tokens=32)
#         end = time.time()
#         print(f'Inference time: {end-st} s')
#         output_str = tokenizer.decode(output[0], skip_special_tokens=True)
#         print(output_str)

for _ in range(5):
    response_ = ""
    response = ""
    timeFirst = 0
    timeFirstRecord = False
    torch.xpu.synchronize()
    timeStart = time.time()
    with torch.inference_mode():
        for response, history in stream_chat(model, tokenizer, prompt,32):
            print(response.replace(response_, ""), end="")  ###  !!!! return 
            response_ = response
            if timeFirstRecord == False:
                torch.xpu.synchronize()
                timeFirst = time.time() - timeStart
                timeFirstRecord = True
        timeCost = time.time() - timeStart
    token_count_input = len(tokenizer.tokenize(prompt))
    token_count_output = len(tokenizer.tokenize(response))
    ms_first_token = timeFirst * 1000
    ms_after_token = (timeCost - timeFirst) / (token_count_output - 1+1e-8) * 1000
    print("input: ", prompt)
    print("output: ", response)
    print("token count input: ", token_count_input)
    print("token count output: ", token_count_output)
    print("time cost(s): ", timeCost)
    print("First token latency(ms): ", ms_first_token)
    print("After token latency(ms/token)", ms_after_token)

```

log:

```
stream_chat-----input_ids: {'input_ids': tensor([[13602,  5920,  1346,  1750, 92323,  1772, 29165,  1346,  3110,  5074,
          1642, 16077,  1375,  1527, 27044,    72,  2556,  4891,  1375,  1596,
          1375,  6679,  1377,  3099,  1662,  1808, 92323,  1377,  1527,  2431]],
       device='xpu:0'), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1]], device='xpu:0')}
C:\Users\Administrator\Documents\audiollm\benchmark_util.py:1491: UserWarning: You are calling .generate() with the `input_ids` being on a device type different than your model's device. `input_ids` is on xpu, whereas the model is on cpu. You may experience unexpected behaviors or slower generation. Please make sure that you have put `input_ids` to the correct device by calling for example input_ids = input_ids.to('cpu') before running `.generate()`.
  warnings.warn(
Exception in thread Thread-4:
Traceback (most recent call last):
  File "C:\ProgramData\miniconda3\envs\audio\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\miniconda3\envs\audio\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ProgramData\miniconda3\envs\audio\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Administrator\Documents\audiollm\benchmark_util.py", line 1561, in generate
    return self.greedy_search(
  File "C:\Users\Administrator\Documents\audiollm\benchmark_util.py", line 2382, in greedy_search
    outputs = self(
  File "C:\Users\Administrator\Documents\audiollm\benchmark_util.py", line 531, in __call__
    return self.model(*args, **kwargs)
  File "C:\ProgramData\miniconda3\envs\audio\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Administrator/.cache\huggingface\modules\transformers_modules\Baichuan2-13B-Chat\modeling_baichuan.py", line 694, in forward
    outputs = self.model(
  File "C:\ProgramData\miniconda3\envs\audio\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Administrator/.cache\huggingface\modules\transformers_modules\Baichuan2-13B-Chat\modeling_baichuan.py", line 405, in forward
    alibi_mask = self.get_alibi_mask(inputs_embeds, seq_length_with_past)
  File "C:\Users\Administrator/.cache\huggingface\modules\transformers_modules\Baichuan2-13B-Chat\modeling_baichuan.py", line 340, in get_alibi_mask
    _gen_alibi_mask(tensor, self.n_head, self.max_cache_pos).to(
RuntimeError: Native API failed. Native API returns: -5 (PI_ERROR_OUT_OF_RESOURCES) -5 (PI_ERROR_OUT_OF_RESOURCES)
```

envionment:
```
bigdl-core-xe               2.4.0.dev0
bigdl-llm                   2.4.0b20231009
intel-extension-for-pytorch 2.0.110+gitba7f6c1
torch                       2.0.0a0+gitc6a572f
```

MTL  u7  32G mem.
when inference, iGPU mem is 15.1GB
GPU driver: 5002

put embed to iGPU， got error:
```
Traceback (most recent call last):
  File "C:\ProgramData\miniconda3\envs\llm\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\miniconda3\envs\llm\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ProgramData\miniconda3\envs\llm\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Administrator\Documents\audiollm\benchmark_util.py", line 1561, in generate
    return self.greedy_search(
  File "C:\Users\Administrator\Documents\audiollm\benchmark_util.py", line 2382, in greedy_search
    outputs = self(
  File "C:\Users\Administrator\Documents\audiollm\benchmark_util.py", line 531, in __call__
    return self.model(*args, **kwargs)
  File "C:\ProgramData\miniconda3\envs\llm\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Administrator/.cache\huggingface\modules\transformers_modules\Baichuan2-13B-Chat\modeling_baichuan.py", line 694, in forward
    outputs = self.model(
  File "C:\ProgramData\miniconda3\envs\llm\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Administrator/.cache\huggingface\modules\transformers_modules\Baichuan2-13B-Chat\modeling_baichuan.py", line 405, in forward
    alibi_mask = self.get_alibi_mask(inputs_embeds, seq_length_with_past)
  File "C:\Users\Administrator/.cache\huggingface\modules\transformers_modules\Baichuan2-13B-Chat\modeling_baichuan.py", line 340, in get_alibi_mask
    _gen_alibi_mask(tensor, self.n_head, self.max_cache_pos).to(
RuntimeError: Native API failed. Native API returns: -5 (PI_ERROR_OUT_OF_RESOURCES) -5 (PI_ERROR_OUT_OF_RESOURCES)
```

load_low_bit  and put embed to cpu, got error:

```
2023-11-15 11:03:40,972 - transformers_modules.Baichuan2-13B-Chat-int4.modeling_baichuan - WARNING - Xformers is not installed correctly. If you want to use memory_efficient_attention to accelerate training use the following command to install Xformers
pip install xformers.
Traceback (most recent call last):
  File "C:\Users\Administrator\Documents\audiollm\example3.py", line 50, in <module>
    model = AutoModelForCausalLM.load_low_bit(model_path, trust_remote_code=True, optimize_model=False).eval()
  File "C:\ProgramData\miniconda3\envs\audio\lib\site-packages\bigdl\llm\transformers\model.py", line 296, in load_low_bit
    ) = model_class._load_pretrained_model(
  File "C:\ProgramData\miniconda3\envs\audio\lib\site-packages\transformers\modeling_utils.py", line 3260, in _load_pretrained_model
    new_error_msgs, offload_index, state_dict_index = _load_state_dict_into_meta_model(
  File "C:\ProgramData\miniconda3\envs\audio\lib\site-packages\transformers\modeling_utils.py", line 717, in _load_state_dict_into_meta_model
    set_module_tensor_to_device(model, param_name, param_device, **set_module_kwargs)
  File "C:\ProgramData\miniconda3\envs\audio\lib\site-packages\accelerate\utils\modeling.py", line 285, in set_module_tensor_to_device
    raise ValueError(
ValueError: Trying to set a tensor of shape torch.Size([341893120]) in "weight" (which has shape torch.Size([125696, 5120])), this look incorrect.
```

**Comment by hkvision** [comment]
@MeouSker77 Please take a look.

**Comment by MeouSker77** [comment]
This is caused by OOM, and you can add `model = model.bfloat16()` before moving model to xpu to use less gpu memory for now

**Comment by violet17** [comment]
Thanks.
