### ISSUE TITLE
Baichuan2-7B can't run on 16GB 

### ISSUE THREAD

**Issue by KiwiHana** [intel-analytics/BigDL#9483]
Baichuan2-7B can't run on 16GB memory Ultra5 even if we have moved embedding layer to cpu. (Qwen-7B-chat, Aquila2 and internlm-7B-chat-8k can be put into the shard memory and complete inference after `replace_embedding=True`.)

model = AutoModelForCausalLM.load_low_bit(model_path, trust_remote_code=True, optimize_model=True, use_cache=True,replace_embedding=True).eval()

```
>python example3.py
2023-11-17 14:01:58,867 - transformers_modules.Baichuan2-7B-Chat-int4.modeling_baichuan - WARNING - Xformers is not installed correctly. If you want to use memory_efficient_attention to accelerate training use the following command to install Xformers
pip install xformers.
2023-11-17 14:01:59,010 - bigdl.llm.transformers.utils - INFO - Converting the current model to sym_int4 format......
2023-11-17 14:01:59,216 - bigdl.llm.transformers.models.baichuan2 - WARNING - Xformers is not installed correctly. If you want to use memory_efficient_attention to accelerate training use the following command to install Xformers
pip install xformers.
finish to load
finish to xpu
stream_chat-----input_ids: {'input_ids': tensor([[13602,  5920,  1346,  1750, 92323,  1772, 29165,  1346,  3110,  5074,
          1642, 16077,  1375,  1527, 27044,    72,  2556,  4891,  1375,  1596,
          1375,  6679,  1377,  3099,  1662,  1808, 92323,  1377,  1527,  2431]],
       device='xpu:0'), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1]], device='xpu:0')}
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Users\MTL822\miniconda3\envs\audio\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Users\MTL822\miniconda3\envs\audio\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\MTL822\miniconda3\envs\audio\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\MTL822\miniconda3\envs\audio\lib\site-packages\transformers\generation\utils.py", line 1538, in generate
    return self.greedy_search(
  File "C:\Users\MTL822\miniconda3\envs\audio\lib\site-packages\transformers\generation\utils.py", line 2362, in greedy_search
    outputs = self(
  File "C:\Users\MTL822\miniconda3\envs\audio\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\MTL822/.cache\huggingface\modules\transformers_modules\Baichuan2-7B-Chat-int4\modeling_baichuan.py", line 686, in forward
    outputs = self.model(
  File "C:\Users\MTL822\miniconda3\envs\audio\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\MTL822/.cache\huggingface\modules\transformers_modules\Baichuan2-7B-Chat-int4\modeling_baichuan.py", line 414, in forward
    inputs_embeds = self.embed_tokens(input_ids)
  File "C:\Users\MTL822\miniconda3\envs\audio\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\MTL822\miniconda3\envs\audio\lib\site-packages\bigdl\llm\transformers\embedding.py", line 25, in forward
    self.to('cpu')
  File "C:\Users\MTL822\miniconda3\envs\audio\lib\site-packages\torch\nn\modules\module.py", line 1145, in to
    return self._apply(convert)
  File "C:\Users\MTL822\miniconda3\envs\audio\lib\site-packages\torch\nn\modules\module.py", line 820, in _apply
    param_applied = fn(param)
  File "C:\Users\MTL822\miniconda3\envs\audio\lib\site-packages\torch\nn\modules\module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: Native API failed. Native API returns: -5 (PI_ERROR_OUT_OF_RESOURCES) -5 (PI_ERROR_OUT_OF_RESOURCES)
```

**Comment by leonardozcm** [comment]
I'm afraid that I can not reproduce this OOM issue.
A baichuan7b-int4 model will occupy about 5.3GB VRAM, and if we replace embedding layer to cpu it will decrease to about 3.3GB(1964MB of embedding layer weights offload to cpu), for kvcache is not a problem when your sq_len is 32, it will only occupy about 0.5GB, so during inference the VRAM usage should remain at ~3.8GB. I have made some memory footprint to validate this:
```
before inference XPU Used Memory: 5522.86 MB, CPU Used Memory: 13098.29 MB
fwd XPU Used Memory: 5522.86 MB, CPU Used Memory: 13392.34 MB
fwd XPU Used Memory: 3830.67 MB, CPU Used Memory: 14257.41 MB
fwd XPU Used Memory: 3826.83 MB, CPU Used Memory: 13262.25 MB
fwd XPU Used Memory: 3826.83 MB, CPU Used Memory: 13257.82 MB
...
Lily stumbledinput:  Once upon a time, there existed a little girl who liked to have adventures.
output:   Her name was Lily, and she lived in a small village with her parents and older brother, Tim. One day, while exploring the nearby forest, Lily stumbled
token count input:  16
token count output:  32
time cost(s):  XXXX
```

**Comment by leonardozcm** [comment]
There is some new findings that after moving embedding layer to cpu will cause the incremental total memory as twice the embedding layer(should remain the same as expect, for igpu an cpu both shares the same memory)
```
## before replacing embedding
fwd XPU Used Memory: 5522.86 MB, CPU Used Memory: 13844.76 MB
## before replacing embedding
fwd XPU Used Memory: 3829.14 MB, CPU Used Memory: 15915.61 MB
```

After replacing embedding the total memory comes to the edge of the limitation.

**Comment by leonardozcm** [comment]
close as completed.
