### ISSUE TITLE
[LLM ON SPR] Tensor size mismatch during mpt-7b model inference

### ISSUE THREAD

**Issue by Jasonzzt** [intel-analytics/BigDL#9539]
Model: `mosaicml/mpt-7b-chat`
bigdl-llm: 2.4.0
torch: 2.1.0+cpu
transformers: 4.31.0
The config of all-in-one is as follows:
```
repo_id:
  - 'mosaicml/mpt-7b-chat'
local_model_hub: '/models/'
warm_up: 2
num_trials: 3
num_beams: 1 # default to greedy search
low_bit: 'sym_int4' # default to use 'sym_int4' (i.e. symmetric int4)
in_out_pairs:
  - '2048-256'
test_api:
  - "transformer_int4"
```
Startup script:
```
source bigdl-llm-init -t
export OMP_NUM_THREADS=48
numactl -C 0-47 -m 0 python $(dirname "$0")/run.py
```
The following error occurred when running
```
Traceback (most recent call last):
  File "/benchmark/all-in-one/run.py", line 653, in <module>
    run_model(model, api, conf['in_out_pairs'], conf['local_model_hub'], conf['warm_up'], conf['num_trials'], conf['num_beams'], conf['low_bit'])
  File "/benchmark/all-in-one/run.py", line 47, in run_model
    result = run_transformer_int4(repo_id, local_model_hub, in_out_pairs, warm_up, num_trials, num_beams, low_bit)
  File "/benchmark/all-in-one/run.py", line 187, in run_transformer_int4
    output_ids = model.generate(input_ids, do_sample=False, max_new_tokens=out_len,
  File "/usr/local/lib/python3.9/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/benchmark/all-in-one/../benchmark_util.py", line 1561, in generate
    return self.greedy_search(
  File "/benchmark/all-in-one/../benchmark_util.py", line 2382, in greedy_search
    outputs = self(
  File "/benchmark/all-in-one/../benchmark_util.py", line 531, in __call__
    return self.model(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/mpt-7b-chat/modeling_mpt.py", line 273, in forward
    outputs = self.transformer(input_ids=input_ids, past_key_values=past_key_values, attention_mask=attention_mask, prefix_mask=prefix_mask, sequence_id=sequence_id, return_dict=return_dict, output_attentions=output_attentions, output_hidden_states=output_hidden_states, use_cache=use_cache)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/mpt-7b-chat/modeling_mpt.py", line 195, in forward
    (attn_bias, attention_mask) = self._attn_bias(device=x.device, dtype=torch.float32, attention_mask=attention_mask, prefix_mask=prefix_mask, sequence_id=sequence_id)
  File "/usr/local/lib/python3.9/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/mpt-7b-chat/modeling_mpt.py", line 115, in _attn_bias
    attn_bias = attn_bias.masked_fill(~attention_mask.view(-1, 1, 1, s_k), min_val)
RuntimeError: The size of tensor a (2049) must match the size of tensor b (2048) at non-singleton dimension 3

```

**Comment by Jasonzzt** [comment]
In code `attn_bias = attn_bias.masked_fill(~attention_mask.view(-1, 1, 1, s_k), min_val)`, the size of attn_bias cannot match the size of attention_mask, so I tried to modify attn_bias to match the size of attention_mask in the file `modeling_mpt.py` of model `mpt-7b-chat`. [location of modified code](https://huggingface.co/mosaicml/mpt-7b-chat/blob/df5a0d74bf7a93f8f76f64ae6b45e2b996ca4764/modeling_mpt.py#L108)
```
        if attention_mask is not None:
            s_k = attention_mask.shape[-1]
            if attn_bias is None:
                attn_bias = torch.zeros((1, 1, 1, s_k), device=device, dtype=dtype)
            elif attn_bias.size(-1) < s_k:
                padding_size = s_k - attn_bias.size(-1)
                padding = torch.zeros(*attn_bias.shape[:-1], padding_size, device=device, dtype=dtype)
                attn_bias = torch.cat([attn_bias, padding], dim=-1)
            else:
                _s_k = max(0, attn_bias.size(-1) - s_k)
                attn_bias = attn_bias[:, :, :, _s_k:]
            if prefix_mask is not None and attention_mask.shape != prefix_mask.shape:
                raise ValueError(f'attention_mask shape={attention_mask.shape} ' + f'and prefix_mask shape={prefix_mask.shape} are not equal.')
            min_val = torch.finfo(attn_bias.dtype).min
            attn_bias = attn_bias.masked_fill(~attention_mask.view(-1, 1, 1, s_k), min_val)
```
The above modification mainly adds that if the size of attn_bias is smaller than s_k, add enough zero padding to match `s_k (length of the last dimension of the attention_mask tensor)`. Finally, I got the correct output.

**Comment by Jasonzzt** [comment]
I think the reason is adding newly generated tokens (next_tokens) to the existing input_ids sequence causes the length of the input_ids sequence to be greater than model_max_length (2048), during the autoregressive text generation process. [Here is the code](https://github.com/intel-analytics/BigDL/blob/22d21577c7fbf55b3a12c5c98a164ecfb94e592f/python/llm/dev/benchmark/benchmark_util.py#L2424)
```
# update generated ids, model inputs, and length for next step
input_ids = torch.cat([input_ids, next_tokens[:, None]], dim=-1)
```
So I am wondering whether model `mpt-7b-chat` (model_max_length=2048) supports inference with an in-out-pair of `2048-256`.

**Comment by Jasonzzt** [comment]
Here is the solution. 
Set the key named max_seq_len in config.json in model's directory to a value > 2048+256.
https://github.com/intel-analytics/BigDL/issues/9158#issuecomment-1760658356
