### ISSUE TITLE
packaging.version.InvalidVersion: Invalid version: '2023.2.0-13089-cfd42bd2cb0-HEAD'

### ISSUE THREAD

**Issue by Lucas-Wye** [intel-analytics/BigDL#9540]
Traceback (most recent call last):
  File "D:\code\AI\BigDL\python\nano\client-application\StableDiffusion\stable_diffusion\converter.py", line 66, in convert
    nano_pipe.convert_pipeline(accelerator=accelerator, device=device, precision=precision, ipex=ipex, cache=True, low_memory=low_memory, cache_dir=cache_dir)
  File "C:\Users\lustrew\miniconda3\envs\bigdl-sd\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\code\AI\BigDL\python\nano\client-application\StableDiffusion\stable_diffusion\pipelines\nano_stable_diffusion.py", line 151, in convert_pipeline
    nano_vae_decoder = InferenceOptimizer.quantize(vae_decoder,
  File "C:\Users\lustrew\miniconda3\envs\bigdl-sd\lib\site-packages\bigdl\nano\pytorch\inference\optimizer.py", line 1020, in quantize
    return PytorchOpenVINOModel(model, input_sample,
  File "C:\Users\lustrew\miniconda3\envs\bigdl-sd\lib\site-packages\bigdl\nano\deps\openvino\openvino_api.py", line 57, in PytorchOpenVINOModel
    from .pytorch.model import PytorchOpenVINOModel
  File "C:\Users\lustrew\miniconda3\envs\bigdl-sd\lib\site-packages\bigdl\nano\deps\openvino\pytorch\model.py", line 21, in <module>
    from ..core.model import OpenVINOModel
  File "C:\Users\lustrew\miniconda3\envs\bigdl-sd\lib\site-packages\bigdl\nano\deps\openvino\core\model.py", line 25, in <module>
    from .utils import save, OpenVINO_LESS_2022_3
  File "C:\Users\lustrew\miniconda3\envs\bigdl-sd\lib\site-packages\bigdl\nano\deps\openvino\core\utils.py", line 23, in <module>
    OpenVINO_LESS_2022_3 = compare_version("openvino", operator.lt, "2022.3")
  File "C:\Users\lustrew\miniconda3\envs\bigdl-sd\lib\site-packages\bigdl\nano\utils\common\version.py", line 40, in compare_version
    pkg_version = Version(pkg.__version__)
  File "C:\Users\lustrew\miniconda3\envs\bigdl-sd\lib\site-packages\packaging\version.py", line 200, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: '2023.2.0-13089-cfd42bd2cb0-HEAD'

**Comment by shane-huang** [comment]
It seems you're using OpenVINO 2023.2. For this example we only support OV 2022.3.

**Comment by Lucas-Wye** [comment]
> It seems you're using OpenVINO 2023.2. For this example we only support OV 2022.3.

Thanks for your reply. I just follow the README in this example. How can I use  OV 2022.3?

**Comment by season-studio** [comment]
> > It seems you're using OpenVINO 2023.2. For this example we only support OV 2022.3.
> 
> Thanks for your reply. I just follow the README in this example. How can I use OV 2022.3?

You should uninstall the current OV using `pip uninstall openvino-dev`. Then installing the correct version using pip install `openvino-dev==2022.3`. @Lucas-Wye
