### ISSUE TITLE
Segmentation fault with 256 input token on Xeon 8468v with ChatGLM2-6B

### ISSUE THREAD

**Issue by jessie-zhao** [intel-analytics/BigDL#9545]
bigdl-llm CPU can work on Xeon with 32 input tokens but get "Segmentation fault" with larger input token, such as 256.

numactl -c 0 -m 0 python generate.py --repo-id-or-model-path /home/jessie/BigDL_LLM/chatglm2-6b/ --n-predict 512 --prompt "糕点商店里原本有三种蛋糕：草莓奶油蛋糕，巧克力椰蓉蛋糕，和红丝绒布朗尼蛋糕。如名字所描述的那样，每种蛋糕都有两种成分：草莓奶油蛋糕包含草莓和奶油两个成分，巧克力椰蓉蛋糕包含巧克力和椰蓉两种成分，红丝绒布朗尼蛋糕包含红丝绒和布朗尼两种成分。在蛋糕制作完成后，往往每种成分的材料都会有所剩余。为了减少浪费，商店常常会把多出来的成分两两搭配，做成新的小商品卖出去。比如草莓和巧克力可以做成草莓味巧克力酱，布朗尼和椰蓉可以做成布朗尼椰蓉饼干。以此类推可知，如果所有的成分都可以两两组合，那么最终商店能做出哪些小商品出来？"
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  1.84it/s]
2023-11-28 16:04:38,724 - INFO - Converting the current model to sym_int4 format......
<class 'transformers_modules.modeling_chatglm.ChatGLMForConditionalGeneration'>
Segmentation fault (core dumped)

**Comment by jason-dai** [comment]
@qiyuangong please take a look

**Comment by Jasonzzt** [comment]
Hi @jessie-zhao, we cannot reproduce this issue on SPR machine. 
There is an issue reported the same error https://github.com/intel-analytics/BigDL/issues/9392, you could try the methods in comments https://github.com/intel-analytics/BigDL/issues/9392#issuecomment-1803274509 and https://github.com/intel-analytics/BigDL/issues/9392#issuecomment-1804916536. And I recommend you to use `source bigdl-llm-init -t` rather than `source bigdl-nano-init`.

**Comment by qiyuangong** [comment]
Failed to reproduce this issue with ChatGLM downloaded in July.

```bash
spr@spr-14:~/qiyuan/example/CPU/HF-Transformers-AutoModels/Model/chatglm$ numactl -c 0 -m 0 python generate.py --repo-id-or-model-path /mnt/disk1/models/chatglm2-6b --n-predict 512 --prompt "糕点商店里原本有三种蛋糕：草莓奶油蛋糕，巧克力椰蓉
蛋糕，和红丝绒布朗尼蛋糕。如名字所描述的那样，每种蛋糕都有两种成分：草莓奶油蛋糕包含草莓和奶油两个成分，巧克力椰蓉蛋糕包含巧克
力和椰蓉两种成分，红丝绒布朗尼蛋糕包含红丝绒和布朗尼两种成分。在蛋糕制作完成后，往往每种成分的材料都会有所剩余。为了减少浪费，
商店常常会把多出来的成分两两搭配，做成新的小商品卖出去。比如草莓和巧克力可以做成草莓味巧克力酱，布朗尼和椰蓉可以做成布朗尼椰蓉
饼干。以此类推可知，如果所有的成分都可以两两组合，那么最终商店能做出哪些小商品出来？"
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████| 7/7 [00:07<00:00,  1.08s/it]
2023-11-29 18:53:01,739 - INFO - Converting the current model to sym_int4 format......
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Inference time: 5.254871606826782 s
-------------------- Output --------------------
问：糕点商店里原本有三种蛋糕：草莓奶油蛋糕，巧克力椰蓉蛋糕，和红丝绒布朗尼蛋糕。如名字所描述的那样，每种蛋糕都有两种成分：草莓
  油蛋糕包含草莓和奶油两个成分，巧克力椰蓉蛋糕包含巧克力和椰蓉两种成分，红丝绒布朗尼蛋糕包含红丝绒和布朗尼两种成分。在蛋糕制作
  成后，往往每种成分的材料都会有所剩余。为了减少浪费，商店常常会把多出来的成分两两搭配，做成新的小商品卖出去。比如草莓和巧克力
  以做成草莓味巧克力酱，布朗尼和椰蓉可以做成布朗尼椰蓉饼干。以此类推可知，如果所有的成分都可以两两组合，那么最终商店能做出哪些
  商品出来？
答： 由于每种蛋糕都有两种成分，所以我们可以列出所有可能的组合：

1. 草莓 + 巧克力
2. 草莓 + 红丝绒
3. 草莓 + 布朗尼
4. 巧克力 + 椰蓉
5. 巧克力 + 红丝绒
6. 红丝绒 + 布朗尼

然后我们可以将这些组合两两配对，得到以下六个小商品：

1. 草莓味巧克力酱
2. 布朗尼椰蓉饼干
3. 草莓味红丝绒蛋糕
4. 巧克力味椰蓉蛋糕
5. 红丝绒布朗尼蛋糕
6. 布朗尼草莓蛋糕

所以，商店最终可以做这六个小商品。
```

Found that ChatGLM changed `modeling_chatglm.py` and `tokenization_chatglm.py` in the recent 2 months. Using latest `modeling_chatglm.py` and `tokenization_chatglm.py`  will lead to 
```
(qiyuan-llm) spr@spr-14:~/qiyuan/example/CPU/HF-Transformers-AutoModels/Model/chatglm$ numactl -c 0 -m 0 python generate.py --r
epo-id-or-model-path /mnt/disk1/models/chatglm2-6b --n-predict 512 --prompt "糕点商店里原本有三种蛋糕：草莓奶油蛋糕，巧克力椰蓉
蛋糕，和红丝绒布朗尼蛋糕。如名字所描述的那样，每种蛋糕都有两种成分：草莓奶油蛋糕包含草莓和奶油两个成分，巧克力椰蓉蛋糕包含巧克
力和椰蓉两种成分，红丝绒布朗尼蛋糕包含红丝绒和布朗尼两种成分。在蛋糕制作完成后，往往每种成分的材料都会有所剩余。为了减少浪费， 商店常常会把多出来的成分两两搭配，做成新的小商品卖出去。比如草莓和巧克力可以做成草莓味巧克力酱，布朗尼和椰蓉可以做成布朗尼椰蓉 饼干。以此类推可知，如果所有的成分都可以两两组合，那么最终商店能做出哪些小商品出来？"                                          Traceback (most recent call last):                                                                                               File "/mnt/disk1/qiyuan/example/CPU/HF-Transformers-AutoModels/Model/chatglm/generate.py", line 44, in <module>                  model = AutoModel.from_pretrained(model_path,
  File "/home/spr/anaconda3/envs/qiyuan-llm/lib/python3.9/site-packages/bigdl/llm/transformers/model.py", line 186, in from_pre
trained
    model = cls.load_convert(q_k, optimize_model, *args, **kwargs)                                                               File "/home/spr/anaconda3/envs/qiyuan-llm/lib/python3.9/site-packages/bigdl/llm/transformers/model.py", line 261, in load_con
vert
    model = cls.HF_Model.from_pretrained(*args, **kwargs)
  File "/home/spr/anaconda3/envs/qiyuan-llm/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 488, in
 from_pretrained
    return model_class.from_pretrained(
  File "/home/spr/anaconda3/envs/qiyuan-llm/lib/python3.9/site-packages/transformers/modeling_utils.py", line 2700, in from_pre
trained
    model = cls(config, *model_args, **model_kwargs)
  File "/home/spr/.cache/huggingface/modules/transformers_modules/chatglm2-6b/modeling_chatglm.py", line 856, in __init__
    self.transformer = ChatGLMModel(config, empty_init=empty_init, device=device)
  File "/home/spr/.cache/huggingface/modules/transformers_modules/chatglm2-6b/modeling_chatglm.py", line 759, in __init__
    self.pre_seq_len = config.pre_seq_len
  File "/home/spr/anaconda3/envs/qiyuan-llm/lib/python3.9/site-packages/transformers/configuration_utils.py", line 261, in __ge
tattribute__
    return super().__getattribute__(key)
AttributeError: 'ChatGLMConfig' object has no attribute 'pre_seq_len'
```
```

**Comment by jessie-zhao** [comment]
Thanks for your great support.  After uninstall bigdl-nano, this issue was resolved. thanks a lot.

**Comment by qiyuangong** [comment]
> Thanks for your great support. After uninstall bigdl-nano, this issue was resolved. thanks a lot.

You are welcome! :)

We apologize for the inconvenience caused by outdated documents. We have created a PR to fix the outdated documents https://github.com/intel-analytics/BigDL/pull/9558
