### ISSUE TITLE
Issue to run Qlora finetuning with OneAPI 2024.0.0

### ISSUE THREAD

**Issue by xiangyang-95** [intel-analytics/BigDL#9622]
When I run the qlora example with the OneAPI 2024 installed, it prompts an error where libsycl.so.7 is not found.
```
 warnings.warn(
  0%|                                                   | 0/200 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/user/WorkSpaces/LLM/finetuning_notebooks/BigDL/python/llm/example/GPU/QLoRA-FineTuning/qlora_finetuning.py", line 85, in <module>
    result = trainer.train()
  File "/home/user/miniconda3/envs/bigdl-llm-xpu/lib/python3.9/site-packages/transformers/trainer.py", line 1591, in train
    return inner_training_loop(
  File "/home/user/miniconda3/envs/bigdl-llm-xpu/lib/python3.9/site-packages/transformers/trainer.py", line 1892, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/user/miniconda3/envs/bigdl-llm-xpu/lib/python3.9/site-packages/transformers/trainer.py", line 2776, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home/user/miniconda3/envs/bigdl-llm-xpu/lib/python3.9/site-packages/transformers/trainer.py", line 2801, in compute_loss
    outputs = model(**inputs)
  File "/home/user/miniconda3/envs/bigdl-llm-xpu/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/miniconda3/envs/bigdl-llm-xpu/lib/python3.9/site-packages/accelerate/utils/operations.py", line 581, in forward
    return model_forward(*args, **kwargs)
  File "/home/user/miniconda3/envs/bigdl-llm-xpu/lib/python3.9/site-packages/accelerate/utils/operations.py", line 569, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/home/user/miniconda3/envs/bigdl-llm-xpu/lib/python3.9/site-packages/torch/amp/autocast_mode.py", line 14, in decorate_autocast
    return func(*args, **kwargs)
  File "/home/user/miniconda3/envs/bigdl-llm-xpu/lib/python3.9/site-packages/peft/peft_model.py", line 918, in forward
    return self.base_model(
  File "/home/user/miniconda3/envs/bigdl-llm-xpu/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/miniconda3/envs/bigdl-llm-xpu/lib/python3.9/site-packages/peft/tuners/tuners_utils.py", line 94, in forward
    return self.model.forward(*args, **kwargs)
  File "/home/user/miniconda3/envs/bigdl-llm-xpu/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 1038, in forward
    outputs = self.model(
  File "/home/user/miniconda3/envs/bigdl-llm-xpu/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/miniconda3/envs/bigdl-llm-xpu/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 921, in forward
    layer_outputs = torch.utils.checkpoint.checkpoint(
  File "/home/user/miniconda3/envs/bigdl-llm-xpu/lib/python3.9/site-packages/torch/utils/checkpoint.py", line 249, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File "/home/user/miniconda3/envs/bigdl-llm-xpu/lib/python3.9/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/user/miniconda3/envs/bigdl-llm-xpu/lib/python3.9/site-packages/torch/utils/checkpoint.py", line 107, in forward
    outputs = run_function(*args)
  File "/home/user/miniconda3/envs/bigdl-llm-xpu/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 917, in custom_forward
    return module(*inputs, past_key_value, output_attentions, padding_mask=padding_mask)
  File "/home/user/miniconda3/envs/bigdl-llm-xpu/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/miniconda3/envs/bigdl-llm-xpu/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 635, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/user/miniconda3/envs/bigdl-llm-xpu/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/miniconda3/envs/bigdl-llm-xpu/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 349, in forward
    query_states = self.q_proj(hidden_states)
  File "/home/user/miniconda3/envs/bigdl-llm-xpu/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/miniconda3/envs/bigdl-llm-xpu/lib/python3.9/site-packages/bigdl/llm/transformers/qlora.py", line 88, in forward
    result = super().forward(x)
  File "/home/user/miniconda3/envs/bigdl-llm-xpu/lib/python3.9/site-packages/bigdl/llm/transformers/low_bit_linear.py", line 428, in forward
    import linear_q4_0
ImportError: libsycl.so.7: cannot open shared object file: No such file or directory
```

**Comment by xiangyang-95** [comment]
Yes, I have installed it.
Verified with `pip list | grep intel`
```
intel-extension-for-pytorch 2.0.110+xpu
```

**Comment by rnwang04** [comment]
intel-extension-for-pytorch 2.0.110+xpu requires Intel® oneAPI Base Toolkit’s version == 2023.2.0 .
You can refer to https://bigdl.readthedocs.io/en/latest/doc/LLM/Overview/install_gpu.html#recommended-requirements
