### ISSUE TITLE
Fail to run Flan-T5-small on Windows with GPU

### ISSUE THREAD

**Issue by cold-blue** [intel-analytics/BigDL#9629]
I am trying to run an example code of flant5-small as follows.
System: Windows
Device: GPU

```
import torch
import intel_extension_for_pytorch as ipex
from bigdl.llm.transformers import AutoModelForSeq2SeqLM
from transformers import AutoTokenizer
from benchmark_util import BenchmarkWrapper

model_path ='google/flan-t5-small'
model = AutoModelForSeq2SeqLM.from_pretrained(model_path, trust_remote_code=True)
model = model.to('xpu')
model = BenchmarkWrapper(model, do_print=True)
tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
prompt = "今天睡不着怎么办"
 
with torch.inference_mode():
    # wamup two times as use ipex
    for i in range(2):
        input_ids = tokenizer.encode(prompt, return_tensors="pt").to('xpu')
        output = model.generate(input_ids, do_sample=False, max_new_tokens=32)
        output_str = tokenizer.decode(output[0], skip_special_tokens=True)
    # collect performance data now
    for i in range(5):
        input_ids = tokenizer.encode(prompt, return_tensors="pt").to('xpu')
        output = model.generate(input_ids, do_sample=False, max_new_tokens=32)
        output_str = tokenizer.decode(output[0], skip_special_tokens=True)

```
The same code works well on CPU. But when I switch to GPU code version (related environment variables have been set), an error occured:
```
(bigdl_gpu_env) C:\Users\Local_Admin\Models\BigDLTest>python test.py
<class 'transformers.models.t5.modeling_t5.T5ForConditionalGeneration'>
Traceback (most recent call last):
  File "C:\Users\Local_Admin\Models\BigDLTest\test.py", line 18, in <module>
    output = model.generate(input_ids, do_sample=False, max_new_tokens=32)
  File "C:\ProgramData\anaconda3\envs\bigdl_gpu_env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Local_Admin\Models\BigDLTest\benchmark_util.py", line 1364, in generate
    model_kwargs = self._prepare_encoder_decoder_kwargs_for_generation(
  File "C:\Users\Local_Admin\Models\BigDLTest\benchmark_util.py", line 677, in _prepare_encoder_decoder_kwargs_for_generation
    model_kwargs["encoder_outputs"]: ModelOutput = encoder(**encoder_kwargs)
  File "C:\ProgramData\anaconda3\envs\bigdl_gpu_env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\ProgramData\anaconda3\envs\bigdl_gpu_env\lib\site-packages\transformers\models\t5\modeling_t5.py", line 1094, in forward
    layer_outputs = layer_module(
  File "C:\ProgramData\anaconda3\envs\bigdl_gpu_env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\ProgramData\anaconda3\envs\bigdl_gpu_env\lib\site-packages\transformers\models\t5\modeling_t5.py", line 694, in forward
    self_attention_outputs = self.layer[0](
  File "C:\ProgramData\anaconda3\envs\bigdl_gpu_env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\ProgramData\anaconda3\envs\bigdl_gpu_env\lib\site-packages\transformers\models\t5\modeling_t5.py", line 600, in forward
    normed_hidden_states = self.layer_norm(hidden_states)
  File "C:\ProgramData\anaconda3\envs\bigdl_gpu_env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\ProgramData\anaconda3\envs\bigdl_gpu_env\lib\site-packages\transformers\models\t5\modeling_t5.py", line 253, in forward
    variance = hidden_states.to(torch.float32).pow(2).mean(-1, keepdim=True)
RuntimeError: Native API failed. Native API returns: -997 (Command failed to enqueue/execute) -997 (Command failed to enqueue/execute)
```

**Comment by Oscilloscope98** [comment]
Could you have with `cpu_embedding=True` in the `from_pretrained` function?
