### ISSUE TITLE
`RuntimeError: Last dim of input tensor must be multiple of 64` when loading CogAgent model

### ISSUE THREAD

**Issue by notsyncing** [intel-analytics/BigDL#9947]
Hello, I'm trying to load the `CogAgent` model (https://github.com/THUDM/CogAgent) with BigDL and quantize it to int4, with its example code `basic_demo/cli_demo_hf.py` slightly modified:

```python
import argparse
import torch

from PIL import Image
from transformers import AutoModelForCausalLM, LlamaTokenizer

# Added this line
from bigdl.llm import optimize_model

parser = argparse.ArgumentParser()
parser.add_argument("--quant", choices=[4], type=int, default=None, help='quantization bits')
parser.add_argument("--from_pretrained", type=str, default="THUDM/cogagent-chat-hf", help='pretrained ckpt')
parser.add_argument("--local_tokenizer", type=str, default="lmsys/vicuna-7b-v1.5", help='tokenizer path')
parser.add_argument("--fp16", action="store_true")
parser.add_argument("--bf16", action="store_true")

args = parser.parse_args()
MODEL_PATH = args.from_pretrained
TOKENIZER_PATH = args.local_tokenizer
DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'

tokenizer = LlamaTokenizer.from_pretrained(TOKENIZER_PATH)
if args.bf16:
    torch_type = torch.bfloat16
else:
    torch_type = torch.float16

print("========Use torch type as:{} with device:{}========\n\n".format(torch_type, DEVICE))

if args.quant:
    model = AutoModelForCausalLM.from_pretrained(
        MODEL_PATH,
        torch_dtype=torch_type,
        low_cpu_mem_usage=True,
        load_in_4bit=True,
        trust_remote_code=True
    ).eval()
else:
    model = AutoModelForCausalLM.from_pretrained(
        MODEL_PATH,
        torch_dtype=torch_type,
        low_cpu_mem_usage=True,
        load_in_4bit=args.quant is not None,
        trust_remote_code=True
    ).to(DEVICE).eval()

# Added these lines: use BigDL to quantize it to 4bit
print("Optimizing model...")
model = optimize_model(model)
print("BigDL done.")
```

and run it with `--bf16` option. It prints errors:

```
/mnt/data/podman/.conda/envs/cogvlm/lib/python3.11/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: ''If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
2024-01-19 21:49:01,038 - INFO - intel_extension_for_pytorch auto imported
========Use torch type as:torch.bfloat16 with device:cpu========


2024-01-19 21:49:01,223 - WARNING - WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.1.2+cu121 with CUDA 1201 (you have 2.1.0a0+cxx11.abi)
    Python  3.11.7 (you have 3.11.7)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
Please 'pip install apex'
2024-01-19 21:49:02,125 - INFO - Shape of rope freq: torch.Size([6400, 64])
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:01<00:00,  4.55it/s]
Optimizing model...
2024-01-19 21:49:05,415 - INFO - Converting the current model to sym_int4 format......
[2024-01-19 21:49:05,484] [INFO] [real_accelerator.py:161:get_accelerator] Setting ds_accelerator to cpu (auto detect)
2024-01-19 21:55:04,906 - ERROR - 

****************************Usage Error************************
Last dim of input tensor must be multiple of 64
2024-01-19 21:55:04,907 - ERROR - 

****************************Call Stack*************************
Traceback (most recent call last):
  File "/var/mnt/data/podman/CogVLM/basic_demo/cli_demo_hf.py", line 55, in <module>
    model = optimize_model(model)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/podman/.conda/envs/cogvlm/lib/python3.11/site-packages/bigdl/llm/optimize.py", line 241, in optimize_model
    model = ggml_convert_low_bit(model,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/podman/.conda/envs/cogvlm/lib/python3.11/site-packages/bigdl/llm/transformers/convert.py", line 510, in ggml_convert_low_bit
    model, has_been_replaced = _replace_with_low_bit_linear(
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/podman/.conda/envs/cogvlm/lib/python3.11/site-packages/bigdl/llm/transformers/convert.py", line 318, in _replace_with_low_bit_linear
    _, _flag = _replace_with_low_bit_linear(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/podman/.conda/envs/cogvlm/lib/python3.11/site-packages/bigdl/llm/transformers/convert.py", line 318, in _replace_with_low_bit_linear
    _, _flag = _replace_with_low_bit_linear(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/podman/.conda/envs/cogvlm/lib/python3.11/site-packages/bigdl/llm/transformers/convert.py", line 318, in _replace_with_low_bit_linear
    _, _flag = _replace_with_low_bit_linear(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 4 more times]
  File "/mnt/data/podman/.conda/envs/cogvlm/lib/python3.11/site-packages/bigdl/llm/transformers/convert.py", line 237, in _replace_with_low_bit_linear
    new_linear = LowBitLinear(
                 ^^^^^^^^^^^^^
  File "/mnt/data/podman/.conda/envs/cogvlm/lib/python3.11/site-packages/bigdl/llm/transformers/low_bit_linear.py", line 427, in __init__
    self.weight = FP4Params(self.weight.data,
    ^^^^^^^^^^^
  File "/mnt/data/podman/.conda/envs/cogvlm/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1712, in __setattr__
    self.register_parameter(name, value)
  File "/mnt/data/podman/.conda/envs/cogvlm/lib/python3.11/site-packages/accelerate/big_modeling.py", line 126, in register_empty_parameter
    module._parameters[name] = param_cls(module._parameters[name].to(device), **kwargs)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/podman/.conda/envs/cogvlm/lib/python3.11/site-packages/bigdl/llm/transformers/low_bit_linear.py", line 285, in to
    return self.quantize(device.type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/podman/.conda/envs/cogvlm/lib/python3.11/site-packages/bigdl/llm/transformers/low_bit_linear.py", line 256, in quantize
    w_quantized = ggml_convert_qtype(w, self.qtype,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/podman/.conda/envs/cogvlm/lib/python3.11/site-packages/bigdl/llm/transformers/low_bit_linear.py", line 96, in ggml_convert_qtype
    invalidInputError(k % QK == 0,
  File "/mnt/data/podman/.conda/envs/cogvlm/lib/python3.11/site-packages/bigdl/llm/utils/common/log4Error.py", line 32, in invalidInputError
    raise RuntimeError(errMsg)
RuntimeError: Last dim of input tensor must be multiple of 64
```

software versions:

```
python 3.11.7 (conda)
bigdl_llm 2.5.0b20240118
transformers 4.36.2
torch 2.1.0a0+cxx11
intel_extension_for_pytorch 2.1.10+xpu
oneccl_bind_pt 2.1.100+xpu
```

**Comment by qiuxin2012** [comment]
We are looking into this model.

**Comment by Mingyu-Wei** [comment]
@notsyncing Hi, you can avoid the `RuntimeError: Last dim of input tensor must be multiple of 64` by using the `optimize_model` API in this way:
```
modules_to_not_convert = ['w1','w2','act','ffn_ln','w3','drop']
model = optimize_model(model, modules_to_not_convert=modules_to_not_convert)
```

However, during further testing we find that HF version of `CogAgent` relies on the `xformers` package, which only supports `cuda` right now, so inference on `cpu` or `xpu` is not supported for this model.

**Comment by notsyncing** [comment]
> @notsyncing Hi, you can avoid the `RuntimeError: Last dim of input tensor must be multiple of 64` by using the `optimize_model` API in this way:
> 
> ```
> modules_to_not_convert = ['w1','w2','act','ffn_ln','w3','drop']
> model = optimize_model(model, modules_to_not_convert=modules_to_not_convert)
> ```
> 
> However, during further testing we find that HF version of `CogAgent` relies on the `xformers` package, which only supports `cuda` right now, so inference on `cpu` or `xpu` is not supported for this model.

I see. Would you mind considering something like auto skipping unsupported modules?

**Comment by shane-huang** [comment]
Thanks for the suggestion. We will consider adding checks and auto skipping the unsupported modules.
